### ISSUE TITLE
Fatal crash on app startup

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#10096]
It seems [the fix](https://github.com/wordpress-mobile/WordPress-Android/pull/10003) for the non-fatal errors in Sentry which we believed was safe, isn't safe after all.

I'm not sure about the exact steps
1. Create a draft while offline
2. Force kill the app
3. Turn off airplane mode
4. Restart the app and wait for a couple of seconds
5. If it doesn't work kill the app and restart it again

```
2019-06-24 16:25:20.705 2744-2744/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android.beta, PID: 2744
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{8971ece u0 org.wordpress.android.beta/org.wordpress.android.ui.uploads.UploadService}
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Version: 12.7-beta

cc @loremattei @maxme

**Comment by malinajirka** [comment]
Fixed in #10105
