### ISSUE TITLE
IndexOutOfBoundsException in SpannableStringBuilder

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#1033]
Not so helpful of a trace, 7 reports this week:

```
java.lang.IndexOutOfBoundsException: setSpan (3126 ... 3122) has end before start
at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1009)
at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:592)
at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:588)
at android.widget.SpellChecker$SpellParser.setRangeSpan(SpellChecker.java:536)
at android.widget.SpellChecker$SpellParser.parse(SpellChecker.java:736)
at android.widget.SpellChecker$1.run(SpellChecker.java:444)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5017)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
