### ISSUE TITLE
Crash when trying to create a WordPress account 

### ISSUE THREAD

**Issue by huaxunhuang** [wordpress-mobile/WordPress-Android#10357]
### Expected behavior
No crash

### Actual behavior
    java.lang.IllegalStateException: Already managing a GoogleApiClient with id 1001
        at com.google.android.gms.common.internal.Preconditions.checkState(Unknown Source)
        at com.google.android.gms.common.api.internal.zzi.zza(Unknown Source)
        at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
        at org.wordpress.android.login.SignupEmailFragment.onCreate(SignupEmailFragment.java:153)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2414)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

##### Tested on [device], Android [version], WPAndroid [version]
API level 22

**Comment by designsimply** [comment]
Thank you for the report @huaxunhuang !

**Comment by designsimply** [comment]
Prioritizing in Groundskeeping (our maintenance rotation) for Android even though the numbers are low because signup/NUX is an important area of the app.
