### ISSUE TITLE
Crash: IllegalArgumentException - View not attached to window manager

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#10606]
Sentry issue: https://sentry.io/share/issue/136cee38cb79491db456071ee0c686a0/

```
java.lang.IllegalArgumentException: View=DecorView@861288[EditPostActivity] not attached to window manager
    at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:485)
    at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:380)
    at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:99)
    at android.app.Dialog.onWindowAttributesChanged(Dialog.java:771)
    at android.view.Window.dispatchWindowAttributesChanged(Window.java:1134)
    at com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged(PhoneWindow.java:2984)
    at android.view.Window.setFlags(Window.java:1111)
    at android.view.Window.clearFlags(Window.java:1085)
    at com.facebook.react.views.modal.ReactModalHostView.updateProperties(ReactModalHostView.java:304)
    at com.facebook.react.views.modal.ReactModalHostView.showOrUpdate(ReactModalHostView.java:211)
    at com.facebook.react.views.modal.ReactModalHostView.onHostResume(ReactModalHostView.java:175)
    at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:208)
    at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:661)
    at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:580)
    at com.facebook.react.ReactInstanceManager.onHostResume(ReactInstanceManager.java:536)
    at org.wordpress.mobile.WPAndroidGlue.WPAndroidGlueCode.onResume(WPAndroidGlueCode.java:357)
    at org.wordpress.android.editor.GutenbergContainerFragment.onResume(GutenbergContainerFragment.java:86)
    at androidx.fragment.app.Fragment.performResume(Fragment.java:2498)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
    at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
    at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
    at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
    at androidx.fragment.app.Fragment.performResume(Fragment.java:2504)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
    at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
    at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
    at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
    at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:223)
    at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
    at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
    at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
    at android.app.Activity.performResume(Activity.java:7325)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3814)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6718)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.IllegalArgumentException: View=DecorView@861288[EditPostActivity] not attached to window manager
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3854)
    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6718)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by mzorz** [comment]
Comes from https://github.com/wordpress-mobile/WordPress-Android/issues/9494#issuecomment-540833647

**90-day impact:** ~16 per day
**Users affected in the last 90 days:** 626
**Limited to:** Android 9 and above

<sup>https://sentry.io/share/issue/136cee38cb79491db456071ee0c686a0/</sup>

**Comment by mzorz** [comment]
This is actually a duplicate of #10227  - closing
