### ISSUE TITLE
Crash: ClassCastException: android.app.ContextImpl cannot be cast to org.wordpress.android.WordPress

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#10776]
### Expected behavior
Changing the app's language and then trying to open a Notification from the Notifications tab (within the app) should not make the app crash

### Actual behavior
The app crashes when opening certain notifications with images after having switched the language.

```
2019-11-11 13:44:38.854 21776-21776/? D/AndroidRuntime: Shutting down VM
2019-11-11 13:44:38.859 21776-21776/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 21776
    java.lang.ClassCastException: android.app.ContextImpl cannot be cast to org.wordpress.android.WordPress
        at org.wordpress.android.util.image.getters.WPCustomImageGetter.<init>(WPCustomImageGetter.kt:38)
        at org.wordpress.android.ui.notifications.utils.NotificationsUtils.addImageSpansForBlockMedia(NotificationsUtils.java:331)
        at org.wordpress.android.ui.notifications.utils.NotificationsUtils.getSpannableContentForRanges(NotificationsUtils.java:258)
        at org.wordpress.android.ui.notifications.utils.NotificationsUtils.getSpannableContentForRanges(NotificationsUtils.java:202)
        at org.wordpress.android.ui.notifications.utils.NotificationsUtilsWrapper.getSpannableContentForRanges(NotificationsUtilsWrapper.kt:54)
        at org.wordpress.android.ui.notifications.blocks.CommentUserNoteBlock.getCommentTextOfNotification(CommentUserNoteBlock.java:185)
        at org.wordpress.android.ui.notifications.blocks.CommentUserNoteBlock.configureView(CommentUserNoteBlock.java:125)
        at org.wordpress.android.ui.notifications.adapters.NoteBlockAdapter.getView(NoteBlockAdapter.java:53)
        at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
        at android.widget.AbsListView.obtainView(AbsListView.java:2365)
        at android.widget.ListView.measureHeightOfChildren(ListView.java:1408)
        at android.widget.ListView.onMeasure(ListView.java:1315)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.widget.ScrollView.onMeasure(ScrollView.java:381)
        at android.view.View.measure(View.java:22071)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:22071)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:401)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
2019-11-11 13:44:38.859 21776-21776/? E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:724)
        at android.view.View.measure(View.java:22071)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2422)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1504)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

### Steps to reproduce the behavior
1. open the app
2. go to Me -> App Settings
3. Change language
4. Go to Notifications
5. try to open a Notification that shows an image in it (such as a comment where you were mentioned that has an embedded image)

**Comment by mzorz** [comment]
Closing via #10778

**Comment by zonemoney1** [comment]
When is it crashing?

**Comment by designsimply** [comment]
In this case, the alpha version (noted in the last line of the report above) was crashing when changing the app's language and then trying to open a Notification from the Notifications tab, however, that should be fixed prior to the next release.
