### ISSUE TITLE
Post scheduled in far future (year 4139) on self hosted

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#11220]
A user intended to publish a post on a self hosted site without Jetpack.  The post was published in the future (Year 4139).

![Screenshot_20200131-211826](https://user-images.githubusercontent.com/40213/73589183-2e12e580-44d3-11ea-97bf-874fa092aa8a.png)

User might have tried to fetch revision history, which should be disabled on self hosted (no endpoint). Notice the call to wpcom endpoints and the `site_id` in the logs:

```
30 - [Jan-31 20:19 API] Volley error on https://public-api.wordpress.com/rest/v1.1/sites/0/post/4530/diffs/?locale=de_AT - exception: null 31 - [Jan-31 20:19 API] StackTrace: com.android.volley.ClientError at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199) at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90) 32 - [Jan-31 20:19 API] Dispatching action: PostAction-FETCHED_REVISIONS 33 - [Jan-31 20:19 API] Volley error on https://public-api.wordpress.com/rest/v1.1/sites/0/post/4530/diffs/?locale=de_AT - exception: null 34 - [Jan-31 20:19 API] StackTrace: com.android.volley.ClientError at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199) at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131) at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111) at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

**Comment by jhnstn** [comment]
I'm unable to reproduce this with WPAndroid 17.0-rc-2 on a Pixel 5.

I tried on a self hosted site without Jetpack but I am not sure if there are any specific test steps that I am not following.
