### ISSUE TITLE
Offline Support : Pages - handlePostUploadedWithoutError continuation issue

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-Android#11264]
### Expected behavior
When a post is created and the Up button is pressed then it should just perform the auto-save without error. 

### Actual behavior

There are times when a crash occurs, seemingly because the continuation that represents the current upload was already resumed. 
```
2020-02-07 11:45:13.904 E: FATAL EXCEPTION: DefaultDispatcher-worker-4
    Process: org.wordpress.android.beta, PID: 5736
    java.lang.IllegalStateException: Already resumed, but proposed with update kotlin.Unit
        at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:332)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:327)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:247)
        at org.wordpress.android.viewmodel.pages.PagesViewModel.handlePostUploadedWithoutError(PagesViewModel.kt:701)
        at org.wordpress.android.viewmodel.pages.PagesViewModel$start$1.invoke(PagesViewModel.kt:185)
        at org.wordpress.android.viewmodel.pages.PagesViewModel$start$1.invoke(PagesViewModel.kt:76)
        at org.wordpress.android.viewmodel.pages.PageListEventListener$onPostChanged$1.invokeSuspend(PageListEventListener.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

### Steps to reproduce the behavior

1. I created a post. 
2. added a title
3. Click on "Up" button in the editor.

**Comment by malinajirka** [comment]
@jd-alexander I believe this is happening because we call `handlePostUploadedWithoutError` twice in `PageListEventListener`. Once in `onPostUploaded` and once in `OnPostChanged`. When those two events happen at the same time, [this continuation](https://github.com/wordpress-mobile/WordPress-Android/blob/b7686df462be1951f1f5987366b7f2d4f9d9fb5a/WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PagesViewModel.kt#L750) is accessed twice in a row. Do we really need to invoke `handlePostUploadedWithoutError` in `OnPostChanged`?

**Comment by jd-alexander** [comment]
Thanks, Jirka! I had discovered this bug during my work over the weekend but I didn't realize it was this one and changed it to the update event here 
https://github.com/wordpress-mobile/WordPress-Android/blob/65fbb75ac57a1c74c38be6d297240bb671541c04/WordPress/src/main/java/org/wordpress/android/viewmodel/pages/PageListEventListener.kt#L100

**Comment by malinajirka** [comment]
@jd-alexander AFAIU your branch hasn't been merged yet, so I'm not sure we should be closing this issue. Wdyt?
