### ISSUE TITLE
ReaderBlogTable.getBlogInfo(blogId) must not be null

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11451]
```
java.lang.IllegalStateException: ReaderBlogTable.getBlogInfo(blogId) must not be null
    at org.wordpress.android.datasets.ReaderBlogTableWrapper.getBlogInfo(ReaderBlogTableWrapper.kt:9)
    at org.wordpress.android.ui.reader.subfilter.SubfilterListItemMapper.fromJson(SubfilterListItemMapper.kt:43)
    at org.wordpress.android.ui.reader.viewmodels.ReaderPostListViewModel.getCurrentSubfilterValue(ReaderPostListViewModel.kt:227)
    at org.wordpress.android.ui.reader.viewmodels.ReaderPostListViewModel.start(ReaderPostListViewModel.kt:115)
    at org.wordpress.android.ui.reader.ReaderPostListFragment.onActivityCreated(ReaderPostListFragment.java:499)
    at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2460)
```

https://sentry.io/share/issue/e8ca9e80384744998da1a76b96b57546/

@develric Looks like this crash started happening in `14.3`, do you mind having a look at it?

**Comment by oguzkocer** [comment]
Somehow I missed the existing issue #11448 and realized it when I try to link this one to the crash, sorry about that! Closing this one.
