### ISSUE TITLE
NullPointerException in LoginBaseDiscoveryListener.onDiscoverySucceeded

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11491]
https://sentry.io/share/issue/ac3d40b7c28b45ff9d9bce42d35e7944/

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String org.wordpress.android.login.LoginBaseDiscoveryFragment$LoginBaseDiscoveryListener.getRequestedSiteAddress()' on a null object reference
    at org.wordpress.android.login.LoginBaseDiscoveryFragment.onDiscoverySucceeded(LoginBaseDiscoveryFragment.java:43)
    at java.lang.reflect.Method.invoke(Method.java)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6912)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
    at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:527)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:509)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6912)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
```

**Comment by oguzkocer** [comment]
Fixed in #11492.
