### ISSUE TITLE
Crash: Opening New or Existing Empty Blog Post

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#11508]
### Expected
Opening a new or existing blog post that is empty will not crash.

### Observed
Opening a new or existing blog post that is empty will crash.  See the stack trace below for details.

<details>
<summary>Stack Trace</summary>
<pre>
   --------- beginning of crash
2020-03-23 20:30:04.414 8159-8405/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: org.wordpress.android.beta, PID: 8159
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: dlopen failed: library "libc++_shared.so" not found
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
        at java.lang.Thread.run(Thread.java:919)
2020-03-23 20:30:04.419 1788-8407/? E/ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
2020-03-23 20:30:04.560 8159-8159/org.wordpress.android.beta E/WordPress-EDITOR: EditPostRepository: Transaction is writing on a locked thread [dalvik.system.VMStack.getThreadStackTrace(Native Method), java.lang.Thread.getStackTrace(Thread.java:1720), org.wordpress.android.ui.posts.EditPostRepository.reportTransactionState(EditPostRepository.kt:149), org.wordpress.android.ui.posts.EditPostRepository.access$reportTransactionState(EditPostRepository.kt:36), org.wordpress.android.ui.posts.EditPostRepository$updateAsync$1.invokeSuspend(EditPostRepository.kt:119), kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33), kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56), android.os.Handler.handleCallback(Handler.java:883), android.os.Handler.dispatchMessage(Handler.java:100), android.os.Looper.loop(Looper.java:214), android.app.ActivityThread.main(ActivityThread.java:7356), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)]
2020-03-23 20:30:04.770 8159-8159/org.wordpress.android.beta E/WordPress-EDITOR: EditPostRepository: Transaction is writing on a locked thread [dalvik.system.VMStack.getThreadStackTrace(Native Method), java.lang.Thread.getStackTrace(Thread.java:1720), org.wordpress.android.ui.posts.EditPostRepository.reportTransactionState(EditPostRepository.kt:149), org.wordpress.android.ui.posts.EditPostRepository.access$reportTransactionState(EditPostRepository.kt:36), org.wordpress.android.ui.posts.EditPostRepository$updateAsync$1.invokeSuspend(EditPostRepository.kt:119), kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33), kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56), android.os.Handler.handleCallback(Handler.java:883), android.os.Handler.dispatchMessage(Handler.java:100), android.os.Looper.loop(Looper.java:214), android.app.ActivityThread.main(ActivityThread.java:7356), java.lang.reflect.Method.invoke(Native Method), com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492), com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)]
2020-03-23 20:30:04.894 8159-8199/org.wordpress.android.beta E/Volley: [497] BasicNetwork.performRequest: Unexpected response code 400 for https://public-api.wordpress.com/rest/v1.1/sites/145499482/post/0/diffs/?locale=en_US
2020-03-23 20:30:04.907 8159-8159/org.wordpress.android.beta E/WordPress-API: Volley error on https://public-api.wordpress.com/rest/v1.1/sites/145499482/post/0/diffs/?locale=en_US
    com.android.volley.ClientError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
2020-03-23 20:30:04.920 8159-8159/org.wordpress.android.beta E/WordPress-API: An error occurred while fetching History revisions
2020-03-23 20:30:04.962 8159-8159/org.wordpress.android.beta E/WordPress-EDITOR: A non-started editor session cannot be attempted to be ended
</pre>
</details>

### Reproduced
1. Go to ***Sites*** tab.
2. Tap ***Blog Posts*** item under ***Publish*** section.
3. Tap ***Create a post*** floating action button.
4. Notice crash.
5. Tap ***Blog Posts*** item under ***Publish*** section.
6. Tap ***Drafts*** tab.
7. Tap ***(Untitled)*** post.
8. Notice crash.

##### Tested
Google Pixel 2 on Android 10.0 with WordPress Android alpha-213

**Comment by gibtang** [comment]
The console log showed this error when I tried to replicate the issue

**E/WordPress-API: An error occurred while fetching History revisions
E/Volley: [881] BasicNetwork.performRequest: Unexpected response code 400 for https://public-api.wordpress.com/rest/v1.1/sites/129970496/post/0/diffs/?locale=en_US
E/WordPress-API: Volley error on https://public-api.wordpress.com/rest/v1.1/sites/129970496/post/0/diffs/?locale=en_US
    com.android.volley.ClientError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
D/WordPress-API: Dispatching action: PostAction-FETCHED_REVISIONS
E/WordPress-API: An error occurred while fetching History revisions
E/FirebaseInstanceId: Token retrieval failed: INVALID_PARAMETERS**

Could this be a possible cause of the crash?

**Comment by designsimply** [comment]
I tried the testing steps using WPAndroid 14.7-rc-3 on Pixel 3 Android 10 and was unable to get the crash to happen. 

I labeled the issue as `gutenberg-mobile` because of the references to `libhermes.so` in the stacktrace—although please let me know if that label is not correct. Aside: if we haven't already updated to RN 0.62 (can someone explain how to check on that?), do you think it would help? cc @hypest 

Note: seems to match up with this crash report from Sentry:

Sentry Issue: [WORDPRESS-ANDROID-7MW](https://sentry.io/share/issue/5ee331bb9deb4ba1935b04396b01a880/)

```
UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/org.wordpress.android/lib-0/libc++_shared.so" is 32-bit instead of 64-bit
    at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
    at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
    at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
    at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
...
(3 additional frame(s) were not displayed)

couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/org.wordpress.android/lib-0/libc++_shared.so" is 32-bit instead of 64-bit
```

**Comment by mchowning** [comment]
> Could this be a possible reason of the crash?

It seems pretty unlikely that is the cause, but the additional info is helpful. Thanks for reporting @gibtang !

Just confirming, but am I understanding correctly that this only happens with a new or empty post? So you can open a non-empty post with no issues? cc: @theck13

**Comment by mchowning** [comment]
May be some relevant discussion here: https://github.com/facebook/react-native/issues/25490

**Comment by theck13** [comment]
@mchowning, I can't reproduce the crash with WordPress Android 14.7-rc-3.

**Comment by designsimply** [comment]
99 events have been tracked for crash [WORDPRESS-ANDROID-7MW](https://sentry.io/share/issue/5ee331bb9deb4ba1935b04396b01a880/) in 14.7 and 14.7.1 since they were released 15d and 4d ago on May 15 and May 4 respectively.

**Events:** 511
**Events in the last 15d for 14.7:** [93](https://sentry.io/organizations/a8c/discover/results/?field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1395731613+version%3A14.7&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)
**Events in the last 4d for 14.7.1:** [6](https://sentry.io/organizations/a8c/discover/results/?field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1395731613+version%3A14.7.1&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29) (mainly Android 6.0 Infinix)
**Users affected:** 107
<sub>https://sentry.io/share/issue/5ee331bb9deb4ba1935b04396b01a880/</sub>

**Comment by designsimply** [comment]
**Events in the last 90d:** 575
**Events in the last 9d since 14.8 was released:** [29](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1395731613+version%3A14.8&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)
**Users affected in the last 90d:** 126
<sub>https://sentry.io/share/issue/5ee331bb9deb4ba1935b04396b01a880/</sub>

**Comment by designsimply** [comment]
**Events in the last 90d:** 1,000
**Users affected in the last 90d:** 181
<sub>WORDPRESS-ANDROID-7MW: https://sentry.io/share/issue/5ee331bb9deb4ba1935b04396b01a880/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1395731613&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85910277-2aae2c80-b7db-11ea-986f-950c97f60b34.png)</a>

Events in the last 90d seem to be trending up.

**Comment by hypest** [comment]
This issue looks totally related to the RN integration of the block editor so, I'm moving it to the gutenberg-mobile repo.
