### ISSUE TITLE
InflateException: Binary XML file line #32 in org.wordpress.android:layout/login_epilogue_screen: Binary XML file l...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11616]
@khaykov We have quite a few crashes for the new beta with the following details. I thought it might be related to the material theme changes. Do you mind having a look at it? If you end up fixing it, do you mind targeting `release/14.6`? Thanks!

**Sentry Url**: https://sentry.io/share/issue/70f1b96539b74988a1ce307b3e86f5c3/
**User Count**: 12
**Count**: 74
**First Release**: org.wordpress.android-14.6-rc-1
**First Seen**: 2020-04-06T21:53:41Z
**Last Release**: org.wordpress.android-14.6-rc-1
**Last Seen**: 2020-04-08T13:02:24Z
**24 Hours**: 42
**30 Days**: 74

**Stacktrace**:
```
InflateException: Binary XML file line #32 in org.wordpress.android:layout/login_epilogue_screen: Binary XML file line #32 in org.wordpress.android:layout/login_epilogue_screen: Error inflating class com.google.android.material.card.MaterialCardView
    at android.content.res.TypedArray.getColorStateList(TypedArray.java:597)
    at androidx.cardview.widget.CardView.<init>(CardView.java:127)
    at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:118)
    at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:114)
    at java.lang.reflect.Constructor.newInstance0(Constructor.java:null)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at android.view.LayoutInflater.createView(LayoutInflater.java:854)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
    at java.lang.reflect.Constructor.newInstance0(Constructor.java:null)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at android.view.LayoutInflater.createView(LayoutInflater.java:854)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
    at org.wordpress.android.ui.ShareIntentReceiverFragment.onCreateView(ShareIntentReceiverFragment.java:86)
```

**Comment by oguzkocer** [comment]
Fixed in #11623.
