### ISSUE TITLE
AztecLoggingException: InlineFormatter.applySpan - setSpan has end before start. Start:-1 End:106

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11661]
Note that I have merged about 20 different issues with the same message and same line (didn't check every single one but I am pretty sure) to make it easier to see its impact. Please let me know if this causes any issues.

---

**Sentry Url**: https://sentry.io/share/issue/cbda39a9cb6e48179f2d2f26f25b6275/
**User Count**: 20
**Count**: 206
**First Release**: org.wordpress.android-14.5
**First Seen**: 2020-04-07T17:27:11Z
**Last Release**: org.wordpress.android-14.5
**Last Seen**: 2020-04-14T07:39:39Z
**24 Hours**: 69
**30 Days**: 206

**Stacktrace**:
```
AztecLoggingException: InlineFormatter.applySpan - setSpan has end before start. Start:-1 End:1383
    at org.wordpress.android.ui.posts.EditPostActivity$3.log(EditPostActivity.java:1618)
    at org.wordpress.aztec.formatting.InlineFormatter.applySpan(InlineFormatter.kt:184)
    at org.wordpress.aztec.formatting.InlineFormatter.joinStyleSpans(InlineFormatter.kt:277)
    at org.wordpress.aztec.formatting.InlineFormatter.applyInlineStyle(InlineFormatter.kt:176)
    at org.wordpress.aztec.formatting.InlineFormatter.applyInlineStyle$default(InlineFormatter.kt:106)
    at org.wordpress.aztec.formatting.InlineFormatter.handleInlineStyling(InlineFormatter.kt:74)
    at org.wordpress.aztec.watchers.InlineTextWatcher.afterTextChanged(InlineTextWatcher.kt:63)
    at android.widget.TextView.sendAfterTextChanged(TextView.java:10551)
    at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13388)
    at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
...
(14 additional frame(s) were not displayed)
```

**Comment by oguzkocer** [comment]
Please note that even though `EditPostAcitivity: 1618` is the one the stacktrace points out, this whole  part should be investigated: https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1611-L1652 as I have seen some instances of this crash in different lines.

**Comment by planarvoid** [comment]
I've looked into this and it's not a crash. This code:
```
EditPostActivity$3.log(EditPostActivity.java:1618)
```
is wrapping the logging from the AztecEditor in this method `ExternalLogger::log` set in the `EditPostActivity`. The change that was introduced there was done in February and it's an error case when we're trying to remove spans from an html in `org.wordpress.aztec.formatting.InlineFormatter#applySpan`. Previously we were only logging the case when the selection `start > end`. Now there is a check `start > end || start < 0 || end > editableText.length` which I think fixed some crashes and replaced them with this error.

**Comment by planarvoid** [comment]
Looking at the issue in sentry, the level is "error", not "fatal"

**Comment by oguzkocer** [comment]
Thanks for the clarification @planarvoid! I am sorry I missed that this was an `error` and not a `crash`. I'll keep an eye on that from here after.

**Comment by oguzkocer** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-Android/issues/12100.

**Comment by ercanduman** [comment]
**java.lang.IndexOutOfBoundsException org.wordpress.aztec.formatting.InlineFormatter.applySpan**

java.lang.IndexOutOfBoundsException: 
  at android.text.SpannableStringBuilder.checkRange (SpannableStringBuilder.java:1326)
  at android.text.SpannableStringBuilder.setSpan (SpannableStringBuilder.java:682)
  at android.text.SpannableStringBuilder.setSpan (SpannableStringBuilder.java:674)
  at org.wordpress.aztec.formatting.InlineFormatter.applySpan (InlineFormatter.kt:194)
  at org.wordpress.aztec.formatting.InlineFormatter.joinStyleSpans (InlineFormatter.kt:277)
  at org.wordpress.aztec.formatting.InlineFormatter.applyInlineStyle (InlineFormatter.kt:176)
  at org.wordpress.aztec.formatting.InlineFormatter.removeInlineStyle (InlineFormatter.kt:230)
  at org.wordpress.aztec.formatting.InlineFormatter.clearInlineStyles (InlineFormatter.kt:101)
  at org.wordpress.aztec.formatting.InlineFormatter.handleInlineStyling (InlineFormatter.kt:59)
  at org.wordpress.aztec.watchers.InlineTextWatcher.afterTextChanged (InlineTextWatcher.kt:63)
  at android.widget.TextView.sendAfterTextChanged (TextView.java:9812)
  at android.widget.TextView$ChangeWatcher.afterTextChanged (TextView.java:12600)
  at android.text.SpannableStringBuilder.sendAfterTextChanged (SpannableStringBuilder.java:1273)
  at android.text.SpannableStringBuilder.replace (SpannableStringBuilder.java:576)
  at android.text.SpannableStringBuilder.replace (SpannableStringBuilder.java:506)
  at android.text.SpannableStringBuilder.replace (SpannableStringBuilder.java:36)
  at android.text.method.QwertyKeyListener.onKeyDown (QwertyKeyListener.java:228)
  at android.text.method.TextKeyListener.onKeyDown (TextKeyListener.java:141)
  at android.widget.TextView.doKeyDown (TextView.java:7707)
  at android.widget.TextView.onKeyDown (TextView.java:7484)
  at android.view.KeyEvent.dispatch (KeyEvent.java:2720)
  at android.view.View.dispatchKeyEvent (View.java:12463)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1896)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1896)
  at androidx.core.widget.NestedScrollView.dispatchKeyEvent (NestedScrollView.java:621)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1896)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1896)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1896)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1896)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1896)
  at com.android.internal.policy.DecorView.superDispatchKeyEvent (DecorView.java:432)
  at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent (PhoneWindow.java:1825)
  at android.app.Dialog.dispatchKeyEvent (Dialog.java:811)
  at com.android.internal.policy.DecorView.dispatchKeyEvent (DecorView.java:346)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent (ViewRootImpl.java:5215)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:5083)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4602)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4655)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4621)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4761)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4629)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4818)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4602)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4655)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4621)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4629)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4602)
  at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:7330)
  at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:7299)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:7260)
  at android.view.ViewRootImpl$ViewRootHandler.handleMessage (ViewRootImpl.java:4372)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6810)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)
