### ISSUE TITLE
RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: j...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11662]
**Sentry Url**: https://sentry.io/share/issue/51b412ae3fb846d485242c8e78dbf170/
**User Count**: 1
**Count**: 10
**First Release**: org.wordpress.android-14.5
**First Seen**: 2020-04-14T14:26:20Z
**Last Release**: org.wordpress.android-14.5
**Last Seen**: 2020-04-14T14:30:32Z
**24 Hours**: 10
**30 Days**: 10

**Stacktrace**:
```
RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
    at org.wordpress.android.models.SiteSettingsModel.deserializeOptionsDatabaseCursor(SiteSettingsModel.java:406)
    at org.wordpress.android.ui.prefs.SiteSettingsInterface.loadCachedSettings(SiteSettingsInterface.java:1046)
    at org.wordpress.android.ui.prefs.SiteSettingsInterface.init(SiteSettingsInterface.java:991)
    at org.wordpress.android.ui.main.MySiteFragment.updateSiteSettingsIfNecessary(MySiteFragment.java:335)
    at org.wordpress.android.ui.main.MySiteFragment.onResume(MySiteFragment.java:213)
    at androidx.fragment.app.Fragment.performResume(Fragment.java:2498)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
    at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
    at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3392)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3423)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725)
    at android.app.ActivityThread.access$900(ActivityThread.java:196)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:210)
    at android.app.ActivityThread.main(ActivityThread.java:5982)
    at java.lang.reflect.Method.invoke(Method.java:null)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
```

**Comment by bummytime** [comment]
@develric very low priority — could you take a look at this crasher when resuming the MySite frag?

**Comment by develric** [comment]
Hey @bummytime 👋! Not sure can work on it within this week but will dig into in next few days 👍(since low pri I guess should be fine).

**Comment by bummytime** [comment]
@develric Perfect. Again no rush, just wanted to get it on your radar 😀
