### ISSUE TITLE
IndexOutOfBoundsException: Index out of bounds - passed position = 50, old list size = 50

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11792]
**Sentry Url**: https://sentry.io/share/issue/d7e6d223b7bc46049450062f01dbe04e/
**User Count**: 120
**Count**: 174
**First Release**: org.wordpress.android-14.6-rc-1
**First Seen**: 2020-04-09T09:30:29Z
**Last Seen**: 2020-04-30T11:33:55Z
**24 Hours**: 41
**30 Days**: 173

```
IndexOutOfBoundsException: Index out of bounds - passed position = 26, old list size = 26
     at androidx.recyclerview.widget.DiffUtil$DiffResult.convertOldPositionToNew(DiffUtil.java:672)
     at androidx.paging.PagedStorageDiffHelper.transformAnchorIndex(PagedStorageDiffHelper.java:215)
     at androidx.paging.AsyncPagedListDiffer.latchPagedList(AsyncPagedListDiffer.java:382)
     at androidx.paging.AsyncPagedListDiffer$2$1.run(AsyncPagedListDiffer.java:345)
     at android.os.Handler.handleCallback(Handler.java:815)
     at android.os.Handler.dispatchMessage(Handler.java:104)
     at android.os.Looper.loop(Looper.java:194)
     at android.app.ActivityThread.main(ActivityThread.java:5651)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at java.lang.reflect.Method.invoke(Method.java:372)
...
(2 additional frame(s) were not displayed)
```

**Comment by oguzkocer** [comment]
This is the same issue we have in woo-android: https://github.com/woocommerce/woocommerce-android/issues/1782 and caused by the paging library which is used in FluxC.
