### ISSUE TITLE
(PhotoPickerFragment) NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnC...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11844]
Looks like this might be related to c826433c225956720f4f9c5fd37da408493b4813 authored by @malinajirka.

**Sentry Url**: https://sentry.io/share/issue/587aa32832f54120a9f543dbee6b0e79/
**User Count**: 1
**Count**: 2
**First Release**: org.wordpress.android-14.8-rc-1
**First Seen**: 2020-05-06T14:47:33Z
**Last Seen**: 2020-05-06T14:48:07Z
**24 Hours**: 2
**30 Days**: 2

```
NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
     at org.wordpress.android.ui.photopicker.PhotoPickerFragment.onCreateView(PhotoPickerFragment.java:217)
     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
...
(19 additional frame(s) were not displayed)
```

**Comment by malinajirka** [comment]
I'm not sure how come this is crashing. I'm wondering @ashiagr, do you think it's possible we recorded this crash into Sentry while testing - https://github.com/wordpress-mobile/WordPress-Android/pull/11828 ?

**Comment by ashiagr** [comment]
Yes I confirm, it was recorded at that time. We can close this issue.

**Comment by malinajirka** [comment]
👍 Closing, thanks for the confirmation! (cc @oguzkocer )

**Comment by oguzkocer** [comment]
Thanks for also resolving the issue in Sentry @malinajirka 🙇
