### ISSUE TITLE
RuntimeException: Unable to start service org.wordpress.android.ui.uploads.UploadService@763ef67 with Intent { cmp=...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#11923]
**Sentry Url**: https://sentry.io/share/issue/8f3d0837ab064be2b1b31e2e5cb5ad0d/
**User Count**: 1
**Count**: 10
**First Release**: org.wordpress.android-14.7.1
**First Seen**: 2020-05-14T11:02:31Z
**Last Seen**: 2020-05-14T12:08:04Z
**24 Hours**: 10
**30 Days**: 10

```
RuntimeException: Unable to start service org.wordpress.android.ui.uploads.UploadService@630bea2 with Intent { cmp=org.wordpress.android/.ui.uploads.UploadService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.m4m.domain.MediaFormat.getMimeType()' on a null object reference
     at org.m4m.domain.MediaSource.getMediaFormatByType(MediaSource.java:166)
     at org.m4m.MediaFile.getAudioFormat(MediaFile.java:122)
     at org.m4m.MediaFileInfo.prepareMediaFile(MediaFileInfo.java:136)
     at org.m4m.MediaFileInfo.setUri(MediaFileInfo.java:88)
     at org.wordpress.android.util.WPVideoUtils.getVideoOptimizationComposer(WPVideoUtils.java:56)
     at org.wordpress.android.ui.uploads.VideoOptimizer.start(VideoOptimizer.java:88)
     at org.wordpress.android.ui.uploads.MediaUploadHandler.prepareForUpload(MediaUploadHandler.java:282)
     at org.wordpress.android.ui.uploads.MediaUploadHandler.uploadNextInQueue(MediaUploadHandler.java:214)
     at org.wordpress.android.ui.uploads.MediaUploadHandler.upload(MediaUploadHandler.java:71)
     at org.wordpress.android.ui.uploads.UploadService.unpackMediaIntent(UploadService.java:209)
...
(10 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
Graph to watch: [90d Discover graph for issue.id:1665303780](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.brand&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1665303780&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)

**Note:** a split between Android 6.0 Infinix and Android 9 HONOR devices is odd 🤨 maybe it's just too early to tell what's what for devices affected on this one.

@frosty consider keeping an eye on this one and raising in priority if there's an uptick because it appears to have to do with failed media uploads which are problematic area for our users and because the `notifications_upload_post_error_retry` mentions in it are fishy.

**Comment by designsimply** [comment]
**Events:** 25
**Users affected:** 2
**Culprit:** `android.app.ActivityThread in handleServiceArgs`
<sub>WORDPRESS-ANDROID-BSQ: https://sentry.io/share/issue/8f3d0837ab064be2b1b31e2e5cb5ad0d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.brand&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1665303780&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85910686-909bb380-b7dd-11ea-878f-f43e9677df12.png)</a>

Closing because the number of occurrences is dismally low. We can re-open if the number of occurrences picks up in Sentry again later.
