### ISSUE TITLE
NullPointerException: Attempt to read from field 'java.util.List org.wordpress.android.ui.accounts.signup.UsernameChang...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12036]
@bummytime This is not a new crash, but it looks like it'd be very easy to fix this. The reason it went kind of unnoticed despite its numbers is because we had 20+ separate issues for it and merging them all revealed the number. I only noticed these crashes while working on a different crash.

**Sentry Url**: https://sentry.io/share/issue/d57306c7818b40978d4e71420f3acf5d/
**User Count**: 544
**Count**: 1266
**First Release**: org.wordpress.android-13.3
**First Seen**: 2019-10-09T06:24:15Z
**Last Seen**: 2020-05-27T05:20:26Z
**24 Hours**: 6
**30 Days**: 228

```
NullPointerException: Attempt to read from field 'java.util.List org.wordpress.android.ui.accounts.signup.UsernameChangerRecyclerViewAdapter.mItems' on a null object reference
     at org.wordpress.android.ui.accounts.signup.BaseUsernameChangerFullScreenDialogFragment.onSaveInstanceState(BaseUsernameChangerFullScreenDialogFragment.java:247)
     at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2766)
     at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
     at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
     at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2768)
     at androidx.fragment.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManagerImpl.java:2289)
     at androidx.fragment.app.FragmentManagerImpl.saveAllState(FragmentManagerImpl.java:2348)
     at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:151)
     at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:513)
     at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
...
(16 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Thanks for coalescing all the separate issues @oguzkocer. 🙇 

@planarvoid Low priority → would you mind taking a peek at this NPE whenever you have a few spare cycles? As @oguzkocer mentioned, I'm assuming this is easy to fix. 🙇

**Comment by designsimply** [comment]
**Events in the last 90d:** 1,200
**Events in the last 9d since 14.8 was released:** [43](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.brand&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1268257161+version%3A14.8&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)
**Users affected in the last 90d:** 541
**Also see:** [90d graph](https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.brand&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1268257161&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29)
<sub>https://sentry.io/share/issue/d57306c7818b40978d4e71420f3acf5d/</sub>

**Comment by planarvoid** [comment]
I'll look into this after the hack week
