### ISSUE TITLE
Editor crashing on launch for 14.9 release build

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12053]
```
05-29 11:03:13.917 12481 12794 E AndroidRuntime: java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.
05-29 11:03:13.917 12481 12794 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromAssets(Native Method)
05-29 11:03:13.917 12481 12794 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromAssets(CatalystInstanceImpl.java:227)
05-29 11:03:13.917 12481 12794 E AndroidRuntime: 	at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:28)
05-29 11:03:13.917 12481 12794 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:261)
05-29 11:03:13.917 12481 12794 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1175)
05-29 11:03:13.917 12481 12794 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
05-29 11:03:13.917 12481 12794 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
05-29 11:03:13.917 12481 12794 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by oguzkocer** [comment]
This turned out to be a build issue, a temporary one, and with @mchowning's help it was addressed without any code changes.
