### ISSUE TITLE
ReaderPostDetailFragment - Resources$NotFoundException: Resource ID #0x7f0801a9

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12075]
@jd-alexander @ashiagr It looks like you have added this logging, so I hope you find the report useful.

**Sentry Url**: https://sentry.io/share/issue/303f3a31a935422e9814d908c90ad1eb/
**User Count**: 1
**Count**: 5
**First Release**: org.wordpress.android@15.0-rc-1+874
**First Seen**: 2020-06-02T03:28:48.597000Z
**Last Seen**: 2020-06-02T03:28:49Z
**24 Hours**: 5
**30 Days**: 5

```
Resources$NotFoundException: Resource ID #0x7f0801a9
     at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
     at android.content.res.Resources.getDrawableForDensity(Resources.java:905)
     at android.content.res.Resources.getDrawable(Resources.java:845)
     at android.content.Context.getDrawable(Context.java:687)
     at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:455)
     at org.wordpress.android.ui.reader.ReaderPostDetailFragment.showError(ReaderPostDetailFragment.kt:1168)
     at org.wordpress.android.ui.reader.ReaderPostDetailFragment.access$showError(ReaderPostDetailFragment.kt:130)
     at org.wordpress.android.ui.reader.ReaderPostDetailFragment$ShowPostTask.onPostExecute(ReaderPostDetailFragment.kt:1307)
     at org.wordpress.android.ui.reader.ReaderPostDetailFragment$ShowPostTask.onPostExecute(ReaderPostDetailFragment.kt:1246)
     at android.os.AsyncTask.finish(AsyncTask.java:755)
...
(8 additional frame(s) were not displayed)
```

**Comment by jkmassel** [comment]
Closing this issue — the referenced Sentry issue no longer exists (the share link returns 404), and this was primarily a Sentry crash report from 2020 with no additional context or comments. If this crash is still occurring, it would appear as a new Sentry issue.
