### ISSUE TITLE
[LoginActivity.onGoogleLoginFinished] EventBusException: Invoking subscriber failed

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12108]
**Sentry Url**: https://sentry.io/share/issue/eb26cf22fb65402283fa5af8a03f52c9/
**User Count**: 170
**Count**: 556
**First Release**: org.wordpress.android-12.3.1
**First Seen**: 2019-05-09T10:20:18Z
**Last Seen**: 2020-06-03T19:10:33Z
**24 Hours**: 0
**30 Days**: 67

```
EventBusException: Invoking subscriber failed
     at org.wordpress.android.ui.accounts.LoginActivity.onGoogleLoginFinished(LoginActivity.java:758)
     at org.wordpress.android.login.LoginGoogleFragment.onAuthenticationChanged(LoginGoogleFragment.java:161)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
     at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
     at android.os.Handler.dispatchMessage(Handler.java:107)
     at android.os.Looper.loop(Looper.java:237)
     at android.app.ActivityThread.main(ActivityThread.java:7811)
     at java.lang.reflect.Method.invoke(Method.java:null)
...
(2 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
@renanferrari 👋 → Any thoughts on this one?

**Comment by designsimply** [comment]
**Events in the last 90d:** 612
**Users affected in the last 90d:** 183
**Culprit:** `org.greenrobot.eventbus.EventBus in handleSubscriberException`
<sub>WORDPRESS-ANDROID-47: https://sentry.io/share/issue/eb26cf22fb65402283fa5af8a03f52c9/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1018983026&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85911182-d27a2900-b7e0-11ea-8062-d92a998ec776.png)</a>
