### ISSUE TITLE
[LoginBaseDiscoveryFragment.initiateDiscovery] EventBusException: Invoking subscriber failed

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12109]
**Sentry Url**: https://sentry.io/share/issue/ada60f9a343f4c19889c7dde3269a756/
**User Count**: 117
**Count**: 202
**First Release**: org.wordpress.android-13.8
**First Seen**: 2019-12-19T15:20:34Z
**Last Seen**: 2020-06-03T14:15:36Z
**24 Hours**: 0
**30 Days**: 42

```
EventBusException: Invoking subscriber failed
     at org.wordpress.android.login.LoginBaseDiscoveryFragment.initiateDiscovery(LoginBaseDiscoveryFragment.java:35)
     at org.wordpress.android.login.LoginSiteAddressFragment.onWPComSiteFetched(LoginSiteAddressFragment.java:340)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
     at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loop(Looper.java:226)
     at android.app.ActivityThread.main(ActivityThread.java:7191)
     at java.lang.reflect.Method.invoke(Method.java:null)
...
(2 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
@renanferrari → last login/signup-related eventbus ping I promise! 😆 Is this related to the others?

**Comment by renanferrari** [comment]
@bummytime Thanks for pinging me on these issues. Even though this, #12106 and #12108 are all being wrapped by the same `EventBusException`, it seems that their underlying causes are fairly different, so I don't believe they're related to each other. 

They also don't seem to be high-impact issues, so probably good candidates for groundskeeping? Please, let me know if I'm missing something.

**Comment by bummytime** [comment]
@renanferrari 

> it seems that their underlying causes are fairly different, so I don't believe they're related to each other.

👍 

> They also don't seem to be high-impact issues, so probably good candidates for groundskeeping? Please, let me know if I'm missing something.

I agree. Looking at Sentry again today, the number of affected users is remaining fairly low therefore I will add these 3 issues to groundskeeping. Thank you.

**Comment by designsimply** [comment]
**Events in the last 90d:** 239
**Users affected in the last 90d:** 130
**Culprit:** `org.greenrobot.eventbus.EventBus in handleSubscriberException`
<sub>WORDPRESS-ANDROID-7NJ: https://sentry.io/share/issue/ada60f9a343f4c19889c7dde3269a756/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1396681270&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85911229-343a9300-b7e1-11ea-9a7c-822181c21257.png)</a>

Note: the goal for pinging a developer specifically for a newly reported crash is mainly to try to match up the crash with any recently-shipped-code or recently-worked-on-code _if at all possible_. So, if you do get pinged on a case like this, it's worth doing a very quick check to see if you can trace the crash back to a specific PR. If you cannot, then move on quickly and feel free to send the issue to Groundskeeping yourself directly with a note saying something like: "took a quick look and not sure where this is coming from, let's re-visit it in Groundskeeping". Thanks so much! cc @renanferrari @bummytime
