### ISSUE TITLE
[ImageBlockProcessor] EventBusException: Invoking subscriber failed

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12105]
This is very similar to #12104 and I think there are more issues similar to these ones. They are hard to identify because in Sentry most of these issues show up as `EventBusException`s which doesn't tell us much. I've opened [a PR to address that](https://github.com/wordpress-mobile/WordPress-Android/pull/12102) but in the meantime @mkevins could you maybe look at these issues and do a general audit of similar actions since you seem to be familiar with them?

**Sentry Url**: https://sentry.io/share/issue/b84b65caa6e64c33b756500945809386/
**User Count**: 11
**Count**: 256
**First Release**: org.wordpress.android-14.8
**First Seen**: 2020-05-22T16:29:47Z
**Last Seen**: 2020-06-04T20:44:07Z
**24 Hours**: 35
**30 Days**: 256

```
EventBusException: Invoking subscriber failed
     at java.lang.Integer.parseInt(Integer.java:570)
     at java.lang.Integer.parseInt(Integer.java:643)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.ImageBlockProcessor.processBlockJsonAttributes(ImageBlockProcessor.java:35)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.BlockProcessor.processBlock(BlockProcessor.java:91)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processBlock(MediaUploadCompletionProcessor.java:78)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processContent(MediaUploadCompletionProcessor.java:59)
     at org.wordpress.android.ui.posts.PostUtils.replaceMediaFileWithUrlInGutenbergPost(PostUtils.java:429)
     at org.wordpress.android.ui.uploads.MediaUploadReadyProcessor.replaceMediaFileWithUrlInPost(MediaUploadReadyProcessor.java:25)
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithMediaUrl(UploadService.java:611)
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithCurrentlyCompletedUploads(UploadService.java:459)
...
(14 additional frame(s) were not displayed)
```

**Comment by oguzkocer** [comment]
Here is another one: https://sentry.io/share/issue/6c3149abcc8a4eeabdc441a5cb378a7b/

**Comment by mkevins** [comment]
Hi @oguzkocer :wave: :smile: 

> in the meantime @mkevins could you maybe look at these issues and do a general audit of similar actions since you seem to be familiar with them

Actually, coincidentally, I observed an NPE related to the processors code while trying to reproduce https://github.com/wordpress-mobile/WordPress-Android/issues/10493, and I made a note to circle back to that code to clean up / guard some unsafe dereferences. I've found at least one, but I will conduct a more thorough search of the processors code and have a PR soon.

**Comment by mkevins** [comment]
Drafted a PR for this here: https://github.com/wordpress-mobile/WordPress-Android/pull/12114

**Comment by oguzkocer** [comment]
@mkevins Thank you for having a look at this so quickly! 🙇‍♂️

**Comment by mkevins** [comment]
The PR guarding the NPE is merged. Thanks Oguz for the PR unmasking the EventBus exceptions!

**Comment by bummytime** [comment]
> The PR guarding the NPE is merged.

@mkevins 👋 — should we leave this issue open still given that PR ☝️ ?

**Comment by mkevins** [comment]
> > The PR guarding the NPE is merged.
> 
> @mkevins  — should we leave this issue open still given that PR  ?

Yes, this is resolved now. :+1:
