### ISSUE TITLE
[UploadService] EventBusException: Invoking subscriber failed

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12107]
**Sentry Url**: https://sentry.io/share/issue/89a8739fc0e04963b97d87fcba21d9af/
**User Count**: 11
**Count**: 262
**First Release**: org.wordpress.android-14.1
**First Seen**: 2020-02-28T05:53:06Z
**Last Seen**: 2020-06-04T16:07:47Z
**24 Hours**: 3
**30 Days**: 117

```
EventBusException: Invoking subscriber failed
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithMediaUrl(UploadService.java:612)
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithCurrentlyCompletedUploads(UploadService.java:459)
     at org.wordpress.android.ui.uploads.UploadService.updateOnePostModelWithCompletedAndFailedUploads(UploadService.java:707)
     at org.wordpress.android.ui.uploads.UploadService.doFinalProcessingOfPosts(UploadService.java:993)
     at org.wordpress.android.ui.uploads.UploadService.stopServiceIfUploadsComplete(UploadService.java:670)
     at org.wordpress.android.ui.uploads.UploadService.onPostUploaded(UploadService.java:1082)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
     at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
...
(6 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
**Events in the last 90d:** 340
**Users affected in the last 90d:** 17
**Culprit:** `org.greenrobot.eventbus.EventBus in handleSubscriberException`
<sub>WORDPRESS-ANDROID-9B2: https://sentry.io/share/issue/89a8739fc0e04963b97d87fcba21d9af/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1536760625&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85911113-2fc1aa80-b7e0-11ea-8e72-d0af7fefcabc.png)</a>
