### ISSUE TITLE
[SignupEpilogueFragment] EventBusException: Invoking subscriber failed

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12106]
**Sentry Url**: https://sentry.io/share/issue/3852997eefa94a84b2aca89154a52c90/
**User Count**: 187
**Count**: 523
**First Release**: org.wordpress.android-12.3.1
**First Seen**: 2019-05-08T07:41:44Z
**Last Seen**: 2020-06-04T03:03:42Z
**24 Hours**: 1
**30 Days**: 73

```
EventBusException: Invoking subscriber failed
     at java.lang.String.substring(String.java:1971)
     at org.wordpress.android.ui.accounts.signup.SignupEpilogueFragment.createDisplayNameFromEmail(SignupEpilogueFragment.java:541)
     at org.wordpress.android.ui.accounts.signup.SignupEpilogueFragment.populateViews(SignupEpilogueFragment.java:622)
     at org.wordpress.android.ui.accounts.signup.SignupEpilogueFragment.onAccountChanged(SignupEpilogueFragment.java:478)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
     at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loop(Looper.java:192)
...
(4 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
@renanferrari — more of an awareness ping for you since this is related to signup. Any thoughts?

**Comment by designsimply** [comment]
**Events in the last 90d:** 569
**Users affected in the last 90d:** 187
**Culprit:** `org.greenrobot.eventbus.EventBus in handleSubscriberException`
<sub>WORDPRESS-ANDROID-2C: https://sentry.io/share/issue/3852997eefa94a84b2aca89154a52c90/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1017203349&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85911069-ccd01380-b7df-11ea-96ce-0d94f57a9d59.png)</a>

**Comment by designsimply** [comment]
A search for "issue.id:1017203349 version:15.0*" in Sentry Discover returned a few results while a search for "issue.id:1017203349 version:15.1*" returned no results. 

Closing as no new events are being recorded for this crash since version 15.1.

**Comment by designsimply** [comment]
Aside: a more general search for `"SignupEpilogueFragment"` in Sentry Discover returns events but a search for `"SignupEpilogueFragment" "Invoking subscriber failed"` returns no events. @oguzkocer I believe this meant the crash from the Sentry issue noted in this GitHub ticket (1017203349) is no longer happening and I assume if crashes related to `SignupEpilogueFragment` will show up in other Sentry issues if they are still relevant and that it was okay to close this issue—I wanted to double check it, do you agree with my assessment?
