### ISSUE TITLE
[ImageBlockProcessor] NumberFormatException: s == null

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12228]
@mkevins This seems similar to #12227. I thought I'd report it in case it contains any new information for you. If not, please feel free to close it.

**Sentry Url**: https://sentry.io/share/issue/8505b04cd4ab41deaf5bd49590c09cdd/
**User Count**: 1
**Count**: 2
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-16T21:06:47.002000Z
**Last Seen**: 2020-06-16T23:00:02Z
**24 Hours**: 0
**30 Days**: 2

```
NumberFormatException: s == null
     at java.lang.Integer.parseInt(Integer.java:577)
     at java.lang.Integer.parseInt(Integer.java:650)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.ImageBlockProcessor.processBlockJsonAttributes(ImageBlockProcessor.java:37)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.BlockProcessor.processBlock(BlockProcessor.java:91)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processBlock(MediaUploadCompletionProcessor.java:78)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processContent(MediaUploadCompletionProcessor.java:59)
     at org.wordpress.android.ui.posts.PostUtils.replaceMediaFileWithUrlInGutenbergPost(PostUtils.java:433)
     at org.wordpress.android.ui.uploads.MediaUploadReadyProcessor.replaceMediaFileWithUrlInPost(MediaUploadReadyProcessor.java:25)
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithMediaUrl(UploadService.java:611)
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithCurrentlyCompletedUploads(UploadService.java:459)
...
(14 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
@mkevins — your call on leaving this open or not ... removing triage label. 😄

**Comment by mkevins** [comment]
Thanks @oguzkocer !

I looked into this a bit, and it seems that the `MediaFile` has a null remote id somehow. It is passed in to update the url and id from the `UploadService` here: https://github.com/wordpress-mobile/WordPress-Android/blob/db1d3611f9b745fc0532f3990daf7be6bf153a5a/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadService.java#L612

It isn't clear why that would be null, so that might be worth investigating. It seems to be a very infrequent exception, but it's also recent, so maybe we can close this, and reopen it if the volume increases. In that case, it may be worth further investigation of either the `UploadService`, or `FluxC` to find out why a null id can be assigned to the media file after successful upload (and perhaps guarding to prevent calling `replaceMediaFileWithUrlInPost` if needed).
