### ISSUE TITLE
UploadSqlUtils.getPostModelsForPostUploadModels: too many SQL variables

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12229]
This is not a new issue and it's only happening to 4 users, but it's happening to them a lot. It also might point to an edge case we'd want to fix, so a quick look from a developer might be a good idea.

**Sentry Url**: https://sentry.io/share/issue/2fdbe7aac585419aa54f84d760fb003d/
**User Count**: 4
**Count**: 435
**First Release**: org.wordpress.android-13.9
**First Seen**: 2020-04-21T17:19:21Z
**Last Seen**: 2020-06-18T23:28:13Z
**24 Hours**: 39
**30 Days**: 416

The stacktrace in the Sentry issue contains more information, so I suggest checking it out.

```
EventBusException: Invoking subscriber failed
     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java:null)
     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1096)
     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:661)
     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1746)
     at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:549)
     at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:459)
...
(19 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
**Events:** 469
**Users affected:** 5
<sub>WORDPRESS-ANDROID-AS6: https://sentry.io/share/issue/2fdbe7aac585419aa54f84d760fb003d/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1623676656&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85980371-832e2700-b99f-11ea-9d44-3a83457d58db.png)</a>
