### ISSUE TITLE
Several NPEs in NotificationsListFragmentPage

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12227]
I combined several NPE crashes in the `NotificationsListFragmentPage` into a single issue. None of these issues are happening very frequently, but they are all probably easy to fix and we can fix them all in one go.

**Sentry Url**: https://sentry.io/share/issue/0a7bb29dcc6e476a9c6b52fbc65d3e9c/
**User Count**: 1
**Count**: 3
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-16T16:53:51.297000Z
**Last Seen**: 2020-06-17T16:10:06Z
**24 Hours**: 0
**30 Days**: 3

```
IllegalStateException: actionable_empty_view must not be null
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.hideEmptyView(NotificationsListFragmentPage.kt:235)
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.onDataLoaded(NotificationsListFragmentPage.kt:140)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.myNotifyDatasetChanged(NotesAdapter.java:134)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.access$900(NotesAdapter.java:41)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:356)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:346)
     at android.os.AsyncTask.finish(AsyncTask.java:695)
     at android.os.AsyncTask.access$600(AsyncTask.java:180)
     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
     at android.os.Handler.dispatchMessage(Handler.java:107)
...
(5 additional frame(s) were not displayed)
```

**Sentry Url**: https://sentry.io/share/issue/11e8fd49add5405796fc301c818b216a/
**User Count**: 1
**Count**: 1
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-18T21:38:46.945000Z
**Last Seen**: 2020-06-18T21:38:46Z
**24 Hours**: 1
**30 Days**: 1

```
IllegalStateException: actionable_empty_view must not be null
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.showEmptyView(NotificationsListFragmentPage.kt:283)
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.showEmptyViewForCurrentFilter(NotificationsListFragmentPage.kt:331)
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.onDataLoaded(NotificationsListFragmentPage.kt:142)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.myNotifyDatasetChanged(NotesAdapter.java:134)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.access$900(NotesAdapter.java:41)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:356)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:346)
     at android.os.AsyncTask.finish(AsyncTask.java:695)
     at android.os.AsyncTask.access$600(AsyncTask.java:180)
     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
...
(6 additional frame(s) were not displayed)
```

**Sentry Url**: https://sentry.io/share/issue/0086b32a5d8f4eca85ce612aa4b9003a/
**User Count**: 1
**Count**: 1
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-18T09:51:32.375000Z
**Last Seen**: 2020-06-18T09:51:32Z
**24 Hours**: 1
**30 Days**: 1

```
KotlinNullPointerException: 
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage$onEventMainThread$1.onResponse(NotificationsListFragmentPage.kt:394)
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage$onEventMainThread$1.onResponse(NotificationsListFragmentPage.kt:387)
     at org.wordpress.android.ui.notifications.utils.NotificationsActions$5.onResponse(NotificationsActions.java:108)
     at org.wordpress.android.ui.notifications.utils.NotificationsActions$5.onResponse(NotificationsActions.java:87)
     at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:76)
     at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:19)
     at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
     at android.os.Handler.handleCallback(Handler.java:874)
     at android.os.Handler.dispatchMessage(Handler.java:100)
     at android.os.Looper.loop(Looper.java:198)
...
(4 additional frame(s) were not displayed)
```

**Sentry Url**: https://sentry.io/share/issue/a38306ca83c247ec98009f3f7d6745bf/
**User Count**: 1
**Count**: 1
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-18T05:03:11.110000Z
**Last Seen**: 2020-06-18T05:03:11Z
**24 Hours**: 1
**30 Days**: 1

```
NullPointerException: Attempt to invoke virtual method 'void androidx.recyclerview.widget.RecyclerView.addOnScrollListener(androidx.recyclerview.widget.RecyclerView$OnScrollListener)' on a null object reference
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage$showNewUnseenNotificationsUI$1.run(NotificationsListFragmentPage.kt:357)
     at android.os.Handler.handleCallback(Handler.java:874)
     at android.os.Handler.dispatchMessage(Handler.java:100)
     at android.os.Looper.loop(Looper.java:198)
     at android.app.ActivityThread.main(ActivityThread.java:6729)
     at java.lang.reflect.Method.invoke(Method.java:null)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

**Sentry Url**: https://sentry.io/share/issue/66c700157cb245549ebefa4dab8d0e9b/
**User Count**: 1
**Count**: 1
**First Release**: org.wordpress.android@15.1-rc-1+881
**First Seen**: 2020-06-18T05:02:56.472000Z
**Last Seen**: 2020-06-18T05:02:56Z
**24 Hours**: 1
**30 Days**: 1

```
NullPointerException: Attempt to invoke virtual method 'android.widget.ImageView org.wordpress.android.ui.ActionableEmptyView.getImage()' on a null object reference
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.showEmptyViewForCurrentFilter(NotificationsListFragmentPage.kt:339)
     at org.wordpress.android.ui.notifications.NotificationsListFragmentPage.onDataLoaded(NotificationsListFragmentPage.kt:142)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.myNotifyDatasetChanged(NotesAdapter.java:134)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter.access$900(NotesAdapter.java:41)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:356)
     at org.wordpress.android.ui.notifications.adapters.NotesAdapter$ReloadNotesFromDBTask.onPostExecute(NotesAdapter.java:346)
     at android.os.AsyncTask.finish(AsyncTask.java:695)
     at android.os.AsyncTask.access$600(AsyncTask.java:180)
     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
     at android.os.Handler.dispatchMessage(Handler.java:107)
...
(5 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
Quite low numbers overall, but as Oguz mentions it's worth a look since these crashes do appear to be new in 15.1-rc-1 (881) and they're especially worth a look if they are easy to fix.

 I did a search for `NotificationsListFragmentPage` in Sentry and found that there have been 35 events recorded so far, which could be considered a high number for beta/RC releases.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=NotificationsListFragmentPage&sort=-timestamp&statsPeriod=30d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85979576-ffc00600-b99d-11ea-8695-8b916b021843.png)</a>
