### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence org.wordpress.android.editor.EditorFragm...

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12230]
It looks like we had this issue for quite some time and from a quick look it seems very easy to fix with a null check [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1591-L1600).

**Sentry Url**: https://sentry.io/share/issue/49102bcf1b0b45d6b0e858fb593895b8/
**User Count**: 550
**Count**: 985
**First Release**: org.wordpress.android-14.0-rc-2
**First Seen**: 2020-01-24T11:23:59Z
**Last Seen**: 2020-06-18T19:41:42Z
**24 Hours**: 11
**30 Days**: 263

```
NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence org.wordpress.android.editor.EditorFragmentAbstract.getTitle()' on a null object reference
     at org.wordpress.android.ui.posts.EditPostActivity.updateFromEditor(EditPostActivity.java:1617)
     at org.wordpress.android.ui.posts.EditPostActivity.lambda$z66Q6rgnL2-ilBgAFSI3ofQXDxo(null:0)
     at org.wordpress.android.ui.posts.-$$Lambda$EditPostActivity$z66Q6rgnL2-ilBgAFSI3ofQXDxo.invoke(null:4)
     at org.wordpress.android.ui.posts.editor.StorePostViewModel.updatePostObjectWithUI(StorePostViewModel.kt:112)
     at org.wordpress.android.ui.posts.editor.StorePostViewModel.access$updatePostObjectWithUI(StorePostViewModel.kt:34)
     at org.wordpress.android.ui.posts.editor.StorePostViewModel$updatePostObjectWithUIAsync$1.invoke(StorePostViewModel.kt:95)
     at org.wordpress.android.ui.posts.editor.StorePostViewModel$updatePostObjectWithUIAsync$1.invoke(StorePostViewModel.kt:34)
     at org.wordpress.android.ui.posts.EditPostRepository$updateAsync$1$isUpdated$1.invokeSuspend(EditPostRepository.kt:121)
     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
...
(4 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Thank for filing this @oguzkocer — we'll try to squeeze it in when we can.

**Comment by designsimply** [comment]
**Events:** 1,000
**Users affected:** 561
<sub>WORDPRESS-ANDROID-8FM: https://sentry.io/share/issue/49102bcf1b0b45d6b0e858fb593895b8/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1470017626&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/85980566-e750eb00-b99f-11ea-9cc3-a4a8ac7dab76.png)</a>
