### ISSUE TITLE
ApplicationNotResponding in UserAgent

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12259]
ANRs weren't available in Sentry until the last release, so this issue is not newly introduced. Please keep that in mind while debugging the issue so as not to limit it to the changes introduced recently.

**Sentry Url**: https://sentry.io/share/issue/09ee294fc5b3453bb0b2920117ae4387/
**User Count**: 712
**Count**: 1339
**First Release**: org.wordpress.android@15.0-rc-1+874
**First Seen**: 2020-06-03T13:44:42.073000Z
**Last Seen**: 2020-06-24T01:23:36Z
**24 Hours**: 296
**30 Days**: 1334

```
ApplicationNotResponding: Application Not Responding for at least 5000 ms.
     at org.wordpress.android.fluxc.network.UserAgent.<init>(UserAgent.java:18)
     at org.wordpress.android.modules.AppConfigModule.provideUserAgent(AppConfigModule.java:22)
     at org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.provideUserAgent(AppConfigModule_ProvideUserAgentFactory.java:37)
     at org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.get(AppConfigModule_ProvideUserAgentFactory.java:27)
     at org.wordpress.android.modules.AppConfigModule_ProvideUserAgentFactory.get(AppConfigModule_ProvideUserAgentFactory.java:10)
     at org.wordpress.android.fluxc.module.ReleaseNetworkModule_ProvideAccountRestClientFactory.get(ReleaseNetworkModule_ProvideAccountRestClientFactory.java:61)
     at org.wordpress.android.fluxc.module.ReleaseNetworkModule_ProvideAccountRestClientFactory.get(ReleaseNetworkModule_ProvideAccountRestClientFactory.java:15)
     at org.wordpress.android.fluxc.store.AccountStore_Factory.get(AccountStore_Factory.java:44)
     at org.wordpress.android.fluxc.store.AccountStore_Factory.get(AccountStore_Factory.java:12)
     at org.wordpress.android.modules.DaggerAppComponent.injectWordPress(DaggerAppComponent.java:5578)
...
(28 additional frame(s) were not displayed)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by antonis** [comment]
Probably fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/20296 since there are no occurrences after `24.3.1`. Feel free to reopen if the issue persist

**Comment by antonis** [comment]
> Probably fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/20296 since there are no occurrences after 24.3.1. Feel free to reopen if the issue persist

I'm reopening this issue since the ANR still persist after the fix and is related to a know limitation of the `getDefaultUserAgent` call https://issuetracker.google.com/issues/289118199#comment9

The issue seems to occur almost exclusively on low end devices.

**Comment by antonis** [comment]
The ANR roots in two places:

1. [The AppConfigModule](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/modules/AppConfigModule.java#L30) that uses [the FluxC implemantation](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/network/UserAgent.kt).
```
io.sentry.android.core.ApplicationNotResponding: Background ANR
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:509)
    at WV.ir.<init>(chromium-TrichromeWebViewGoogle6432.aab-stable-626111933:43)
    at WV.rC.<init>(chromium-TrichromeWebViewGoogle6432.aab-stable-626111933:8)
    at org.chromium.android_webview.AwBrowserProcess.f(chromium-TrichromeWebViewGoogle6432.aab-stable-626111933:106)
    at com.android.webview.chromium.M.e(chromium-TrichromeWebViewGoogle6432.aab-stable-626111933:208)
    at com.android.webview.chromium.M.b(chromium-TrichromeWebViewGoogle6432.aab-stable-626111933:42)
    at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(chromium-TrichromeWebViewGoogle6432.aab-stable-626111933:16)
    at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1355)
    at org.wordpress.android.fluxc.network.UserAgent.<init>(UserAgent.kt:17)
    at org.wordpress.android.modules.AppConfigModule.provideUserAgent(AppConfigModule.java:30)
```

2. [The AppInitialiser](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/java/org/wordpress/android/AppInitializer.kt#L1063).
```
io.sentry.android.core.ApplicationNotResponding: Background ANR
    at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:227)
    at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1355)
    at org.wordpress.android.AppInitializer$Companion$defaultUserAgent$2.invoke(AppInitializer.kt:1065)
    at org.wordpress.android.AppInitializer$Companion$defaultUserAgent$2.invoke(AppInitializer.kt:1063)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at org.wordpress.android.AppInitializer$Companion.getDefaultUserAgent(AppInitializer.kt:1063)
    at org.wordpress.android.AppInitializer$Companion$userAgent$2.invoke(AppInitializer.kt:1097)
    at org.wordpress.android.AppInitializer$Companion$userAgent$2.invoke(AppInitializer.kt:1096)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at org.wordpress.android.AppInitializer$Companion.getUserAgent(AppInitializer.kt:1096)
    at org.wordpress.android.AppInitializer.init(AppInitializer.kt:308)
    at org.wordpress.android.WordPressApp.onCreate(WordPressApp.java:20)
```

**Comment by irfano** [comment]
@antonis, is your investigation ongoing? Can I assign this issue and [WORDPRESS-ANDROID-2WA6](https://a8c.sentry.io/issues/5083633345/?referrer=github_integration) to you?

**Comment by antonis** [comment]
Hey @irfano 👋 
I'll be glad to continue looking at this. I've requested feedback internally (ref pcdRpT-5Us-p2#comment-9676) to see if we can avoid calling `getDefaultUserAgent` on initialisation when possible. I think that this might also be one of the root causes of https://github.com/wordpress-mobile/WordPress-Android/issues/20147

**Comment by antonis** [comment]
Reopening since the issue persist after https://github.com/wordpress-mobile/WordPress-Android/pull/20603:
* [WORDPRESS-ANDROID-2Y27](https://a8c.sentry.io/issues/5266717695/?referrer=github_integration)
* [JETPACK-ANDROID-QTP](https://a8c.sentry.io/issues/5260400500/?referrer=github_integration)

The rate seems lower but I'll keep monitoring how this evolves.

**Comment by antonis** [comment]
Added the `SSLCertsViewActivity` related crashes in a separate issue https://github.com/wordpress-mobile/WordPress-Android/issues/20786

**Comment by jkmassel** [comment]
Closing this issue — the referenced Sentry issue no longer exists (the share link returns 404), which means this ANR hasn't been seen in at least 90 days. If this ANR resurfaces, it will appear as a new Sentry issue.
