### ISSUE TITLE
NoSuchElementException: See issue #12064; zendesk-unknown-plan-ids [0]

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12340]
@ashiagr This might be an interest for you.

**Sentry Url**: https://sentry.io/share/issue/4f971313a6ac4ba08fff337f957e5031/
**User Count**: 2
**Count**: 8
**First Release**: org.wordpress.android@15.1+885
**First Seen**: 2020-07-01T05:02:04.193000Z
**Last Seen**: 2020-07-02T22:40:04Z
**24 Hours**: 3
**30 Days**: 8

```
NoSuchElementException: See issue #12064; zendesk-unknown-plan-ids [0]
     at org.wordpress.android.support.ZendeskPlanFieldHelper.getHighestPlan(ZendeskPlanFieldHelper.kt:92)
     at org.wordpress.android.support.ZendeskHelperKt.buildZendeskCustomFields(ZendeskHelper.kt:417)
     at org.wordpress.android.support.ZendeskHelperKt.buildZendeskConfig(ZendeskHelper.kt:382)
     at org.wordpress.android.support.ZendeskHelperKt.access$buildZendeskConfig(ZendeskHelper.kt:1)
     at org.wordpress.android.support.ZendeskHelper$showAllTickets$2.invoke(ZendeskHelper.kt:195)
     at org.wordpress.android.support.ZendeskHelper$showAllTickets$2.invoke(ZendeskHelper.kt:46)
     at org.wordpress.android.support.ZendeskHelper.requireIdentity(ZendeskHelper.kt:299)
     at org.wordpress.android.support.ZendeskHelper.showAllTickets(ZendeskHelper.kt:190)
     at org.wordpress.android.ui.accounts.HelpActivity.showZendeskTickets(HelpActivity.kt:123)
     at org.wordpress.android.ui.accounts.HelpActivity.access$showZendeskTickets(HelpActivity.kt:27)
...
(12 additional frame(s) were not displayed)
```

**Comment by oguzkocer** [comment]
I just merged a few similar issues, so the total number is more than in the original description. Still not too high, but would be good to address.
