### ISSUE TITLE
[ImageBlockProcessor] UnsupportedOperationException: JsonNull

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12395]
@mkevins This seems to be very similar to some recent issues you worked on. Do you mind taking a quick look at it?

**Sentry Url**: https://sentry.io/share/issue/7a947ef52c4d46e0928004e1dbdf826f/
**User Count**: 16
**Count**: 77
**First Release**: org.wordpress.android@15.2-rc-1+886
**First Seen**: 2020-07-02T13:02:56.074000Z
**Last Seen**: 2020-07-09T05:10:27Z
**24 Hours**: 18
**30 Days**: 77

```
UnsupportedOperationException: JsonNull
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.ImageBlockProcessor.processBlockJsonAttributes(ImageBlockProcessor.java:36)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.BlockProcessor.processBlock(BlockProcessor.java:91)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processBlock(MediaUploadCompletionProcessor.java:78)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processContent(MediaUploadCompletionProcessor.java:59)
     at org.wordpress.android.ui.posts.mediauploadcompletionprocessors.MediaUploadCompletionProcessor.processContent(MediaUploadCompletionProcessor.java:60)
     at org.wordpress.android.ui.posts.PostUtils.replaceMediaFileWithUrlInGutenbergPost(PostUtils.java:433)
     at org.wordpress.android.ui.uploads.MediaUploadReadyProcessor.replaceMediaFileWithUrlInPost(MediaUploadReadyProcessor.java:25)
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithMediaUrl(UploadService.java:611)
     at org.wordpress.android.ui.uploads.UploadService.updatePostWithCurrentlyCompletedUploads(UploadService.java:459)
     at org.wordpress.android.ui.uploads.UploadService.updateOnePostModelWithCompletedAndFailedUploads(UploadService.java:707)
...
(15 additional frame(s) were not displayed)
```

**Comment by oguzkocer** [comment]
Closing this issue to open a new one with more accurate details and some analysis.
