### ISSUE TITLE
StringIndexOutOfBoundsException in SignupEpilogueFragment.createDisplayNameFromEmail

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#12399]
**Sentry Url**: https://sentry.io/share/issue/ad03935f8e3d4eb2a46e8168e3e3c54d/
**User Count**: 31
**Count**: 88
**First Release**: org.wordpress.android-12.3.1
**First Seen**: 2019-05-11T12:59:11Z
**Last Seen**: 2020-07-08T15:43:35Z
**24 Hours**: 4
**30 Days**: 23

```
StringIndexOutOfBoundsException: length=0; index=1
     at org.wordpress.android.ui.accounts.signup.SignupEpilogueFragment.createDisplayNameFromEmail(SignupEpilogueFragment.java:541)
     at org.wordpress.android.ui.accounts.signup.SignupEpilogueFragment.populateViews(SignupEpilogueFragment.java:622)
     at org.wordpress.android.ui.accounts.signup.SignupEpilogueFragment.onAccountChanged(SignupEpilogueFragment.java:478)
...
(4 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Heads up for you @renanferrari 😄
