### ISSUE TITLE
Reader: Error in logcat when enabling notifications on follow site

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#12857]
### Expected behavior
Enabling notifications on follow site from the more menu on a reader post should not display error in the logs

### Actual behavior
Enabling notifications on follow site from the more menu on a reader post displays error in the logs
```
org.wordpress.android.prealpha E/SQLiteDatabase: Error inserting EMAIL_POSTS_FREQUENCY=null SHOULD_EMAIL_POSTS=false FEED_ID=108454787 SUBSCRIPTION_ID=609519261 BLOG_NAME=Site Title SHOULD_NOTIFY_POSTS=false BLOG_ID=182078938 URL=http://gfsdgw343ye4atgaeye5yh.car.blog SHOULD_EMAIL_COMMENTS=false
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: SubscriptionModel.FEED_ID, SubscriptionModel.URL (code 2067)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1417)
        at com.yarolegovich.wellsql.InsertQuery.execute(InsertQuery.java:61)
        at org.wordpress.android.fluxc.persistence.AccountSqlUtils.updateSubscriptions(AccountSqlUtils.java:147)
        at org.wordpress.android.fluxc.store.AccountStore.updateSubscriptions(AccountStore.java:1307)
        at org.wordpress.android.fluxc.store.AccountStore.onAccountAction(AccountStore.java:912)
        at org.wordpress.android.fluxc.store.AccountStore.onAction(AccountStore.java:818)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
        at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

### Steps to reproduce the behavior
1. Launch app and go to the Reader -> Following tab
2. Click on More -> unfollow blog
3. Click on More -> follow blog
4. Click on More -> enable notifs
6. See error in logcat

![logcat error](https://user-images.githubusercontent.com/1405144/91852471-86cf7a00-ec7e-11ea-9351-b6d02f8d6ae3.gif)

Noticed here: https://github.com/wordpress-mobile/WordPress-Android/pull/12667#issuecomment-684654211 but reproducible on develop as well.

**Comment by ashiagr** [comment]
This is fixed. Duplicate of https://github.com/wordpress-mobile/WordPress-Android/issues/13812.
