### ISSUE TITLE
Reader crashes when I open a post with a video on API 23

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-Android#13070]
### Expected behavior
The app doesn't freeze+crash when I open a post with a video.

### Actual behavior
The app freezes and crashes after +-5s after I open a post with a video.

```
Process: org.wordpress.android.beta, PID: 20806
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at com.android.webview.chromium.WebViewContentsClientAdapter.getDefaultVideoPoster(WebViewContentsClientAdapter.java:1208)
        at org.chromium.android_webview.DefaultVideoPosterRequestHandler$1.run(DefaultVideoPosterRequestHandler.java:39)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

### Steps to reproduce the behavior
1. The app works on API 29, I was able to reproduce this behavior on Emulator API 23
2. Go to reader
3. Open a post with a video (eg. https://wp.me/sbblmJ-video)
4. Notice the app crashes

##### Tested on [device], Android [version], WPAndroid [version]
Emulator API 23 (works on API 29)

**Comment by bummytime** [comment]
@malinajirka nice sleuthing! 🕵️  I _think_ this NPE is related to #11791. I also found the following Sentry issues:
- https://sentry.io/share/issue/7f9c48c8dba04519a745cc00768bdd85/
- https://sentry.io/share/issue/9d64bf025649420fb83bac618692477b/
- https://sentry.io/share/issue/67d62c7540d84aaa905934ede9da4888/

Should we close this one in favor of #11791 (or vise versa)? With the repro steps you identified, is there anything that we can do to mitigate this?

**Comment by malinajirka** [comment]
Closing in favor of #11791
