### ISSUE TITLE
IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13251]
**Sentry Url**: https://sentry.io/share/issue/d6f9d3ea2f804f0491cc08d97f112fe8/
**User Count**: 450
**Count**: 604
**First Release**: org.wordpress.android@15.7-rc-2+918
**First Seen**: 2020-09-14T08:42:39.457000Z
**Last Seen**: 2020-10-28T10:19:58Z
**24 Hours**: 4
**30 Days**: 563

```
IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
     at org.wordpress.android.widgets.WPSnackbar.<init>(WPSnackbar.java:30)
     at org.wordpress.android.widgets.WPSnackbar.make(WPSnackbar.java:85)
     at org.wordpress.android.ui.reader.discover.ReaderDiscoverFragment.showSnackbar(ReaderDiscoverFragment.kt:175)
     at org.wordpress.android.ui.reader.discover.ReaderDiscoverFragment.access$showSnackbar(ReaderDiscoverFragment.kt:53)
     at org.wordpress.android.ui.reader.discover.ReaderDiscoverFragment$initViewModel$3$1.invoke(ReaderDiscoverFragment.kt:143)
     at org.wordpress.android.ui.reader.discover.ReaderDiscoverFragment$initViewModel$3$1.invoke(ReaderDiscoverFragment.kt:53)
     at org.wordpress.android.viewmodel.Event.applyIfNotHandled(Event.kt:23)
     at org.wordpress.android.ui.reader.discover.ReaderDiscoverFragment$initViewModel$3.onChanged(ReaderDiscoverFragment.kt:142)
     at org.wordpress.android.ui.reader.discover.ReaderDiscoverFragment$initViewModel$3.onChanged(ReaderDiscoverFragment.kt:53)
...
(43 additional frame(s) were not displayed)
```

**Comment by emilylaguna** [comment]
I'm unable to reproduce on my Android device or in the emulator.

👋 @malinajirka I see that you recently made the change to the [offending line](https://github.com/wordpress-mobile/WordPress-Android/blame/develop/WordPress/src/main/java/org/wordpress/android/ui/reader/discover/ReaderDiscoverFragment.kt#L175). Could you please take a look at this?
