### ISSUE TITLE
IllegalStateException: jsonInterests.optJSONObject(i) must not be null

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13303]
**Sentry Url**: https://sentry.io/share/issue/95aeaf8dea364fdcb5d45550c3110de0/
**User Count**: 132
**Count**: 863
**First Release**: org.wordpress.android@15.8.1+932
**First Seen**: 2020-10-21T17:48:22.658000Z
**Last Seen**: 2020-11-06T07:56:03Z
**24 Hours**: 43
**30 Days**: 861

```
IllegalStateException: jsonInterests.optJSONObject(i) must not be null
     at org.wordpress.android.ui.reader.repository.usecases.ParseDiscoverCardsJsonUseCase.parseInterestCard(ParseDiscoverCardsJsonUseCase.kt:34)
     at org.wordpress.android.ui.reader.services.discover.ReaderDiscoverLogic.parseCards(ReaderDiscoverLogic.kt:153)
     at org.wordpress.android.ui.reader.services.discover.ReaderDiscoverLogic.handleRequestDiscoverDataResponse(ReaderDiscoverLogic.kt:132)
     at org.wordpress.android.ui.reader.services.discover.ReaderDiscoverLogic.access$handleRequestDiscoverDataResponse(ReaderDiscoverLogic.kt:49)
     at org.wordpress.android.ui.reader.services.discover.ReaderDiscoverLogic$requestDataForDiscover$1$listener$1$1.invokeSuspend(ReaderDiscoverLogic.kt:106)
...
(1 additional frame(s) were not displayed)
```

**Comment by diegoreymendez** [comment]
Hey @AdamGrzybkowski !  I'm pinging you since you did the most recent modifications to `ParseDiscoverCardsJsonUseCase.kt` around the area that's showing up in the crash log for this issue.

Can I ask you to take a look at this crash?

I'm marking this as medium priority ([high severity, low impact](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/docs/issue-triage.md#prioritization)).  Feel free to revisit the priority.

**Comment by designsimply** [comment]
WORDPRESS-ANDROID-VHE: https://sentry.io/share/issue/95aeaf8dea364fdcb5d45550c3110de0/

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=issue.id%3A1971496684&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105526985-5c6b7100-5ca0-11eb-9ff9-f376ede25ebe.png)</a>

This crash appears to be trending way down and there have been no new cases of it reported in Sentry in version 16.2 or higher. Recommend closing.
