### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'java.lang.String org.wordpress.android.login.LoginBaseDiscove...

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13418]
**Sentry Url**: https://sentry.io/share/issue/9721304529a044e2a0b8bd82f2664128/
**User Count**: 88
**Count**: 400
**First Release**: org.wordpress.android@15.8-rc-2+927
**First Seen**: 2020-10-02T12:44:19.353112Z
**Last Seen**: 2020-11-18T08:02:02Z
**24 Hours**: 12
**30 Days**: 275

```
NullPointerException: Attempt to invoke interface method 'java.lang.String org.wordpress.android.login.LoginBaseDiscoveryFragment$LoginBaseDiscoveryListener.getRequestedSiteAddress()' on a null object reference
     at org.wordpress.android.login.LoginBaseDiscoveryFragment.initiateDiscovery(LoginBaseDiscoveryFragment.java:35)
     at org.wordpress.android.login.LoginSiteAddressFragment.handleConnectSiteInfoForWordPress(LoginSiteAddressFragment.java:418)
     at org.wordpress.android.login.LoginSiteAddressFragment.onFetchedConnectSiteInfo(LoginSiteAddressFragment.java:375)
...
(3 additional frame(s) were not displayed)
```

**Comment by renanferrari** [comment]
I'm labeling this issue as high priority ([high severity, medium impact](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/docs/issue-triage.md#prioritization)) and assigning it to myself since I believe it's related to #12978.
