### ISSUE TITLE
UninitializedPropertyAccessException lateinit property editorMediaListener has not been initialized

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#13649]
Sentry Url: https://sentry.io/share/issue/99b88499bf6c46e48ce8036c8a47223d/

```
2020-12-21 11:50:23.222 7425-7425/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 7425
    kotlin.UninitializedPropertyAccessException: lateinit property editorMediaListener has not been initialized
        at org.wordpress.android.ui.posts.editor.media.EditorMedia.access$getEditorMediaListener$p(EditorMedia.kt:52)
        at org.wordpress.android.ui.posts.editor.media.EditorMedia$retryFailedMediaAsync$1.invokeSuspend(EditorMedia.kt:233)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I was able to reproduce:
1. create a story with a new slide and add some text on it
2. once you publish it, turn airplane mode ON to prevent the image from being uploaded and incur in error
3. wait for the error to appear
4. open the failed Post in the draft post list
5. tap on the failed Story block, and when the retry dialog appears, tap RETRY
6. wait for a few seconds and watch it ANR and crash

**Comment by mzorz** [comment]
Closing via #13659
