### ISSUE TITLE
NullPointerException: mediaStore.getMediaWithLocalId(localMediaId) must not be null

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#13658]
Sentry Url: https://sentry.io/share/issue/1b40a91b8aee4f4dabcd377427cd1cbb/

```
java.lang.NullPointerException: mediaStore.getMediaWithLocalId(localMediaId) must not be null
    at org.wordpress.android.ui.posts.editor.StoriesEventListener.onRetryUploadForMediaCollection(StoriesEventListener.kt:278)
    at org.wordpress.android.ui.posts.EditPostActivity.onRetryUploadForMediaCollection(EditPostActivity.java:3321)
    at org.wordpress.android.editor.gutenberg.GutenbergEditorFragment$17.onClick(GutenbergEditorFragment.java:722)
    at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
    at java.lang.Thread.run(Thread.java:764)

```

The user logs show this:

```
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
15:34:53
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
15:34:53
generic
d/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
info
15:34:53
generic
i/WordPress-MEDIA: MediaUploadHandler > 107 - progress: 0.053134926
info
15:34:53
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
15:34:53
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
15:34:53
generic
d/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
info
15:34:53
generic
i/WordPress-MEDIA: MediaUploadHandler > 103 - progress: 0.69968206
info
15:34:53
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
15:34:53
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
15:34:53
generic
d/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
info
15:34:53

[...]

generic
i/WordPress-MEDIA: MediaUploadHandler > 103 - progress: 0.72335553
info
15:34:54
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
15:34:54
generic
d/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
info
15:34:54
generic
i/WordPress-MEDIA: MediaUploadHandler > 107 - progress: 0.054344654
info
15:34:54
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
15:34:54
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
15:34:54
generic
d/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
info
15:34:54
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
15:34:54
exception
NullPointerException: mediaStore.getMediaWithLocalId(localMediaId) must not be null
```

**Comment by mzorz** [comment]
Closing via #13660
