### ISSUE TITLE
IllegalArgumentException: Required value was null

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#13662]
Sentry Url: https://sentry.io/share/issue/a32c45528c414af8973965f6c9edd293/
Senry Url 2: https://sentry.io/share/issue/fa68ef7d97294b979c94299bb1d78f0d/

```
java.lang.IllegalArgumentException: Required value was null.
    at org.wordpress.android.ui.posts.editor.StoriesEventListener.onStoryFrameSaveCompleted(StoriesEventListener.kt:123)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5648)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

Logs for the user show a low memory situation, let's keep an eye on this and see if it has more occurences:

```
state: saveInstanceState
screen: PagesActivity
info
19:48:43
ui.lifecycle
state: stopped
screen: PagesActivity
info
19:48:43
generic
d/WordPress-API: ReactNativeStore: executeRequest
info
19:48:44
generic
d/WordPress-API: Dispatching action: PostAction-UPDATE_POST
info
19:48:46
generic
d/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
info
19:48:46
generic
d/WordPress-POSTS: PageStore: getPagesFromDb
info
19:48:46
device.event
Low memory
level: 10
action: LOW_MEMORY
warning
19:49:03
exception
IllegalArgumentException: Required value was null.
```

**Comment by mzorz** [comment]
I was able to reproduce this one on [16.3 tag](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/16.3):

0. set the developer options to "don't keep activities"
1. create a story from scratch and publish it
2. go to the published Posts list
3. open the Story post you just published, tap on the block and then tap on the edit tool icon
4. when the Story composer appears, tap on the + control to add a new slide (that's on the right-bottom corner of the screen)
5. pick an image, add some text on it
6. tap on the ✅ icon on the top-right of the screen to save your changes
7. observe the crash happens

**Comment by designsimply** [comment]
I noticed the crashes recorded in Sentry for these two issues are limited to Android 5 and Android 6, 7 respectively.

**Events in the last 90d:** 7
**Users affected in the last 90d:** 7
**OS:** Android 5.1.x
<sub>WORDPRESS-ANDROID-11X4: https://sentry.io/share/issue/a32c45528c414af8973965f6c9edd293/</sub>

**Events in the last 90d:** 9
**Users affected in the last 90d:** 9
**OS:** Android 6.0.x and 7.x
<sub>WORDPRESS-ANDROID-11XG: https://sentry.io/share/issue/fa68ef7d97294b979c94299bb1d78f0d/</sub>

A search in Sentry Discover for `culprit:"org.wordpress.android.ui.posts.editor.StoriesEventListener in onStoryFrameSaveCompleted" ` returned  178 total events from the past 90 days:

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=version&field=os&field=device.family&field=culprit&name=All+Events&project=1438088&query=culprit%3A%22org.wordpress.android.ui.posts.editor.StoriesEventListener+in+onStoryFrameSaveCompleted%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1&yAxis=count%28%29">![image](https://user-images.githubusercontent.com/1119271/105532824-95a7df00-5ca8-11eb-9018-023dfff05def.png)</a>

**Comment by mzorz** [comment]
I was able to reproduce this one on [`17.0-rc-2` ](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/17.0-rc-2)

```
    --------- beginning of crash
2021-03-25 13:34:44.813 24971-24971/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 24971
    org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
        at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:530)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:512)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:504)
        at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Required value was null.
        at org.wordpress.android.ui.posts.editor.StoriesEventListener.onStoryFrameSaveCompleted(StoriesEventListener.kt:173)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:504) 
        at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```
Steps to reproduce:
1. create a story and publish it
2. create a new Post
3. observe the crash

**Comment by mzorz** [comment]
Closing via #14351
