### ISSUE TITLE
Crash report 2.8 - OOM in ImageHelper

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#1369]
<pre>
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:200)
       at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
       at java.util.concurrent.FutureTask.run(FutureTask.java:138)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
       at java.lang.Thread.run(Thread.java:1019)
Caused by: java.lang.OutOfMemoryError: bitmap size exceeds VM budget
       at android.graphics.BitmapFactory.nativeDecodeStream(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:470)
       at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:284)
       at org.wordpress.android.util.ImageHelper$BitmapWorkerTask.doInBackground(ImageHelper.java:219)
       at org.wordpress.android.util.ImageHelper$BitmapWorkerTask.doInBackground(ImageHelper.java:183)
       at android.os.AsyncTask$2.call(AsyncTask.java:185)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
       at java.util.concurrent.FutureTask.run(FutureTask.java:138)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
       at java.lang.Thread.run(Thread.java:1019)
</pre>

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
