### ISSUE TITLE
IllegalStateException: Fetch already in progress.

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#13814]
**Sentry Url**: https://sentry.io/share/issue/276329361a114955bf64043333a8b202/
**User Count**: 536
**Count**: 611
**First Release**: org.wordpress.android@16.2-rc-2+959
**First Seen**: 2020-11-25T08:29:44.213000Z
**Last Seen**: 2021-01-19T08:12:20Z
**24 Hours**: 20
**30 Days**: 459

```
IllegalStateException: Fetch already in progress.
     at org.wordpress.android.ui.sitecreation.usecases.FetchHomePageLayoutsUseCase.fetchStarterDesigns(FetchHomePageLayoutsUseCase.kt:25)
     at org.wordpress.android.ui.sitecreation.theme.HomePagePickerViewModel$fetchLayouts$1.invokeSuspend(HomePagePickerViewModel.kt:93)
```

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/13822
