### ISSUE TITLE
Reader: tapping the login link in the filters bottom sheet in logged-out Reader causes the app to freeze and close

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-Android#13987]
To prepare:

* Add a self-hosted site.
* Log out of the app.

To test: 

1. Go to Reader > Following > Filter.
1. Observe there are zero sites and topics followed in the bottom sheet that appears.
1. Tap the "Log in to WordPress.com" link inside the bottom sheet.

**Result:** the app stops responding if you tap the login link in the filters bottom sheet in logged-out Reader. ([41s](https://cloudup.com/cd2nn3UnG16))

<img src="https://user-images.githubusercontent.com/1119271/107105988-75b70600-67e6-11eb-82f6-98dc8d4884a0.png" width="270" alt="image">
<sup>Tested with WPAndroid 16.6-rc-2 on Pixel 3 Android 11.</sup>

**Comment by develric** [comment]
Sharing a bit of searching in the GH issues. I think this is possibly related to #13153 

On my OnePlus 7T with Android 10 I can reproduce the issue but not always, meaning like 4 times out of 10 it reproduces and 6 times it works; so at gut level it could seem like some sort of race condition but cannot be sure.

The above mentioned 13153 issue seems much correlated and I was able to get basically the same stack error like below for 16.6-rc-2

```
2021-02-08 11:49:16.451 3663-3663/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 3663
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1703)
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1743)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
        at org.wordpress.android.ui.main.WPMainNavigationView.updateCurrentPosition(WPMainNavigationView.kt:170)
        at org.wordpress.android.ui.main.WPMainNavigationView.setCurrentSelectedPage(WPMainNavigationView.kt:64)
        at org.wordpress.android.ui.main.WPMainActivity$1.run(WPMainActivity.java:552)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
@designsimply not sure if the issue always happens in your case, if so, given it does not reproduce every time on my device, would be good if you could confirm the following. Sampling back on releases first one for which I can reproduce the above seems to be 15.4. If confirmed, based on [release notes](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/15.4) of that version probably there is something to investigate further in the interaction between that login link in the reader bottom sheet and the introduction of the new login flow. Let me know wdyt 🙇

**Comment by designsimply** [comment]
So far, the problem happened every time on my Pixel 3 device using 16.6-rc-2. Are you asking if I can also confirm it happens if I install the 15.4 apk from the GitHub releases section?

**Comment by develric** [comment]
>So far, the problem happened every time on my Pixel 3 device using 16.6-rc-2

That sounds good, in this case yep, the goal would be to confirm it happens with 15.4 but not with 15.3. In this way we should be confident we at least narrowed down to the version where the issue was introduced; thanks for your time Sheri 🙇
