### ISSUE TITLE
Fix NullPointerException in the new my site fragment onSaveInstanceState

### ISSUE THREAD

**Issue by planarvoid** [wordpress-mobile/WordPress-Android#14024]
I've experienced the following crash while debugging:

```
java.lang.NullPointerException: recycler_view must not be null
        at org.wordpress.android.ui.mysite.ImprovedMySiteFragment.onSaveInstanceState(ImprovedMySiteFragment.kt:336)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2864)
        at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:434)
        at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:400)
        at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:143)
        at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2398)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)
        at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:512)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
```

**Comment by renanferrari** [comment]
I've looked a bit into this but I wasn't able to reproduce it. Do you remember what you were doing when the crash happened?

**Comment by planarvoid** [comment]
oh yeah, sorry for not giving the context. I think our bottom navigation sometimes causes this issue (I've seen it in other fragments). I think the fragment is initialized without a view and when it gets killed, we try to save instance but we don't have the view. The fix should be to add safe call to the view `?`. 

I don't have consistent steps to repro it. I was switching randomly between bottom nav tabs and I've left the app when it crashed.
