### ISSUE TITLE
EventBusException: Subscriber class org.wordpress.android.ui.jetpack.JetpackCapabilitiesUseCase already registered t...

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#14106]
**Sentry Url**: https://sentry.io/share/issue/f764090f74314f32a43e09ab9240713b/
**User Count**: 86
**Count**: 182
**First Release**: org.wordpress.android@16.7-rc-1+988
**First Seen**: 2021-02-08T23:54:21.978000Z
**Last Seen**: 2021-02-18T13:36:42Z
**24 Hours**: 35
**30 Days**: 182

```
EventBusException: Subscriber class org.wordpress.android.ui.jetpack.JetpackCapabilitiesUseCase already registered to event class org.wordpress.android.fluxc.store.SiteStore$OnJetpackCapabilitiesFetched
     at org.wordpress.android.fluxc.Dispatcher.register(Dispatcher.java:24)
     at org.wordpress.android.ui.jetpack.JetpackCapabilitiesUseCase.fetchJetpackCapabilities(JetpackCapabilitiesUseCase.kt:68)
     at org.wordpress.android.ui.jetpack.JetpackCapabilitiesUseCase.fetchJetpackPurchasedProducts(JetpackCapabilitiesUseCase.kt:48)
     at org.wordpress.android.ui.main.MySiteFragment$updateScanAndBackup$1.invokeSuspend(MySiteFragment.kt:291)
...
(6 additional frame(s) were not displayed)
```

**Comment by malinajirka** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/14101
