### ISSUE TITLE
NullPointerException: row_scan must not be null

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#14107]
**Sentry Url**: https://sentry.io/share/issue/d4d49740d05249ffaf6922b53df0d3e6/
**User Count**: 97
**Count**: 243
**First Release**: org.wordpress.android@16.7-rc-1+988
**First Seen**: 2021-02-10T14:31:13.613000Z
**Last Seen**: 2021-02-18T14:22:07Z
**24 Hours**: 31
**30 Days**: 241

```
NullPointerException: row_scan must not be null
     at org.wordpress.android.ui.main.MySiteFragment.updateScanAndBackupVisibility(MySiteFragment.kt:299)
     at org.wordpress.android.ui.main.MySiteFragment.access$updateScanAndBackupVisibility(MySiteFragment.kt:183)
     at org.wordpress.android.ui.main.MySiteFragment$updateScanAndBackup$1.invokeSuspend(MySiteFragment.kt:289)
...
(2 additional frame(s) were not displayed)
```

**Comment by renanferrari** [comment]
I'm closing this as it has already been addressed by #14108.
