### ISSUE TITLE
NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParame...

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#14150]
**Sentry Url**: https://sentry.io/share/issue/84d9ff222a3248ccab6c168bf7de8361/
**User Count**: 370
**Count**: 1143
**First Release**: org.wordpress.android@16.7+1002
**First Seen**: 2021-02-24T21:33:58.670000Z
**Last Seen**: 2021-02-25T10:17:21Z
**24 Hours**: 1126
**30 Days**: 1126

```
NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter emoji
     at org.wordpress.android.fluxc.model.layouts.GutenbergLayoutCategoryModel.<init>(null:19)
     at org.wordpress.android.fluxc.model.layouts.GutenbergLayoutCategoryModel.<init>(GutenbergLayoutCategoryModel.kt:19)
     at org.wordpress.android.fluxc.model.layouts.GutenbergLayoutCategoryModelKt.transform(GutenbergLayoutCategoryModel.kt:28)
     at org.wordpress.android.fluxc.model.layouts.GutenbergLayoutCategoryModelKt.transform(GutenbergLayoutCategoryModel.kt:45)
     at org.wordpress.android.fluxc.persistence.SiteSqlUtils.insertOrReplaceBlockLayouts(SiteSqlUtils.java:335)
     at org.wordpress.android.fluxc.store.SiteStore.handleFetchedBlockLayouts(SiteStore.java:2189)
     at org.wordpress.android.fluxc.store.SiteStore.onAction(SiteStore.java:1582)
...
(4 additional frame(s) were not displayed)
```

**Comment by ceyhun** [comment]
@loremattei The Sentry link doesn't seem to work, I'm getting a `Page Not Found` error when I click it.

**Comment by loremattei** [comment]
Thanks for the heads up @ceyhun! I guess someone wanted to share it while working on it and didn't notice it was already shared. Sentry isn't great in this case and generates a new link. 
I've fixed the description with the new link now. 

btw: @antonis and @geriux already took care of this.

**Comment by antonis** [comment]
Hey @loremattei, @ceyhun  👋 
Thank you for reporting this 🙇 

A server side fix was applied (internal ref: `pb3aDo-Pe-p2`) to stop the Android app from crashing and a [client side fix will be included in the next version](https://github.com/wordpress-mobile/WordPress-Android/pull/14153) to prevent such issue from occurring in the future.

I'm closing this issue. Please reopen if the issue persists 🙇
