### ISSUE TITLE
Unable to upload post with WordPress.com REST API v.1.2

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-Android#14921]
It was reported in 4087101-zd-woothemes that the user was having trouble updating/uploading posts through the app. They've tried re-installing the app and the issue seems to happen on the app only.

In the app log, the following error can be found. I removed the site ID but it can be retrieved in the ticket I linked.

```
26 - [Jun-22 16:16 API] Volley error on https://public-api.wordpress.com/rest/v1.2/sites/{site-id}/posts/7611/?context=edit&locale=en_IN - exception: null
27 - [Jun-22 16:16 API] StackTrace: com.android.volley.TimeoutError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:173)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

28 - [Jun-22 16:16 API] Dispatching action: UploadAction-PUSHED_POST
29 - [Jun-22 16:16 API] Dispatching action: PostAction-PUSHED_POST
30 - [Jun-22 16:16 POSTS] PostUploadHandler > Post upload failed. GENERIC_ERROR: 
31 - [Jun-22 16:16 MAIN] Error message:  ,Error Type: GENERIC_ERROR
32 - [Jun-22 16:16 POSTS] updateNotificationErrorForPost: There was an error uploading this post: We couldn't complete this action..
33 - [Jun-22 16:16 STATS] 🔵 Tracked: my_site_icon_upload_unsuccessful
34 - [Jun-22 16:16 STATS] 🔵 Tracked: notification_shown, Properties: {"notification_type":"post_upload_error"}
```

When I visited the URL, I wasn't able to load the page. If I changed `v1.2` to `v.1.1`, I was able to load the page with the following response:

`{"error":"unauthorized","message":"User cannot edit post"}`

##### Tested on LYF LS-5002, WPAndroid 17.5

**Comment by reginabally** [comment]
On another ticket (4087098-zd-woothemes) from the same user, I found this error in the app log (actual site-id removed):

```
89 - [Jun-22 16:12 API] Volley error on https://public-api.wordpress.com/rest/v1.1/sites/{site-id}/posts/?number=60&meta=autosave&order=DESC&fields=ID%2Cmodified%2Cstatus%2Cmeta&status=draft%2Cpending&context=edit&meta_fields=autosave.modified&order_by=date&locale=en_IN - exception: okhttp3.internal.http2.StreamResetException: stream was reset: REFUSED_STREAM
```

Is this something related to the user's account?

**Comment by thehenrybyrd** [comment]
Internal troubleshooting at p4a5px-2Ks, closing for now (will reopen if reproducible)
