### ISSUE TITLE
ApplicationNotResponding: Application Not Responding for at least 5000 ms.

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15080]
**Sentry Url**: https://sentry.io/share/issue/a7e72546e49b43f78dd96407c1686d1c/
**User Count**: 1313
**Count**: 28087
**First Release**: org.wordpress.android@15.0-rc-1+874
**First Seen**: 2020-06-05T12:53:14.935000Z
**Last Seen**: 2021-07-27T08:56:17Z
**24 Hours**: 33
**30 Days**: 1184

```
ApplicationNotResponding: Application Not Responding for at least 5000 ms.
     at org.wordpress.android.WordPressDB.<init>(WordPressDB.java:179)
     at org.wordpress.android.WordPress.createAndVerifyWpDb(WordPress.java:500)
     at org.wordpress.android.WordPress.initWpDb(WordPress.java:490)
     at org.wordpress.android.WordPress.onCreate(WordPress.java:291)
...
(12 additional frame(s) were not displayed)
```

**Comment by AliSoftware** [comment]
Not new but seems to happen at a steady rate since 15.0, so maybe worth monitoring.

**Comment by AmandaRiu** [comment]
**Crash Triage:**

This is a tough one. The error is basically saying that `WordPress.onCreate` didn't finish within 5 seconds and the ANR was thrown while processing `WordPressDB <init>`. I looked at the changes from WPAndroid version `14.9 (FluxC 1.6.12)` to `15.0-rc-1 (FluxC 1.6.13)` and noticed there were no changes to `WordPressDB` so I don't believe the issue is with that class specifically. Several other items are processed before we initialize `WordPressDB` and the only item that really stands out is `initWellSql`. [We did tweak the `CursorWindow` size of the database in this release](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1586) but only on debug builds and even if that were a factor it would only come into play on Android P and higher. Some additional dagger modules were added, but nothing stands out.

**Comment by jkmassel** [comment]
Closing this issue — the referenced Sentry issue no longer exists (the share link returns 404). This was an ANR in WordPressDB from 2020 that was being monitored. If this ANR is still occurring, it would appear as a new Sentry issue.
