### ISSUE TITLE
Self-Hosted Sites: Crash on creating a post with Aztec Editor enabled 

### ISSUE THREAD

**Issue by ashiagr** [wordpress-mobile/WordPress-Android#15316]
### Expected behavior
Disabling "Block Editor" using site settings and creating a post for a self-hosted site should not crash the application.

### Actual behavior
Disabling "Block Editor" using site settings and creating a post for a self-hosted site crashes the application.

### Steps to reproduce the behavior

1. Login using a Jurassic Ninja site 
2. Go to My Site -> Site Settings
3. Disable "Use Block Editor" 
4. Return to My Site
5. Go to Posts list
6. Create a new post
7. 💥 

https://user-images.githubusercontent.com/1405144/132807065-968cfa56-88c4-4442-b895-24d7735bf10e.mp4

Crash logs:

```
1631250105.181 E: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 31938
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.wordpress.android.fluxc.model.EditorThemeSupport org.wordpress.android.fluxc.model.EditorTheme.getThemeSupport()' on a null object reference
        at org.wordpress.android.ui.posts.EditPostActivity.onEditorFinalTouchesBeforeShowing(EditPostActivity.java:3305)
        at org.wordpress.android.ui.posts.EditPostActivity.onEditorFragmentInitialized(EditPostActivity.java:3283)
        at org.wordpress.android.editor.AztecEditorFragment.onCreateView(AztecEditorFragment.java:382)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2950)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:515)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1959)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
        at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:25466)
```

**Comment by ashiagr** [comment]
👋  @antonis 

[This line](https://github.com/wordpress-mobile/WordPress-Android/blame/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L3304) was added last month, could we possibly address the crash by adding a null check for `editorTheme`?

**Comment by antonis** [comment]
Thank you for the ping @ashiagr 🙇 

> This line was added last month, could we possibly address the crash by adding a null check for editorTheme?

Just merged a [fix](https://github.com/wordpress-mobile/WordPress-Android/pull/15311) for this in `18.2`
