### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15410]
**Sentry Url**: https://sentry.io/share/issue/309f47401bba4f0ba067589c90115b99/
**User Count**: 237
**Count**: 575
**First Release**: 18.2-rc-1
**First Seen**: 2021-09-10T13:05:37.016000Z
**Last Seen**: 2021-10-04T09:10:33Z
**24 Hours**: 39
**30 Days**: 578

```
NullPointerException: 
     at org.wordpress.android.util.KeyboardResizeViewUtil.getInsetBottom(KeyboardResizeViewUtil.java:73)
     at org.wordpress.android.util.KeyboardResizeViewUtil.access$300(KeyboardResizeViewUtil.java:20)
     at org.wordpress.android.util.KeyboardResizeViewUtil$1.lambda$onGlobalLayout$0(KeyboardResizeViewUtil.java:50)
     at org.wordpress.android.util.KeyboardResizeViewUtil$1.lambda$onGlobalLayout$0$KeyboardResizeViewUtil$1(null:0)
     at org.wordpress.android.util.-$$Lambda$KeyboardResizeViewUtil$1$5VvpPWyxMisP3Et7cwHLIWQgBfw.run(null:2)
...
(6 additional frame(s) were not displayed)
```

**Comment by AliSoftware** [comment]
Linked another Sentry report ☝️ which seems to be the same to me… but this one appeared in 18.1.

**Comment by dcalhoun** [comment]
Hey @ashiagr. 👋🏻 From reviewing this issue, it looks like the error appears to originate from [code added](https://github.com/wordpress-mobile/WordPress-Android/pull/14533/files#diff-2dc49cec7de6ae14ea7c866075dbe717bd8fe936b4c957d00e609a28e3ac0e37R72-R75) in https://github.com/wordpress-mobile/WordPress-Android/pull/14533. Currently 248 users have been impacted, which I estimate to be 0.17%, and I have assigned a `[Pri] Medium` label. 

I have assigned this to you, but please let me know if you think someone else is more appropriate or think we should change the priority of the issue. Thank you!

**Comment by dcalhoun** [comment]
@ashiagr @jd-alexander I am closing this issue as I noticed #15414 merged claiming to fix this. Please reopen this issue if I am mistaken. Thanks!
