### ISSUE TITLE
ApplicationNotResponding: Application Not Responding for at least 5000 ms.

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15446]
**Sentry Url**: https://sentry.io/share/issue/37b2a625b35540a68dca2ba1c958a6ed/
**User Count**: 807
**Count**: 18282
**First Release**: org.wordpress.android@15.0-rc-2+876
**First Seen**: 2020-06-12T02:57:56.362000Z
**Last Seen**: 2021-10-12T11:03:22Z
**24 Hours**: 10
**30 Days**: 496

```
ApplicationNotResponding: Application Not Responding for at least 5000 ms.
     at org.wordpress.android.support.ZendeskHelper.setupZendesk(ZendeskHelper.kt:106)
     at org.wordpress.android.support.ZendeskHelper.setupZendesk$default(ZendeskHelper.kt:98)
     at org.wordpress.android.support.ZendeskHelper.setupZendesk(ZendeskHelper.kt:null)
     at org.wordpress.android.WordPress.onCreate(WordPress.java:306)
...
(24 additional frame(s) were not displayed)
```

**Comment by AliSoftware** [comment]
Quite an old one (release 15.0+) and steady for a while so doesn't seem urgent; but since it happens on launch, and also around Zendesk (aka help/support), I figured it would still be nice to take a look at it at some point.

**Comment by dcalhoun** [comment]
I am unable to reproduce this issue, but it appears related to start up and the Zendesk SDK integration. All the event breadcrumbs appear to be the same — `onCreate` and then initialization of Zendesk followed by the error. Zendesk could be a red herring, but it is a least a starting place. 

Hey @ashiagr. 👋🏻 I noticed that you have worked in this area of the code recently, so I figured I would assign you. Given the age of the error and low user count, I am classifying this as `[Pri] Low`. Please let me know you disagree with that assessment or believe there may be a better person to have investigate this. Thanks! 🙇🏻

**Comment by jkmassel** [comment]
Closing this issue — the referenced Sentry issue no longer exists (the share link returns 404). This was an unreproducible ANR in ZendeskHelper from 2020. If this ANR is still occurring, it would appear as a new Sentry issue.
