### ISSUE TITLE
NullPointerException: selectedSite.email must not be null

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15448]
**Sentry Url**: https://sentry.io/share/issue/f388e43d2d954b5bb3b0aa66f5a80fa9/
**User Count**: 89
**Count**: 484
**First Release**: 18.0-rc-2
**First Seen**: 2021-08-18T01:51:57.075000Z
**Last Seen**: 2021-10-12T07:44:01Z
**24 Hours**: 8
**30 Days**: 294

```
NullPointerException: selectedSite.email must not be null
     at org.wordpress.android.ui.comments.unified.UnrepliedCommentsUtils.isMyComment(UnrepliedCommentsUtils.kt:49)
     at org.wordpress.android.ui.comments.unified.UnrepliedCommentsUtils.getUnrepliedComments(UnrepliedCommentsUtils.kt:24)
     at org.wordpress.android.models.usecases.PaginateCommentsUseCase$PaginateCommentsState$Idle.runAction(PaginateCommentsUseCase.kt:86)
     at org.wordpress.android.models.usecases.PaginateCommentsUseCase$PaginateCommentsState$Idle.runAction(PaginateCommentsUseCase.kt:86)
     at org.wordpress.android.models.usecases.PaginateCommentsUseCase$PaginateCommentsState$Idle$runAction$1.invokeSuspend(null:12)
...
(2 additional frame(s) were not displayed)
```

Not _that_ high numbers of events/users so far… but I am guessing it'd be an easy-enough one to fix anyway?

**Comment by dcalhoun** [comment]
Hey @ParaskP7. 👋🏻 I am unable to reproduce this, but based upon the error, I wonder if this is similar to https://github.com/wordpress-mobile/WordPress-Android/pull/15415 and potentially related to https://github.com/wordpress-mobile/WordPress-Android/pull/15197. Would you be willing to look into this please? 

The user counts appear low currently, so I am going to classify this as `[Pri] Low`. Please let me know if you disagree with that assessment or if you believe someone else may be a better fit for investigating this. Thanks! 🙇🏻

**Comment by ParaskP7** [comment]
👋 @dcalhoun !

Thanks for reaching out and bringing this to my attention! 🙏 

> Hey @ParaskP7. 👋🏻 I am unable to reproduce this, but based upon the error, I wonder if this is similar to #15415 and potentially related to #15197. Would you be willing to look into this please?

From the looks of it, it doesn't seem to be similar to #15415 or related to #15197, below is my reasonings:
- #15415 refers to a null-pointer-exception on the `selectedSite` level, but this null-pointer-exception is on the `selectedSite.email`, which means that although the `selectedSite` can be retrieved from the repository, it doesn't hold an `email` value inside, for some unknown-to-me, at least this point, reason.
- #15197 refers to a refactor that was developed and merged to `develop` on the `16th/24th of August 2021`. However, the `isMyComment(...)` function and as such the whole `UnrepliedCommentsUtils` class was created on the `22nd of July 2021`. As such, this logic already existed, even before the refactor. PS: I am not saying that the refactor didn't possible messed-up with the overall logic, but it seems, at least initially, not to be related.
- I am also seeing that these crashes started happening from the `24th of August 2021` onwards, but the #15197 was added later and into the [18.2 ](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/18.2) release, which went live at some point later on, on the `20th/21st of September 2021`.

> The user counts appear low currently, so I am going to classify this as [Pri] Low. Please let me know if you disagree with that assessment or if you believe someone else may be a better fit for investigating this. Thanks! 🙇🏻

As described above, it seems that this is an `email` related null-pointer-exception problem and not a `selectedSite` one. As such, I believe anyone could be at least as a good fit as me in investigating and getting to the bottom of this. I can definitely help no matter! 🙇

**Comment by dcalhoun** [comment]
> I am also seeing that these crashes started happening from the `24th of August 2021` onwards, but the [My Site Dashboard - Phase 1 - Refactor use of Repository in favor of Prefs for Selected Site #15197](https://github.com/wordpress-mobile/WordPress-Android/pull/15197) was added later and into the [18.2 ](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/18.2) release, which went live at some point later on, on the `20th/21st of September 2021`.

Considering the refactor as unrelated due to the misaligned dates makes total sense. Not sure why my brain skipped over that. 😄 Thank you for explaining your reasoning. 

> As described above, it seems that this is an `email` related null-pointer-exception problem and not a `selectedSite` one. As such, I believe anyone could be at least as a good fit as me in investigating and getting to the bottom of this. I can definitely help no matter! 🙇

Thank you for the willingness to help, @ParaskP7. 🙇🏻

**Comment by ParaskP7** [comment]
👋 @dcalhoun !

> Considering the refactor as unrelated due to the misaligned dates makes total sense. Not sure why my brain skipped over that. 😄 Thank you for explaining your reasoning.

Of course, and who knows it might turn out to be somehow related in the end... 😅 For now however, I would indeed solely focus on the `email` value being `null` instead of the whole `selectedSite`.

> Thank you for the willingness to help, @ParaskP7. 🙇🏻

Anytime, just let me know and I will try to help out as much as I can. 👍

**Comment by dcalhoun** [comment]
> Anytime, just let me know and I will try to help out as much as I can. 👍

@ParaskP7 my plan is to leave you as the assignee for this issue. With the current low, flat user count, it doesn't seem like a high priority to fix immediately, but when you can make time will you please see if you can identify and address the core issue? Thank you!

**Comment by ParaskP7** [comment]
👋 @dcalhoun !

> @ParaskP7 my plan is to leave you as the assignee for this issue.

👍 

> With the current low, flat user count, it doesn't seem like a high priority to fix immediately

I agree.

> but when you can make time will you please see if you can identify and address the core issue?

Sure, just an FYI however that this week I am on support rotation, while next week I'll be on a conference. As such this might be delayed on my part a bit. But, I can definitely keep an eye on it and jump on and try to fix it as some point in the future.

**Comment by antonis** [comment]
Linked up the two related crash reports above. The issue still persists in the latest versions of the app.

**Comment by SiobhyB** [comment]
I've gone ahead to update the priority to reflect that this is now the fifth most frequent crash for the WordPress app.

**Comment by zwarm** [comment]
@AjeshRPai - while doing research on another topic (going back a month or so), I came across multiple situations in which a self-hosted site will be in the local database without email/psw credentials. I don't have the exact steps, but usually once the site is connected to wp.com via JP, the local site table is updated and the self-hosted credentials are removed from the database. (Also the "origin" of the site changes from '2" to "1", and a remote site_id is added). If the user then deactivates/disconnects JP, and navigates to an area of the app that needs those credentials to perform a function, they are no longer available - hence the "null" pointer exception, as they are null in the db.

I'm not sure that holding on to those credentials would eliminate the issue entirely. I wonder if we need to prompt for the credentials again? 🤔

**Comment by jkmassel** [comment]
Closing this issue — the referenced Sentry issue no longer exists (the share link returns 404), which means this crash hasn't been seen in at least 90 days. If this crash resurfaces, it will appear as a new Sentry issue.
