### ISSUE TITLE
RuntimeException: Failure from system

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15447]
**Sentry Url**: https://sentry.io/share/issue/af1fb84874d641b6bdf5b362a32b3f62/
**User Count**: 387
**Count**: 3665
**First Release**: org.wordpress.android-12.7
**First Seen**: 2019-07-05T19:31:03Z
**Last Seen**: 2021-10-12T05:40:44Z
**24 Hours**: 12
**30 Days**: 345

```
RuntimeException: Failure from system
     at org.wordpress.android.ui.ActivityLauncher.viewHistoryDetailForResult(ActivityLauncher.java:1076)
     at org.wordpress.android.ui.posts.EditPostActivity.onHistoryItemClicked(EditPostActivity.java:1945)
     at org.wordpress.android.ui.posts.HistoryListFragment$setObservers$3.onChanged(HistoryListFragment.kt:155)
     at org.wordpress.android.ui.posts.HistoryListFragment$setObservers$3.onChanged(HistoryListFragment.kt:25)
     at org.wordpress.android.viewmodel.SingleLiveEvent$observe$1.onChanged(SingleLiveEvent.kt:50)
     at org.wordpress.android.viewmodel.SingleLiveEvent.setValue(SingleLiveEvent.kt:58)
     at org.wordpress.android.viewmodel.history.HistoryViewModel.onItemClicked(HistoryViewModel.kt:218)
     at org.wordpress.android.ui.posts.HistoryListFragment.onItemClicked(HistoryListFragment.kt:49)
     at org.wordpress.android.ui.posts.HistoryListFragment.access$onItemClicked(HistoryListFragment.kt:25)
     at org.wordpress.android.ui.posts.HistoryListFragment$setList$1.invoke(HistoryListFragment.kt:109)
...
(26 additional frame(s) were not displayed)
```

**Comment by dcalhoun** [comment]
This appears to be a similar error as https://github.com/wordpress-mobile/WordPress-Android/pull/14422 and https://github.com/wordpress-mobile/WordPress-Android/pull/10240. I wonder if the content restored from the transaction history for the block editor is too large, which causes the crash. Is there a way we could apply a fix similar to the aforementioned PRs? 

Hey @antonis. 👋🏻 I noticed you worked on a similar issue in one of the PRs I mentioned. Would you be willing to take a look at this please? Based on the age and user count, I have classified this as `[Pri] low`. Please let me know if you disagree with that assessment or believe there is a better person to have investigate this. Thanks! 🙇🏻

**Comment by antonis** [comment]
I'll close this issue since a newer issue that tracks this crash from 18.8 onwards has been created https://github.com/wordpress-mobile/WordPress-Android/issues/16012
