### ISSUE TITLE
NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParame...

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15499]
**Sentry Url**: https://sentry.io/share/issue/bc015811a5544b44beec85bc52fd0994/
**User Count**: 1
**Count**: 2
**First Release**: 18.5-rc-2
**First Seen**: 2021-10-26T02:57:52.922000Z
**Last Seen**: 2021-10-26T02:57:59Z
**24 Hours**: 0
**30 Days**: 2

```
NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter username
     at org.wordpress.android.fluxc.network.xmlrpc.media.MediaXMLRPCClient.uploadMedia(MediaXMLRPCClient.java:175)
     at org.wordpress.android.fluxc.store.MediaStore.performUploadMedia(MediaStore.java:793)
     at org.wordpress.android.fluxc.store.MediaStore.onAction(MediaStore.java:494)
...
(1 additional frame(s) were not displayed)
```

Super low user and event count, and I usually don't escalate as a GH issue for so low numbers… but since this is a brand new introduced on the current beta (which isn't out yet, which can also explain low counts), I figured better flag it sooner than later. \cc @jhnstn I'll let you decide on priority.

**Comment by jd-alexander** [comment]
I investigated this issue. It seems when media is being uploaded the `SiteModel`'s `username` is null and causing this crash. Since this value can be null, the API design should cover this case. The offending line is [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/98d43f5f4ed25dbacac85fc42889a6ac529c03e4/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/media/MediaXMLRPCClient.java#L175) Based on how error cases are handled there, a `MediaError` should encapsulate this result so that a crash does not occur.

**Comment by jkmassel** [comment]
Closing this issue — the referenced Sentry issue no longer exists (the share link returns 404). This crash affected 1 user with 2 occurrences back in 2021. If this crash is still occurring, it would appear as a new Sentry issue.
