### ISSUE TITLE
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditP...

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15607]
**Sentry Url**: https://sentry.io/share/issue/b074a52ff6994322bfa9e912535efff3/
**User Count**: 30 + 19 + 4 = 53
**Count**: 85 + 69 + 18 = 172
**First Release**: 18.7-rc-1
**First Seen**: 2021-11-16T04:23:59.172000Z
**Last Seen**: 2021-11-22T08:19:39Z
**24 Hours**: 2
**30 Days**: 85

```
RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException: Attempt to write to field 'org.wordpress.android.util.analytics.AnalyticsTrackerWrapper org.wordpress.android.ui.posts.PostEditorAnalyticsSession.mAnalyticsTrackerWrapper' on a null object reference
     at org.wordpress.android.ui.posts.PostEditorAnalyticsSession.fromBundle(PostEditorAnalyticsSession.java:70)
     at org.wordpress.android.ui.posts.EditPostActivity.onCreate(EditPostActivity.java:606)
...
(7 additional frame(s) were not displayed)
```

---

This crash is new in **latest beta**.

I found multiple Sentry issues related to it – see [this search query](https://sentry.io/organizations/a8c/issues/?project=1438088&query=firstRelease%3A18.7-rc-1+EditPostActivity&sort=freq&statsPeriod=14d)
 - https://sentry.io/share/issue/b074a52ff6994322bfa9e912535efff3/ (85/30)
 - https://sentry.io/share/issue/d114a7af430c474c86f83e7b27b748f8/ (69/19)
 - https://sentry.io/share/issue/5f7415afdaed49219c9029be54563ffc/ (18/4)
 - And multiple more with smaller numbers but apparently same exception

**Comment by hypest** [comment]
Took a look and apparently, this is another manifestation of the https://github.com/wordpress-mobile/WordPress-Android/issues/15578 ticket, and already fixed in the v18.7-rc-2 at that. The crashes here also don't seem to happen on the `rc-2` so, chances are they are fixed too. As discussed in Slack, let's leave this open for a few days to monitor, after which we'll close as fixed if no new clues arise.

**Comment by fluiddot** [comment]
I checked the current stats of the issue:
- Total users in `18.7-rc-1` (on Nov 23): 800
- Users affected by the issue: 30
- Ratio of users affected: 3,75%

I assigned the `Blocking` priority tag as it produces a crash and affects a high number of users. However, I'd like to highlight that this issue can only be reproduced in the beta version `18.7-rc-1`. As mentioned, in previous comments, this was fixed in `18.7-rc-2`, and so far we haven't received any Sentry event for that version, so most likely the issue is already addressed.

**Comment by antonis** [comment]
[The issue seems to persist in the latest versions of the app (19.1, 19.2)](https://sentry.io/organizations/a8c/issues/2793452408/events/?project=1438088). It's also interesting that [~75% of the events derive from the same user](https://sentry.io/organizations/a8c/issues/2793452408/tags/user/?project=1438088) and [all from a limited set of devices (Redmi, Oppo, Realme)](https://sentry.io/organizations/a8c/issues/2793452408/tags/device/?project=1438088).

**Comment by thehenrybyrd** [comment]
@fluiddot @antonis this has been open for some time now; do we still think the `Blocking` priority is appropriate?

**Comment by antonis** [comment]
Thank you for the ping @thehenrybyrd 🙇 
Given that [the issue has occurred 9 times in the last 30 days](https://sentry.io/organizations/a8c/issues/2793452408/?project=1438088) I think we can lower the priority. Since it's a low impact and high severity (crash) I'm setting the priority to medium.

**Comment by jkmassel** [comment]
Closing this issue — the referenced Sentry issue no longer exists (the share link returns 404). Per the comments, this crash was already fixed in v18.7-rc-2 as a duplicate of #15578.
