### ISSUE TITLE
🚨 Update all our dependencies to be compatible with our kotlin version

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15703]
### Expected behavior

All our dependencies use a compatible version of kotlin

### Actual behavior

Currently the app uses kotlin `1.5.32`, after it has been updated (from `1.4.0`) in https://github.com/wordpress-mobile/WordPress-Android/pull/15646 (h/t @ParaskP7) to fix a compilation issue.

But when I did the release build for 18.8 today, even if the build succeeded, I still saw a LOT (1000+) of those error messages in the log output:
```
[16:19:51]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[16:19:51]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.0/a40b8b22529b733892edf4b73468ce598bb17f04/kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[16:19:51]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
…
```

See also p1639156434202200/1639150575.196500-slack-C02QANACA for more context and info.

We've shipped WPAndroid 18.8 to the PlayStore despite those errors but we should definitively ensure that those are fixed ASAP so we can be confident on the releases going forward. This is why I've made this issue target the 18.9 milestone.

### Steps to reproduce the behavior

 - Compile the app via `./gradlew buildWordPressVanillaRelease`
 - The build ends with "Build Succeeded"… yet the logs contains a lot of errors related to kotlin version mismatches and conflicts.

**Comment by oguzkocer** [comment]
I am afraid I don't agree with the premise of this issue. This issue would make sense if any of the dependencies we use fail to compile with the resolved version of one of its own dependencies. An example being, the dependency `libA` depending on Kotlin's `a.b.c` version failing to compile with the resolved version `x.y.z`.

On the contrary, in a case like this, trying to update all the dependencies to a certain version is a losing battle as we are not in control of all the dependencies. I think it'd be good to use the same version number for all our projects as much as we can, and that's why we have an upcoming project for this [where we'll centralize the dependency versions](https://docs.gradle.org/current/userguide/platforms.html). However, I don't think it'll fix all the resolution issues.

Finally, it's worth noting that the dependency resolution issue we are facing was happening in one of the modules `libs/editor` and not in one of our dependencies. This was at least my experience when I worked on https://github.com/wordpress-mobile/WordPress-Android/pull/15642 and it happened again during the Plugin DSL transition in #15314's 320eed4952cbcddcfc76a36cce445a77e3ad6b75.

In terms of how to fix this issue, in my humble opinion, we should be configuring Gradle to resolve the dependency in the more predictable & desirable way. [There are different ways to achieve this](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html), and I think the one that makes sense in our current setup (even if temporarily) is to force Kotlin dependencies to the defined version as I'll be suggesting in 9bdab5230e5b87693d666e0a7d9f037cdb7bc544 as part of #15314. I think there is a case to be made to do this for all major dependencies, especially the ones we store in S3 since the "latest" dependency information will not be correct with our custom versioning scheme and a library can easily end up forcing the application to a different version. It might be possible to do this part with [preferProjectModules()](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html#org.gradle.api.artifacts.ResolutionStrategy:preferProjectModules()) but there is some research to do there.

In any case, assuming #15314 is approved and merged, I _think_ we won't face this issue again, not for Kotlin dependencies anyway 🤷‍♂️ 

_P.S: I am not an expert in Gradle dependency resolution. I am hoping to build up more experience with that upcoming project where we'll centralize the dependency versions, but at least for now, take everything I said with a grain of salt and if in doubt check the documentation and the Gradle scans._

**Comment by AliSoftware** [comment]
> In terms of how to fix this issue, in my humble opinion, we should be configuring Gradle to resolve the dependency in the more predictable & desirable way. There are different ways to achieve this, and I think the one that makes sense in our current setup (even if temporarily) is to force Kotlin dependencies to the defined version as I'll be suggesting in 9bdab52 as part of #15314.

That's a very good point and I tend to agree with your suggested solution 👍  Thanks for your thorough explanation and analysis.

Let's wait for 15314 to me merged then check again during the next release build after it if that solved the issue.

**Comment by AliSoftware** [comment]
FWIW the errors were still present during lint last Friday during `finalize_release` of `18.9`

<details><summary>Extract of the log I got when running <tt>fastlane finalize_release</tt>, which includes a call to <tt>lintWordpressVanillaRelease</tt></summary>

```
…
…
[17:53:52]: ▸ > Task :WordPress:lintWordpressVanillaRelease
[17:53:52]: ▸ w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
[17:53:52]: ▸ /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.31/6dd50665802f54ba9bc3f70ecb20227d1bc81323/kotlin-stdlib-common-1.4.31.jar (version 1.4)
[17:53:52]: ▸ /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.31/a58e0fb9812a6a93ca24b5da75e4b5a0cb89c957/kotlin-stdlib-1.4.31.jar (version 1.4)
[17:53:52]: ▸ /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.31/ff5d99aecd328872494e8921b72bf6e3af97af3e/kotlin-stdlib-jdk8-1.5.31.jar (version 1.5)
[17:53:52]: ▸ /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.5.32/2e8f666555c2a6bf10ef712be8a738e665132c8/kotlin-stdlib-jdk7-1.5.32.jar (version 1.5)
[17:53:52]: ▸ /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.0/a40b8b22529b733892edf4b73468ce598bb17f04/kotlin-stdlib-1.6.0.jar (version 1.6)
[17:53:52]: ▸ /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar (version 1.6)
[17:53:52]: ▸ /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.20/636c5653641cd956de9aee5792155b07ea49825e/kotlin-stdlib-jdk8-1.5.20.jar (version 1.5)
[17:53:52]: ▸ /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.32/a1f8a73f899b85e6eb4337dff7e81b8b914bd2c9/kotlin-stdlib-1.5.32.jar (version 1.5)
[17:53:52]: ▸ /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.32/8befc4a20c17094a148f1409c1bac163bc3ca630/kotlin-stdlib-common-1.5.32.jar (version 1.5)
[17:53:52]: ▸ w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
[17:53:53]: ▸ Could not load custom lint check jar file /Users/olivier/.gradle/caches/transforms-3/f868b70e5c4a6dbe93d9a839236cf5cd/transformed/jetified-ui-graphics-1.1.0-beta04/jars/lint.jar
[17:53:53]: ▸ java.lang.NoClassDefFoundError: com/android/tools/lint/client/api/Vendor
[17:53:53]: ▸ at androidx.compose.ui.graphics.lint.UiGraphicsIssueRegistry.<init>(UiGraphicsIssueRegistry.kt:34)
[17:53:53]: ▸ at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:53:53]: ▸ at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
(…)
[17:53:53]: ▸ Caused by: java.lang.ClassNotFoundException: com.android.tools.lint.client.api.Vendor
[17:53:53]: ▸ at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:357)
[17:53:53]: ▸ at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[17:53:53]: ▸ at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[17:53:53]: ▸ ... 155 more
[17:53:53]: ▸ Could not load custom lint check jar file /Users/olivier/.gradle/caches/transforms-3/9a18aa17c50dc813b95fc65f8c817aa2/transformed/jetified-runtime-1.1.0-beta04/jars/lint.jar
[17:53:53]: ▸ java.lang.NoClassDefFoundError: com/android/tools/lint/client/api/Vendor
[17:53:53]: ▸ at androidx.compose.runtime.lint.RuntimeIssueRegistry.<init>(RuntimeIssueRegistry.kt:45)
(… and many similar exceptions …)

[17:53:53]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.0/a40b8b22529b733892edf4b73468ce598bb17f04/kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:53:53]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:59:15]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.0/a40b8b22529b733892edf4b73468ce598bb17f04/kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:59:15]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:59:15]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.0/a40b8b22529b733892edf4b73468ce598bb17f04/kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:59:15]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:59:15]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.0/a40b8b22529b733892edf4b73468ce598bb17f04/kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:59:15]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:59:15]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.0/a40b8b22529b733892edf4b73468ce598bb17f04/kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:59:15]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:59:15]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.0/a40b8b22529b733892edf4b73468ce598bb17f04/kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
[17:59:15]: ▸ e: /Users/olivier/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.0/7857e365f925cfa060f941c1357cda1f8790502c/kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.
(… repeated 100+ times)

[18:01:14]: ▸ Wrote HTML report to file:///Users/olivier/Documents/Dev/apps/WordPress-Android/WordPress/build/reports/lint-results-wordpressVanillaRelease.html
[18:01:15]: ▸ Wrote XML report to file:///Users/olivier/Documents/Dev/apps/WordPress-Android/WordPress/build/reports/lint-results-wordpressVanillaRelease.xml
[18:01:15]: ▸ Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[18:01:15]: ▸ You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[18:01:15]: ▸ See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings
[18:01:15]: ▸ BUILD SUCCESSFUL in 11m 26s
[18:01:15]: ▸ 89 actionable tasks: 15 executed, 74 up-to-date
```
</details>

That's not really surprising since the PluginDSL PR is still in Draft and hasn't been merged (and nothing else related to dependency resolution changed since either); so I didn't really expect it to be different this time around, but just wanted to still document it officially here for tracking that 18.9 still had it.
