### ISSUE TITLE
NullPointerException: jsonInterests.optJSONObject(i) must not be null

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#15786]
**Sentry Url**: https://sentry.io/share/issue/5b329a7fd8524549b801f81ba1d962b5/
**User Count**: 56
**Count**: 487
**First Release**: 18.8
**First Seen**: 2021-12-16T09:28:42.346000Z
**Last Seen**: 2022-01-03T11:36:29Z
**24 Hours**: 30
**30 Days**: 489

```
NullPointerException: jsonInterests.optJSONObject(i) must not be null
     at org.wordpress.android.ui.reader.repository.usecases.ParseDiscoverCardsJsonUseCase.parseInterestCard(ParseDiscoverCardsJsonUseCase.kt:49)
     at org.wordpress.android.ui.reader.services.discover.ReaderDiscoverLogic.parseCards(ReaderDiscoverLogic.kt:168)
     at org.wordpress.android.ui.reader.services.discover.ReaderDiscoverLogic.handleRequestDiscoverDataResponse(ReaderDiscoverLogic.kt:142)
     at org.wordpress.android.ui.reader.services.discover.ReaderDiscoverLogic.access$getRecommendedBlogsToBeDeleted(ReaderDiscoverLogic.kt:57)
     at org.wordpress.android.ui.reader.services.discover.ReaderDiscoverLogic.access$handleRequestDiscoverDataResponse(ReaderDiscoverLogic.kt:57)
     at org.wordpress.android.ui.reader.services.discover.ReaderDiscoverLogic$requestDataForDiscover$1$listener$1$1.invokeSuspend(ReaderDiscoverLogic.kt:116)
...
(2 additional frame(s) were not displayed)
```

This is currently pretty low on # of users, but it's also new in the latest version published in the PlayStore (18.8), so has a potential for growing fast, so it's probably still worth monitoring its evolution in the upcoming days.

**Comment by ashiagr** [comment]
Hey @AliSoftware 👋 

This issue just caught my eye. It looks like a duplicate of this one: https://github.com/wordpress-mobile/WordPress-Android/issues/15722 and handled as part of this PR: https://github.com/wordpress-mobile/WordPress-Android/pull/15773. I'm not sure why it is marked as first seen in `18.8`. 🤔 The other issue  #15722  dates back to the `16.2` release.

**Comment by AliSoftware** [comment]
Nice spotting!

I think Sentry considered it a new issue because the stacktrace differs very slightly in the overall path that led to the call to the final `optJSONObject(i)` so that probably prevented it from merging the 2 issues together, despite them indeed looking like duplicates. I'm gonna close this one then to avoid the noise.
