### ISSUE TITLE
RuntimeException: Failure from system

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#16012]
**Sentry Url**: https://sentry.io/share/issue/7a2d9cc64ef945169866fd2d7fe42af6/
**User Count**: 323
**Count**: 886
**First Release**: 18.8-rc-2
**First Seen**: 2021-12-08T09:37:41.206000Z
**Last Seen**: 2022-02-28T06:39:16Z
**24 Hours**: 8
**30 Days**: 440

```
RuntimeException: Failure from system
     at org.wordpress.android.ui.ActivityLauncher.viewHistoryDetailForResult(ActivityLauncher.java:1102)
     at org.wordpress.android.ui.posts.EditPostActivity.onHistoryItemClicked(EditPostActivity.java:1937)
     at org.wordpress.android.ui.posts.HistoryListFragment.setObservers$lambda-7(HistoryListFragment.kt:155)
     at org.wordpress.android.ui.posts.HistoryListFragment.lambda$lEsuMbG6B9pBZTJlu9vkgLw-Wk4(null:0)
     at org.wordpress.android.ui.posts.-$$Lambda$HistoryListFragment$lEsuMbG6B9pBZTJlu9vkgLw-Wk4.onChanged(null:4)
     at org.wordpress.android.viewmodel.SingleLiveEvent.observe$lambda-0(SingleLiveEvent.kt:50)
     at org.wordpress.android.viewmodel.SingleLiveEvent.lambda$QDPJ8FUoo3cDlf_Lb7Y_qP14f6o(null:0)
     at org.wordpress.android.viewmodel.-$$Lambda$SingleLiveEvent$QDPJ8FUoo3cDlf_Lb7Y_qP14f6o.onChanged(null:4)
     at org.wordpress.android.viewmodel.SingleLiveEvent.setValue(SingleLiveEvent.kt:58)
     at org.wordpress.android.viewmodel.history.HistoryViewModel.onItemClicked(HistoryViewModel.kt:218)
...
(32 additional frame(s) were not displayed)
```

**Comment by antonis** [comment]
Occurrences of this before `18.8` can be tracked with https://github.com/wordpress-mobile/WordPress-Android/issues/11406 and https://github.com/wordpress-mobile/WordPress-Android/issues/15447.

A solution similar to https://github.com/wordpress-mobile/WordPress-Android/pull/10240 in order to avoid bundling all the revisions as parcels might be possible.
