### ISSUE TITLE
RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#16015]
**Sentry Url**: https://sentry.io/share/issue/11c975422ad64c298086272646122619/
**User Count**: 463
**Count**: 2829
**First Release**: org.wordpress.android-13.2
**First Seen**: 2019-09-10T22:51:40Z
**Last Seen**: 2022-02-28T04:57:48Z
**24 Hours**: 11
**30 Days**: 330

```
RuntimeException: An error occurred while executing doInBackground()

```

**Comment by ravishanker** [comment]
It is hard to trace where and when this crash is occurring.  Assigned a low priority, since it's been a long outstanding issue and also it could be android OS related.  Based on information in the Sentry, added this issue to My Site Dashboard project.  Please update if you feel it doesn't belong to My Site Dashboard.

**Comment by antonis** [comment]
Checking the stack trace this should be [related to this Android issue](https://issuetracker.google.com/issues/63622293).
<details>
<summary>Exception stack trace</summary>

```
java.lang.SecurityException: Caller no longer running, last stopped +3s267ms because: timed out while starting
    at android.os.Parcel.createException(Parcel.java:2071)
    at android.os.Parcel.readException(Parcel.java:2039)
    at android.os.Parcel.readException(Parcel.java:1987)
    at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:292)
    at android.app.job.JobParameters.dequeueWork(JobParameters.java:248)
    at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:319)
    at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:645)
    at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
    at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
    at android.os.AsyncTask$3.call(AsyncTask.java:378)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:399)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```
</details>

Since the `JobIntentService` has been deprecated in Android a [possible way forward would be to migrate to `WorkManager`.](https://medium.com/tech-takeaways/how-to-migrate-the-deprecated-jobintentservice-a0071a7957ed)

**Comment by mkevins** [comment]
For some reason this was listed as an unlinked duplicate in Sentry, so this issue was created: https://github.com/wordpress-mobile/WordPress-Android/issues/18632. I have repurposed that issue into a task which has potential to address the crash numbers. Either way, I agree with Antonis that we should migrate to `WorkManager` (actually came to the same conclusion independently, before realizing this was already discussed here 😅).

Going forward I propose the following:

1. We keep both issues open
   * This issue will track the crashes and the task to migrate to `WorkManager`
   * The second issue (the duplicate) will also track the same crash, and be focused on the task of `WorkManager` configuration (job id ranges)
2. We monitor the crash numbers after the task from the second issue is complete (and rolled out)
   * If that fix resolves the crashes, this issue can be kept open, as a "tech debt" task to migrate to `WorkManager`
   * If that fix does not resolve the crash, this issue will still be related with migrating to `WorkManager`, but also to continue tracking the crash numbers
   * Either way, the second issue would be closed after monitoring the rollout of the id range fix

**Comment by mkevins** [comment]
> Please update if you feel it doesn't belong to My Site Dashboard.

👋 😄 @ravishanker fyi, I'm updating this to the Android Crash Focus board, since it feels the appropriate place, now that we have a dedicated board for these kinds of things. I'll also remove from the My Site Dashboard, but please let me know and feel free to add it back if you think that makes the most sense.

**Comment by mkevins** [comment]
Following up with the monitoring plan described [here](https://github.com/wordpress-mobile/WordPress-Android/issues/16015#issuecomment-1635276078):

The id collision fix did _not_ seem to resolve the issue ([as described here](https://github.com/wordpress-mobile/WordPress-Android/issues/18632#issuecomment-1687303586)). I have elevated the priority of this issue, since migrating to `WorkManager` is not only a tech-debt issue, but has potential to reduce or eliminate the frequency of this crash.

**Comment by antonis** [comment]
> Sentry issue: [JETPACK-ANDROID-7YC](https://a8c.sentry.io/issues/4263088378/?referrer=github_integration)

Stack trace for the newly linked issue 

```
java.lang.SecurityException: Caller no longer running, last stopped +2s882ms because: timed out while starting
    at android.os.Parcel.createException(Parcel.java:1950)
    at android.os.Parcel.readException(Parcel.java:1918)
    at android.os.Parcel.readException(Parcel.java:1868)
    at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:195)
    at android.app.job.JobParameters.dequeueWork(JobParameters.java:243)
    at androidx.core.app.JobIntentService$JobServiceEngineImpl$$InternalSyntheticApiModelOutline$1$ebcacfecb6783417b73e5ea173a4d8004aeacce96fe4c10fe466eb1f942c2d4b$0.m(R8$$SyntheticClass:0)
    at androidx.core.app.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:319)
    at androidx.core.app.JobIntentService.dequeueWork(JobIntentService.java:645)
    at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:394)
    at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
    at android.os.AsyncTask$2.call(AsyncTask.java:333)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:354)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)
```
