### ISSUE TITLE
AccountSettings : App crashes on changing the password

### ISSUE THREAD

**Issue by SowmiaS** [wordpress-mobile/WordPress-Android#16526]
In the `Account Settings` screen, the app is crashing on changing the password.

 java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
        at org.wordpress.android.ui.prefs.AccountSettingsFragment.onPreferenceChange(AccountSettingsFragment.java:197)
        at android.preference.Preference.callChangeListener(Preference.java:1254)
        at org.wordpress.android.ui.prefs.EditTextPreferenceWithValidation.lambda$showDialog$0$org-wordpress-android-ui-prefs-EditTextPreferenceWithValidation(EditTextPreferenceWithValidation.java:41)
        at org.wordpress.android.ui.prefs.EditTextPreferenceWithValidation$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:8160)
        at android.widget.TextView.performClick(TextView.java:16222)
        at android.view.View.performClickInternal(View.java:8137)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30236)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)

### Expected behavior
When the user navigates to the Account Settings screen
And try to change the password
Then the user should be able to change the password

### Actual behavior

When the user navigates to the Account Settings screen
And try to change the password
Then the app crashes.

### Steps to reproduce the behavior
1. Go to the Account Settings screen
2. click change password
3. enter some valid password and click ok
4. observe the app crash

**Comment by thehenrybyrd** [comment]
@SowmiaS thanks for reporting this!
I was able to reproduce the issue.

**To reproduce:**
1. Log in with a WordPress.com account
2. Head to Me > Account Settings and tap "Change password"
3. Enter a new password and tap "Ok" to change it
4. Note that the app display darkens briefly and returns to Account Settings. No failure or success message is shown. Password is not changed.

**Recording:**

https://user-images.githubusercontent.com/15107387/169261327-2391ca30-5e59-4fc9-a38f-de583b9a0fd0.mp4


**Tested on Samsung Galaxy S21, Android 12, WP Android 19.9-rc-2**

**Comment by carl-duncan** [comment]
https://github.com/wordpress-mobile/WordPress-Android/pull/16623
