### ISSUE TITLE
RuntimeException: Unable to unbind to service org.wordpress.android.login.LoginWpcomService@2489de8 with Intent { c...

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-Android#17465]
**Sentry Url**: https://sentry.io/share/issue/5d6b5c89bb124cf08e3c13e9f35bf761/
**User Count**: 87
**Count**: 1769
**First Release**: 21.0-rc-2
**First Seen**: 2022-10-18T02:10:48.813000Z
**Last Seen**: 2022-11-15T10:51:55Z
**24 Hours**: 139
**30 Days**: 1758

```
RuntimeException: Unable to unbind to service org.wordpress.android.login.LoginWpcomService@2489de8 with Intent { cmp=org.wordpress.android/.login.LoginWpcomService }: java.lang.IllegalArgumentException: org.wordpress.android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
     at org.wordpress.android.util.AutoForegroundNotification.getNotificationBuilder(AutoForegroundNotification.java:45)
     at org.wordpress.android.util.AutoForegroundNotification.progress(AutoForegroundNotification.java:55)
     at org.wordpress.android.login.LoginWpcomService$LoginNotification.progress(LoginWpcomService.java:122)
     at org.wordpress.android.login.LoginWpcomService.getNotification(LoginWpcomService.java:206)
     at org.wordpress.android.login.LoginWpcomService.getNotification(LoginWpcomService.java:42)
     at org.wordpress.android.util.AutoForeground.promoteForeground(AutoForeground.java:153)
     at org.wordpress.android.util.AutoForeground.onUnbind(AutoForeground.java:131)
...
(11 additional frame(s) were not displayed)
```

**Comment by ovitrif** [comment]
I've closed the other issue (https://github.com/wordpress-mobile/WordPress-Android/issues/17466) since in Sentry they are grouped as `similar issues` based on the shared stack trace.

Details from the closed issue:

**Sentry Url**: https://sentry.io/share/issue/c986b14e6af643c79a19824082fbac44/
**User Count**: 31
**Count**: 441
**First Release**: 21.0-rc-2
**First Seen**: 2022-10-24T17:54:09.292000Z
**Last Seen**: 2022-11-15T09:32:09Z
**24 Hours**: 42
**30 Days**: 443

```
RuntimeException: Unable to start service org.wordpress.android.login.LoginWpcomService@2155942 with Intent { cmp=org.wordpress.android/.login.LoginWpcomService (has extras) }: java.lang.IllegalArgumentException: org.wordpress.android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
     at org.wordpress.android.util.AutoForegroundNotification.getNotificationBuilder(AutoForegroundNotification.java:45)
     at org.wordpress.android.util.AutoForegroundNotification.progress(AutoForegroundNotification.java:55)
     at org.wordpress.android.login.LoginWpcomService$LoginNotification.progress(LoginWpcomService.java:122)
     at org.wordpress.android.login.LoginWpcomService.getNotification(LoginWpcomService.java:206)
     at org.wordpress.android.login.LoginWpcomService.getNotification(LoginWpcomService.java:42)
     at org.wordpress.android.util.AutoForeground.notifyState(AutoForeground.java:208)
     at org.wordpress.android.util.AutoForeground.setState(AutoForeground.java:170)
     at org.wordpress.android.login.LoginWpcomService.setState(LoginWpcomService.java:232)
     at org.wordpress.android.login.LoginWpcomService.onStartCommand(LoginWpcomService.java:257)
...
(13 additional frame(s) were not displayed)
```

**Comment by ovitrif** [comment]
According to my investigation on a number of occurrences in Sentry, this issue can affect different functionality that relies on updates to the app that are handled via the foreground notifications service.

The crash is related to the recent **target sdk update to 31 (Android 12)**, and one of the most critical functionality it can affect is the Login flow.

The fix should be fairly straightforward by setting the pending intent flag to `FLAG_IMMUTABLE` in https://github.com/wordpress-mobile/WordPress-Utils-Android, in [`AutoForegroundNotification.java:49`](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/trunk/WordPressUtils/src/main/java/org/wordpress/android/util/AutoForegroundNotification.java#L49).

This can be coordinated with the [open PR on `WordPress-Utils-Android` to update `minSdk` version to `24`](https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/111), since the flag requires API level `23`.

While this isn't affecting many users the numbers are continuing to rise every day, therefore I'm considering a HIGH priority for it taking into account it affects core functionality of the apps (login) and other updates via foreground notifications.

P.S. I couldn't reproduce the crash during testing.
