### ISSUE TITLE
Sites that have been deleted or destroyed remain in site list, causing a crash when selected

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-Android#18761]
### Expected behavior

If a deleted/destroyed site displays in the app's site list, I'd expect to be able to select that site and possibly see an informative error message.

### Actual behavior

Destroyed sites remain in the app's site list and a crash occurs when selecting them.

Note, I encountered this behaviour by selecting an older jurassic.ninja site. However, I assume the same behaviour can be replicated for sites hosted elsewhere that have been deleted or destroyed.

### Steps to reproduce the behavior

* Spin up a new site at jurassic.ninja.
* Follow the app's self-hosted login flow to log into the new site.
* Wait 7 days for the site to be destroyed.
* Go back to select the site from the app's list.

##### Tested on Pixel 6, Android 13, JPAndroid / WPAndroid 22.7

**Comment by AjeshRPai** [comment]
I was able to reproduce this issue in 23.8 with the steps mentioned by @SiobhyB.  Sentry Issue: [JETPACK-ANDROID-76C](https://a8c.sentry.io/issues/4227761466/?referrer=github_integration)

Stack trace
```
FATAL EXCEPTION: DefaultDispatcher-worker-3
Process: com.jetpack.android.prealpha, PID: 12631
java.lang.NullPointerException: site.username must not be null
at org.wordpress.android.fluxc.network.rest.wpapi.NonceRestClient.requestNonce(NonceRestClient.kt:40)
at org.wordpress.android.fluxc.store.ReactNativeStore.executeWPAPIRequest(ReactNativeStore.kt:190)
at org.wordpress.android.fluxc.store.ReactNativeStore.executeWPAPIGetRequest(ReactNativeStore.kt:135)
at org.wordpress.android.fluxc.store.ReactNativeStore.access$executeWPAPIGetRequest(ReactNativeStore.kt:33)
at org.wordpress.android.fluxc.store.ReactNativeStore$executeGetRequest$2.invokeSuspend(ReactNativeStore.kt:78)
at org.wordpress.android.fluxc.store.ReactNativeStore$executeGetRequest$2.invoke(Unknown Source:8)
at org.wordpress.android.fluxc.store.ReactNativeStore$executeGetRequest$2.invoke(Unknown Source:4)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at org.wordpress.android.fluxc.tools.CoroutineEngine.withDefaultContext(CoroutineEngine.kt:34)
at org.wordpress.android.fluxc.store.ReactNativeStore.executeGetRequest(ReactNativeStore.kt:74)
at org.wordpress.android.fluxc.store.EditorThemeStore.fetchEditorSettings(EditorThemeStore.kt:131)
at org.wordpress.android.fluxc.store.EditorThemeStore.access$fetchEditorSettings(EditorThemeStore.kt:31)
at org.wordpress.android.fluxc.store.EditorThemeStore$onAction$1.invokeSuspend(EditorThemeStore.kt:81)
at org.wordpress.android.fluxc.store.EditorThemeStore$onAction$1.invoke(Unknown Source:8)
at org.wordpress.android.fluxc.store.EditorThemeStore$onAction$1.invoke(Unknown Source:4)
at org.wordpress.android.fluxc.tools.CoroutineEngine$launch$1.invokeSuspend(CoroutineEngine.kt:62)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1d01f90, Dispatchers.Default]
```

**Comment by AjeshRPai** [comment]
Hey @RenanLukas 

I can see that you have created a GitHub issue for the same crash here - https://github.com/wordpress-mobile/WordPress-Android/issues/19646. I couldn't reproduce the crash by the steps you have mentioned. Further investigation shows that the crash logs mentioned in the [issue](https://a8c.sentry.io/issues/4227761466/?referrer=github_integration) also have site picker activity. 

Is it possible that the underlying cause of the issue is the steps mentioned by @SiobhyB in the description? If that's the case, maybe we can close the other issue and keep this one open. 🤔 

We can keep both issues open if you feel there can be multiple causes of this crash. I am adding both of these GitHub issues as notes on the sentry and will try to find a fix for the scenario in which the site is deleted.

**Comment by zwarm** [comment]
@AjeshRPai - It might be best to do a fetch sites on SitesList and raise an event to remove the site if the selected one has been deleted. I will move forward with this approach. wdyt?

**Comment by zwarm** [comment]
@AjeshRPai - I submitted a fix for the `site.username` NullPointerException in #19783 ; however it doesn't address deleted self-hosted sites not being removed from the list.  

I'm not 100% certain that self-hosted sites stay on your site list forever; but I'm not past 7 days yet. I'll be testing that within the next week.

**Adding some notes/log lines from my investigation** 
SiteErrorUtils - SiteError(type=GENERIC_ERROR, message=API calls to this endpoint have been disabled., selfHostedErrorType=NOT_SET).

The BE [code](fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Spynff.jcpbz%2Qwfba%2Qncv.cuc%3Se%3Q8p2n3r57%231673-og) sets this message, along with a 403 - unauthorized. I was thinking that perhaps, for mobile clients (not sure about Woo), that we can send a unique status code/message the let's the app know that this site has been deleted. Then it would be much easier to clean up self-hosted sites. I still have investigation to do, but the crash fix was the top priority.

**Comment by AjeshRPai** [comment]
Hey @zwarm 

>The BE [code](https://github.com/wordpress-mobile/WordPress-Android/issues/fbhepr%2Skers%2Sjcpbz%2Schoyvp.ncv%2Serfg%2Spynff.jcpbz%2Qwfba%2Qncv.cuc%3Se%3Q8p2n3r57%231673-og) sets this message, along with a 403 - unauthorized. I was thinking that perhaps, for mobile clients (not sure about Woo), that we can send a unique status code/message the let's the app know that this site has been deleted. Then it would be much easier to clean up self-hosted sites. I still have investigation to do, but the crash fix was the top priority.

I agree, I think we should address the deletion of sites from the app. The logic you have described here for deleting the sites from the app also makes sense.

**Comment by jkmassel** [comment]
Closing this issue — the referenced Sentry issue(s) no longer exist (404), which means this crash/error hasn't been seen in at least 90 days. If it resurfaces, it will appear as a new Sentry issue.
