### ISSUE TITLE
[Reader] NPE on Search - String.length() on a null object reference

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#20249]
https://a8c.sentry.io/issues/4263022768/events/e96c4793edb84e3e95b28f0044786571/

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
    at java.net.URLEncoder.encode(URLEncoder.java:224)
    at java.net.URLEncoder.encode(URLEncoder.java:196)
    at org.wordpress.android.util.UrlUtils.urlEncode(UrlUtils.java:29)
    at org.wordpress.android.ui.reader.services.search.ReaderSearchLogic.startSearch(ReaderSearchLogic.java:30)
    at org.wordpress.android.ui.reader.services.search.ReaderSearchJobService.onStartJob(ReaderSearchJobService.java:23)
    at android.app.job.JobService$1.onStartJob(JobService.java:102)
    at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:168)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8248)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
    at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:172)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8248)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
