### ISSUE TITLE
Can't comment 

### ISSUE THREAD

**Issue by Happyfeet01** [wordpress-mobile/WordPress-Android#2039]
Hello on my Blog I can't answer to comments with the Android App. It shows me "Answer not possible". With the browser it works. 

Here the error log from my phone. 

```
11-30 19:23:44.674 I/ActivityManager(3856): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.wordpress.android/.ui.WPLaunchActivity bnds=[24,805][282,1158]} from pid 5481
11-30 19:23:44.774 I/ActivityManager(3856): Start proc org.wordpress.android for activity org.wordpress.android/.ui.WPLaunchActivity: pid=31885 uid=10220 gids={50220, 3003, 1028, 1015}
11-30 19:23:46.104 I/ActivityManager(3856): START u0 {cmp=org.wordpress.android/.ui.posts.PostsActivity} from pid 31885
11-30 19:23:51.404 I/ActivityManager(3856): START u0 {flg=0x10000 cmp=org.wordpress.android/.ui.notifications.NotificationsActivity (has extras)} from pid 31885
11-30 19:25:46.084 I/WindowState(3856): WIN DEATH: Window{44b71d48 u0 org.wordpress.android/org.wordpress.android.ui.notifications.NotificationsActivity}
11-30 19:25:46.084 I/ActivityManager(3856): Process org.wordpress.android (pid 31885) has died.
11-30 19:28:02.014 I/ActivityManager(3856): START u0 {act=android.intent.action.VIEW dat=https://plus.url.google.com/url?q=https://github.com/wordpress-mobile/WordPress-Android/issues/2027&rct=j&ust=1417372381294000&usg=AFQjCNGzBenoP86tj105zljKMZwmFJ2v4g flg=0x80000 cmp=com.android.chrome/com.google.android.apps.chrome.Main (has extras)} from pid 3492
11-30 19:28:02.324 I/ActivityManager(3856): START u0 {act=android.intent.action.VIEW dat=https://plus.url.google.com/url?q=https://github.com/wordpress-mobile/WordPress-Android/issues/2027&rct=j&ust=1417372381294000&usg=AFQjCNGzBenoP86tj105zljKMZwmFJ2v4g flg=0x14002000 cmp=com.android.chrome/com.google.android.apps.chrome.ChromeTabbedActivity (has extras)} from pid 1444
11-30 19:28:37.734 I/ActivityManager(5481): Timeline: Activity_launch_request id:org.wordpress.android time:7983204
11-30 19:28:37.734 I/ActivityManager(3856): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.wordpress.android/.ui.WPLaunchActivity} from pid 5481
11-30 19:28:37.894 I/ActivityManager(3856): Start proc org.wordpress.android for activity org.wordpress.android/.ui.notifications.NotificationsActivity: pid=7077 uid=10220 gids={50220, 3003, 1028, 1015}
11-30 19:28:38.274 I/WordPress-NOTIFS(7077): Configuring Simperium
11-30 19:28:39.004 D/Volley  (7077): [1] VolleyLog.setTag: Changing log tag to WordPress
11-30 19:28:39.164 V/WordPress-UTILS(7077): instantiate OAuth using sFactory: class org.wordpress.android.networking.OAuthAuthenticatorFactoryDefault
11-30 19:28:39.164 V/WordPress-UTILS(7077): instantiate RestClient using sFactory: class org.wordpress.android.networking.RestClientFactoryDefault
11-30 19:28:39.174 V/WordPress-NOTIFS(7077): Already registered for GCM
11-30 19:28:39.174 I/WordPress-SUGGESTION(7077): resetting suggestion table
11-30 19:28:39.414 I/WordPress-NOTIFS(7077): Creating NotificationsActivity
11-30 19:28:39.754 I/WordPress-NOTIFS(7077): Starting Simperium buckets
11-30 19:28:40.174 D/WordPress-NOTIFS(7077): Register token action succeeded
11-30 19:28:40.214 D/WordPress-NOTIFS(7077): Server response OK. The device_id : 7671639
11-30 19:28:40.544 I/ActivityManager(3856): Displayed org.wordpress.android/.ui.notifications.NotificationsActivity: +2s660ms (total +38s294ms)
11-30 19:28:40.544 I/ActivityManager(3856): Timeline: Activity_windows_visible id: ActivityRecord{453cc410 u0 org.wordpress.android/.ui.notifications.NotificationsActivity t25} time:7986014
11-30 19:28:44.794 E/WordPress(7077): [2700] BasicNetwork.performRequest: Unexpected response code 400 for https://public-api.wordpress.com/rest/v1/sites/18038883/comments/1031/replies/new
11-30 19:28:44.794 E/WordPress-COMMENTS(7077): null
11-30 19:28:44.794 E/WordPress-COMMENTS(7077): com.android.volley.ServerError
11-30 19:28:44.794 E/WordPress-COMMENTS(7077): 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:178)
11-30 19:28:44.794 E/WordPress-COMMENTS(7077): 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
```

It's the latest beta and the login data are correct. 

My device: Sony Xperia Z1 C6903
Rooted, Android 4.4.4 

Greets Lars

**Comment by maxme** [comment]
> It's the latest beta and the login data are correct.

Hard to say if this bug still exists, please reopen the ticket if that's the case.
