### ISSUE TITLE
Remote config crash when retrieving integer value

### ISSUE THREAD

**Issue by pantstamp** [wordpress-mobile/WordPress-Android#20857]
During the development of the In-app updates project, a bug was discovered related to Remote Config values.

When our backend returns a remote config value and we try to retrieve its value we get a crash. The reason that this bug was not discovered earlier is that these values were not actually called in our codebase. 

Check the `PhaseFourOverlayFrequencyConfig` for example.

Try to call it from whatever place in the codebase you want. Check that you get the following crash. 

`FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.jetpack.android.prealpha, PID: 12546
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jetpack.android.prealpha/org.wordpress.android.ui.main.WPMainActivity}: java.lang.NumberFormatException: For input string: "7.0"
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3946)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
                                                                                                    Caused by: java.lang.NumberFormatException: For input string: "7.0"
                                                                                                    	at java.lang.Integer.parseInt(Integer.java:797)
                                                                                                    	at java.lang.Integer.parseInt(Integer.java:915)
                                                                                                    	at org.wordpress.android.util.config.RemoteConfigWrapper.getPhaseFourOverlayFrequencyConfig(RemoteConfigWrapper.kt:65)
                                                                                                    	at org.wordpress.android.ui.main.WPMainActivity.onCreate(WPMainActivity.java:534)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8767)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8745)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3928)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) ` 

Most probably, the cause of this crash is how we store these values in our database. 

![Screenshot 2024-05-17 at 9 51 32 AM](https://github.com/wordpress-mobile/WordPress-Android/assets/5176760/b3d999e1-7c44-41fe-bc07-e7cbad7b4bb5)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
