### ISSUE TITLE
TransactionTooLargeException in MediaPreviewActivity

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-Android#20913]
This issue is a specific occurrence of https://github.com/wordpress-mobile/WordPress-Android/issues/9685 rooting from the `MediaPreviewActivity`

### Breadcrumb 
![Screenshot 2024-05-30 at 2 28 50 PM](https://github.com/wordpress-mobile/WordPress-Android/assets/304044/7a324593-b247-4e15-9489-d3dc45878751)

### Stack trace
```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1781496 bytes
    at android.app.ActivityClient.activityStopped(ActivityClient.java:88)
    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
android.os.TransactionTooLargeException: data parcel size 1781496 bytes
    at android.os.BinderProxy.transactNative(BinderProxy.java)
    at android.os.BinderProxy.transact(BinderProxy.java:662)
    at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1309)
    at android.app.ActivityClient.activityStopped(ActivityClient.java:85)
    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8762)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Sentry Issue: [WORDPRESS-ANDROID-2XAX](https://a8c.sentry.io/issues/5176607388/?referrer=github_integration)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by antonis** [comment]
10 occurrences of this issue were recorder on May 27th from the same user on a [SM-A716U1 device](https://www.gsmarena.com/samsung_galaxy_a71_5g-10146.php) with `Android 13`.

**Comment by kernel0x** [comment]
can be fixed using a library Bundle Saver https://github.com/kernel0x/bundlesaver
