### ISSUE TITLE
IllegalArgumentException for drawer shadow drawable

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-Android#2148]
Looks like the drawer shadow drawable is getting resized to be too small and it raises an exception (See http://stackoverflow.com/questions/15428441/android-resource-not-found-because-of-width-and-height)

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.PostsActivity}: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/drawer_shadow.9.png from drawable resource ID #0x7f020088
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1956)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
at android.app.ActivityThread.access$600(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4429)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xxhdpi-v4/drawer_shadow.9.png from drawable resource ID #0x7f020088
at android.content.res.Resources.loadDrawable(Resources.java:1940)
at android.content.res.Resources.getDrawable(Resources.java:664)
at android.support.v4.widget.DrawerLayout.setDrawerShadow(DrawerLayout.java:400)
at org.wordpress.android.ui.WPDrawerActivity.initMenuDrawer(WPDrawerActivity.java:220)
at org.wordpress.android.ui.WPDrawerActivity.createMenuDrawer(WPDrawerActivity.java:187)
at org.wordpress.android.ui.posts.PostsActivity.onCreate(PostsActivity.java:65)
at android.app.Activity.performCreate(Activity.java:4465)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1055)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
... 11 more
Caused by: java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:623)
at android.graphics.Bitmap.createBitmap(Bitmap.java:571)
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:457)
at android.graphics.BitmapFactory.finishDecode(BitmapFactory.java:524)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:499)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:351)
at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:773)
at android.content.res.Resources.loadDrawable(Resources.java:1935)
... 19 more
```

**Comment by nbradbury** [comment]
Closed via #2149
