### ISSUE TITLE
Crash report 3.6: ArrayIndexOutOfBoundsException in StatsVisitorsAndViewsFragment

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2225]
```
java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.stats.StatsActivity}: java.lang.ArrayIndexOutOfBoundsException: length=7; index=9
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3076)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3105)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4054)
       at android.app.ActivityThread.access$1000(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1314)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=7; index=9
       at org.wordpress.android.ui.stats.StatsVisitorsAndViewsFragment.updateUIBelowTheGraph(StatsVisitorsAndViewsFragment.java:298)
       at org.wordpress.android.ui.stats.StatsVisitorsAndViewsFragment.updateUI(StatsVisitorsAndViewsFragment.java:281)
       at org.wordpress.android.ui.stats.StatsVisitorsAndViewsFragment.onResume(StatsVisitorsAndViewsFragment.java:190)
       at android.app.Fragment.performResume(Fragment.java:1743)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:924)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1044)
       at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1869)
       at android.app.Activity.performResume(Activity.java:5540)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3066)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3105)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4054)
       at android.app.ActivityThread.access$1000(ActivityThread.java:175)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1314)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniloercoli** [comment]
This issue could happen if the user bring back the app after device rotation (landscape to portrait).
