### ISSUE TITLE
Crash Report 3.6: Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2228]
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.android.volley.ServerError)
       at android.os.Parcel.writeSerializable(Parcel.java:1316)
       at android.os.Parcel.writeValue(Parcel.java:1264)
       at android.os.Parcel.writeArray(Parcel.java:672)
       at android.os.Parcel.writeValue(Parcel.java:1251)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
       at android.os.Bundle.writeToParcel(Bundle.java:1692)
       at android.os.Parcel.writeBundle(Parcel.java:636)
       at android.app.FragmentState.writeToParcel(Fragment.java:133)
       at android.os.Parcel.writeTypedArray(Parcel.java:1133)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:373)
       at android.os.Parcel.writeParcelable(Parcel.java:1285)
       at android.os.Parcel.writeValue(Parcel.java:1204)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
       at android.os.Bundle.writeToParcel(Bundle.java:1692)
       at android.os.Parcel.writeBundle(Parcel.java:636)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2755)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3396)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5579)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.io.NotSerializableException: com.android.volley.NetworkResponse
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1364)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:979)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:368)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1074)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
       at android.os.Parcel.writeSerializable(Parcel.java:1311)
       at android.os.Parcel.writeValue(Parcel.java:1264)
       at android.os.Parcel.writeArray(Parcel.java:672)
       at android.os.Parcel.writeValue(Parcel.java:1251)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
       at android.os.Bundle.writeToParcel(Bundle.java:1692)
       at android.os.Parcel.writeBundle(Parcel.java:636)
       at android.app.FragmentState.writeToParcel(Fragment.java:133)
       at android.os.Parcel.writeTypedArray(Parcel.java:1133)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:373)
       at android.os.Parcel.writeParcelable(Parcel.java:1285)
       at android.os.Parcel.writeValue(Parcel.java:1204)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:618)
       at android.os.Bundle.writeToParcel(Bundle.java:1692)
       at android.os.Parcel.writeBundle(Parcel.java:636)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2755)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3396)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5579)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by daniloercoli** [comment]
I bet this is something that happens in Stats :/ 
(Caused by: java.io.NotSerializableException: com.android.volley.NetworkResponse)

java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = [Ljava.io.Serializable;)
       at android.os.Parcel.writeSerializable(Parcel.java:1388)
       at android.os.Parcel.writeValue(Parcel.java:1335)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1096)
       at android.os.Parcel.writeBundle(Parcel.java:663)
       at android.app.FragmentState.writeToParcel(Fragment.java:139)
       at android.os.Parcel.writeTypedArray(Parcel.java:1191)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:376)
       at android.os.Parcel.writeParcelable(Parcel.java:1357)
       at android.os.Parcel.writeValue(Parcel.java:1262)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1096)
       at android.os.Parcel.writeBundle(Parcel.java:663)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2884)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3261)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.io.NotSerializableException: com.android.volley.NetworkResponse
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at java.io.ObjectOutputStream.writeNewArray(ObjectOutputStream.java:1185)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1642)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at android.os.Parcel.writeSerializable(Parcel.java:1383)
       at android.os.Parcel.writeValue(Parcel.java:1335)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1096)
       at android.os.Parcel.writeBundle(Parcel.java:663)
       at android.app.FragmentState.writeToParcel(Fragment.java:139)
       at android.os.Parcel.writeTypedArray(Parcel.java:1191)
       at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:376)
       at android.os.Parcel.writeParcelable(Parcel.java:1357)
       at android.os.Parcel.writeValue(Parcel.java:1262)
       at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
       at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
       at android.os.Bundle.writeToParcel(Bundle.java:1096)
       at android.os.Parcel.writeBundle(Parcel.java:663)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2884)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3261)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
