### ISSUE TITLE
Crash report 3.6: NullPointerException in ThemeSearchFragment

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2237]
Very rare:
```
java.lang.NullPointerException
       at org.wordpress.android.ui.themes.ThemeSearchFragment.onItemClick(ThemeSearchFragment.java:95)
       at android.widget.AdapterView.performItemClick(AdapterView.java:292)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:2715)
       at android.widget.AbsListView$1.run(AbsListView.java:3473)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4511)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:976)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:743)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
#2496 was not included in the 3.9 release (nor the 3.9.1 hotfix) but has addressed this for versions 4.+
