### ISSUE TITLE
Reader IllegalStateException with reveal animation

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2245]
There are three reports of the below exception in 3.6. Problem is caused by starting the blog/tag preview reveal animation when the view is invalid.
```
java.lang.IllegalStateException: Cannot start this animator on a detached view!
       at android.view.RenderNode.addAnimator(RenderNode.java:817)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:277)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:261)
       at android.animation.RevealAnimator.(RevealAnimator.java:37)
       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:48)
       at org.wordpress.android.ui.reader.ReaderPostListFragment$3.run(ReaderPostListFragment.java:363)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5255)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by zhangxiaang** [comment]
you started the animator before ur view had inflated , so u should do like this:

view.post( new Runnable(){
@Override
            public void run() {
                enterRevel();
            }
}
);
maybe this method will resolve ur problem :)

**Comment by TheLoyalCruel** [comment]
@zhangxiaang thank you... :)
it works like charm...

**Comment by CHRehan** [comment]
Check your Layout is attached to window or not by using r`ootLayout.isAttachedToWindow()` method.

```
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        if (rootLayout!= null) {

            if(rootLayout.isAttachedToWindow()) {
                ViewTreeObserver viewTreeObserver = drawerLayout.getViewTreeObserver();
                if (viewTreeObserver.isAlive()) {
                    viewTreeObserver.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
                        @Override
                        public void onGlobalLayout() {
                            startRevealAnimation(rootLayout);
                            rootLayout.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                        }
                    });
                }
            }
        }
```
