### ISSUE TITLE
Reader: IndexOutOfBoundsException liking a comment

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2249]
Only one report of this in 3.6, but looking at my code it's a valid bug that should be fixed.
```
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.set(ArrayList.java:481)
       at org.wordpress.android.ui.reader.adapters.ReaderCommentAdapter.toggleLike(ReaderCommentAdapter.java:310)
       at org.wordpress.android.ui.reader.adapters.ReaderCommentAdapter.access$1600(ReaderCommentAdapter.java:35)
       at org.wordpress.android.ui.reader.adapters.ReaderCommentAdapter$3.onClick(ReaderCommentAdapter.java:276)
       at android.view.View.performClick(View.java:4463)
       at android.view.View$PerformClick.run(View.java:18789)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5323)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniloercoli** [comment]
How the user can perform an action on an item, in this case toggleLike, if the item is not in the comments list (position is invalid)?

**Comment by nbradbury** [comment]
That is a very good question :) There were only two things I could think of that *might* cause this:
* The device was rotated at the same time the comment was liked
* The user liked a comment at the same time the list of comments was being updated, and after the update the list had fewer comments (ex: a comment was deleted, the author removed all comments, etc.)

At any rate, my bug was not checking whether the passed position was valid, which should always be done.

**Comment by daniloercoli** [comment]
:+1:
