### ISSUE TITLE
Crash Report 3.6: Notifications Index OutOfBoundsException

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2258]
This crash is high in crashes list:

```
java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at org.wordpress.android.ui.notifications.adapters.NoteBlockAdapter.getView(NoteBlockAdapter.java:36)
       at android.widget.AbsListView.obtainView(AbsListView.java:2605)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1261)
       at android.widget.ListView.onMeasure(ListView.java:1173)
       at android.view.View.measure(View.java:16840)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16840)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:477)
       at android.view.View.measure(View.java:16840)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16840)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16840)
       at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:851)
       at android.view.View.measure(View.java:16840)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16840)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16840)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16840)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16840)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2586)
       at android.view.View.measure(View.java:16840)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2072)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1232)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1415)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1129)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6282)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:561)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:177)
       at android.app.ActivityThread.main(ActivityThread.java:5496)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by roundhill** [comment]
I figured out how to reproduce, which I think is a fairly rare situation:

1. View a 'x people liked your post' note.
2. Unlike the post using an account that was already in the likers list.
3. Simperium sends the change with a shorter list and the out of index happens.
