### ISSUE TITLE
Crash report 3.6: null host passed to `getXmlrpcByUserEnteredPath`

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2269]
```
java.lang.IllegalArgumentException: Host name may not be null
       at org.apache.http.HttpHost.(HttpHost.java:83)
       at org.apache.http.impl.client.DefaultRequestDirector.handleResponse(DefaultRequestDirector.java:2894)
       at org.apache.http.impl.client.DefaultRequestDirector.executeOriginal(DefaultRequestDirector.java:1347)
       at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:677)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:567)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:491)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:469)
       at org.xmlrpc.android.XMLRPCClient$Caller.callXMLRPC(XMLRPCClient.java:466)
       at org.xmlrpc.android.XMLRPCClient$Caller.access$000(XMLRPCClient.java:396)
       at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:216)
       at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:211)
       at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getXmlrpcByUserEnteredPath(FetchBlogListWPOrg.java:159)
       at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getSelfHostedXmlrpcUrl(FetchBlogListWPOrg.java:266)
       at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.fetchBlogList(FetchBlogListWPOrg.java:109)
       at org.wordpress.android.ui.accounts.helpers.FetchBlogListAbstract$1.run(FetchBlogListAbstract.java:26)
```

**Comment by maxme** [comment]
This is weird, we're checking the URL is valid just before this crash:

https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/accounts/helpers/FetchBlogListWPOrg.java#L147

**Comment by nbradbury** [comment]
Could the problem be due to an underscore in the URL? Underscores in URLs won't be an issue with our `UrlUtils.isValidUrlAndHostNotUrl()` but [they were known to cause the "host name may not be null" exception with HttpClient](https://issues.apache.org/jira/browse/HTTPCLIENT-911).

**Comment by maxme** [comment]
> Could the problem be due to an underscore in the URL

Apparently not, just tried with an underscore in a URL and <a href="https://github.com/wordpress-mobile/WordPress-Android/blob/fc9f1990b7562ea2c5650b0ca5f0321e73b9f018/libs/utils/WordPressUtils/src/main/java/org/wordpress/android/util/UrlUtils.java#L154-L164">this</a> returns false (`uri.getHost() == null`).

**Comment by nbradbury** [comment]
Right, a URL containing an underscore is considered valid by our `isValidUrlAndHostNotUrl()` check but it *might* not be considered valid by Apache's HttpClient. In other words, our URL validation _may_ be different than that used by HttpClient, which could result in this exception.

**Comment by maxme** [comment]
That's weird cause, they use the same `java.net.URI` class we check before the call:
https://github.com/android/platform_external_apache-http/blob/master/src/org/apache/http/impl/client/DefaultRequestDirector.java#L923-L928

**Comment by maxme** [comment]
FYI: Same exception (different line numbers)

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.IllegalArgumentException: Host name may not be null
       at org.apache.http.HttpHost.(HttpHost.java:83)
       at org.apache.http.impl.client.DefaultRequestDirector.handleResponse(DefaultRequestDirector.java:925)
       at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:475)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
       at org.xmlrpc.android.XMLRPCClient$Caller.callXMLRPC(XMLRPCClient.java:466)
       at org.xmlrpc.android.XMLRPCClient$Caller.access$000(XMLRPCClient.java:396)
       at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:216)
       at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:200)
       at org.xmlrpc.android.ApiHelper$FetchPostsTask.doInBackground(ApiHelper.java:439)
       at org.xmlrpc.android.ApiHelper$FetchPostsTask.doInBackground(ApiHelper.java:407)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
```

I think I'll add a catch around `callXMLRPC` and log the passed URL using `CrashlyticsUtilslogException(e, ExceptionType.SPECIFIC)`

**Comment by maxme** [comment]
No more of this crash  and no "non-fatal" report in 3.7 - I'm pretty sure this was fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/2295
