### ISSUE TITLE
Crash report 3.6: OOM in WPImageSpan.draw

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2315]
We should not decode bitmap resource during the `draw` call [here](https://github.com/wordpress-mobile/WordPress-Android/blob/fc9f1990b7562ea2c5650b0ca5f0321e73b9f018/WordPress/src/main/java/org/wordpress/android/widgets/WPImageSpan.java#L82) (load it once and only call ` canvas.drawBitmap` during `draw`)

```
java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:706)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:531)
       at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:559)
       at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:589)
       at org.wordpress.android.widgets.WPImageSpan.draw(WPImageSpan.java:82)
       at android.text.TextLine.handleReplacement(TextLine.java:927)
       at android.text.TextLine.handleRun(TextLine.java:1010)
       at android.text.TextLine.drawRun(TextLine.java:464)
       at android.text.TextLine.draw(TextLine.java:262)
       at android.text.Layout.drawText(Layout.java:363)
       at android.text.Layout.draw(Layout.java:220)
       at android.widget.TextView.onDraw(TextView.java:6668)
       at android.view.View.draw(View.java:15551)
       at android.view.View.getDisplayList(View.java:14445)
       at android.view.View.getDisplayList(View.java:14487)
       at android.view.View.draw(View.java:15265)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3366)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
       at android.view.View.getDisplayList(View.java:14440)
       at android.view.View.getDisplayList(View.java:14487)
       at android.view.View.draw(View.java:15265)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3366)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3202)
       at android.view.View.draw(View.java:15554)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.widget.ScrollView.draw(ScrollView.java:2424)
       at android.view.View.getDisplayList(View.java:14445)
       at android.view.View.getDisplayList(View.java:14487)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
       at android.view.View.getDisplayList(View.java:14382)
       at android.view.View.getDisplayList(View.java:14487)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
       at android.view.View.getDisplayList(View.java:14382)
       at android.view.View.getDisplayList(View.java:14487)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
       at android.view.View.getDisplayList(View.java:14382)
       at android.view.View.getDisplayList(View.java:14487)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
       at android.view.View.getDisplayList(View.java:14382)
       at android.view.View.getDisplayList(View.java:14487)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
       at android.view.View.getDisplayList(View.java:14382)
       at android.view.View.getDisplayList(View.java:14487)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
       at android.view.View.getDisplayList(View.java:14382)
       at android.view.View.getDisplayList(View.java:14487)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3340)
       at android.view.View.getDisplayList(View.java:14382)
       at android.view.View.getDisplayList(View.java:14487)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1597)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1469)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2839)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2705)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2275)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1297)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6773)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
       at android.view.Choreographer.doCallbacks(Choreographer.java:613)
       at android.view.Choreographer.doFrame(Choreographer.java:583)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5748)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by maxme** [comment]
It's going to be fixed by this branch: https://github.com/wordpress-mobile/WordPress-Android/tree/feature/modularize-editor

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
