### ISSUE TITLE
Crash report 3.8-rc-2: NullPointerException in HtmlToSpannedConverter.convert

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2416]
```
03-10 11:30:34.651    8847-8948/org.wordpress.android.beta E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #4
    Process: org.wordpress.android.beta, PID: 8847
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
            at org.wordpress.android.util.HtmlToSpannedConverter.startImg(WPHtml.java:810)
            at org.wordpress.android.util.HtmlToSpannedConverter.handleStartTag(WPHtml.java:652)
            at org.wordpress.android.util.HtmlToSpannedConverter.startElement(WPHtml.java:992)
            at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
            at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
            at org.ccil.cowan.tagsoup.Parser.stage(Parser.java:1026)
            at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:632)
            at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
            at org.wordpress.android.util.HtmlToSpannedConverter.convert(WPHtml.java:552)
            at org.wordpress.android.util.WPHtml.fromHtml(WPHtml.java:159)
            at org.wordpress.android.util.WPHtml.fromHtml(WPHtml.java:122)
            at org.wordpress.android.ui.posts.EditPostPreviewFragment$LoadPostPreviewTask.doInBackground(EditPostPreviewFragment.java:78)
            at org.wordpress.android.ui.posts.EditPostPreviewFragment$LoadPostPreviewTask.doInBackground(EditPostPreviewFragment.java:62)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.
