### ISSUE TITLE
Crash report 3.9-rc-1: NullPointerException in EditPostContentFragment

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2441]
```
java.lang.NullPointerException
       at org.wordpress.android.util.ToastUtils.showToast(ToastUtils.java:23)
       at org.wordpress.android.ui.posts.EditPostContentFragment$19.onFailure(EditPostContentFragment.java:1689)
       at org.xmlrpc.android.ApiHelper$SyncMediaLibraryTask.onPostExecute(ApiHelper.java:680)
       at org.xmlrpc.android.ApiHelper$SyncMediaLibraryTask.onPostExecute(ApiHelper.java:582)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5146)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by bummytime** [comment]
Closing issue and migrating to new repo.

**Comment by maxme** [comment]
reopening - 3.9 issue
