### ISSUE TITLE
Crash when signing out from the Media screen

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2457]
```
03-24 11:06:33.193    1890-1890/org.wordpress.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 1890
    java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.wordpress.android.ui.media.MediaBrowserActivity$1@3e507bfa
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:871)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.models.Blog.getLocalTableBlogId()' on a null object reference
            at org.wordpress.android.ui.media.MediaBrowserActivity$1.onReceive(MediaBrowserActivity.java:80)
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:861)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)```

**Comment by maxme** [comment]
dup https://github.com/wordpress-mobile/WordPress-Android/issues/2445
