### ISSUE TITLE
Crash report 3.9-rc-1: NPE in HtmlToSpannedConverter.startImg

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2458]
Probably a side effect introduced by the new media picker:

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:278)
       at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
       at org.wordpress.android.util.HtmlToSpannedConverter.startImg(WPHtml.java:810)
       at org.wordpress.android.util.HtmlToSpannedConverter.handleStartTag(WPHtml.java:652)
       at org.wordpress.android.util.HtmlToSpannedConverter.startElement(WPHtml.java:992)
       at org.ccil.cowan.tagsoup.Parser.push(Parser.java:794)
       at org.ccil.cowan.tagsoup.Parser.rectify(Parser.java:1061)
       at org.ccil.cowan.tagsoup.Parser.stage(Parser.java:1026)
       at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:573)
       at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:449)
       at org.wordpress.android.util.HtmlToSpannedConverter.convert(WPHtml.java:552)
       at org.wordpress.android.util.WPHtml.fromHtml(WPHtml.java:159)
       at org.wordpress.android.util.WPHtml.fromHtml(WPHtml.java:122)
       at org.wordpress.android.ui.posts.EditPostPreviewFragment$LoadPostPreviewTask.doInBackground(EditPostPreviewFragment.java:78)
       at org.wordpress.android.ui.posts.EditPostPreviewFragment$LoadPostPreviewTask.doInBackground(EditPostPreviewFragment.java:62)
       at android.os.AsyncTask$2.call(AsyncTask.java:264)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by tonyr59h** [comment]
Looks like the context is null [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/WPHtml.java#L810).

We should probably wrap that block with a null check, but on top of that figure out why it's null in the first place. [Here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java#L80) is the offending null Activity. I'm going to store the load task and cancel it if the fragment is destroyed, onResume will attempt another reload.

**Comment by tonyr59h** [comment]
Also, it's odd that mActivity is available and [non-null](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostPreviewFragment.java#L68) but getActivity() is being used.
