### ISSUE TITLE
Crash when returning from the media picker with no selected media

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2501]
In the `develop` branch:

1. Create a new post
1. Tap the pick media button
1. Tap the back button -> crash

```
E/AndroidRuntime( 4432): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android.beta/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException
E/AndroidRuntime( 4432): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
E/AndroidRuntime( 4432): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
E/AndroidRuntime( 4432): 	at android.app.ActivityThread.access$600(ActivityThread.java:130)
E/AndroidRuntime( 4432): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
E/AndroidRuntime( 4432): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4432): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 4432): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 4432): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4432): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 4432): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 4432): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 4432): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 4432): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 4432): 	at org.wordpress.android.ui.posts.EditPostActivity.fillContentEditorFields(EditPostActivity.java:680)
E/AndroidRuntime( 4432): 	at org.wordpress.android.ui.posts.EditPostActivity.onEditorFragmentInitialized(EditPostActivity.java:1439)
E/AndroidRuntime( 4432): 	at org.wordpress.android.editor.LegacyEditorFragment.onCreateView(LegacyEditorFragment.java:220)
E/AndroidRuntime( 4432): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:829)
E/AndroidRuntime( 4432): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
E/AndroidRuntime( 4432): 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1017)
E/AndroidRuntime( 4432): 	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1802)
E/AndroidRuntime( 4432): 	at android.app.Activity.performCreate(Activity.java:5011)
E/AndroidRuntime( 4432): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
E/AndroidRuntime( 4432): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
E/AndroidRuntime( 4432): 	... 11 more
```

**Comment by maxme** [comment]
Just noticed "Don't keep activities" is checked in my settings.

**Comment by tonyr59h** [comment]
This is actually a pretty tricky issue. [Lifecycle calls](http://vardhan-justlikethat.blogspot.in/2014/05/fragment-lifecycle-with-respect-to-its.html) for the fragment and the activity are different if the Activity gets destroyed and re-created. This NPE is only the start of the problems, we need to defer appending media files until after instantiateItem is called.

**Comment by tonyr59h** [comment]
Found a somewhat elegant solution thanks to FragmentManagers' [ability to pass fragments via Bundle.](http://developer.android.com/reference/android/app/FragmentManager.html#getFragment(android.os.Bundle, java.lang.String))

**Comment by maxme** [comment]
Yep it's not an easy one, I've noticed something weird too: `FragmentStatePagerAdapter.onRestore()` is not called.

**Comment by maxme** [comment]
> Found a somewhat elegant solution thanks to FragmentManagers' ability to pass fragments via Bundle.

Yep, actually that's what `FragmentStatePagerAdapter` is using: https://github.com/android/platform_frameworks_support/blob/master/v4/java/android/support/v4/app/FragmentStatePagerAdapter.java#L211
