### ISSUE TITLE
Tapping the image button in the editor returns the user back to the post list with a local draft

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2512]
Reported by several users on different devices:
 - Nexus 5 - 5.0.1
 - Samsung Galaxy S5 - 5.0
 - ? - 4.4

I wasn't able to repro, potential steps:

1. Create a new post
1. Tap the image button in the toolbar

**Comment by maxme** [comment]
It's probably not related to a device / android version. I can't repro on a Nexus 5 - 5.0.1.

**Comment by roundhill** [comment]
Repro'd on Sony Z3 compact, picking this one up

**Comment by roundhill** [comment]
```
A/ActivityManager﹕ Exception thrown launching activities in ProcessRecord{3c6bff04 10914:org.wordpress.android/u0a417}
    android.os.TransactionTooLargeException
            at android.os.BinderProxy.transactNative(Native Method)
            at android.os.BinderProxy.transact(Binder.java:496)
            at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:798)
            at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1187)
            at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:556)
            at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6321)
            at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6383)
            at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:482)
            at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2449)
            at android.os.Binder.execTransact(Binder.java:446)
```

**Comment by maxme** [comment]
https://github.com/wordpress-mobile/WordPress-Android/blob/d0ba0604c0cf1aec6b36638fe36d5e9c3f5d1127/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1303-L1318
