### ISSUE TITLE
Crash report 3.9-rc-4: RejectedExecutionException in MediaUtils.fadeMediaItemImageIntoView

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2522]
Too many AsyncTask queued (from `MediaUtils.fadeMediaItemImageIntoView`)

```
java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@364d4662 rejected from java.util.concurrent.ThreadPoolExecutor@3c2503f3[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 556]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:590)
       at org.wordpress.mediapicker.MediaUtils.fadeMediaItemImageIntoView(MediaUtils.java:123)
       at org.wordpress.mediapicker.source.MediaSourceDeviceImages.getView(MediaSourceDeviceImages.java:143)
       at org.wordpress.mediapicker.MediaSourceAdapter.getView(MediaSourceAdapter.java:83)
       at android.widget.AbsListView.obtainView(AbsListView.java:2344)
       at android.widget.GridView.makeAndAddView(GridView.java:1433)
       at android.widget.GridView.makeRow(GridView.java:361)
       at android.widget.GridView.fillDown(GridView.java:302)
       at android.widget.GridView.fillGap(GridView.java:262)
       at android.widget.AbsListView.trackMotionScroll(AbsListView.java:4972)
       at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4516)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:549)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5336)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by maxme** [comment]
Comment from the Playstore, I think it's related:

> Last update killed the app! After the last update I cannot upload pictures. Each time I want to add a picture the application crashes.

**Comment by maxme** [comment]
Same kind of issue:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.media.MediaPickerActivity}: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@445f4760 rejected from java.util.concurrent.ThreadPoolExecutor@41c95560[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 386]
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3930)
       at android.app.ActivityThread.access$900(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@445f4760 rejected from java.util.concurrent.ThreadPoolExecutor@41c95560[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 386]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:590)
       at org.wordpress.android.ui.media.MediaSourceWPImages.removeDeletedEntries(MediaSourceWPImages.java:212)
       at org.wordpress.android.ui.media.MediaSourceWPImages.addWordPressImagesFromCursor(MediaSourceWPImages.java:162)
       at org.wordpress.android.ui.media.MediaSourceWPImages.gather(MediaSourceWPImages.java:49)
       at org.wordpress.mediapicker.MediaSourceAdapter.gatherFromSources(MediaSourceAdapter.java:46)
       at org.wordpress.mediapicker.MediaPickerFragment.generateAdapter(MediaPickerFragment.java:536)
       at org.wordpress.mediapicker.MediaPickerFragment.setMediaSources(MediaPickerFragment.java:338)
       at org.wordpress.mediapicker.MediaPickerFragment.restoreFromBundle(MediaPickerFragment.java:468)
       at org.wordpress.mediapicker.MediaPickerFragment.onCreate(MediaPickerFragment.java:133)
       at android.app.Fragment.performCreate(Fragment.java:1678)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1044)
       at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1848)
       at android.app.Activity.onCreate(Activity.java:902)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:255)
       at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:122)
       at org.wordpress.android.ui.media.MediaPickerActivity.onCreate(MediaPickerActivity.java:98)
       at android.app.Activity.performCreate(Activity.java:5264)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3930)
       at android.app.ActivityThread.access$900(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1327)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
[This update](https://github.com/wordpress-mobile/MediaPicker-Android/pull/16) to the media library should resolve the RejectedExecutionException issue. I'm going to hold off on a merge until tomorrow while I make sure it doesn't break anything in WordPress for Android.

**Comment by Bwc84** [comment]
Thanks man I'm new I need all the guidance I can get

**Comment by maxme** [comment]
@tonyr59h we should also implement the same kind of throttling here https://github.com/wordpress-mobile/WordPress-Android/blob/102b476211c3d2b30480f500297d61ba0fe8ee71/WordPress/src/main/java/org/wordpress/android/ui/media/MediaSourceWPImages.java#L175 (to fix ://github.com/wordpress-mobile/WordPress-Android/issues/2522#issuecomment-93995886)
