### ISSUE TITLE
Crash report 4.0 - ExceptionInInitializerError in SignInFragment

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2531]
```
java.lang.ExceptionInInitializerError
       at org.wordpress.android.ui.accounts.SignInFragment.refreshBlogContent(SignInFragment.java:844)
       at org.wordpress.android.ui.accounts.SignInFragment.refreshFirstBlogContent(SignInFragment.java:857)
       at org.wordpress.android.ui.accounts.SignInFragment.access$1900(SignInFragment.java:70)
       at org.wordpress.android.ui.accounts.SignInFragment$11.onSuccess(SignInFragment.java:434)
       at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getBlogList(FetchBlogListWPOrg.java:87)
       at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.fetchBlogList(FetchBlogListWPOrg.java:127)
       at org.wordpress.android.ui.accounts.helpers.FetchBlogListAbstract$1.run(FetchBlogListAbstract.java:27)
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
       at android.os.Handler.(Handler.java:121)
       at android.os.AsyncTask$InternalHandler.(AsyncTask.java:607)
       at android.os.AsyncTask$InternalHandler.(AsyncTask.java:607)
       at android.os.AsyncTask.(AsyncTask.java:190)
       at org.wordpress.android.ui.accounts.SignInFragment.refreshBlogContent(SignInFragment.java:844)
       at org.wordpress.android.ui.accounts.SignInFragment.refreshFirstBlogContent(SignInFragment.java:857)
       at org.wordpress.android.ui.accounts.SignInFragment.access$1900(SignInFragment.java:70)
       at org.wordpress.android.ui.accounts.SignInFragment$11.onSuccess(SignInFragment.java:434)
       at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.getBlogList(FetchBlogListWPOrg.java:87)
       at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg.fetchBlogList(FetchBlogListWPOrg.java:127)
       at org.wordpress.android.ui.accounts.helpers.FetchBlogListAbstract$1.run(FetchBlogListAbstract.java:27)
```

**Comment by maxme** [comment]
dup #2459
