### ISSUE TITLE
Crash report 4.0 - NPE in ThemeSearchFragment onItemClick

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2532]
```
java.lang.NullPointerException
       at org.wordpress.android.ui.themes.ThemeSearchFragment.onItemClick(ThemeSearchFragment.java:95)
       at android.widget.AdapterView.performItemClick(AdapterView.java:292)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1068)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:2525)
       at android.widget.AbsListView$1.run(AbsListView.java:3186)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4448)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by maxme** [comment]
dup #2237 (reopening)
