### ISSUE TITLE
Crash report 4.0-rc-1: NPE in EditPostActivity

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2564]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.editor.EditorFragmentAbstract.setFeaturedImageSupported(boolean)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2405)
       at android.app.ActivityThread.access$800(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5317)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.editor.EditorFragmentAbstract.setFeaturedImageSupported(boolean)' on a null object reference
       at org.wordpress.android.ui.posts.EditPostActivity.fillContentEditorFields(EditPostActivity.java:689)
       at org.wordpress.android.ui.posts.EditPostActivity.onEditorFragmentInitialized(EditPostActivity.java:1449)
       at org.wordpress.android.editor.LegacyEditorFragment.onCreateView(LegacyEditorFragment.java:220)
       at android.app.Fragment.performCreateView(Fragment.java:2053)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
       at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1869)
       at android.app.Activity.performCreateCommon(Activity.java:5928)
       at android.app.Activity.performCreate(Activity.java:5935)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2405)
       at android.app.ActivityThread.access$800(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5317)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by maxme** [comment]
A slightly different one:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2218)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268)
       at android.app.ActivityThread.access$600(ActivityThread.java:148)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1263)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5162)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:756)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:572)
       at miui.dexspy.DexspyInstaller.main(DexspyInstaller.java:171)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at org.wordpress.android.ui.posts.EditPostActivity.fillContentEditorFields(EditPostActivity.java:689)
       at org.wordpress.android.ui.posts.EditPostActivity.onEditorFragmentInitialized(EditPostActivity.java:1449)
       at org.wordpress.android.editor.LegacyEditorFragment.onCreateView(LegacyEditorFragment.java:220)
       at android.app.Fragment.performCreateView(Fragment.java:1699)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1039)
       at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1847)
       at android.app.Activity.performCreate(Activity.java:5138)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at com.lbe.security.service.core.client.b.x.callActivityOnCreate()
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2182)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2268)
       at android.app.ActivityThread.access$600(ActivityThread.java:148)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1263)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5162)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:756)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:572)
       at miui.dexspy.DexspyInstaller.main(DexspyInstaller.java:171)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
Looks very similar to #2501 which involves "Don't keep Activities" being on.
