### ISSUE TITLE
Crash report 3.9.1: NPE in MediaUtils.getMediaItemFromVideoCursor

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#2640]
```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.(Uri.java:467)
       at android.net.Uri$StringUri.(Uri.java:457)
       at android.net.Uri.parse(Uri.java:429)
       at org.wordpress.mediapicker.MediaUtils.getMediaItemFromVideoCursor(MediaUtils.java:324)
       at org.wordpress.mediapicker.MediaUtils.createMediaItems(MediaUtils.java:89)
       at org.wordpress.mediapicker.source.MediaSourceDeviceVideos.createMediaItems(MediaSourceDeviceVideos.java:40)
       at org.wordpress.mediapicker.source.MediaSourceDeviceImages$GatherDeviceImagesTask.doInBackground(MediaSourceDeviceImages.java:191)
       at org.wordpress.mediapicker.source.MediaSourceDeviceImages$GatherDeviceImagesTask.doInBackground(MediaSourceDeviceImages.java:182)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by maxme** [comment]
Note: must be fixed in https://github.com/wordpress-mobile/MediaPicker-Android

**Comment by maxme** [comment]
fixed via https://github.com/wordpress-mobile/WordPress-Android/pull/2657
