### ISSUE TITLE
NPE saving null fragment state in EditPostActivity

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2675]
Shouldn't save a null fragment.

```
java.lang.NullPointerException
       at android.app.FragmentManagerImpl.putFragment(FragmentManager.java:521)
       at org.wordpress.android.ui.posts.EditPostActivity.onSaveInstanceState(EditPostActivity.java:322)
       at android.app.Activity.performSaveInstanceState(Activity.java:1171)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1230)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3018)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3077)
       at android.app.ActivityThread.access$1000(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1268)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4953)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
Addressed in #2678, closing.
