### ISSUE TITLE
NPE when updating post settings

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2696]
[Looks like](https://github.com/wordpress-mobile/WordPress-Android/blob/4.0/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostSettingsFragment.java#L461) mPostFormatSpinner is null.
```
java.lang.NullPointerException
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.updatePostSettings(EditPostSettingsFragment.java:461)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:559)
       at org.wordpress.android.ui.posts.EditPostActivity.savePost(EditPostActivity.java:569)
       at org.wordpress.android.ui.posts.EditPostActivity.savePost(EditPostActivity.java:564)
       at org.wordpress.android.ui.posts.EditPostActivity.access$400(EditPostActivity.java:93)
       at org.wordpress.android.ui.posts.EditPostActivity$AutoSaveTask.run(EditPostActivity.java:273)
       at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by tonyr59h** [comment]
Addressed in #2744, closing.
