### ISSUE TITLE
Bad array lengths in PostUploadService notification update

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2697]
```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:820)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:348)
       at android.app.NotificationManager.notify(NotificationManager.java:139)
       at android.app.NotificationManager.notify(NotificationManager.java:112)
       at org.wordpress.android.ui.posts.PostUploadService$PostUploadNotifier.updateNotificationProgress(PostUploadService.java:960)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask$1.onBytesUploaded(PostUploadService.java:811)
       at org.xmlrpc.android.XMLRPCClient$CountingOutputStream.write(XMLRPCClient.java:680)
       at org.apache.http.entity.FileEntity.writeTo(FileEntity.java:83)
       at org.xmlrpc.android.XMLRPCClient$1.writeTo(XMLRPCClient.java:371)
       at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:97)
       at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:162)
       at org.apache.http.impl.conn.AbstractClientConnAdapter.sendRequestEntity(AbstractClientConnAdapter.java:272)
       at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
       at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:119)
       at org.apache.http.impl.client.DefaultRequestDirector.executeOriginal(DefaultRequestDirector.java:1248)
       at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:644)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:564)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:491)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:469)
       at org.xmlrpc.android.XMLRPCClient$Caller.callXMLRPC(XMLRPCClient.java:481)
       at org.xmlrpc.android.XMLRPCClient$Caller.access$000(XMLRPCClient.java:411)
       at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:228)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.uploadFileHelper(PostUploadService.java:817)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.uploadImageFile(PostUploadService.java:776)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.uploadImage(PostUploadService.java:628)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.processPostMedia(PostUploadService.java:483)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.doInBackground(PostUploadService.java:222)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.doInBackground(PostUploadService.java:150)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by tonyr59h** [comment]
[Possibly related discussion.](http://stackoverflow.com/questions/7988018/custom-notification-java-lang-runtimeexception-bad-array-lengths)

**Comment by tonyr59h** [comment]
Duplicate of #2858, closing.
