### ISSUE TITLE
IllegalStateException when selecting media items

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2698]
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
       at android.app.BackStackRecord.commit(BackStackRecord.java:575)
       at org.wordpress.android.ui.media.MediaBrowserActivity.onMediaItemSelected(MediaBrowserActivity.java:341)
       at org.wordpress.android.ui.media.MediaGridFragment.onItemClick(MediaGridFragment.java:464)
       at android.widget.AdapterView.performItemClick(AdapterView.java:308)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1495)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3457)
       at android.widget.AbsListView$3.run(AbsListView.java:4820)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5479)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
Addressed in #2746, closing.
