### ISSUE TITLE
NPE creating image span after image loads

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2700]
Tough one, Activity is null when span is created.
```
java.lang.NullPointerException
       at org.wordpress.android.editor.legacy.WPEditImageSpan.init(WPEditImageSpan.java:35)
       at org.wordpress.android.editor.legacy.WPEditImageSpan.(WPEditImageSpan.java:26)
       at org.wordpress.android.editor.LegacyEditorFragment$14.onResponse(LegacyEditorFragment.java:981)
       at com.android.volley.toolbox.ImageLoader$4.run(ImageLoader.java:474)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5748)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
[Moved](https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/156) to Editor repository.
