### ISSUE TITLE
Crash report 4.1-rc1: AssertionError in StatsFollowersFragment 

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#2759]
Related to https://github.com/wordpress-mobile/WordPress-Android/issues/2639

``` 
de.greenrobot.event.EventBusException: Invoking subscriber failed
       at de.greenrobot.event.EventBus.handleSubscriberException(EventBus.java:518)
       at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:500)
       at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:492)
       at de.greenrobot.event.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5398)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.AssertionError: couldn't initialize LocaleData for locale en-gb
       at libcore.icu.LocaleData.initLocaleData(LocaleData.java:167)
       at libcore.icu.LocaleData.get(LocaleData.java:121)
       at java.util.Formatter.format(Formatter.java:1039)
       at java.util.Formatter.format(Formatter.java:1009)
       at java.lang.String.format(String.java:1992)
       at android.content.res.Resources.getString(Resources.java:368)
       at android.app.Fragment.getString(Fragment.java:801)
       at org.wordpress.android.ui.stats.StatsFollowersFragment$DotComFollowerAdapter.getSinceLabel(StatsFollowersFragment.java:426)
       at org.wordpress.android.ui.stats.StatsFollowersFragment$DotComFollowerAdapter.getView(StatsFollowersFragment.java:328)
       at org.wordpress.android.ui.stats.StatsUIHelper.reloadLinearLayout(StatsUIHelper.java:78)
       at org.wordpress.android.ui.stats.StatsFollowersFragment.updateUI(StatsFollowersFragment.java:127)
       at org.wordpress.android.ui.stats.StatsAbstractListFragment.onEventMainThread(StatsAbstractListFragment.java:437)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:498)
       at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:492)
       at de.greenrobot.event.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5398)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:836)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniloercoli** [comment]
@maxme - Should the Country part of the constructor be in uppercase here ?https://github.com/wordpress-mobile/WordPress-Android/blob/release/4.1/WordPress/src/main/java/org/wordpress/android/ui/prefs/SettingsFragment.java#L263

Something like `new Locale("en", "US")`.

**Comment by maxme** [comment]
> @maxme - Should the Country part of the constructor be in uppercase here ?https://github.com/wordpress-mobile/WordPress-Android/blob/release/4.1/WordPress/src/main/java/org/wordpress/android/ui/prefs/SettingsFragment.java#L263

It's already in uppercase (it would crash here if it wasn't)

**Comment by daniloercoli** [comment]
> It's already in uppercase (it would crash here if it wasn't).

No, it doesn't crash in the constructor.

Where the Country part is "uppercased"?  I see in the file available-languages.xml lower case strings.

**Comment by maxme** [comment]
> Where the Country part is "uppercased"? I see in the file available-languages.xml lower case strings.

Ah right, I thought the file was reading directory names, but it's reading the config file. We could try to force uppercase here and see how it works in the next RC (4.1-rc-3).

**Comment by daniloercoli** [comment]
Ok, will add the change in the PR that tries to fix this issue.

**Comment by maxme** [comment]
> Ok, will add the change in the PR that tries to fix this issue.

IMO, we should only apply the uppercase fix to test if that works, and also revert this https://github.com/wordpress-mobile/WordPress-Android/pull/2648

**Comment by daniloercoli** [comment]
Don't think fixing the uppercase will fix our issue, since in the link where the issue is reported on google here https://code.google.com/p/android/issues/detail?id=43162 the reported has fixed the issue by not using getString(int ResID, args..)
