### ISSUE TITLE
IllegalStateException adding MediaAddFragment to MySiteFragment

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#2851]
[This line](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/main/MySiteFragment.java#L86) where MediaAddFragment is added to MySiteFragment is causing quite a few exception reports.
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1328)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1346)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:728)
       at android.app.BackStackRecord.commit(BackStackRecord.java:704)
       at org.wordpress.android.ui.main.MySiteFragment.onCreateView(MySiteFragment.java:86)
```

This fragment transaction can be removed, since the ability to add media from "My Site" was dropped shortly before the 4.1 release.

**Comment by nbradbury** [comment]
Closing - dup of #2852
