### ISSUE TITLE
4.1 crash - IllegalState adding fragment after onSaveInstanceState is called

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2852]
We should remove the fragment altogether since the Add button is no longer part of the My Sites page.

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1328)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1346)
       at android.app.BackStackRecord.commitInternal(BackStackRecord.java:728)
       at android.app.BackStackRecord.commit(BackStackRecord.java:704)
       at org.wordpress.android.ui.main.MySiteFragment.onCreateView(MySiteFragment.java:86)
       at android.app.Fragment.performCreateView(Fragment.java:2053)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.app.BackStackRecord.run(BackStackRecord.java:833)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
       at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
       at android.support.v13.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1441)
       at android.view.View.measure(View.java:17429)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
       at android.view.View.measure(View.java:17429)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at android.view.View.measure(View.java:17429)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
       at android.view.View.measure(View.java:17429)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2815)
       at android.view.View.measure(View.java:17429)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2001)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1166)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5786)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by nbradbury** [comment]
Closed via #2853
