### ISSUE TITLE
Crash report 4.1 - IllegalStateException accessing comment Cursor

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2855]
[Accessing](https://github.com/wordpress-mobile/WordPress-Android/blob/4.1/WordPress/src/main/java/org/wordpress/android/datasets/CommentTable.java#L321) an OOB row? Weird because [moveToNext](https://github.com/wordpress-mobile/WordPress-Android/blob/4.1/WordPress/src/main/java/org/wordpress/android/datasets/CommentTable.java#L140) just returned true.

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
Caused by: java.lang.IllegalStateException: Couldn't read row 3, col 6 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetString(CursorWindow.java)
       at android.database.CursorWindow.getString(CursorWindow.java:518)
       at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:62)
       at org.wordpress.android.datasets.CommentTable.getCommentFromCursor(CommentTable.java:321)
       at org.wordpress.android.datasets.CommentTable.getCommentsForBlog(CommentTable.java:140)
       at org.wordpress.android.ui.comments.CommentAdapter$LoadCommentsTask.doInBackground(CommentAdapter.java:340)
       at org.wordpress.android.ui.comments.CommentAdapter$LoadCommentsTask.doInBackground(CommentAdapter.java:327)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
```

**Comment by nbradbury** [comment]
Interesting that every report of this exception happens while reading column 6, which is the `author_name` column - the very first column read by `getCommentFromCursor()`.

This *may* be due to CursorWindow's poorly-documented 2MB limit on row data - if any row exceeds that limit, you get an IllegalStateException like the one reported here. I ran into this problem in the reader a while back - [here's the relevant PR](https://github.com/wordpress-mobile/WordPress-Android/pull/1878).

**Comment by tonyr59h** [comment]
Addressed in #2883, closing.

**Comment by tonyr59h** [comment]
Crash is still being reported in 4.2 release.

**Comment by maxme** [comment]
That's weird, even with new tests, I can't repro, I'm wondering if CursorWindow max size could be different on some roms
