### ISSUE TITLE
Crash report 4.1 - bad array lengths updating notification progress

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2858]
[This post](http://stackoverflow.com/questions/19309541/custom-notification-java-lang-runtimeexception-crash-on-notification#answers) suggests that we should run the [notification update](https://github.com/wordpress-mobile/WordPress-Android/blob/4.1/WordPress/src/main/java/org/wordpress/android/ui/posts/PostUploadService.java#L815) on the main thread.
```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:827)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:321)
       at android.app.NotificationManager.notify(NotificationManager.java:136)
       at android.app.NotificationManager.notify(NotificationManager.java:109)
       at org.wordpress.android.ui.posts.PostUploadService$PostUploadNotifier.updateNotificationProgress(PostUploadService.java:946)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask$1.onBytesUploaded(PostUploadService.java:815)
       at org.xmlrpc.android.XMLRPCClient$CountingOutputStream.write(XMLRPCClient.java:681)
       at org.apache.http.entity.FileEntity.writeTo(FileEntity.java:83)
       at org.xmlrpc.android.XMLRPCClient$1.writeTo(XMLRPCClient.java:372)
       at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:97)
       at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:162)
       at org.apache.http.impl.conn.AbstractClientConnAdapter.sendRequestEntity(AbstractClientConnAdapter.java:272)
       at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
       at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:119)
       at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:442)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:575)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:498)
       at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:476)
       at org.xmlrpc.android.XMLRPCClient$Caller.callXMLRPC(XMLRPCClient.java:482)
       at org.xmlrpc.android.XMLRPCClient$Caller.access$000(XMLRPCClient.java:412)
       at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:229)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.uploadFileHelper(PostUploadService.java:821)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.uploadImageFile(PostUploadService.java:780)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.uploadImage(PostUploadService.java:607)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.processPostMedia(PostUploadService.java:487)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.doInBackground(PostUploadService.java:226)
       at org.wordpress.android.ui.posts.PostUploadService$UploadPostTask.doInBackground(PostUploadService.java:153)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by daniloercoli** [comment]
Seems that's OK to call NoticationManager.notify() from a worker thread:
http://stackoverflow.com/questions/15530293/can-noticationmanager-notify-be-called-from-a-worker-thread.

**Comment by daniloercoli** [comment]
Lots of discussions on stackoverflow around this issue. None of those has a definite response that fixes the issue. The most relevant discussion IMO around this topic is the following:
http://stackoverflow.com/questions/7988018/custom-notification-java-lang-runtimeexception-bad-array-lengths where the crash seems to be related to the RemoteView.

**Comment by tonyr59h** [comment]
Been combing through the source code to try and find a solution but I'm not having any luck. We could try putting the notify call into a try/catch block until we can get to the root of it.

**Comment by maxme** [comment]
> We could try putting the notify call into a try/catch block until we can get to the root of it.

I don't see any better solution :( - If we do that please log exception in crashlytics using `CrashlyticsUtils.logException` so we can keep an eye on them.

**Comment by hotchemi** [comment]
I've experienced the same problem and my fix is to make sure to update progress per 10%(0, 10, 20...). Not found out the exact cause but I could deal with that.

**Comment by maxme** [comment]
@hotchemi thanks for the tip, we might implement this in a future version.

**Comment by HanteIsHante** [comment]
我也遇到此问题：
Fatal Exception: java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:926)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:777)
       at android.app.NotificationManager.notify(NotificationManager.java:272)
       at android.app.NotificationManager.notify(NotificationManager.java:211)
       at cc.netpas.android_firewall.service.BackgroundDaemon$3.run(BackgroundDaemon.java:297)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)
不知道有没有解决办法

**Comment by hotchemi** [comment]
@HanteIsHante You should use English.

**Comment by HanteIsHante** [comment]
I have the same problem: How to do ?
 I have the same problem：
Fatal Exception: java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:926)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:777)
       at android.app.NotificationManager.notify(NotificationManager.java:272)
       at android.app.NotificationManager.notify(NotificationManager.java:211)
       at aa.netpas.android.service.BackgroundDaemon$3.run(BackgroundDaemon.java:297)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)
