### ISSUE TITLE
Crash report 4.1 - IllegalStateException calling onBackPressed after Activity starts pausing

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2859]
Activity already being paused/stopped when calling [onBackPressed](https://github.com/wordpress-mobile/WordPress-Android/blob/4.1/WordPress/src/main/java/org/wordpress/android/ui/notifications/NotificationsDetailActivity.java#L116).
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1377)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:504)
       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
       at org.wordpress.android.ui.notifications.NotificationsDetailActivity.onOptionsItemSelected(NotificationsDetailActivity.java:116)
       at android.app.Activity.onMenuItemSelected(Activity.java:2608)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
       at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
       at android.support.v7.internal.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:190)
       at android.view.View.performClick(View.java:4456)
       at android.view.View$PerformClick.run(View.java:18465)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5086)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
Addressed in #2864, closing.

**Comment by tonyr59h** [comment]
Still being reported in 4.3.2, re-opening.

**Comment by daniloercoli** [comment]
Is it the same stackframe?

**Comment by tonyr59h** [comment]
I updated the initial comments' stack trace when re-opening the issue. There were some minor differences but the method calls were the same.

**Comment by daniloercoli** [comment]
@roundhill - I'm running out of idea on how to fix this issue. Any idea?

**Comment by roundhill** [comment]
@daniloercoli Hmm, I would have done the same `commitAllowingStateLoss` fix...

But maybe we can just call `finish()` there? Not sure why `onBackPressed()` needs to be called. Not sure if that would fix it though.

**Comment by tonyr59h** [comment]
There's a ton of discussion on this topic [here](http://stackoverflow.com/questions/7575921/illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-h#answers).

After reading a few threads it doesn't look like there are any options that 100% fix it.

* We could add a `try/catch` block so there are no user-facing crashes, but that means we lose state.
* We could try removing the call to `super.onSaveInstanceState` but we'd need another way to save our variables.
* We could call `finish()` instead but I'm not certain of the consequences.

I'm with @roundhill on this one, calling finish seems like our best bet to avoid the `IllegalStateException`. We can keep an eye on crash reports to see if introduces any unforeseen issues.

**Comment by daniloercoli** [comment]
Yeah, I read a lot of stuff on Internet about how to fix this issue, and now I'am confused more than before :)
Will give `finish()` a chance.
