### ISSUE TITLE
SSL certificate verification error

### ISSUE THREAD

**Issue by cconover** [wordpress-mobile/WordPress-Android#2906]
When attempting to log in to my self-hosted install, I get an error that I could not be logged in, and the following application log output:

```
WordPress Android version: 4.1
Android device name: Motorola Nexus 6

01 - resetting suggestion tables
02 - Number of old stats deleted : 0
03 - NewAccountAbstractOage.onCreate()
04 - trackLastActivity, activityId: Login Screen
05 - SSLPeerUnverifiedException failed. Erroneous SSL certificate detected.
06 - Exception received from XMLRPC call wp.getUsersBlogs - exception: No peer certificate
07 - StackTrace: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
	at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:98)
	at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:393)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:365)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
	at org.xmlrpc.android.XMLRPCClient$Caller.callXMLRPC(XMLRPCClient.java:482)
	at org.xmlrpc.android.XMLRPCClient$Caller.access$000(XMLRPCClient.java:412)
	at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:229)
	at org.xmlrpc.android.XMLRPCClient.call(XMLRPCClient.java:213)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg$FetchBlogListTask.doInBackground(FetchBlogListWPOrg.java:254)
	at org.wordpress.android.ui.accounts.helpers.FetchBlogListWPOrg$FetchBlogListTask.doInBackground(FetchBlogListWPOrg.java:225)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

08 - Server response: 
```

I know that my SSL certificate is valid, and I have verified that using [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=christiaanconover.com&s=104.28.23.17&latest). This leads me to believe that it's an issue with the implementation of SSL authentication in the app.

**Comment by maxme** [comment]
dup #2927 (should be fixed soon)

**Comment by cconover** [comment]
This is not actually a self-signed cert error, since my certificate is issued by [StartSSL](https://startssl.com/).

**Comment by maxme** [comment]
@cconover Right sorry. I misread the title. We made some changes in [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/3150) on how ssl sites are handled (it fixes self signed issues, but it also solve some problem with endpoint discovery). We released 4.4.2 with this patch, can you try 4.4.2 or 4.5-rc-4 version of wpandroid on your site?

**Comment by cconover** [comment]
Looks like it's working now! Fantastic, thanks!

**Comment by maxme** [comment]
Perfect, thanks!
