### ISSUE TITLE
Crash report 4.1.1 - NPE WPEditImageSpan

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2909]
```
java.lang.NullPointerException
       at org.wordpress.android.editor.legacy.WPEditImageSpan.init(WPEditImageSpan.java:35)
       at org.wordpress.android.editor.legacy.WPEditImageSpan.(WPEditImageSpan.java:26)
       at org.wordpress.android.editor.LegacyEditorFragment$14.onResponse(LegacyEditorFragment.java:990)
       at com.android.volley.toolbox.ImageLoader$4.run(ImageLoader.java:474)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5045)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
Addressed in [WordPress-Editor-Android#168](https://github.com/wordpress-mobile/WordPress-Editor-Android/pull/168), closing.
