### ISSUE TITLE
Crash report 4.1.1 - IllegalStateException, onSaveInstanceState already called

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2910]
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1328)
       at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1346)
       at android.app.FragmentManagerImpl.popBackStack(FragmentManager.java:488)
       at org.wordpress.android.ui.media.MediaBrowserActivity.onSavedEdit(MediaBrowserActivity.java:461)
       at org.wordpress.android.ui.media.MediaEditFragment$2.onSuccess(MediaEditFragment.java:217)
       at org.xmlrpc.android.ApiHelper$EditMediaItemTask.onPostExecute(ApiHelper.java:739)
       at org.xmlrpc.android.ApiHelper$EditMediaItemTask.onPostExecute(ApiHelper.java:679)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by tonyr59h** [comment]
Addressed in #2972, closing.
