### ISSUE TITLE
Crash report 4.1.1 - IllegalStateException, Reader attempting to pop backstack after onSaveInstanceState

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#2912]
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1365)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:500)
       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:176)
       at android.support.v7.app.ActionBarActivity.onBackPressed(ActionBarActivity.java:298)
       at org.wordpress.android.ui.reader.ReaderPostPagerActivity.onBackPressed(ReaderPostPagerActivity.java:212)
       at org.wordpress.android.ui.reader.ReaderPostPagerActivity$1.onClick(ReaderPostPagerActivity.java:81)
       at android.view.View.performClick(View.java:5217)
       at android.view.View$PerformClick.run(View.java:20983)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6141)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by nbradbury** [comment]
The last report of this I see for `ReaderPostPagerActivity` in the GPlay console is dated Jun 13, but I see a few similar reports for `ReaderPostListActivity`, `ViewSiteActivity`, and `NotificationsDetailActivity`. In each case the exception occurs when calling `super.onBackPressed()` in the `onBackPressed` event.

**Comment by nbradbury** [comment]
Looks like [it's an issue with AppCompat](https://code.google.com/p/android/issues/detail?id=183771).

**Comment by nbradbury** [comment]
Given the rarity of this crash coupled with the fact that it's a problem in Android itself, we're leaving this as-is.
