### ISSUE TITLE
ReaderUtils crash

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#2954]
Crash reported (15 times, 9 users) in `ReaderUtils`

```
java.lang.AssertionError: couldn't initialize LocaleData for locale en-gb
       at libcore.icu.LocaleData.initLocaleData(LocaleData.java:167)
       at libcore.icu.LocaleData.get(LocaleData.java:121)
       at java.util.Formatter.format(Formatter.java:1039)
       at java.util.Formatter.format(Formatter.java:1009)
       at java.lang.String.format(String.java:1988)
       at android.content.res.Resources.getString(Resources.java:1178)
       at android.content.Context.getString(Context.java:345)
       at org.wordpress.android.ui.reader.utils.ReaderUtils.getLongLikeLabelText(ReaderUtils.java:85)
       at org.wordpress.android.ui.reader.ReaderPostDetailFragment.refreshLikes(ReaderPostDetailFragment.java:554)
       at org.wordpress.android.ui.reader.ReaderPostDetailFragment.access$500(ReaderPostDetailFragment.java:52)
       at org.wordpress.android.ui.reader.ReaderPostDetailFragment$8.run(ReaderPostDetailFragment.java:863)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:175)
       at android.app.ActivityThread.main(ActivityThread.java:5279)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
Largest crash of 4.2 so please fix for 4.2.1 hotfix

**Comment by tonyr59h** [comment]
Addressed in #2955, closing.
