### ISSUE TITLE
Crash report 4.3.2 - UnsupportedOperationException in media browser

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3051]
Need to be using `MenuItemCompat` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/media/MediaBrowserActivity.java#L72), should fix this.
```
java.lang.UnsupportedOperationException: This is not supported, use MenuItemCompat.setOnActionExpandListener()
       at android.support.v7.internal.view.menu.MenuItemImpl.setOnActionExpandListener(MenuItemImpl.java:740)
       at org.wordpress.android.ui.media.MediaBrowserActivity.onOptionsItemSelected(MediaBrowserActivity.java:345)
       at android.app.Activity.onMenuItemSelected(Activity.java:2611)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
       at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
       at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
       at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:541)
       at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
       at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
       at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
       at android.support.v7.internal.view.menu.ListMenuPresenter.onItemClick(ListMenuPresenter.java:169)
       at android.widget.AdapterView.performItemClick(AdapterView.java:301)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1287)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3078)
       at android.widget.AbsListView$1.run(AbsListView.java:4159)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4944)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
Addressed in #3130, closing.
