### ISSUE TITLE
Crash report 4.4.2 - NPE adding media in EditPostActivity

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#3198]
```
java.lang.NullPointerException
       at org.wordpress.android.ui.posts.EditPostActivity.addMedia(EditPostActivity.java:1110)
       at org.wordpress.android.ui.posts.EditPostActivity.setPostContentFromShareAction(EditPostActivity.java:907)
       at org.wordpress.android.ui.posts.EditPostActivity.fillContentEditorFields(EditPostActivity.java:843)
       at org.wordpress.android.ui.posts.EditPostActivity.onEditorFragmentInitialized(EditPostActivity.java:1579)
       at org.wordpress.android.editor.LegacyEditorFragment.onCreateView(LegacyEditorFragment.java:229)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:829)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
       at android.app.BackStackRecord.run(BackStackRecord.java:635)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397)
       at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:437)
       at android.support.v13.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
       at android.view.View.measure(View.java:15273)
```

**Comment by tonyr59h** [comment]
Addressed in #3220, closing.
