### ISSUE TITLE
Build error due to com.android.ide.common.process.ProcessException

### ISSUE THREAD

**Issue by stream101** [wordpress-mobile/WordPress-Android#3230]
I run "./gradlew assembleVanillaDebug" to build Wordpress, but got the following build error:
````
11:11:33.972 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':WordPress:dexVanillaDebug'.
11:11:33.972 [ERROR] [org.gradle.BuildExceptionReporter] > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```
After I add --debug option, I can see the exception stack: 
```
11:11:33.940 [ERROR] [org.gradle.api.Project] Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lorg/wordpress/android/analytics/AnalyticsTracker$Stat;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)
```
Please help me ... Thanks!

**Comment by maxme** [comment]
Have you changed anything in `WordPress/build.gradle`?

**Comment by maxme** [comment]
Reopen if this still happens.
