### ISSUE TITLE
Crash tapping "Open source licenses" in v4.6

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#3233]
To repro, go to the Me tab, click Account Settings, then click Open source licenses.

```
09-23 20:32:15.220 16731-16731/org.wordpress.android E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.prefs.LicensesActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
09-23 20:32:15.220 16731-16731/org.wordpress.android E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
09-23 20:32:15.220 16731-16731/org.wordpress.android E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
09-23 20:32:15.220 16731-16731/org.wordpress.android E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
09-23 20:32:15.220 16731-16731/org.wordpress.android E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
09-23 20:32:15.220 16731-16731/org.wordpress.android E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
```

**Comment by tonyr59h** [comment]
Addressed in #3234, closing.
