### ISSUE TITLE
Crash report 4.5.1: NPE in NotificationsSettingsDialogPreference

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3249]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
       at org.wordpress.android.util.JSONUtils.queryJSON(JSONUtils.java:33)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsDialogPreference.configureLayoutForView(NotificationsSettingsDialogPreference.java:82)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsDialogPreference.onCreateDialogView(NotificationsSettingsDialogPreference.java:71)
       at android.preference.DialogPreference.showDialog(DialogPreference.java:307)
       at android.preference.DialogPreference.onClick(DialogPreference.java:286)
       at android.preference.Preference.performClick(Preference.java:1121)
       at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
       at android.widget.AdapterView.performItemClick(AdapterView.java:334)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1544)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3682)
       at android.widget.AbsListView$3.run(AbsListView.java:5596)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by tonyr59h** [comment]
Addressed in #3251, closing.
