### ISSUE TITLE
Crash: App crashes when rotating while signing out.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-Android#3283]
Nexus 7, OS 5.1.1

To reproduce:
- Be logged into wpcom.
- Tap the button to disconnect wpcom. 
- Rotate the device while the spinner is visible.

Boom.

**Comment by daniloercoli** [comment]
I think this is in some way related to https://github.com/wordpress-mobile/WordPress-Android/issues/3209

**Comment by maxme** [comment]
Same kind of issue than #3209 - stacktrace:
```
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime: java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{2297a98b V.E..... R......D 0,0-1368,406} not attached to window manager
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:386)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:312)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.app.Dialog.dismissDialog(Dialog.java:341)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.app.Dialog.dismiss(Dialog.java:324)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at org.wordpress.android.WordPress$SignOutWordPressComAsync.onPostExecute(WordPress.java:559)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at org.wordpress.android.WordPress$SignOutWordPressComAsync.onPostExecute(WordPress.java:529)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.os.AsyncTask.finish(AsyncTask.java:632)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.os.AsyncTask.access$600(AsyncTask.java:177)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5221)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
10-08 14:18:14.495 3122-3122/org.wordpress.android E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```
