### ISSUE TITLE
Crash report 4.7: NPE in EditPostActivity.fetchMedia

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3461]
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2000, result=-1, data=Intent { (has extras) }} to activity {org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3319)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3362)
       at android.app.ActivityThread.access$1100(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at org.wordpress.android.ui.posts.EditPostActivity.fetchMedia(EditPostActivity.java:1100)
       at org.wordpress.android.ui.posts.EditPostActivity.onActivityResult(EditPostActivity.java:1226)
       at android.app.Activity.dispatchActivityResult(Activity.java:5293)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3315)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3362)
       at android.app.ActivityThread.access$1100(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by nbradbury** [comment]
Closed via #3462
