### ISSUE TITLE
Crash report 4.8: NPE in GCMMessageService

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3516]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference
       at org.wordpress.android.GCMMessageService.handleDefaultPush(GCMMessageService.java:214)
       at org.wordpress.android.GCMMessageService.onMessageReceived(GCMMessageService.java:380)
       at com.google.android.gms.gcm.GcmListenerService.zzt(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zzk(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by maxme** [comment]
Same kind of crash:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at org.wordpress.android.GCMMessageService.handleDefaultPush(GCMMessageService.java:124)
       at org.wordpress.android.GCMMessageService.onMessageReceived(GCMMessageService.java:380)
       at com.google.android.gms.gcm.GcmListenerService.zzt(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zzk(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by maxme** [comment]
Bandaid added in #3517 - this is probably due to a concurrent access on the `mActiveNotificationsMap` map. We should synchronize blocks [#1](https://github.com/wordpress-mobile/WordPress-Android/blob/9f6cf246123980c4ff3f7acb81e4b55816289060/WordPress/src/main/java/org/wordpress/android/GCMMessageService.java#L124-L140) and [#2](https://github.com/wordpress-mobile/WordPress-Android/blob/9f6cf246123980c4ff3f7acb81e4b55816289060/WordPress/src/main/java/org/wordpress/android/GCMMessageService.java#L210-L256)

**Comment by daniloercoli** [comment]
Isn't get addressed by https://github.com/wordpress-mobile/WordPress-Android/pull/3547 ?

**Comment by maxme** [comment]
Yep, closing!
