### ISSUE TITLE
Crash report when underlining text in the legacy editor (Android 6.0)

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3521]
Underline text in the legacy editor on Android 6.0:

```
Fatal Exception: java.lang.AbstractMethodError: abstract method "int android.text.ParcelableSpan.getSpanTypeIdInternal()"
       at android.text.TextUtils.writeToParcel(TextUtils.java:653)
       at com.android.internal.view.IInputContextCallback$Stub$Proxy.setTextBeforeCursor(IInputContextCallback.java:153)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:225)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by nbradbury** [comment]
Closed via #3528
