### ISSUE TITLE
Theme name in actionbar crashing when can't find theme

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-Android#3525]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.themes.ThemeWebActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2318)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
       at android.app.ActivityThread.access$800(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at org.wordpress.android.ui.themes.ThemeWebActivity.setActionBarTitleToThemeName(ThemeWebActivity.java:143)
       at org.wordpress.android.ui.themes.ThemeWebActivity.configureView(ThemeWebActivity.java:138)
       at org.wordpress.android.ui.WebViewActivity.onCreate(WebViewActivity.java:35)
       at org.wordpress.android.ui.WPWebViewActivity.onCreate(WPWebViewActivity.java:161)
       at android.app.Activity.performCreate(Activity.java:5411)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
       at android.app.ActivityThread.access$800(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5257)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by kwonye** [comment]
#3524 has a different crash so reopening
