### ISSUE TITLE
Unable to Log In

### ISSUE THREAD

**Issue by rishabh7m** [wordpress-mobile/WordPress-Android#3570]
We can't login in screen shows up on trying to Log in.
Log:
01-07 16:48:28.406 10464-10464/org.wordpress.android E/ActivityThread: Performing stop of activity that is not resumed: {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}
                                                                       java.lang.RuntimeException: Performing stop of activity that is not resumed: {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}
                                                                           at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3377)
                                                                           at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3458)
                                                                           at android.app.ActivityThread.access$1200(ActivityThread.java:154)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
01-07 16:48:28.566 10464-10668/org.wordpress.android E/WordPress-NOTIFS: Google Play Services unavailable: 
                                                                         java.io.IOException: INVALID_SENDER
                                                                             at com.google.android.gms.iid.zzc.zzb(Unknown Source)
                                                                             at com.google.android.gms.iid.zzc.zza(Unknown Source)
                                                                             at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
                                                                             at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
                                                                             at org.wordpress.android.GCMRegistrationIntentService.onHandleIntent(GCMRegistrationIntentService.java:36)
                                                                             at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
01-07 16:48:28.827 10464-10464/org.wordpress.android I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2f73c4d3 time:135109883
01-07 16:48:43.396 10464-10588/org.wordpress.android E/WordPress: [47156] BasicNetwork.performRequest: Unexpected response code 400 for https://public-api.wordpress.com/oauth2/token
01-07 16:48:43.406 10464-10464/org.wordpress.android E/WordPress-NUX: Server response:

**Comment by maxme** [comment]
Hi @rishabh7m, it looks like you tried to login on a wordpress.com site but you haven't filled the OAUTH id and secret. Please read this first: https://github.com/wordpress-mobile/WordPress-Android#oauth2-authentication and edit your `./WordPress/gradle.properties` file accordingly to the doc.

**Comment by rishabh7m** [comment]
Hi @maxme , I was missing that. Thanks :+1:

**Comment by sudhirkhanger** [comment]
@maxme Are `WP.OAUTH.APP_ID` and `WP.OAUTH.APP_SECRET` the only fields that need to be added? I have changed those and I still am not able to build the project.

```
02-16 18:44:35.738 22968-23070/org.wordpress.android E/WordPress-NOTIFS: Google Play Services unavailable: 
                                                                         java.io.IOException: INVALID_SENDER
                                                                             at com.google.android.gms.iid.zzc.zzb(Unknown Source:58)
                                                                             at com.google.android.gms.iid.zzc.zza(Unknown Source:15)
                                                                             at com.google.android.gms.iid.InstanceID.zzc(Unknown Source:65)
                                                                             at com.google.android.gms.iid.InstanceID.getToken(Unknown Source:73)
                                                                             at org.wordpress.android.push.GCMRegistrationIntentService.onHandleIntent(GCMRegistrationIntentService.java:47)
                                                                             at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:65)
```

![screenshot_1518806795](https://user-images.githubusercontent.com/841656/36323709-d7322a52-1377-11e8-8447-a41a49e0a7c9.png)
