### ISSUE TITLE
Crash report 4.9: NameNotFoundException: com.google.android.webview

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3594]
Makes me sad...

```
Fatal Exception: java.lang.RuntimeException: Unable to create application org.wordpress.android.WordPress: android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4529)
       at android.app.ActivityThread.access$1500(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5249)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
Caused by android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:161)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
       at android.webkit.WebView.getFactory(WebView.java:2185)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2180)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2239)
       at android.view.View.(View.java)
       at android.view.View.(View.java)
       at android.view.ViewGroup.(ViewGroup.java)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at org.wordpress.android.WordPress.getDefaultUserAgent(WordPress.java:577)
       at org.wordpress.android.WordPress.getUserAgent(WordPress.java:595)
       at org.wordpress.android.WordPress.onCreate(WordPress.java:189)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
       at android.app.ActivityThread.access$1500(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5249)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

Someone tried to find the cause of it: http://stackoverflow.com/a/29809338/58332

**Comment by tonyr59h** [comment]
Addressed in #3599.
