### ISSUE TITLE
Crash report 4.9: IndexOutOfBoundsException in CommentsListFragment

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3625]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at org.wordpress.android.ui.comments.CommentAdapter.getItem(CommentAdapter.java:220)
       at org.wordpress.android.ui.comments.CommentsListFragment$4.onCommentPressed(CommentsListFragment.java:114)
       at org.wordpress.android.ui.comments.CommentAdapter$1.onClick(CommentAdapter.java:198)
       at android.view.View.performClick(View.java:4785)
       at android.view.View$PerformClick.run(View.java:19881)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5689)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

**Comment by maxme** [comment]
fixed via #3630
