### ISSUE TITLE
Crash report 5.0: NPE in SiteSettingsModel.copyFrom

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3655]
```
Process: org.wordpress.android, PID: 2175
java.lang.NullPointerException: collection == null
   at java.util.ArrayList.<init>(ArrayList.java:94)
   at org.wordpress.android.models.SiteSettingsModel.copyFrom(SiteSettingsModel.java:206)
   at org.wordpress.android.ui.prefs.DotComSiteSettings$1.onResponse(DotComSiteSettings.java:96)
   at org.wordpress.android.ui.prefs.DotComSiteSettings$1.onResponse(DotComSiteSettings.java:91)
   at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:74)
   at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:18)
   at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5221)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by tonyr59h** [comment]
Addressed in #3671
