### ISSUE TITLE
Should not call SelfSignedSSLCertsManager.getInstance() with "null"

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#3835]
There are a few `SelfSignedSSLCertsManager.getInstance(null)` calls but the `SelfSignedSSLCertsManager` constructor does not guard for null. These calls should be revised.

A proposal by @maxme is to extract the SelfSignedSSLCertsManager singleton, instantiate it and keep it in the Application class.

**Comment by maxme** [comment]
We had a crash related to that issue (try to call `getFilesDir` on a null context):

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:325)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getFilesDir()' on a null object reference
       at org.wordpress.android.networking.SelfSignedSSLCertsManager.<init>(SelfSignedSSLCertsManager.java:44)
       at org.wordpress.android.networking.SelfSignedSSLCertsManager.getInstance(SelfSignedSSLCertsManager.java:88)
       at org.xmlrpc.android.TrustUserSSLCertsSocketFactory.<init>(TrustUserSSLCertsSocketFactory.java:50)
       at org.xmlrpc.android.XMLRPCClient$ConnectionClient.<init>(XMLRPCClient.java:125)
       at org.xmlrpc.android.XMLRPCClient.instantiateClientForUri(XMLRPCClient.java:146)
       at org.xmlrpc.android.XMLRPCClient.<init>(XMLRPCClient.java:111)
       at org.xmlrpc.android.XMLRPCFactoryDefault.make(XMLRPCFactoryDefault.java:7)
       at org.xmlrpc.android.XMLRPCFactory.instantiate(XMLRPCFactory.java:12)
       at org.xmlrpc.android.ApiHelper$RefreshBlogContentTask.doInBackground(ApiHelper.java:275)
       at org.xmlrpc.android.ApiHelper$RefreshBlogContentTask.doInBackground(ApiHelper.java:232)
       at android.os.AsyncTask$2.call(AsyncTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by aforcier** [comment]
`SelfSignedSSLCertsManager` has been replaced by [MemorizingTrustManager](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/bb8a116a3293403918604fbfe2aeefbb577e4344/fluxc/src/main/java/org/wordpress/android/fluxc/network/MemorizingTrustManager.java), which is initialized by injection and so should never have a `null` context.
