### ISSUE TITLE
Update Helpshift version to fix a frequent crash

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3839]
Helpshift support told me they're going to release the next version of the library in less than a week

Crash:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/com.helpshift.support.activities.ParentActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2304)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2354)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5382)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:970)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.helpshift.support.fragments.SupportFragment.onStart(SupportFragment.java:445)
       at android.support.v4.app.Fragment.performStart(Fragment.java:1986)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
       at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2047)
       at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:176)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:553)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1183)
       at android.app.Activity.performStart(Activity.java:5273)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2275)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2354)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5382)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:970)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
Addressed in #3889.
