### ISSUE TITLE
Crash report 5.1: ArrayIndexOutOfBoundsException in DetailListPreference

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3846]
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
       at android.preference.ListPreference.getEntry(ListPreference.java:219)
       at android.preference.ListPreference.getSummary(ListPreference.java:164)
       at android.preference.Preference.onBindView(Preference.java:657)
       at org.wordpress.android.ui.prefs.DetailListPreference.onBindView(DetailListPreference.java:64)
       at android.preference.Preference.getView(Preference.java:560)
       at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:295)
       at android.widget.AbsListView.obtainView(AbsListView.java:2402)
       at android.widget.ListView.makeAndAddView(ListView.java:1891)
       at android.widget.ListView.fillDown(ListView.java:713)
       at android.widget.ListView.fillGap(ListView.java:677)
       at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5227)
       at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3526)
       at android.widget.AbsListView.onTouchMove(AbsListView.java:3909)
       at android.widget.AbsListView.onTouchEvent(AbsListView.java:3740)
       at android.view.View.dispatchTouchEvent(View.java:8808)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2569)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2581)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2607)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1779)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:765)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2568)
       at android.view.View.dispatchPointerEvent(View.java:9003)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4209)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4072)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3680)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3763)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3654)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3820)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3680)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3646)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3654)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3627)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5910)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5884)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5855)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6000)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5971)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6023)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:548)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5910)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

**Comment by tonyr59h** [comment]
I tracked this crash down to a translations issue. This reproduces if the selected locale does not have all the translations in a `string-array` resource that is used as the `entries` or `entryValues` property in `site_settings.xml`.

The one I caught was Portuguese (pt-BR), but there may be more translations with incorrect `string-array` lengths. Ultimately we'll need to sanitize strings we pull for translation updates to flag and/or remove incomplete translations. In the interim I've got a PR ready to go that will ensure that this crash does not occur.
