### ISSUE TITLE
Crash report in the visual editor - alpha-5

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3930]
Crash:

```
04-07 15:25:38.963 4034-4266/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
Process: org.wordpress.android.beta, PID: 4034
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:309)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
    at android.os.Handler.<init>(Handler.java:200)
    at android.os.Handler.<init>(Handler.java:114)
    at android.widget.Toast$TN.<init>(Toast.java:359)
    at android.widget.Toast.<init>(Toast.java:105)
    at android.widget.Toast.makeText(Toast.java:266)
    at android.widget.Toast.makeText(Toast.java:293)
    at org.wordpress.android.ui.posts.EditPostActivity.queueFileForUpload(EditPostActivity.java:1930)
    at org.wordpress.android.ui.posts.EditPostActivity.addMediaVisualEditor(EditPostActivity.java:1476)
    at org.wordpress.android.ui.posts.EditPostActivity.addMedia(EditPostActivity.java:1443)
    at org.wordpress.android.ui.posts.EditPostActivity.handleMediaSelectionResult(EditPostActivity.java:1678)
    at org.wordpress.android.ui.posts.EditPostActivity.access$1100(EditPostActivity.java:124)
    at org.wordpress.android.ui.posts.EditPostActivity$HandleMediaSelectionTask.doInBackground(EditPostActivity.java:1067)
    at org.wordpress.android.ui.posts.EditPostActivity$HandleMediaSelectionTask.doInBackground(EditPostActivity.java:1064)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 
```

### Steps to reproduce the behavior

With the visual editor, add new images, then add an "Invalid image" (not sure how this happens, but my Z5C is pretty good at creating unreadable images).

The crash comes from the Toast call, so it should be easy to repro by just showing a random toast message in `queueFileForUpload`.

**Comment by maxme** [comment]
Related to this changeset: https://github.com/wordpress-mobile/WordPress-Android/pull/2515/files
