### ISSUE TITLE
Crash report alpha-5: GoogleApiClient is not connected when `saveCrendentialsInSmartLock` is called

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#3962]
```
Fatal Exception: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
       at com.google.android.gms.internal.zzmf.zzb(Unknown Source)
       at com.google.android.gms.internal.zzmi.zzb(Unknown Source)
       at com.google.android.gms.internal.zzmg.zzb(Unknown Source)
       at com.google.android.gms.auth.api.credentials.internal.zzd.save(Unknown Source)
       at org.wordpress.android.ui.accounts.SignInFragment.saveCrendentialsInSmartLock(SignInFragment.java:643)
       at org.wordpress.android.ui.accounts.SignInFragment.access$2400(SignInFragment.java:85)
       at org.wordpress.android.ui.accounts.SignInFragment$15.onSuccess(SignInFragment.java:677)
       at org.wordpress.android.ui.accounts.helpers.LoginWPCom$1.onResponse(LoginWPCom.java:97)
       at org.wordpress.android.ui.accounts.helpers.LoginWPCom$1.onResponse(LoginWPCom.java:73)
       at com.wordpress.rest.Oauth$Request.deliverResponse(Oauth.java:96)
       at com.wordpress.rest.Oauth$PasswordRequest.deliverResponse(Oauth.java:113)
       at com.wordpress.rest.Oauth$Request.deliverResponse(Oauth.java:77)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4745)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by maxme** [comment]
Others calls must be checked too (delete / update credentials).

**Comment by maxme** [comment]
It's weird, I don't see anywhere in the docs or samples that `GoogleApiClient` must be connected before calling `Auth.CredentialsApi` methods, and actually it works fine when disconnected and calling ` Auth.CredentialsApi.request()`.
