### ISSUE TITLE
Wordpress 3.9 not working in newer versions of Android Studio 1.5

### ISSUE THREAD

**Issue by Stackflood** [wordpress-mobile/WordPress-Android#3989]
Wordpress 3.9 not working in newer versions of Android Studio.

I had it configured - build file etc and it was working properly. Now after the update, it's not working. Please help as I am following/debugging through some important codes from the same which is helpful in the app I am working upon.

Just running it on Android Studio 1.5 - I am getting this :

Error:Execution failed for task ':WordPress:dexVanillaDebug'.

> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     C:\Users\Manish\AppData\Local\Android\sdk\build-tools\21.1.1\dx.bat --dex --no-optimize --output C:\Users\Manish\Desktop\WordPress-Android-3.9\WordPress-Android-3.9\WordPress\build\intermediates\dex\vanilla\debug --input-list=C:\Users\Manish\Desktop\WordPress-Android-3.9\WordPress-Android-3.9\WordPress\build\intermediates\tmp\dex\vanilla\debug\inputList.txt
> Error Code:
>     2
> Output:
>     UNEXPECTED TOP-LEVEL EXCEPTION:
>     com.android.dex.DexException: Multiple dex files define Lnet/jcip/annotations/GuardedBy;
>         at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
>         at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
>         at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
>         at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
>         at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
>         at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
>         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
>         at com.android.dx.command.dexer.Main.run(Main.java:245)
>         at com.android.dx.command.dexer.Main.main(Main.java:214)
>         at com.android.dx.command.Main.main(Main.java:106)

**Comment by kwonye** [comment]
Thanks for the report @Stackflood. Please try Android Studio 2.0 and let us know if the issue still occurs.

**Comment by maxme** [comment]
Does the project build when you use the command line `gradlew.bat` tool? We won't update old versions to run with newer Android Studio.

**Comment by Stackflood** [comment]
@kwonye , @maxme .. thanks for the quick replies. Even after updating android to version 2.0 , the build is fine, but getting the above mentioned error on running the app. I understand that you won't update older versions to run with newer Android studio, but can you suggest a workaround ?

**Comment by maxme** [comment]
@Stackflood you get this error `com.android.dex.DexException: Multiple dex files define Lnet/jcip/annotations/GuardedBy;` when you run the app? Have you tried to build and install from command line with the `gradlew.bat` script?

**Comment by Stackflood** [comment]
Hi @maxme , sorry for the very late reply. I tried to build using command line tools :  gradlew.bat assembleDebug. I am getting a similar error : 

UNEXPECTED TOP-LEVEL EXCEPTION:            
com.android.dex.DexException: Multiple dex files define Lnet/jcip/annotations/GuardedBy;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
        at com.android.dx.command.dexer.Main.run(Main.java:245)
        at com.android.dx.command.dexer.Main.main(Main.java:214)
        at com.android.dx.command.Main.main(Main.java:106)
                                           
:WordPress:dexVanillaDebug FAILED          
              
FAILURE: Build failed with an exception.
              
* What went wrong:
Execution failed for task ':WordPress:dexVanillaDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        C:\Users\-----\AppData\Local\Android\sdk\build-tools\21.1.1\dx.bat --dex --no-optimize --output C:\Users\-----\Desktop\WordPress-Android-3.9\WordPress-Android-3.9\WordPress\build\intermediates\dex\vanilla\debug --input-list=
C:\Users\-----\Desktop\WordPress-Android-3.9\WordPress-Android-3.9\WordPress\build\intermediates\tmp\dex\vanilla\deb
ug\inputList.txt
Error Code:
        2
Output:

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Lnet/jcip/annotations/GuardedBy;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
                at com.android.dx.command.dexer.Main.run(Main.java:245)
                at com.android.dx.command.dexer.Main.main(Main.java:214)
                at com.android.dx.command.Main.main(Main.java:106)

**Comment by maxme** [comment]
It's weird because when i checkoud the `3.9` tag and build, it works without any issue. Have you changed anything in the project? Like adding new libraries?

**Comment by Stackflood** [comment]
Let me try to build and install with a fresh download. I will get back to you.

**Comment by maxme** [comment]
@Stackflood did it work with the fresh download?

**Comment by Stackflood** [comment]
No, tried everything. It's showing the same error.

**Comment by Stackflood** [comment]
@maxme Request you to try it out in your free time, will be great if you can help to resolve this issue.

**Comment by maxme** [comment]
@Stackflood from the dependency tree (`gradlew dependencies --offline --configuration compile`), it looks like `net.jcip:jcip-annotations` is only used in `com.google.code.findbugs`, should be solved if you apply these changes:

```
diff --git a/WordPress/build.gradle b/WordPress/build.gradle
index 3672d4d..1f2452c 100644
--- a/WordPress/build.gradle
+++ b/WordPress/build.gradle
@@ -5,7 +5,6 @@ buildscript {
     }
     dependencies {
         classpath 'com.android.tools.build:gradle:1.0.0'
-        classpath 'com.github.nrudenko:gradle-android-cq-plugin:0.1+'
         classpath 'com.crashlytics.tools.gradle:crashlytics-gradle:+'
     }
 }
@@ -17,7 +16,6 @@ repositories {
 }
 
 apply plugin: 'com.android.application'
-apply plugin: 'android-cq'
 apply plugin: 'crashlytics'
 
 android {
```

**Comment by maxme** [comment]
@Stackflood have you tried removing `gradle-android-cq-plugin`?

**Comment by Stackflood** [comment]
Removing the pluggin is giving me 29 errors at runtime. 

All errors are related to the following in various activity/fragment classes : Error:(41, 24) error: package javax.annotation does not exist.

It will be most helpful if you can sort out the issue on your personal computer and let me know of the modifications. I am sure it won't take you much time to do it.

**Comment by maxme** [comment]
Hi there, are you still having issues building the app?

**Comment by hoverduck** [comment]
Closing due to inactivity.  Please re-open if you're still having problems.
