### ISSUE TITLE
Crash report 5.4:  NPE in LegacyEditorFragment.createWPEditImageSpanLocal

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4137]
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at org.wordpress.android.editor.LegacyEditorFragment.createWPEditImageSpanLocal(LegacyEditorFragment.java:471)
       at org.wordpress.android.editor.LegacyEditorFragment.createWPEditImageSpan(LegacyEditorFragment.java:496)
       at org.wordpress.android.editor.LegacyEditorFragment.addMediaFile(LegacyEditorFragment.java:1029)
       at org.wordpress.android.editor.LegacyEditorFragment.appendMediaFile(LegacyEditorFragment.java:1090)
       at org.wordpress.android.ui.posts.EditPostActivity.addMediaLegacyEditor(EditPostActivity.java:1500)
       at org.wordpress.android.ui.posts.EditPostActivity.addMedia(EditPostActivity.java:1445)
       at org.wordpress.android.ui.posts.EditPostActivity.handleMediaSelectionResult(EditPostActivity.java:1678)
       at org.wordpress.android.ui.posts.EditPostActivity.access$1100(EditPostActivity.java:124)
       at org.wordpress.android.ui.posts.EditPostActivity$HandleMediaSelectionTask.doInBackground(EditPostActivity.java:1067)
       at org.wordpress.android.ui.posts.EditPostActivity$HandleMediaSelectionTask.doInBackground(EditPostActivity.java:1064)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by maxme** [comment]
```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: uriString
       at android.net.Uri$StringUri.(Uri.java)
       at android.net.Uri$StringUri.(Uri.java)
       at android.net.Uri.parse(Uri.java:433)
       at org.wordpress.android.editor.LegacyEditorFragment.createWPEditImageSpanLocal(LegacyEditorFragment.java:467)
       at org.wordpress.android.editor.LegacyEditorFragment.createWPEditImageSpan(LegacyEditorFragment.java:495)
       at org.wordpress.android.editor.LegacyEditorFragment.access$1800(LegacyEditorFragment.java:70)
       at org.wordpress.android.editor.LegacyEditorFragment$AddMediaFileTask.doInBackground(LegacyEditorFragment.java:1043)
       at org.wordpress.android.editor.LegacyEditorFragment$AddMediaFileTask.doInBackground(LegacyEditorFragment.java:1025)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```
