### ISSUE TITLE
Crash report 5.4: NPE in MagicLinkSignInFragment.showPasswordField

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4159]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.accounts.login.MagicLinkSignInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.widgets.WPTextView.setVisibility(int)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.widgets.WPTextView.setVisibility(int)' on a null object reference
       at org.wordpress.android.ui.accounts.login.MagicLinkSignInFragment.showPasswordField(MagicLinkSignInFragment.java:202)
       at org.wordpress.android.ui.accounts.login.MagicLinkSignInFragment.showSelfHostedSignInForm(MagicLinkSignInFragment.java:177)
       at org.wordpress.android.ui.accounts.SignInFragment.onCreateView(SignInFragment.java:186)
       at org.wordpress.android.ui.accounts.login.MagicLinkSignInFragment.onCreateView(MagicLinkSignInFragment.java:71)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:174)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
       at android.app.Activity.performStart(Activity.java:6323)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2656)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by maxme** [comment]
To reproduce this one:

1. On the magic link sign in screen
1. Tap "Add self hosted site"
1. Rotate the phone -> crash
