### ISSUE TITLE
Crash report alpha-12: ClassCastException FrameLayout$LayoutParams 

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4168]
User comment: Crash when opening a notification from the notification list

```
Fatal Exception: java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
       at android.widget.ListView.clearRecycledState(ListView.java:560)
       at android.widget.ListView.resetList(ListView.java:547)
       at android.widget.ListView.layoutChildren(ListView.java:1535)
       at android.widget.AbsListView.onLayout(AbsListView.java:2723)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.widget.ScrollView.onLayout(ScrollView.java:2402)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
       at android.view.View.layout(View.java:17938)
       at android.view.ViewGroup.layout(ViewGroup.java:5812)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2666)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7414)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by maxme** [comment]
Crash is caused by https://github.com/wordpress-mobile/WordPress-Android/commit/8dc63cfe73039d206af00889ad64fd2d5d87e9e9 - reverted in https://github.com/wordpress-mobile/WordPress-Android/commit/04e590486dd3077eed109ad41de3af346b125f04
