### ISSUE TITLE
Crash report 5.4: NumberFormatException in EditPostSettingsFragment.onActivityResult

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4169]
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:1, request=4000, result=-1, data=Intent { (has extras) }} to activity {org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NumberFormatException: Invalid int: "1465119825102"
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3774)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3817)
       at android.app.ActivityThread.access$1300(ActivityThread.java:176)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1486)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
Caused by java.lang.NumberFormatException: Invalid int: "1465119825102"
       at java.lang.Integer.invalidInt(Integer.java:138)
       at java.lang.Integer.parse(Integer.java:413)
       at java.lang.Integer.parseInt(Integer.java:367)
       at java.lang.Integer.parseInt(Integer.java:334)
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.onActivityResult(EditPostSettingsFragment.java:456)
       at android.app.Activity.dispatchActivityResult(Activity.java:6211)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3770)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3817)
       at android.app.ActivityThread.access$1300(ActivityThread.java:176)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1486)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
```

**Comment by maxme** [comment]
Addressed by #4207
