### ISSUE TITLE
Crash when clicking the automattic.com link in the About screen

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#4182]
### Expected behavior

Open the link in a browser 

### Actual behavior

Crash:
`java.lang.IllegalArgumentException: Expected receiver of type org.wordpress.android.ui.prefs.AboutActivity, but got android.support.v7.widget.TintContextWrapper
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at android.view.View$DeclaredOnClickListener.onClick(View.java:4453)
                                                                           at android.view.View.performClick(View.java:5204)
                                                                           at android.view.View$PerformClick.run(View.java:21156)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

### Steps to reproduce the behavior

Go to Me tab -> App Settings -> WordPress for Android -> click on automattic.com

**Comment by 0nko** [comment]
Known issue: https://code.google.com/p/android/issues/detail?id=174871
