### ISSUE TITLE
Crash report 5.4.1: MagicLinkSignInFragment.openEmailClient

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4185]
No default email app on the device
```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.MAIN cat=[android.intent.category.APP_EMAIL] }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1765)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1485)
       at android.app.Activity.startActivityForResult(Activity.java:3778)
       at android.app.Activity.startActivityForResult(Activity.java:3739)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
       at android.app.Activity.startActivity(Activity.java:4049)
       at android.app.Activity.startActivity(Activity.java:4017)
       at org.wordpress.android.ui.accounts.login.MagicLinkSentFragment.openEmailClient(MagicLinkSentFragment.java:80)
       at org.wordpress.android.ui.accounts.login.MagicLinkSentFragment.access$100(MagicLinkSentFragment.java:17)
       at org.wordpress.android.ui.accounts.login.MagicLinkSentFragment$2.onClick(MagicLinkSentFragment.java:55)
       at android.view.View.performClick(View.java:4756)
       at android.view.View$PerformClick.run(View.java:19761)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5253)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by kwonye** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1158819/15919027/15ddaada-2dc2-11e6-8131-77b11321684b.gif)
