### ISSUE TITLE
Crash report 5.4.2: ClassCastException in WPActivityUtils.addToolbarToDialog

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4224]
```
Process: org.wordpress.android.beta, PID: 3638
java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.LinearLayout
    at org.wordpress.android.util.WPActivityUtils.addToolbarToDialog(WPActivityUtils.java:45)
    at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.onPreferenceTreeClick(NotificationsSettingsFragment.java:442)
    at android.preference.Preference.performClick(Preference.java:1005)
    at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
    at android.widget.AdapterView.performItemClick(AdapterView.java:310)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1155)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3087)
    at android.widget.AbsListView$3.run(AbsListView.java:4002)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:5969)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:801)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
```

**Comment by maxme** [comment]
1. Go to "Me" -> "Notification settings"
1. Tap a site, crash.

**Comment by maxme** [comment]
Same issue in "Site settings" -> "More" (on a wpcom site)
