### ISSUE TITLE
Crash report 5.6-rc-1: NPE in CommentDetailFragment

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4306]
Probably introduced by https://github.com/wordpress-mobile/WordPress-Android/pull/4268

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'org.wordpress.android.models.CommentStatus org.wordpress.android.models.Comment.getStatusEnum()' on a null object reference
       at org.wordpress.android.ui.comments.CommentDetailFragment$10.onActionResult(CommentDetailFragment.java:826)
       at org.wordpress.android.ui.comments.CommentActions$2.onResponse(CommentActions.java:167)
       at org.wordpress.android.ui.comments.CommentActions$2.onResponse(CommentActions.java:163)
       at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:76)
       at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:19)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
```

**Comment by maxme** [comment]
Note: this happened in 5.6-rc-1, please submit your PR against the `release/5.6` branch.
