### ISSUE TITLE
Crash report 5.5: NPE in SiteSettingsFragment

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#4339]
### Expected
To delete a word from the Hold for Moderation screen, long-press on the list item to activate the action mode and contextual action bar.

### Observed
When the Hold for Moderation word list exceeds the size of the device screen, long-pressing on items near the end of the list causes the app to crash.  See the animation and stack trace below.

![crash_moderation](https://cloud.githubusercontent.com/assets/3827611/16543322/ed812f1c-408b-11e6-949e-5c4a40c740ae.gif)

```
07-02 18:56:56.150 30629-30629/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 30629
    Theme: themes:{}
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setBackgroundColor(int)' on a null object reference
        at org.wordpress.android.ui.prefs.MultiSelectListView.onItemLongClick(MultiSelectListView.java:68)
        at android.widget.AbsListView.performLongPress(AbsListView.java:3151)
        at android.widget.AbsListView$CheckForLongPress.run(AbsListView.java:3083)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5461)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
### Reproduced
1. Go to Sites tab.
2. Tap Settings option under Configuration section.
3. Tap More option under Discussion section.
4. Tap Hold for Moderation under Comments section.
5. Scroll to bottom of list.
6. Long-press last item in list.

#### Tested
LG G4 (LG-H815) on Android 6.0.1 with WordPress 5.5
Samsung Galaxy S IV (SGH-I337) on Android 5.0.1 with WordPress 5.5
Samsung Galaxy S III (SGH-I747) on Android 4.4.4 with WordPress 5.5
Samsung Galaxy Tab 3 (SM-T310) on Android 4.4.2 with WordPress 5.5

**Comment by khaykov** [comment]
Fixed in #4482
