### ISSUE TITLE
Error 404 when replying to comments with device language set to Arabic or Farsi (Persian)

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-Android#4342]
### Expected behavior

Users should be able to reply to comments (e.g. from the notifications comment detail view) no matter what device language they use.
### Actual behavior

Comment replies fail when the device language is set to Arabic or Farsi (Persian).

Replies work as expected with other languages (tested in Spanish and Hebrew) or with the device language set to English and keyboard language set to Arabic.

I get this error when I try to reply to a comment with my device language set to Farsi:

```
07-04 13:07:06.996 11904-11947/? E/WordPress: [11795] BasicNetwork.performRequest: Unexpected response code 404 for https://public-api.wordpress.com/rest/v1/sites/۷۶۰۲۶۹۶۲/comments/۳۷/replies/new?locale=fa_IR
07-04 13:07:07.010 11904-11904/? E/WordPress-COMMENTS: com.android.volley.ServerError
                                                           at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:179)
                                                           at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
```

It looks like the issue is that these languages use different numerals, so the site ID and comment ID in the API request are being sent in the wrong numeral system.
### Steps to reproduce the behavior
1. On a WordPress.com or Jetpack blog, leave a comment (to trigger a notification)
2. In the app, open the comment notification and approve the comment if needed
3. Reply to the comment. Result: Comment is successfully published.
4. In the device settings, switch the language to Arabic or Farsi (Persian)
5. Return to the app and reply to the comment. Result: Comment fails.
##### Tested on Nexus 9, Android 6.0.1, WPAndroid alpha-16

Reported by a user in 114004-h using WPAndroid 5.5 (h/t Sandy for the report)

**Comment by rachelmcr** [comment]
I also tested from the site dashboard > Comments, and the comment reply is published from there without any issues. The only problem is when replying from the comment detail view in the notifications tab.
