### ISSUE TITLE
Crash report 5.7-rc-2: SQLite error in PeopleTable

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4464]
Empty string returned [here](https://github.com/wordpress-mobile/WordPress-Android/blob/6b08082858ae0a3432b23617b0557ee5708697bd/WordPress/src/main/java/org/wordpress/android/datasets/PeopleTable.java#L317-L317) will lead to a crash [there](https://github.com/wordpress-mobile/WordPress-Android/blob/6b08082858ae0a3432b23617b0557ee5708697bd/WordPress/src/main/java/org/wordpress/android/datasets/PeopleTable.java#L182).

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.people.PeopleManagementActivity}: android.database.sqlite.SQLiteException: near "DESC": syntax error (code 1): , while compiling: DELETE FROM people_email_followers WHERE local_blog_id=?1 AND person_id IN (SELECT person_id FROM people_email_followers WHERE local_blog_id=?1 DESC LIMIT ?2)
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
	(near "DESC": syntax error (code 1): , while compiling: DELETE FROM people_email_followers WHERE local_blog_id=?1 AND person_id IN (SELECT person_id FROM people_email_followers WHERE local_blog_id=?1 DESC LIMIT ?2))
#################################################################
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
Caused by android.database.sqlite.SQLiteException: near "DESC": syntax error (code 1): , while compiling: DELETE FROM people_email_followers WHERE local_blog_id=?1 AND person_id IN (SELECT person_id FROM people_email_followers WHERE local_blog_id=?1 DESC LIMIT ?2)
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
	(near "DESC": syntax error (code 1): , while compiling: DELETE FROM people_email_followers WHERE local_blog_id=?1 AND person_id IN (SELECT person_id FROM people_email_followers WHERE local_blog_id=?1 DESC LIMIT ?2))
#################################################################
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
       at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1634)
       at org.wordpress.android.datasets.PeopleTable.deletePeopleExceptForFirstPage(PeopleTable.java:181)
       at org.wordpress.android.ui.people.PeopleManagementActivity.onCreate(PeopleManagementActivity.java:105)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

**Comment by oguzkocer** [comment]
Fixed in #4465.
