### ISSUE TITLE
Editor: media download on UI thread

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4491]
In certain cases [this](https://github.com/wordpress-mobile/WordPress-Android/blob/6cc56aa1f4cf30ce845ae524caa5d2d2c6e01f90/WordPress/src/main/java/org/wordpress/android/ui/posts/EditPostActivity.java#L1517-L1517) can fail, `content://` can be a network link that needs an actual download step: 

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2000, result=-1, data=Intent { dat=content://com.microsoft.skydrive.content.StorageAccessProvider/document/content://com.microsoft.skydrive.content.metadata/property/SOMEONE%40SOMETHING.COM/Items/HASHASHASH/DSC_000001.JPG flg=0x1 }} to activity {org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: android.os.NetworkOnMainThreadException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3798)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3841)
       at android.app.ActivityThread.access$1400(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by android.os.NetworkOnMainThreadException
       at android.os.Parcel.readException(Parcel.java:1642)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1111)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:948)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:668)
       at org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:200)
       at org.wordpress.android.ui.posts.EditPostActivity.addMedia(EditPostActivity.java:1488)
       at org.wordpress.android.ui.posts.EditPostActivity.fetchMedia(EditPostActivity.java:1412)
       at org.wordpress.android.ui.posts.EditPostActivity.onActivityResult(EditPostActivity.java:1592)
       at android.app.Activity.dispatchActivityResult(Activity.java:6490)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3794)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3841)
       at android.app.ActivityThread.access$1400(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by daniloercoli** [comment]
Closing this since the code has been changed and external media should be properly dowloaded now.
