### ISSUE TITLE
ClassCastException bailing from SiteSettingsFragment

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#4534]
### Expected behavior
In Android 7, the app should gracefully pause when exiting to home from the Site settings screen.

### Actual behavior
App crashes in the background (Android pops up a small info window about it).

### Steps to reproduce the behavior
* Have a site selected of which you are an admin
* Head over to the MySite screen and open the "Settings" under the "Configuration" section
* Scroll down and tap the "More" in the "Discussion" section
* Tap the home button to return to the home screen
* :boom: 

Here's the stacktrace:

`Process: org.wordpress.android.beta, PID: 10061
java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.widget.LinearLayout
at org.wordpress.android.util.WPActivityUtils.removeToolbarFromDialog(WPActivityUtils.java:78)
at org.wordpress.android.ui.prefs.SiteSettingsFragment.removeMoreScreenToolbar(SiteSettingsFragment.java:1219)
at org.wordpress.android.ui.prefs.SiteSettingsFragment.onSaveInstanceState(SiteSettingsFragment.java:337)
at android.app.Fragment.performSaveInstanceState(Fragment.java:2514)
at android.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1763)
at android.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1820)
at android.app.FragmentController.saveAllState(FragmentController.java:112)
at android.app.Activity.onSaveInstanceState(Activity.java:1485)
at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:567)
at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:511)
at android.app.Activity.performSaveInstanceState(Activity.java:1414)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1300)
at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4505)
at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3827)
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3886)
at android.app.ActivityThread.-wrap25(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6077)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
`
##### Tested on [device], Android [version]
Nexus 5X, Android v7.0

**Comment by maxme** [comment]
Argh, missed that one when fixed the other here: https://github.com/wordpress-mobile/WordPress-Android/pull/4225

**Comment by maxme** [comment]
Fixed by #4535
