### ISSUE TITLE
Crash while converting string to role

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#4549]
There is an edge case crash happening in `release/5.8` for a user when the role string is read from the DB and converted to the `Role` enum. The crash happens due to an `IllegalArgumentException` we are throwing, if there is an unexpected string. Here is the full stacktrace:

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.people.PeopleManagementActivity}: java.lang.IllegalArgumentException: All roles must be handled
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4156)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.IllegalArgumentException: All roles must be handled
       at org.wordpress.android.models.Role.fromString(Role.java:41)
       at org.wordpress.android.datasets.PeopleTable.getPersonFromCursor(PeopleTable.java:314)
       at org.wordpress.android.datasets.PeopleTable.getPeople(PeopleTable.java:261)
       at org.wordpress.android.datasets.PeopleTable.getUsers(PeopleTable.java:232)
       at org.wordpress.android.ui.people.PeopleListFragment.refreshPeopleList(PeopleListFragment.java:234)
       at org.wordpress.android.ui.people.PeopleListFragment.updatePeople(PeopleListFragment.java:223)
       at org.wordpress.android.ui.people.PeopleListFragment.onResume(PeopleListFragment.java:199)
       at android.app.Fragment.performResume(Fragment.java:2329)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1023)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1163)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1145)
       at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1980)
       at android.app.FragmentController.dispatchResume(FragmentController.java:174)
       at android.app.Activity.performResume(Activity.java:7013)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4145)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4250)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3361)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by oguzkocer** [comment]
Closed in #4550.
