### ISSUE TITLE
Crash report 5.8: SecurityException in MediaUtils.downloadExternalMedia

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4555]
Looks like a Permission issue for at least one kind of content resolver:

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{80397e6 26364:org.wordpress.android/u0a238} (pid=26364, uid=10238) requires android.permission.MANAGE_DOCUMENTS or android.permission.MANAGE_DOCUMENTS
       at android.os.Parcel.readException(Parcel.java:1627)
       at android.os.Parcel.readException(Parcel.java:1579)
       at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3565)
       at android.app.ActivityThread.acquireProvider(ActivityThread.java:4878)
       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2004)
       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1477)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1095)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:948)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:668)
       at org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:200)
       at org.wordpress.android.ui.posts.EditPostActivity.addMedia(EditPostActivity.java:1517)
       at org.wordpress.android.ui.posts.EditPostActivity.access$2300(EditPostActivity.java:127)
       at org.wordpress.android.ui.posts.EditPostActivity$8.doInBackground(EditPostActivity.java:1452)
       at org.wordpress.android.ui.posts.EditPostActivity$8.doInBackground(EditPostActivity.java:1443)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by maxme** [comment]
Probably due to that https://github.com/wordpress-mobile/WordPress-Android/commit/6cc56aa1f4cf30ce845ae524caa5d2d2c6e01f90

**Comment by maxme** [comment]
[From the docs](https://developer.android.com/training/secure-file-sharing/request-file.html):

> File security is preserved in this process because the content URI is the only piece of data that the client app receives. Since this URI doesn't contain a directory path, the client app can't discover and open any other files in the server app. Only the client app gets access to the file, and only for the permissions granted by the server app. The permissions are temporary, so once the client app's task stack is finished, the file is no longer accessible outside the server app. 

So using this temporary uri in an async task is probably not the right thing to do.
