### ISSUE TITLE
Crash report 5.8: GCMMessageService.rebuildAndUpdateNotificationsOnSystemBar

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4556]
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at android.support.v4.util.SimpleArrayMap.keyAt(SimpleArrayMap.java:333)
       at org.wordpress.android.GCMMessageService.rebuildAndUpdateNotificationsOnSystemBar(GCMMessageService.java:410)
       at org.wordpress.android.GCMMessageService.handleBadgeResetPN(GCMMessageService.java:448)
       at org.wordpress.android.GCMMessageService.handleDefaultPush(GCMMessageService.java:105)
       at org.wordpress.android.GCMMessageService.synchronizedHandleDefaultPush(GCMMessageService.java:80)
       at org.wordpress.android.GCMMessageService.onMessageReceived(GCMMessageService.java:532)
       at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by maxme** [comment]
Was solved in 5.8.1
