### ISSUE TITLE
Crash report 5.9: ClassCastException in UploadMediaTask

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4608]
Looks like certain self hosted responses to upload media return a Boolean (?) instead of a string as the media url.

```
Fatal Exception: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
       at org.xmlrpc.android.ApiHelper$UploadMediaTask.onPostExecute(ApiHelper.java:863)
       at org.xmlrpc.android.ApiHelper$UploadMediaTask.onPostExecute(ApiHelper.java:744)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5830)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```

**Comment by aforcier** [comment]
This is fixed as of FluxC.

We no longer parse the `url` field from the `wp.uploadFile` response, but instead do a `wp.getMediaItem` call and pull its `link` field for the URL. If the `link` field were set to `0` for some reason, FluxC will store the URL as "0" instead of interpreting it as a boolean like `ApiHelper` is doing in this crash.
