### ISSUE TITLE
Crash on first run on Android v4.1.1

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#4658]
`FATAL EXCEPTION: IntentService[GCMRegistrationIntentService]
                                                 java.lang.IncompatibleClassChangeError: android.support.v4.content.ContextCompat
                                                     at com.google.android.gms.iid.zzd.zzeb(Unknown Source)
                                                     at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                     at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                                                     at org.wordpress.android.GCMRegistrationIntentService.onHandleIntent(GCMRegistrationIntentService.java:30)
                                                     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.os.HandlerThread.run(HandlerThread.java:60)`
### Steps to reproduce the behavior
- On an Android v4.1.1 emulator
- With the app uninstalled or data-cleaned
- Build and run `vanillaDebug`
- Login into your wpcom account in the app
- 💥 
##### Tested on [device], Android [version]

Nexus 5X Emulator, Android v4.1.1, wpandroid alpha-15, alpha-24

**Comment by hypest** [comment]
This is for an older version of wpandroid. Will verify it for latest shortly.

**Comment by mzorz** [comment]
@hypest is this one still happening to you? I've just tried by following the steps above (with a custom tablet emulator running 4.1.1 but it didn't crash for me)

**Comment by hypest** [comment]
Tried `alpha-27` out and it's not happening anymore. Closing this. Thanks for the ping @mzorz !
