### ISSUE TITLE
Crash report 6.2-rc-1: ActivityNotFoundException android.intent.category.APP_EMAIL

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4845]
We were checking if there is any email app before showing the magic link screen. Not sure if we removed this check or if there is a new bug.

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.MAIN cat=[android.intent.category.APP_EMAIL] }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1657)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
       at android.app.Activity.startActivityForResult(Activity.java:3456)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
       at android.app.Activity.startActivityForResult(Activity.java:3417)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at android.app.Activity.startActivity(Activity.java:3653)
       at android.app.Activity.startActivity(Activity.java:3621)
       at org.wordpress.android.ui.accounts.login.MagicLinkSentFragment.openEmailClient(MagicLinkSentFragment.java:80)
       at org.wordpress.android.ui.accounts.login.MagicLinkSentFragment.access$100(MagicLinkSentFragment.java:17)
       at org.wordpress.android.ui.accounts.login.MagicLinkSentFragment$2.onClick(MagicLinkSentFragment.java:55)
       at android.view.View.performClick(View.java:4240)
       at android.view.View$PerformClick.run(View.java:17742)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5121)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by maxme** [comment]
Apparently `isEmailClientAvailable` is not used anymore https://github.com/wordpress-mobile/WordPress-Android/blob/c08db09504eaf4e7ce55d28bb5403fb1d89630b7/WordPress/src/main/java/org/wordpress/android/util/WPActivityUtils.java#L133-L144

**Comment by daniloercoli** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/4869
