### ISSUE TITLE
Crash report 6.2: ISE in SignInFragment.showSelfHostedSignInForm

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4875]
```
Fatal Exception: java.lang.IllegalStateException: Fragment SignInFragment{5c59e3a} not attached to Activity
       at android.support.v4.app.Fragment.getResources(Fragment.java:651)
       at android.support.v4.app.Fragment.getString(Fragment.java:673)
       at org.wordpress.android.ui.accounts.SignInFragment.showSelfHostedSignInForm(SignInFragment.java:369)
       at org.wordpress.android.ui.accounts.SignInFragment$14.onResponse(SignInFragment.java:925)
       at org.wordpress.android.ui.accounts.SignInFragment$14.onResponse(SignInFragment.java:908)
       at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:76)
       at com.wordpress.rest.RestRequest.deliverResponse(RestRequest.java:19)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5451)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by daniloercoli** [comment]
Fixed in #4876
