### ISSUE TITLE
Crash report 6.2: NPE in NotificationsUtils.moderateCommentForNote

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4877]
Note: must be fixed in `release/6.2`

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=600, result=-1, data=Intent { (has extras) }} to activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.models.Note.getId()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3758)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3801)
       at android.app.ActivityThread.access$1400(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.models.Note.getId()' on a null object reference
       at org.wordpress.android.ui.notifications.utils.NotificationsUtils.moderateCommentForNote(NotificationsUtils.java:541)
       at org.wordpress.android.ui.main.WPMainActivity.moderateCommentOnActivityResult(WPMainActivity.java:473)
       at org.wordpress.android.ui.main.WPMainActivity.onActivityResult(WPMainActivity.java:508)
       at android.app.Activity.dispatchActivityResult(Activity.java:6463)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3754)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3801)
       at android.app.ActivityThread.access$1400(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by nbradbury** [comment]
Closed via #4879
