### ISSUE TITLE
Invalid JSON data prevents post upload

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4926]
Note this happened on a wordpress.com site:

```
85 - Unterminated object at character 9 of {value=a:1:{i:0;i:1;}, id=21, key=sharing_disabled}
86 - StackTrace: org.json.JSONException: Unterminated object at character 9 of {value=a:1:{i:0;i:1;}, id=21, key=sharing_disabled}
    at org.json.JSONTokener.syntaxError(JSONTokener.java:450)
    at org.json.JSONTokener.readObject(JSONTokener.java:394)
    at org.json.JSONTokener.nextValue(JSONTokener.java:100)
    at org.json.JSONObject.<init>(JSONObject.java:155)
    at org.json.JSONObject.<init>(JSONObject.java:172)
    at org.wordpress.android.models.Post.getCustomField(Post.java:157)
    at org.wordpress.android.ui.posts.services.PostUploadService$UploadPostTask.doInBackground(PostUploadService.java:312)
    at org.wordpress.android.ui.posts.services.PostUploadService$UploadPostTask.doInBackground(PostUploadService.java:167)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
```

**Comment by maxme** [comment]
Note: the exception is already handled [here](https://github.com/wordpress-mobile/WordPress-Android/blob/3fa460fb371599d9ad6315b4784c75b15b83b1e4/WordPress/src/main/java/org/wordpress/android/models/Post.java#L156-L164), it doesn't prevent the post to upload.
