### ISSUE TITLE
Crash report 6.4-rc-1: NPE in NotificationsPendingDraftsService

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4935]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.models.Blog.getLocalTableBlogId()' on a null object reference
       at org.wordpress.android.ui.notifications.services.NotificationsPendingDraftsService$1.run(NotificationsPendingDraftsService.java:97)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by mzorz** [comment]
Closing via #4937
