### ISSUE TITLE
NPE when deleting draft post / Notifications

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#4939]
If you have a draft post and delete it from the Blog Post List screen, and hit back without waiting for the UNDO snackbar to disappear, the activity is not present anymore thus leading to the following NPE

```                 
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
                      at android.support.v4.app.NotificationManagerCompat.<init>(NotificationManagerCompat.java:149)
                      at android.support.v4.app.NotificationManagerCompat.from(NotificationManagerCompat.java:144)
                      at org.wordpress.android.push.NativeNotificationsUtils.dismissNotification(NativeNotificationsUtils.java:47)
                      at org.wordpress.android.ui.posts.PostsListFragment$5.onDismissed(PostsListFragment.java:529)
                      at android.support.design.widget.Snackbar.onViewHidden(Snackbar.java:637)
                      at android.support.design.widget.Snackbar$5$1.run(Snackbar.java:504)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by daniloercoli** [comment]
Addressed in #4945
