### ISSUE TITLE
Crash report 6.3: NPE in PostsListAdapter

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4967]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.PostsListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.models.Blog.getLocalTableBlogId()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.models.Blog.getLocalTableBlogId()' on a null object reference
       at org.wordpress.android.ui.posts.adapters.PostsListAdapter.<init>(PostsListAdapter.java:86)
       at org.wordpress.android.ui.posts.PostsListFragment.getPostListAdapter(PostsListFragment.java:141)
       at org.wordpress.android.ui.posts.PostsListFragment.requestPosts(PostsListFragment.java:226)
       at org.wordpress.android.ui.posts.PostsListFragment.onActivityCreated(PostsListFragment.java:168)
       at android.app.Fragment.performActivityCreated(Fragment.java:2228)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:992)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
       at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1953)
       at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:152)
       at android.app.Activity.performCreateCommon(Activity.java:6245)
       at android.app.Activity.performCreate(Activity.java:6253)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by daniloercoli** [comment]
Addressed in #4970
