### ISSUE TITLE
Crash Report 6.4-rc-1: Bad notification posted from package org.wordpress.android: Couldn't expand RemoteViews

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4968]
Happens on 4.x devices:

```
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package org.wordpress.android: Couldn't expand RemoteViews for: StatusBarNotification(pkg=org.wordpress.android id=60001 tag=null score=20 notn=Notification(pri=2 contentView=org.wordpress.android/0x10900a8 vibrate=null sound=null defaults=0x0 flags=0x10 kind=[null] 2 actions))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4895)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by maxme** [comment]
I guess we have some unsupported components in a notification layout - second idea: could be due to vector drawables.

**Comment by maxme** [comment]
Another report happening on a 6.0.1 this time:

```
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package org.wordpress.android: Couldn't expand RemoteViews for: StatusBarNotification(pkg=org.wordpress.android user=UserHandle{0} id=60001 tag=null score=20: Notification(pri=2 contentView=org.wordpress.android/0x10900ed vibrate=null sound=null defaults=0x0 flags=0x10 kind=[null] 2 actions))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1526)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5473)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by maxme** [comment]
Note: I double checked, we're checking for null values before calling `setLargeIcon()`.

**Comment by daniloercoli** [comment]
Don't think the issue is on the `setLargeIcon()` call here:
https://github.com/wordpress-mobile/WordPress-Android/blob/release/6.4/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadService.java#L912

but `BitmapFactory.decodeResource(getApplicationContext().getResources(),               R.mipmap.app_icon)` could potentially return null here.

**Comment by maxme** [comment]
Right, might be worth testing for null value and don't call `setLargeIcon()` there.

**Comment by mzorz** [comment]
Ok been taking a quick look into this issue and it seems indeed we need to provide PNGs here for RemoteViews as @daniloercoli first checked, and as per the following:
https://code.google.com/p/android/issues/detail?id=204245
https://code.google.com/p/android/issues/detail?id=202199

Pinging @drw158 re: this https://github.com/wordpress-mobile/WordPress-Android/pull/4835#issuecomment-263352810  and this conversation up here ☝️ I think we need that gridicon asset converted to PNG (in all sizes for Android just like `ic_close_white_24dp.png` is) so we can use them on notifications on Android 4.x. Could you provide these please?

Just for tracking, this is the commit where we changed the EDIT icon to gridicon
https://github.com/wordpress-mobile/WordPress-Android/pull/4835/commits/43bc1478ba219d4228773e7264fb358af20da131

Thanks @daniloercoli for taking care of this!
