### ISSUE TITLE
Crash report 6.4-rc-1:NPE in NativeNotificationsUtils

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4969]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at android.support.v4.app.NotificationManagerCompat.<init>(NotificationManagerCompat.java:149)
       at android.support.v4.app.NotificationManagerCompat.from(NotificationManagerCompat.java:144)
       at org.wordpress.android.push.NativeNotificationsUtils.dismissNotification(NativeNotificationsUtils.java:47)
       at org.wordpress.android.ui.posts.PostsListFragment$5.onDismissed(PostsListFragment.java:529)
       at android.support.design.widget.Snackbar.onViewHidden(Snackbar.java:637)
       at android.support.design.widget.Snackbar$5$1.run(Snackbar.java:504)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by daniloercoli** [comment]
Fixed here: https://github.com/wordpress-mobile/WordPress-Android/commit/68d6fe2c14e70be49c7185f5a15ae0b35ab63ec1
