### ISSUE TITLE
Crash report 6.3: SecurityException in ActivityLauncher.openUrlExternal

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#4991]
```
Fatal Exception: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=http://amanahproduction.com/... cmp=com.alibaba.intl.android.apps.poseidon/com.alibaba.android.intl.weex.activity.WeexPageActivity } from ProcessRecord{89739bd 17734:org.wordpress.android/u0a217} (pid=17734, uid=10217) not exported from uid 10114
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.os.Parcel.readException(Parcel.java:1573)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2695)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1509)
       at android.app.Activity.startActivityForResult(Activity.java:4001)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
       at android.app.Activity.startActivityForResult(Activity.java:3962)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at android.app.Activity.startActivity(Activity.java:4285)
       at android.app.Activity.startActivity(Activity.java:4253)
       at org.wordpress.android.ui.ActivityLauncher.openUrlExternal(ActivityLauncher.java:298)
       at org.wordpress.android.ui.ActivityLauncher.viewCurrentSite(ActivityLauncher.java:135)
       at org.wordpress.android.ui.main.MySiteFragment$4.onClick(MySiteFragment.java:183)
       at android.view.View.performClick(View.java:5210)
       at android.view.View$PerformClick.run(View.java:21169)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5451)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by maxme** [comment]
To reproduce: install [Alibaba B2B trade app](https://play.google.com/store/apps/details?id=com.alibaba.intl.android.apps.poseidon), tap the "View Site" button in My Site tab, and watch the world burn.

**Comment by maxme** [comment]
From that app's apk:

```
$ aapt l -a Alibaba\ com\ B2B\ Trade\ App_v4.15.1_apkpure.com.apk | grep -A 17 WeexPageActivity 
      E: activity (line=1284)
        A: android:theme(0x01010000)=@0x7f0a010d
        A: android:name(0x01010003)="com.alibaba.android.intl.weex.activity.WeexPageActivity" (Raw: "com.alibaba.android.intl.weex.activity.WeexPageActivity")
        A: android:exported(0x01010010)=(type 0x12)0x0
        A: android:screenOrientation(0x0101001e)=(type 0x10)0xffffffff
        A: android:configChanges(0x0101001f)=(type 0x11)0x4a0
        E: intent-filter (line=1290)
          E: action (line=1291)
            A: android:name(0x01010003)="android.intent.action.VIEW" (Raw: "android.intent.action.VIEW")
          E: category (line=1293)
            A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw: "android.intent.category.DEFAULT")
          E: category (line=1294)
            A: android:name(0x01010003)="com.alibaba.android.intl.category.WEEX" (Raw: "com.alibaba.android.intl.category.WEEX")
          E: data (line=1296)
            A: android:scheme(0x01010027)="http" (Raw: "http")
          E: data (line=1297)
            A: android:scheme(0x01010027)="https" (Raw: "https")
          E: data (line=1298)
            A: android:scheme(0x01010027)="file" (Raw: "file")
```

It looks like they registered http/https/file schemes to an unexported Activity.

**Comment by maxme** [comment]
This should be fixed in their update https://github.com/alibaba/weex/issues/2139#issuecomment-271466227
