### ISSUE TITLE
Crash report 6.4: ISE in WordPressDB.getPostFromCursor

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5004]
```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:831)
Caused by java.lang.IllegalStateException: Couldn't read row 22, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
       at android.database.CursorWindow.getLong(CursorWindow.java:511)
       at android.database.CursorWindow.getInt(CursorWindow.java:578)
       at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:69)
       at org.wordpress.android.WordPressDB.getPostFromCursor(WordPressDB.java:1267)
       at org.wordpress.android.WordPressDB.getPostsListPosts(WordPressDB.java:1238)
       at org.wordpress.android.ui.posts.adapters.PostsListAdapter$LoadPostsTask.doInBackground(PostsListAdapter.java:654)
       at org.wordpress.android.ui.posts.adapters.PostsListAdapter$LoadPostsTask.doInBackground(PostsListAdapter.java:636)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:831)
```

**Comment by nbradbury** [comment]
Note: sounds like the same problem as [this](https://github.com/wordpress-mobile/WordPress-Android/issues/1812) older reader issue.

**Comment by aforcier** [comment]
Closing this as all of this code has been migrated to FluxC. It's possible this issue can still occur in FluxC - if it does we'll receive a new crash report and investigate from there.
