### ISSUE TITLE
[Crash] Select Any Format in Header Popup Menu

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5037]
### Expected
Selecting a format in the header popup menu applies the style to text.

### Observed
Selecting any format causes the app to crash.  The stack trace is shown below.

```
01-21 14:36:27.668 29952-29952/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android.beta, PID: 29952
    java.lang.NoSuchFieldError: No field gallery of type I in class Lorg/wordpress/aztec/R$id; or its superclasses (declaration of 'org.wordpress.aztec.R$id' appears in /data/data/org.wordpress.android.beta/files/instant-run/dex/slice-slice_1-classes.dex)
        at org.wordpress.aztec.toolbar.AztecToolbar.onMenuItemClick(AztecToolbar.kt:97)
        at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:104)
        at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
        at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
        at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
        at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:310)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1156)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3121)
        at android.widget.AbsListView$3.run(AbsListView.java:4036)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### Reproduced
1. Go to ***Sites*** tab.
2. Tap ***Create*** floating action button.
3. Tap in post content area.
4. Tap ***Header*** format toolbar button.
5. Select any format.

##### Tested
Google Pixel on Android 7.1.1 with WordPress alpha-33

**Comment by theck13** [comment]
I can no longer reproduce this on a API 25, 24, 23, 22, 19, 17, or 16.
