### ISSUE TITLE
Aztec: Crash while typing with formatted text

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5174]
I got this crash while writing a draft post in Aztec. It was a gibberish post, with random bold/italic/underline/strikethrough text (no other special formatting). I believe I had just pressed the bold button at the end of a bold word. Couldn't reproduce it when I re-opened the draft.

```
FATAL EXCEPTION: main
Process: org.wordpress.android, PID: 17554
java.lang.StringIndexOutOfBoundsException: length=97; index=97
   at java.lang.String.charAt(Native Method)
   at org.wordpress.aztec.formatting.BlockFormatter.handleBlockStyling(BlockFormatter.kt:235)
   at org.wordpress.aztec.AztecText.afterTextChanged(AztecText.kt:522)
   at android.widget.TextView.sendAfterTextChanged(TextView.java:8203)
   at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10382)
   at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1218)
   at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:579)
   at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
   at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
   at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:844)
   at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:198)
   at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
   at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:158)
   at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:353)
   at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:93)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:6119)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by aforcier** [comment]
Moved to Aztec repo: https://github.com/wordpress-mobile/WordPress-Aztec-Android/issues/256
