### ISSUE TITLE
FluxC - Media Integration - bind/unbind store in the EditPost should be re thinked

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5183]
We should reuse `doUnbindUploadService` from MediaBrowserActivity to avoid any unbinding issues

```
java.lang.RuntimeException: Unable to stop activity {org.wordpress.android.beta/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.IllegalArgumentException: Service not registered: org.wordpress.android.ui.posts.EditPostActivity$10@39b8d19a
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3344)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3390)
    at android.app.ActivityThread.access$1100(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5221)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
 Caused by: java.lang.IllegalArgumentException: Service not registered: org.wordpress.android.ui.posts.EditPostActivity$10@39b8d19a
    at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1024)
    at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
    at android.content.ContextWrapper.unbindService(ContextWrapper.java:550)
    at org.wordpress.android.ui.posts.EditPostActivity.onStop(EditPostActivity.java:443)
    at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1261)
    at android.app.Activity.performStop(Activity.java:6085)
    at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3341)
    at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3390) 
    at android.app.ActivityThread.access$1100(ActivityThread.java:144) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5221) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 
```

**Comment by tonyr59h** [comment]
Addressed in #5191, closing.
