### ISSUE TITLE
Crash report alpha-37: NPE in WPLegacyMigrationUtils.getDraftsFromDeprecatedDB

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5287]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at org.wordpress.android.util.WPLegacyMigrationUtils.getDraftsFromDeprecatedDB(WPLegacyMigrationUtils.java:253)
       at org.wordpress.android.util.WPLegacyMigrationUtils.migrateDraftsFromDeprecatedDB(WPLegacyMigrationUtils.java:80)
       at org.wordpress.android.WordPress.migrateDrafts(WordPress.java:349)
       at org.wordpress.android.WordPress.migrateSelfHostedSites(WordPress.java:343)
       at org.wordpress.android.WordPress.onSiteChanged(WordPress.java:544)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by maxme** [comment]
Easy to fix, but I think we should write a few tests for these utils (with nil values in all fields table fields for instance).
