### ISSUE TITLE
Crash report alpha-37: IAE in WPLaunchActivity.onCompletion

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5297]
```
Caused by java.lang.IllegalArgumentException: View=DecorView@7cfc55b[] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:382)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
       at android.app.Dialog.dismissDialog(Dialog.java:363)
       at android.app.Dialog.dismiss(Dialog.java:346)
       at org.wordpress.android.ui.WPLaunchActivity$1.onCompletion(WPLaunchActivity.java:35)
       at org.wordpress.android.WordPress.endMigration(WordPress.java:361)
       at org.wordpress.android.WordPress.migrateDrafts(WordPress.java:354)
       at org.wordpress.android.WordPress.migrateSelfHostedSites(WordPress.java:343)
       at org.wordpress.android.WordPress.onSiteChanged(WordPress.java:544)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by aforcier** [comment]
Fixed in #5305.
