### ISSUE TITLE
Crash report 6.8: SecurityException: !@Too many alarms (500)

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5356]
We should limit the number of registered alarms

```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.SecurityException: !@Too many alarms (500) registered from pid 8735 uid 10200
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.os.Parcel.readException(Parcel.java:1573)
       at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:217)
       at android.app.AlarmManager.setImpl(AlarmManager.java:484)
       at android.app.AlarmManager.set(AlarmManager.java:260)
       at org.wordpress.android.ui.notifications.utils.PendingDraftsNotificationsUtils.scheduleNextNotifications(PendingDraftsNotificationsUtils.java:57)
       at org.wordpress.android.ui.posts.EditPostActivity$SaveAndFinishTask.doInBackground(EditPostActivity.java:910)
       at org.wordpress.android.ui.posts.EditPostActivity$SaveAndFinishTask.doInBackground(EditPostActivity.java:869)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

cc @mzorz

**Comment by mzorz** [comment]
oh wow! do you know if this was a Samsung device @maxme ?

**Comment by mzorz** [comment]
related information https://groups.google.com/forum/#!topic/firebase-talk/Q_zycHnTGu0

**Comment by mzorz** [comment]
We didn't get any of these in the last 30 days - closing for now
