### ISSUE TITLE
Crash report 7.0-rc-1: NumberFormatException in WPLegacyMigrationUtils.java

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#5372]
```
Caused by java.lang.NumberFormatException: For input string: "false"
       at java.lang.Long.parseLong(Long.java:443)
       at java.lang.Long.valueOf(Long.java:542)
       at org.wordpress.android.util.WPLegacyMigrationUtils.getDraftsFromDeprecatedDB(WPLegacyMigrationUtils.java:255)
       at org.wordpress.android.util.WPLegacyMigrationUtils.migrateDraftsFromDeprecatedDB(WPLegacyMigrationUtils.java:80)
       at org.wordpress.android.WordPress.migrateDrafts(WordPress.java:357)
       at org.wordpress.android.WordPress.migrateSelfHostedSites(WordPress.java:351)
```

It seems the `api_blogid` field can be stored as `false`.

**Comment by aforcier** [comment]
Fixed in #5375.
