### ISSUE TITLE
Crash report 7.0-rc-1: NPE in EditPostActivity.onCreate

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5380]
We shouldn't pass a null site to `instantiatePostModel`.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.SiteModel.getId()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3320)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416)
       at android.app.ActivityThread.access$1100(ActivityThread.java:230)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1822)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7409)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.SiteModel.getId()' on a null object reference
       at org.wordpress.android.fluxc.store.PostStore.instantiatePostModel(PostStore.java:181)
       at org.wordpress.android.ui.posts.EditPostActivity.onCreate(EditPostActivity.java:307)
       at android.app.Activity.performCreate(Activity.java:6904)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3267)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3416)
       at android.app.ActivityThread.access$1100(ActivityThread.java:230)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1822)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7409)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by daniloercoli** [comment]
Fixed in #5381
