### ISSUE TITLE
NPE adding picture from WP media library

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5408]
- Go to WP Media Library
- Select two or more pictures (Among of those selected pictures should be at least one in the "retry" state).
- Tap the pencil icon --> Crash.

```
03-15 10:35:27.702 20283-20283/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: org.wordpress.android, PID: 20283
                                                                       java.lang.NullPointerException
                                                                           at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:990)
                                                                           at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:985)
                                                                           at org.wordpress.android.editor.EditorFragment.appendMediaFile(EditorFragment.java:1022)
                                                                           at org.wordpress.android.ui.posts.EditPostActivity.addExistingMediaToEditor(EditPostActivity.java:1302)
                                                                           at org.wordpress.android.ui.posts.EditPostActivity.prepareMediaPost(EditPostActivity.java:1491)
                                                                           at org.wordpress.android.ui.posts.EditPostActivity.fillContentEditorFields(EditPostActivity.java:1422)
                                                                           at org.wordpress.android.ui.posts.EditPostActivity.onEditorFragmentInitialized(EditPostActivity.java:2241)
                                                                           at org.wordpress.android.editor.EditorFragment.onCreateView(EditorFragment.java:334)
                                                                           at android.app.Fragment.performCreateView(Fragment.java:2353)
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                                           at android.app.BackStackRecord.run(BackStackRecord.java:816)
                                                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                                                                           at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:563)
                                                                           at android.support.v13.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:153)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                           at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                           at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                           at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                           at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                           at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
                                                                           at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
03-15 10:35:27.702 20283-20283/org.wordpress.android E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteIn
```

**Comment by daniloercoli** [comment]
Fixed in #5419
