### ISSUE TITLE
Timeout error uploading media over WiFi to wpcom

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5409]
I'm not able to upload a picture taken from my device to wpcom. The error log just shows a `timeout` error, but i'm on a WiFi connection, and able to upload small pictures to the blog.
```
D/WordPress-EDITOR: Image tapped, id=51~url=file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FWordPress%2Fimages%2FIMG_20170312_132114.jpg~meta=%7B%22align%22%3A%22none%22%2C%22alt%22%3A%22%22%2C%22attachment_id%22%3A%22%22%2C%22caption%22%3A%22%22%2C%22captionClassName%22%3A%22%22%2C%22captionId%22%3A%22%22%2C%22classes%22%3A%22failed%22%2C%22height%22%3A3024%2C%22linkClassName%22%3A%22%22%2C%22linkRel%22%3A%22%22%2C%22linkTargetBlank%22%3Afalse%2C%22linkUrl%22%3A%22%22%2C%22size%22%3A%22custom%22%2C%22src%22%3A%22%2Fstorage%2Femulated%2F0%2FWordPress%2Fimages%2FIMG_20170312_132114.jpg%22%2C%22title%22%3A%22%22%2C%22width%22%3A4032%2C%22naturalWidth%22%3A4032%2C%22naturalHeight%22%3A3024%7D~type=image
D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
I/WordPress-MEDIA: Dispatching upload action for media with local id: 51 and path: /storage/emulated/0/WordPress/images/IMG_20170312_132114.jpg
D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
D/WordPress-API: Dispatching action: MediaAction-UPLOAD_MEDIA
D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
I/WordPress-MEDIA: Ignoring request to uploadNextInQueue, only one media item can be uploaded at a time.
I/WordPress-MEDIA: Ignoring request to uploadNextInQueue, only one media item can be uploaded at a time.
D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
W/WordPress-MEDIA: media upload failed: java.net.SocketTimeoutException: timeout
D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
W/WordPress-MEDIA: Error uploading media: null
D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
V/WordPress-MEDIA: No more media items to upload. Stopping MediaUploadService.
```

**Comment by daniloercoli** [comment]
This is the complete log I get when trying to upload a Picture:
```
03-16 09:52:13.576 16403-17155/org.wordpress.android D/WordPress-EDITOR: New field created, id=zss_field_title
03-16 09:52:13.580 16403-17155/org.wordpress.android D/WordPress-EDITOR: New field created, id=zss_field_content
03-16 09:52:13.599 16403-16403/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup: begin
03-16 09:52:13.600 16403-16403/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup:      0 ms, EditorFragment.onCreate
03-16 09:52:13.600 16403-16403/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup:      117 ms, EditorFragment.initJsEditor
03-16 09:52:13.601 16403-16403/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup:      1582 ms, EditorFragment.onDomLoaded
03-16 09:52:13.601 16403-16403/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup:      18 ms, EditorFragment.onDomLoaded completed
03-16 09:52:13.601 16403-16403/org.wordpress.android D/WordPress-PROFILING: Visual Editor Startup: end, 1717 ms
03-16 09:52:13.656 16403-17155/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getFailedMedia~ids=
03-16 09:52:13.698 16403-17155/org.wordpress.android D/WordPress-EDITOR: Focus in callback received
03-16 09:52:15.091 16403-17155/org.wordpress.android D/WordPress-EDITOR: Focus out callback received
03-16 09:52:15.094 16403-17155/org.wordpress.android D/WordPress-EDITOR: Focus in callback received
03-16 09:52:16.214 16403-16405/org.wordpress.android I/art: Do partial code cache collection, code=1005KB, data=811KB
03-16 09:52:16.215 16403-16405/org.wordpress.android I/art: After code cache collection, code=969KB, data=778KB
03-16 09:52:16.215 16403-16405/org.wordpress.android I/art: Increasing code cache capacity to 3MB
03-16 09:52:16.301 16403-16405/org.wordpress.android I/art: Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()
03-16 09:52:17.919 16403-16403/org.wordpress.android D/WordPress-EDITOR: Illegal state! Can't unregister receiver that was no registered
03-16 09:52:18.432 16403-17130/org.wordpress.android W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-16 09:52:18.445 16403-17130/org.wordpress.android W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-16 09:52:18.459 16403-17130/org.wordpress.android W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection
03-16 09:52:18.459 16403-17130/org.wordpress.android W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-16 09:52:18.497 16403-16403/org.wordpress.android D/WordPress-EDITOR: getTitle() called from UI thread
03-16 09:52:18.504 16403-17155/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
03-16 09:52:18.513 16403-16403/org.wordpress.android D/WordPress-EDITOR: getContent() called from UI thread
03-16 09:52:18.520 16403-17155/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=
03-16 09:52:18.701 16403-17155/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_title~contents=
03-16 09:52:18.712 16403-17155/org.wordpress.android D/WordPress-EDITOR: callback-response-string: function=getHTMLForCallback~id=zss_field_content~contents=
03-16 09:52:18.728 16403-17322/org.wordpress.android D/WordPress-API: Dispatching action: PostAction-UPDATE_POST
03-16 09:52:18.752 16403-16699/org.wordpress.android D/EventBus: No subscribers registered for event class org.wordpress.android.fluxc.store.PostStore$OnPostChanged
03-16 09:52:18.752 16403-16699/org.wordpress.android D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
03-16 09:52:19.916 16403-17244/org.wordpress.android I/WordPress-UTILS: App goes to background
03-16 09:52:19.961 16403-17244/org.wordpress.android I/WordPress-UTILS: ConnectionChangeReceiver.setEnabled false
03-16 09:52:20.542 16403-16403/org.wordpress.android I/WordPress-UTILS: App comes from background
03-16 09:52:20.542 16403-16403/org.wordpress.android I/WordPress-UTILS: ConnectionChangeReceiver.setEnabled true
03-16 09:52:20.544 16403-16403/org.wordpress.android I/WordPress-UTILS: Connection status changed, isConnected=true
03-16 09:52:20.651 16403-16403/org.wordpress.android I/WordPress-NOTIFS: notifications update service > created
03-16 09:52:20.930 16403-16403/org.wordpress.android I/WordPress-MEDIA: New media instantiated localId=111
03-16 09:52:20.933 16403-16403/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
03-16 09:52:21.005 16403-16403/org.wordpress.android I/WordPress-MEDIA: Media Upload Service > created
03-16 09:52:21.031 16403-17382/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
03-16 09:52:21.033 16403-17382/org.wordpress.android I/WordPress-MEDIA: Dispatching upload action for media with local id: 111 and path: /storage/emulated/0/WordPress/images/IMG_20170312_132111.jpg
03-16 09:52:21.033 16403-17382/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
03-16 09:52:21.034 16403-17382/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOAD_MEDIA
03-16 09:52:21.037 16403-16403/org.wordpress.android I/WordPress-MEDIA: Dispatching cancel upload action for media with local id: 111 and path: /storage/emulated/0/WordPress/images/IMG_20170312_132111.jpg
03-16 09:52:21.038 16403-16403/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-CANCEL_MEDIA_UPLOAD
03-16 09:52:21.041 16403-16403/org.wordpress.android I/WordPress-MEDIA: Media Upload Service > destroyed
03-16 09:52:21.042 16403-16707/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-CANCELED_MEDIA_UPLOAD
03-16 09:52:21.193 16403-17391/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
03-16 09:52:21.294 16403-17391/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
03-16 09:52:21.395 16403-17391/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
03-16 09:52:21.496 16403-17391/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
03-16 09:52:23.030 16403-16409/org.wordpress.android W/art: Suspending all threads took: 40.432ms
03-16 09:52:23.039 16403-16414/org.wordpress.android W/art: Suspending all threads took: 8.892ms
03-16 09:52:23.059 16403-16414/org.wordpress.android I/art: Background sticky concurrent mark sweep GC freed 81371(6MB) AllocSpace objects, 35(3MB) LOS objects, 30% free, 24MB/35MB, paused 10.084ms total 74.519ms
03-16 09:52:23.217 16403-16403/org.wordpress.android I/WordPress-NOTIFS: notifications update service > completed
03-16 09:52:23.221 16403-16403/org.wordpress.android I/WordPress-NOTIFS: notifications update service > destroyed
03-16 09:52:37.608 16403-16409/org.wordpress.android W/art: Suspending all threads took: 10.883ms
03-16 09:52:51.513 16403-17391/org.wordpress.android W/WordPress-MEDIA: media upload failed: java.net.SocketTimeoutException: timeout
03-16 09:52:51.514 16403-17391/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
```

Not sure why there is a Dispatching action: MediaAction-CANCEL_MEDIA_UPLOAD few seconds after the upload started
```
03-16 09:52:20.930 16403-16403/org.wordpress.android I/WordPress-MEDIA: New media instantiated localId=111
03-16 09:52:20.933 16403-16403/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
03-16 09:52:21.005 16403-16403/org.wordpress.android I/WordPress-MEDIA: Media Upload Service > created
03-16 09:52:21.031 16403-17382/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
03-16 09:52:21.033 16403-17382/org.wordpress.android I/WordPress-MEDIA: Dispatching upload action for media with local id: 111 and path: /storage/emulated/0/WordPress/images/IMG_20170312_132111.jpg
03-16 09:52:21.033 16403-17382/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
03-16 09:52:21.034 16403-17382/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOAD_MEDIA
03-16 09:52:21.037 16403-16403/org.wordpress.android I/WordPress-MEDIA: Dispatching cancel upload action for media with local id: 111 and path: /storage/emulated/0/WordPress/images/IMG_20170312_132111.jpg
03-16 09:52:21.038 16403-16403/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-CANCEL_MEDIA_UPLOAD
```
When I tap on retry:
```
03-16 09:55:26.769 16403-17155/org.wordpress.android D/WordPress-EDITOR: Image tapped, id=111~url=file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FWordPress%2Fimages%2FIMG_20170312_132111.jpg~meta=%7B%22align%22%3A%22none%22%2C%22alt%22%3A%22%22%2C%22attachment_id%22%3A%22%22%2C%22caption%22%3A%22%22%2C%22captionClassName%22%3A%22%22%2C%22captionId%22%3A%22%22%2C%22classes%22%3A%22failed%22%2C%22height%22%3A3024%2C%22linkClassName%22%3A%22%22%2C%22linkRel%22%3A%22%22%2C%22linkTargetBlank%22%3Afalse%2C%22linkUrl%22%3A%22%22%2C%22size%22%3A%22custom%22%2C%22src%22%3A%22%2Fstorage%2Femulated%2F0%2FWordPress%2Fimages%2FIMG_20170312_132111.jpg%22%2C%22title%22%3A%22%22%2C%22width%22%3A4032%2C%22naturalWidth%22%3A4032%2C%22naturalHeight%22%3A3024%7D~type=image
03-16 09:55:26.787 16403-17155/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
03-16 09:55:26.806 16403-16403/org.wordpress.android I/WordPress-MEDIA: Media Upload Service > created
03-16 09:55:26.836 16403-20039/org.wordpress.android I/WordPress-MEDIA: Dispatching upload action for media with local id: 111 and path: /storage/emulated/0/WordPress/images/IMG_20170312_132111.jpg
03-16 09:55:26.836 16403-20039/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
03-16 09:55:26.838 16403-20039/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOAD_MEDIA
03-16 09:55:26.848 16403-16403/org.wordpress.android I/WordPress-MEDIA: Dispatching cancel upload action for media with local id: 111 and path: /storage/emulated/0/WordPress/images/IMG_20170312_132111.jpg
03-16 09:55:26.849 16403-16403/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-CANCEL_MEDIA_UPLOAD
03-16 09:55:26.851 16403-16403/org.wordpress.android I/WordPress-MEDIA: Media Upload Service > destroyed
03-16 09:55:26.851 16403-19948/org.wordpress.android D/WordPress-MEDIA: Canceled in-progress upload: IMG_20170312_132111.jpg
03-16 09:55:26.852 16403-19948/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-CANCELED_MEDIA_UPLOAD
03-16 09:55:26.871 16403-20042/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
03-16 09:55:26.981 16403-20042/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
03-16 09:55:27.082 16403-20042/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
03-16 09:55:57.117 16403-20042/org.wordpress.android W/WordPress-MEDIA: media upload failed: java.net.SocketTimeoutException: timeout
03-16 09:55:57.118 16403-20042/org.wordpress.android D/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
```

**Comment by maxme** [comment]
@daniloercoli Looking at the logs, I'm pretty sure the culprit is that cancel action. Then looking at the code, I see cancel is only called from the [`MediaUploadService.onDestroy`](https://github.com/wordpress-mobile/WordPress-Android/blob/9fe9c920b72575e0b492e32003431cba4d2b0509/WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java#L98-L98)

* Does this happen only when you switch from the activity to another?
* Can you put a break point in the [cancel method ](https://github.com/wordpress-mobile/WordPress-Android/blob/9fe9c920b72575e0b492e32003431cba4d2b0509/WordPress/src/main/java/org/wordpress/android/ui/media/services/MediaUploadService.java#L290-L295)and make sure it's not called from somewhere else?

This service should be a sticky service (like the post upload service), this would solve this kind of problems in the Media Library (this won't change anything in the Editor for background upload yet, but this problem already exist in 6.9 and previous versions).

Long term: we should try to use Volley for uploads, this will help with cancelling request.

**Comment by daniloercoli** [comment]
This seems to be an issue on both version `6.9` and version `7.0` when you try to upload something "big" over HTTPS to wpcom.
```
java.net.SocketTimeoutException: Read timed out 
at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
```


I can repro the issue on Android 7.1.1, and Android 5.0 easily. Even though Android 7.1.1 seems to be more fragile, since I cannot upload pictures bigger than 3MB, instead on Android 5.0 the problem ecountered when I try to upload >5MB pictures.

`Tried on both versions on a self-hosted site over plain HTTP, and the issue is not there.`

*Note:* The issue is not there if I upload the picture over 4G Networks, since the time taken to upload the picture is really short and the timeone it not fired at all.


As a quick and dirty fix I propose for not to increase the read timeout to 60 secs.

**Comment by daniloercoli** [comment]
We're fixing this FluxC side. `7.0-rc-2` and `alpha-40` have the first patch in it.

Keep this open for reference.

**Comment by daniloercoli** [comment]
Sounds similar but on the old Network stack https://android.forums.wordpress.org/topic/uploading-19mb-photo-gives-read-timed-out

**Comment by daniloercoli** [comment]
Closing this issue for now, since I'm not seeing it anymore on testing devices.
