### ISSUE TITLE
Crash report 7.0-rc-1: NPE in ReaderPostListFragment.blockBlogForPost

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5420]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
       at org.wordpress.android.ui.reader.ReaderPostListFragment.blockBlogForPost(ReaderPostListFragment.java:805)
       at org.wordpress.android.ui.reader.ReaderPostListFragment.access$3900(ReaderPostListFragment.java:85)
       at org.wordpress.android.ui.reader.ReaderPostListFragment$16.onItemClick(ReaderPostListFragment.java:1524)
       at android.widget.AdapterView.performItemClick(AdapterView.java:346)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1577)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3970)
       at android.widget.AbsListView$7.run(AbsListView.java:6065)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7409)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by aforcier** [comment]
Fixed in #5421.
