### ISSUE TITLE
Crash report 6.9: RuntimeException in MediaUtils.getVideoDurationMS

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5431]
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=6000, result=6001, data=Intent { (has extras) }} to activity {org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3783)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3826)
       at android.app.ActivityThread.access$1300(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by java.lang.RuntimeException: setDataSource failed: status = 0x80000000
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java)
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:165)
       at org.wordpress.android.util.MediaUtils.getVideoDurationMS(MediaUtils.java:368)
       at org.wordpress.android.util.MediaUtils.getVideoDurationMS(MediaUtils.java:359)
       at org.wordpress.android.util.AnalyticsUtils.getMediaProperties(AnalyticsUtils.java:396)
       at org.wordpress.android.ui.posts.EditPostActivity.trackAddMediaFromDeviceEvents(EditPostActivity.java:1558)
       at org.wordpress.android.ui.posts.EditPostActivity.addMediaVisualEditor(EditPostActivity.java:1634)
       at org.wordpress.android.ui.posts.EditPostActivity.addMedia(EditPostActivity.java:1598)
       at org.wordpress.android.ui.posts.EditPostActivity.handleMediaSelectionResult(EditPostActivity.java:1827)
       at org.wordpress.android.ui.posts.EditPostActivity.onActivityResult(EditPostActivity.java:1674)
       at android.app.Activity.dispatchActivityResult(Activity.java:6243)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3779)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3826)
       at android.app.ActivityThread.access$1300(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
```

**Comment by aforcier** [comment]
Fixed in #5433.
