### ISSUE TITLE
Crash report 7.0-rc-2: NPE in EditPostActivity.onCreate

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5447]
```
Caused by java.lang.NullPointerException
       at org.wordpress.android.ui.posts.EditPostActivity.onCreate(EditPostActivity.java:292)
       at android.app.Activity.performCreate(Activity.java:5133)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniloercoli** [comment]
Fixed in #5448
