### ISSUE TITLE
Crash while using CursorAdapter's swapCursor

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#5457]
```
Fatal Exception: java.lang.IllegalStateException: Observer android.support.v4.widget.CursorAdapter$ChangeObserver@3863bfb3 is already registered.
       at android.database.Observable.registerObserver(Observable.java:49)
       at android.database.ContentObservable.registerObserver(ContentObservable.java:32)
       at android.database.AbstractCursor.registerContentObserver(AbstractCursor.java:313)
       at android.support.v4.widget.CursorAdapter.swapCursor(CursorAdapter.java:360)
       at android.support.v4.widget.CursorAdapter.changeCursor(CursorAdapter.java:333)
       at android.support.v4.widget.CursorFilter.publishResults(CursorFilter.java:68)
       at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6917)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by designsimply** [comment]
I searched for crash reports mentioning `swapCursor` in both Fabric and Sentry and could not find a matching report. 

I found a mention of someone on StackOverflow solving a similar-sounding problem at https://stackoverflow.com/a/17425361/1100719, however, I feel we can lower priority since the crash report is quite old and I don't see any subsequent reports of it or crash reports. It's also worth noting that if the crash continues and we do find it in logs but with a different keyword then it should get reported separately as part of regular crash monitoring by our release management team. @oguzkocer I'm going to close this issue with an ask that you just re-open if you think it needs further review.
