### ISSUE TITLE
Crash report 7.0-rc-4: NPE in MagicLinkRequestFragment$5.onErrorResponse

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5517]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
       at android.support.design.widget.Snackbar.make(Snackbar.java:165)
       at org.wordpress.android.ui.accounts.login.MagicLinkRequestFragment$5.onErrorResponse(MagicLinkRequestFragment.java:153)
       at com.android.volley.Request.deliverError(Request.java:590)
       at com.wordpress.rest.RestRequest.deliverError(RestRequest.java:87)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5425)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:928)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:723)
```

**Comment by aforcier** [comment]
Fixed in #5523.
