### ISSUE TITLE
Crash in MediaGridFragment caused by CursorWindowAllocationException

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#5541]
```
Fatal Exception: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
       at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=634 (# cursors opened by this proc=634)
       at android.database.CursorWindow.<init>(CursorWindow.java:108)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:300)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
       at android.database.CursorWrapper.getCount(CursorWrapper.java:60)
       at org.wordpress.android.ui.media.MediaGridFragment.updateFilterText(MediaGridFragment.java:360)
       at org.wordpress.android.ui.media.MediaGridFragment.refreshMediaFromDB(MediaGridFragment.java:286)
       at org.wordpress.android.ui.media.MediaBrowserActivity.updateViews(MediaBrowserActivity.java:945)
       at org.wordpress.android.ui.media.MediaBrowserActivity.onMediaUploaded(MediaBrowserActivity.java:578)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by nbradbury** [comment]
This shouldn't be an issue now that we've dropped the cursor from the media browser.

**Comment by daniloercoli** [comment]
Ok, I'm closing this issue then.
