### ISSUE TITLE
Crash when adding an image from the gallery

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#5551]
```
java.lang.IndexOutOfBoundsException: setSpan (1 ... 2) ends beyond length 1
at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
at org.wordpress.aztec.formatting.LineBlockFormatter.insertMedia(LineBlockFormatter.kt:146)
at org.wordpress.aztec.AztecText.insertMedia(AztecText.kt:972)
at org.wordpress.android.editor.AztecEditorFragment.appendMediaFile(AztecEditorFragment.java:466)
at org.wordpress.android.ui.posts.EditPostActivity.addMediaVisualEditor(EditPostActivity.java:1716)
at org.wordpress.android.ui.posts.EditPostActivity.addMedia(EditPostActivity.java:1688)
at org.wordpress.android.ui.posts.EditPostActivity.onPhotoPickerMediaChosen(EditPostActivity.java:618)
at org.wordpress.android.ui.photopicker.PhotoPickerFragment$4.onItemTapped(PhotoPickerFragment.java:133)
```

Reproduced on WP alpha-45 with Aztec v0.5.0-alpha.4

**Comment by catehstn** [comment]
This makes the current alpha unusable - is there an ETA on fixing it?

**Comment by 0nko** [comment]
I'll try to have it ready for the next alpha release.

**Comment by lancewillett** [comment]
I ran into this today in the Android app version alpha-45

0. Make sure Aztec editor is turned on in settings.
1. Create a new post.
2. Click the "add media" button in the editor toolbar.
3. Click on an image to add to the post
4. App crashes.

I sent my crash log just now via the app.

**Comment by designsimply** [comment]
Tested using WP Desktop alpha-45 and was unable to reproduce the problem ([screenshot](https://cloud.githubusercontent.com/assets/1119271/24678118/91da67f2-1946-11e7-8109-e7d54d44a6a9.png)).

**Comment by supernovia** [comment]
I've also reproduced this in alpha-45. I did notice the media is added to the library, just not to the post.

**Comment by mzorz** [comment]
Managed to repro this if the first action you take on a new post is just try to add the media on the first line, without entering any text. If you do enter some text, it does not crash.

**Comment by 0nko** [comment]
The problem was identified and fixed. Stay put for the next alpha release :).

**Comment by mzorz** [comment]
🙇 thank you @0nko !

**Comment by designsimply** [comment]
@0nko, which number release will have the fix? I just tested again based on mzorz's instructions ^ and and was able to crash the app while testing with `alpha-46`.

**Comment by supernovia** [comment]
I also have that crash on alpha-46

**Comment by 0nko** [comment]
What instructions are you referring to? The new Aztec release is included in the `alpha-47` build.

**Comment by lancewillett** [comment]
I haven't seen alpha-47 build come through yet to my phone.

**Comment by mzorz** [comment]
> I haven't seen alpha-47 build come through yet to my phone.

Hi @lancewillett - it's been pushed to full rollout about 3 hours ago, so I guess it should reach everyone shortly if not already

**Comment by designsimply** [comment]
Re-tested with `alpha-49` and was unable to reproduce. LGTM 👍

**Comment by lancewillett** [comment]
Same here — testing again with `alpha-49` and works as expected. 🔆

**Comment by 0nko** [comment]
Woohoo! :smile:
