### ISSUE TITLE
Crash report 7.0: NPE in MixpanelAPI.alias

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5554]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.mixpanel.android.mpmetrics.MixpanelAPI.alias(MixpanelAPI.java:347)
       at org.wordpress.android.analytics.AnalyticsTrackerMixpanel.refreshMetadata(AnalyticsTrackerMixpanel.java:195)
       at org.wordpress.android.analytics.AnalyticsTracker.refreshMetadata(AnalyticsTracker.java:307)
       at org.wordpress.android.util.AnalyticsUtils.refreshMetadataNewUser(AnalyticsUtils.java:80)
       at org.wordpress.android.ui.accounts.NewUserFragment.fetchSiteAndAccount(NewUserFragment.java:612)
       at org.wordpress.android.ui.accounts.NewUserFragment.onNewSiteCreated(NewUserFragment.java:694)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by oguzkocer** [comment]
Fixed in #5555
