### ISSUE TITLE
Crash report 7.1-rc-1: Vector drawables and Android 4.x

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5560]
We can't use vector drawables in `android:drawableRight` on Android < 5.0

```
Fatal Exception: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at org.wordpress.android.ui.FilteredRecyclerView$SpinnerAdapter.getView(FilteredRecyclerView.java:413)
       at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
       at android.widget.Spinner.onMeasure(Spinner.java:482)
       at android.support.v7.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:416)
       at android.view.View.measure(View.java:16505)
       at android.support.v7.widget.Toolbar.measureChildCollapseMargins(Toolbar.java:1549)
       at android.support.v7.widget.Toolbar.onMeasure(Toolbar.java:1657)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.support.design.widget.AppBarLayout.onMeasure(AppBarLayout.java:222)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
       at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:1036)
       at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:766)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1921)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1115)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1300)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5679)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5055)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at org.wordpress.android.ui.FilteredRecyclerView$SpinnerAdapter.getView(FilteredRecyclerView.java:413)
       at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
       at android.widget.Spinner.onMeasure(Spinner.java:482)
       at android.support.v7.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:416)
       at android.view.View.measure(View.java:16505)
       at android.support.v7.widget.Toolbar.measureChildCollapseMargins(Toolbar.java:1549)
       at android.support.v7.widget.Toolbar.onMeasure(Toolbar.java:1657)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.support.design.widget.AppBarLayout.onMeasure(AppBarLayout.java:222)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
       at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:1036)
       at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:766)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1921)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1115)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1300)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5679)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5055)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.content.res.Resources$NotFoundException: File res/drawable/ic_dropdown_blue_light_24dp.xml from drawable resource ID #0x7f020168
       at android.content.res.Resources.loadDrawable(Resources.java:2115)
       at android.content.res.Resources.loadDrawable(Resources.java:2046)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.widget.TextView.<init>(TextView.java:814)
       at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
       at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
       at org.wordpress.android.widgets.WPTextView.<init>(WPTextView.java:25)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at org.wordpress.android.ui.FilteredRecyclerView$SpinnerAdapter.getView(FilteredRecyclerView.java:413)
       at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
       at android.widget.Spinner.onMeasure(Spinner.java:482)
       at android.support.v7.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:416)
       at android.view.View.measure(View.java:16505)
       at android.support.v7.widget.Toolbar.measureChildCollapseMargins(Toolbar.java:1549)
       at android.support.v7.widget.Toolbar.onMeasure(Toolbar.java:1657)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.support.design.widget.AppBarLayout.onMeasure(AppBarLayout.java:222)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
       at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:1036)
       at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:766)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1921)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1115)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1300)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5679)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5055)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
       at android.content.res.Resources.loadDrawable(Resources.java:2111)
       at android.content.res.Resources.loadDrawable(Resources.java:2046)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.widget.TextView.<init>(TextView.java:814)
       at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
       at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
       at org.wordpress.android.widgets.WPTextView.<init>(WPTextView.java:25)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at org.wordpress.android.ui.FilteredRecyclerView$SpinnerAdapter.getView(FilteredRecyclerView.java:413)
       at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
       at android.widget.Spinner.onMeasure(Spinner.java:482)
       at android.support.v7.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:416)
       at android.view.View.measure(View.java:16505)
       at android.support.v7.widget.Toolbar.measureChildCollapseMargins(Toolbar.java:1549)
       at android.support.v7.widget.Toolbar.onMeasure(Toolbar.java:1657)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.support.design.widget.AppBarLayout.onMeasure(AppBarLayout.java:222)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
       at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:1036)
       at android.support.design.widget.AppBarLayout$Behavior.onMeasureChild(AppBarLayout.java:766)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
       at android.view.View.measure(View.java:16505)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5134)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
       at android.view.View.measure(View.java:16505)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1921)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1115)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1300)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5679)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5055)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Reported on Android 4.x

**Comment by tonyr59h** [comment]
Note: Check if we can use `drawableRight` (without `android:`) to support pre-5.0 APIs.

**Comment by tonyr59h** [comment]
[This workaround](http://stackoverflow.com/questions/35761636/is-it-possible-to-use-vectordrawable-in-buttons-and-textviews-using-androiddraw) has been implemented in `WPTextView` with no issues. We'll have to create custom `View`'s for `CheckBox` and any other layout views that use `drawable*` to ensure this issue doesn't pop up again.
