### ISSUE TITLE
Crash Report 7.1 - java.lang.NumberFormatException: Invalid float in vector drawable

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5632]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.prefs.notifications.NotificationsSettingsActivity}: android.content.res.Resources$NotFoundException: File res/drawable/ic_mail_grey_24dp.xml from drawable resource ID #0x7f020193
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
       at android.app.ActivityThread.access$800(ActivityThread.java:148)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5272)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
Caused by android.content.res.Resources$NotFoundException: File res/drawable/ic_mail_grey_24dp.xml from drawable resource ID #0x7f020193
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2469)
       at android.content.res.Resources.loadDrawable(Resources.java:2371)
       at android.content.res.Resources.getDrawable(Resources.java:771)
       at android.content.Context.getDrawable(Context.java:402)
       at android.preference.Preference.setIcon(Preference.java:701)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.addPreferencesForPreferenceScreen(NotificationsSettingsFragment.java:407)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.configureBlogsSettings(NotificationsSettingsFragment.java:331)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.loadNotificationsAndUpdateUI(NotificationsSettingsFragment.java:255)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.onActivityCreated(NotificationsSettingsFragment.java:100)
       at android.app.Fragment.performActivityCreated(Fragment.java:2070)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:912)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.app.BackStackRecord.run(BackStackRecord.java:833)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
       at android.app.Activity.performStart(Activity.java:5992)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2268)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
       at android.app.ActivityThread.access$800(ActivityThread.java:148)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5272)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
Caused by java.lang.NumberFormatException: Invalid float: "1.105.895"
       at java.lang.StringToReal.invalidReal(StringToReal.java:63)
       at java.lang.StringToReal.initialParse(StringToReal.java:160)
       at java.lang.StringToReal.parseFloat(StringToReal.java:323)
       at java.lang.Float.parseFloat(Float.java:306)
       at android.util.PathParser.getFloats(PathParser.java:178)
       at android.util.PathParser.createNodesFromPathData(PathParser.java:59)
       at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1439)
       at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
       at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
       at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2459)
       at android.content.res.Resources.loadDrawable(Resources.java:2371)
       at android.content.res.Resources.getDrawable(Resources.java:771)
       at android.content.Context.getDrawable(Context.java:402)
       at android.preference.Preference.setIcon(Preference.java:701)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.addPreferencesForPreferenceScreen(NotificationsSettingsFragment.java:407)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.configureBlogsSettings(NotificationsSettingsFragment.java:331)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.loadNotificationsAndUpdateUI(NotificationsSettingsFragment.java:255)
       at org.wordpress.android.ui.prefs.notifications.NotificationsSettingsFragment.onActivityCreated(NotificationsSettingsFragment.java:100)
       at android.app.Fragment.performActivityCreated(Fragment.java:2070)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:912)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.app.BackStackRecord.run(BackStackRecord.java:833)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
       at android.app.Activity.performStart(Activity.java:5992)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2268)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
       at android.app.ActivityThread.access$800(ActivityThread.java:148)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5272)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

```

**Comment by mzorz** [comment]
this is the cause and solution http://stackoverflow.com/questions/27561170/vectordrawable-causes-numberformatexception thanks @tonyr59h 🙇

**Comment by tonyr59h** [comment]
Address in #5637, closing.
