### ISSUE TITLE
Crash report 7.1: null payload passed to SiteActionBuilder.newCreateNewSiteAction

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5641]
```
Fatal Exception: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
       at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.wordpress.android.fluxc.store.SiteStore$NewSitePayload.siteName' on a null object reference
       at org.wordpress.android.fluxc.store.SiteStore.createNewSite(SiteStore.java:685)
       at org.wordpress.android.fluxc.store.SiteStore.onAction(SiteStore.java:639)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by aforcier** [comment]
Looks like this one was fixed by https://github.com/wordpress-mobile/WordPress-Android/pull/5718 - since that PR, all uses of `SiteActionBuilder.newCreateNewSiteAction()` use a freshly created payload that can't be `null`.
