### ISSUE TITLE
Crash report 7.1: NPE in NotificationsDetailActivity.onStart

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5646]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.notifications.NotificationsDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.ui.notifications.NotificationsDetailActivity$NotificationDetailFragmentAdapter.getCount()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6247)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.ui.notifications.NotificationsDetailActivity$NotificationDetailFragmentAdapter.getCount()' on a null object reference
       at org.wordpress.android.ui.notifications.NotificationsDetailActivity.onStart(NotificationsDetailActivity.java:220)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
       at android.app.Activity.performStart(Activity.java:6774)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2689)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6247)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by mzorz** [comment]
closed via #5652
