### ISSUE TITLE
Crash Report 7.1: notifications - unable to expand RemoteView

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5648]
``` 
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package org.wordpress.android: Couldn't expand RemoteViews for: StatusBarNotification(pkg=org.wordpress.android user=UserHandle{11} id=30000 tag=null score=0: Notification(pri=0 icon=7f020196 contentView=org.wordpress.android/0x109007f vibrate=null sound=null defaults=0x0 flags=0x11 when=1492112275932 ledARGB=0xff0000ff contentIntent=Y deleteIntent=Y contentTitle=11 contentText=124 tickerText=124 kind=[null] 2 actions))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Logs say:

```2    |    21:52:01:380    |    D/CrashlyticsCore e/WordPress-NOTIFS: Can't parse the Note JSON received in the PN ```

**Comment by mzorz** [comment]
```	D/CrashlyticsCore e/WordPress-NOTIFS: Can't parse the Note JSON received in the PN - exception: Unterminated string at character 4096 of ...```

```D/CrashlyticsCore w/WordPress-NOTIFS: Cannot build the Note object by using info available in the PN payload. Please see previous log messages for detailed information about the error.```

**Comment by mzorz** [comment]
I love it when logs provide useful information:

```ERROR|04-17 17:06:50.784|709|709||StatusBar|couldn't inflate view for notification org.wordpress.android/0x7530
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at java.lang.reflect.Method.invoke(Method.java:515)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at android.os.Looper.loop(Looper.java:146)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
DEBUG|04-17 17:06:50.784|555|555||NotificationService|cancelNotificationLocked: cancel alarm
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at dalvik.system.NativeStart.main(Native Method)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at android.widget.RemoteViews.apply(RemoteViews.java:2921)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	... 20 more
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at com.android.systemui.statusbar.phone.PhoneStatusBar.addNotification(PhoneStatusBar.java:1527)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at android.app.ActivityThread.main(ActivityThread.java:5598)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at android.content.res.Resources.loadDrawable(Resources.java:3442)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at android.content.res.Resources.getDrawable(Resources.java:1924)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at com.android.systemui.statusbar.BaseStatusBar.inflateViews(BaseStatusBar.java:880)
DEBUG|04-17 17:06:50.784|555|555||NotificationService| has clearable items no 
ERROR|04-17 17:06:50.784|709|709||StatusBar|android.content.res.Resources$NotFoundException: File res/drawable/ic_reply_grey_32dp.xml from drawable resource ID #0x7f0201b9
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at java.lang.reflect.Method.invokeNative(Native Method)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at com.android.systemui.statusbar.BaseStatusBar.createNotificationViews(BaseStatusBar.java:1090)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at android.os.Handler.dispatchMessage(Handler.java:102)
ERROR|04-17 17:06:50.784|709|709||StatusBar|Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
DEBUG|04-17 17:06:50.784|555|1462||NotificationService|onNotification error pkg=org.wordpress.android tag=null id=30000; will crashApplication(uid=10195, pid=4736)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at android.widget.RemoteViews.performApply(RemoteViews.java:2962)
DEBUG|04-17 17:06:50.784|555|555||STATUSBAR-StatusBarManagerService|sendNotification(3) - 30000
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at android.widget.RemoteViews.performApply(RemoteViews.java:2962)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:419)
ERROR|04-17 17:06:50.784|709|709||StatusBar|	at android.widget.RemoteViews$TextViewDrawableAction.apply(RemoteViews.java:1492)
```

We were  still using vector drawables in `Quick actions` for notifications. Continuing the patch for this in #5635
