### ISSUE TITLE
Crash report 7.0: NPE in SmartLockHelper.saveCredentialsInSmartLock

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5658]
```
Fatal Exception: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
       at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5401)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)
Caused by java.lang.NullPointerException: credential identifier cannot be null
       at com.google.android.gms.common.internal.zzaa.zzb(Unknown Source)
       at com.google.android.gms.auth.api.credentials.Credential.<init>(Unknown Source)
       at com.google.android.gms.auth.api.credentials.Credential$Builder.build(Unknown Source)
       at org.wordpress.android.ui.accounts.SmartLockHelper.saveCredentialsInSmartLock(SmartLockHelper.java:113)
       at org.wordpress.android.ui.accounts.NewUserFragment.fetchSiteAndAccount(NewUserFragment.java:612)
       at org.wordpress.android.ui.accounts.NewUserFragment.onNewSiteCreated(NewUserFragment.java:689)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5401)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)
```

**Comment by maxme** [comment]
Bumping this one to 7.3, this needs some bigger changes (state saving) also this migth be the problem behind the analytics issue we were seeing in https://github.com/wordpress-mobile/WordPress-Android/pull/5626
