### ISSUE TITLE
Crash report in 7.1: NPE in MediaXMLRPCClient.uploadMedia

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5659]
```
Fatal Exception: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
       at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: username == null
       at okhttp3.HttpUrl$Builder.username(HttpUrl.java:963)
       at org.wordpress.android.fluxc.network.xmlrpc.media.MediaXMLRPCClient.uploadMedia(MediaXMLRPCClient.java:136)
       at org.wordpress.android.fluxc.store.MediaStore.performUploadMedia(MediaStore.java:519)
       at org.wordpress.android.fluxc.store.MediaStore.onAction(MediaStore.java:252)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by maxme** [comment]
I'm 99% sure this is due to a migration quirk and this will less and less happen to the point it won't happen (we'll drop migration in a couple of month).

**Comment by tonyr59h** [comment]
This doesn't appear to be happening anymore, can't find any crash reports for it at least. Time to close the issue?

**Comment by rachelmcr** [comment]
Closing this issue as I can't any crash reports for this; we can reopen if the crash reappears.
