### ISSUE TITLE
Crash report in 7.0: IndexOutOfBoundsException: Inconsistency detected

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5660]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 6(offset:6).state:10
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5456)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3535)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3264)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2722)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2552)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2255)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6708)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
       at android.view.Choreographer.doCallbacks(Choreographer.java:696)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5683)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by hypest** [comment]
Judging from the Fabric reports, this might be happening while on the site picker and while fetching network data.

**Comment by khaykov** [comment]
Reopening this one as it still happens in 8.1

**Comment by khaykov** [comment]
Ah, my bad, I noticed that 8.1 still does not have this one.

**Comment by elibud** [comment]
Reopening as 8.3.1 has this crash again.

**Comment by rachelmcr** [comment]
Closing as I can't find any recent crash reports for this. Please reopen if I'm missing something.
