### ISSUE TITLE
Crash report on 7.0: IllegalStateException in SignInActivity

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5661]
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
       at android.support.v4.app.FragmentManagerImpl.popBackStack(FragmentManager.java:770)
       at org.wordpress.android.ui.accounts.SignInActivity.popBackStackToSignInFragment(SignInActivity.java:203)
       at org.wordpress.android.ui.accounts.SignInActivity.onEnterPasswordRequested(SignInActivity.java:270)
       at org.wordpress.android.ui.accounts.login.MagicLinkRequestFragment$5.onErrorResponse(MagicLinkRequestFragment.java:157)
       at com.android.volley.Request.deliverError(Request.java:590)
       at com.wordpress.rest.RestRequest.deliverError(RestRequest.java:87)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5727)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

**Comment by maxme** [comment]
Reopening, this is not fixed (reproduced in latest 7.7.1)

**Comment by mzorz** [comment]
@hypest what do you think,  is this something that can be closed now that the new login flow is in place?
