### ISSUE TITLE
Crash report on may versions: IAE in sanitizeSiteUrl

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5667]
```
Fatal Exception: java.lang.IllegalArgumentException: U_STRINGPREP_PROHIBITED_ERROR
       at libcore.icu.NativeIDN.convertImpl(NativeIDN.java)
       at libcore.icu.NativeIDN.convert(NativeIDN.java:39)
       at libcore.icu.NativeIDN.toASCII(NativeIDN.java:21)
       at java.net.IDN.toASCII(IDN.java:64)
       at org.wordpress.android.util.UrlUtils.convertUrlToPunycodeIfNeeded(UrlUtils.java:61)
       at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder.sanitizeSiteUrl(SelfHostedEndpointFinder.java:347)
       at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder.verifyOrDiscoverXMLRPCEndpoint(SelfHostedEndpointFinder.java:129)
       at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder.access$100(SelfHostedEndpointFinder.java:40)
       at org.wordpress.android.fluxc.network.discovery.SelfHostedEndpointFinder$1.run(SelfHostedEndpointFinder.java:108)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by tonyr59h** [comment]
Closed via #5840
