### ISSUE TITLE
Crash report on many versions: RuntimeException: Could not read input channel file descriptors from parcel.

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5671]
```
Fatal Exception: java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
       at android.view.InputChannel.nativeReadFromParcel(InputChannel.java)
       at android.view.InputChannel.readFromParcel(InputChannel.java:148)
       at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
       at android.view.InputChannel$1.createFromParcel(InputChannel.java:37)
       at com.android.internal.view.InputBindResult.<init>(InputBindResult.java:68)
       at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:112)
       at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:111)
       at com.android.internal.view.IInputMethodManager$Stub$Proxy.startInputOrWindowGainedFocus(IInputMethodManager.java:838)
       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1723)
       at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:2027)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4046)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by designsimply** [comment]
I searched for "Could not read input channel file descriptors from parcel" and found several questions and answers about that topic in StackOverflow posted in 2015. Here are a couple of the cases and solutions outlined (they may not match exactly with this case but might also provide some insight):

* "You must have something still running in memory that you have now run twice." "I forgot to run cleanup on the SoundManager." [#](https://stackoverflow.com/a/24156985/1100719)
* "The fix for that particular situation was very easy: just preload all sounds as it's suggested in Android documentation." [#](https://stackoverflow.com/a/27812617/1100719)
* "In this case, the workaround is very simple: DO NOT call append on textview directly, use `StringBuilder` or `SpannableStringBuilder` to build text and call `TextView.setText(text)` instead!" [#](https://stackoverflow.com/a/36205108/1100719)
* "I caused this by building a custom alert dialog (containing multiple `TextView` objects) inside of a `while` loop vice an `if` statement. The application crashed before displaying the dialog box(es)." [#](https://stackoverflow.com/a/42013329/1100719)
* "I had same error. It absolutely disappeared after I cleaned all the memory leaks." "For searching some leaks I used Memory Analysis perspective in Eclipse." [#](https://stackoverflow.com/a/29508653/1100719)

Note: I am lowering this issue in priority because it was reported over 2 years ago and hasn't had any activity since and because I didn't see any new crash reports mentioning `parcel` in a search of recent crash reports.

**Comment by designsimply** [comment]
**30-day impact:** 3 in the last 30d
**Users affected:** 1 in the last 30d
**Last seen in:** 12.6

<sup>https://sentry.io/share/issue/a10452d5ab4547b0a700a71ec31c7340/</sup>

**Comment by designsimply** [comment]
Moving to the Prioritized Android list in Groundskeeping as a candidate for closing. Please do a quick check in Sentry to see if you can find anything related and close it if you cannot. I searched for a related crash and couldn't find any!

**Comment by JavonDavis** [comment]
I've attached linked the latest one in Sentry here, the last crash happened 17 days ago and only affected 1 user and in total there's been ~5 crashes in the last 90 days. Think it's safe to close this one out IMO or wait one more cycle if we want to make sure we're all good.

**Comment by malinajirka** [comment]
I've double checked Sentry and it seems like a very low priority issue => closing.
