### ISSUE TITLE
Crash report on 7.0: SecurityException in MediaBrowserActivity

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5672]
http://crashes.to/s/b9794b57ed9

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.SecurityException: Permission Denial: reading com.google.android.apps.docs.storagebackend.StorageBackendContentProvider uri content://com.google.android.apps.docs.storage/document/acc%3D2%3Bdoc%3D6794 from pid=28526, uid=10163 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
       at android.os.Parcel.readException(Parcel.java:1546)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
       at android.content.ContentResolver.query(ContentResolver.java:485)
       at android.content.ContentResolver.query(ContentResolver.java:429)
       at org.wordpress.android.util.MediaUtils.getFilenameFromURI(MediaUtils.java:183)
       at org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:232)
       at org.wordpress.android.ui.media.MediaBrowserActivity$6.doInBackground(MediaBrowserActivity.java:778)
       at org.wordpress.android.ui.media.MediaBrowserActivity$6.doInBackground(MediaBrowserActivity.java:774)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by daniloercoli** [comment]
Do we have some more info about this issue - Device(s)/Android Version(s)? 
I'm unable to reproduce it on Android API 21 (5.0.2) or Android API 25 (7.1.2).

**Comment by hypest** [comment]
Thanks for looking into this @daniloercoli . I've updated the ticket description with a link to the crash report.

**Comment by mzorz** [comment]
Closing via #5827
