### ISSUE TITLE
Crash report on many versions: ClassCastExceptionEditorWebViewCompatibility cannot be cast to EditableWebView

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5675]
```
Fatal Exception: java.lang.ClassCastException: org.wordpress.android.editor.EditorWebViewCompatibility cannot be cast to android.webkit.EditableWebView
       at android.webkit.EditableSelectActionModeCallback.setWebView(EditableSelectActionModeCallback.java:215)
       at android.webkit.WebViewClassic.startSelectActionMode(WebViewClassic.java:7576)
       at android.webkit.WebViewClassic.setupWebkitSelect(WebViewClassic.java:7745)
       at android.webkit.WebViewClassic.setupWebkitSelect(WebViewClassic.java:7735)
       at android.webkit.WebViewClassic.updateTextSelectionFromMessage(WebViewClassic.java:11441)
       at android.webkit.WebViewClassic.access$5300(WebViewClassic.java:198)
       at android.webkit.WebViewClassic$PrivateHandler.handleMessage(WebViewClassic.java:10403)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5511)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniloercoli** [comment]
Crash happens only on *4.1.1* - *HTC devices only*

HTC One S 54%
KDDI Infobar A02 23%
HTC Butterfly 14%
One XL  9%

**Comment by aforcier** [comment]
I think we can call this a wontfix, those devices will be able to use Aztec instead soon enough, and I'm not sure it's worth the time to deal with whatever HTC did to the system WebView on API16.

If you agree with that we can close this @daniloercoli.
