### ISSUE TITLE
Crash report on 7.1: InvalidClassException: fluxc.model.SiteModel; Incompatible class (SUID)

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5677]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.RuntimeException: Parcelable encountered IOException reading a Serializable object (name = org.wordpress.android.fluxc.model.SiteModel)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.RuntimeException: Parcelable encountered IOException reading a Serializable object (name = org.wordpress.android.fluxc.model.SiteModel)
       at android.os.Parcel.readSerializable(Parcel.java:2508)
       at android.os.Parcel.readValue(Parcel.java:2315)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.BaseBundle.getSerializable(BaseBundle.java:992)
       at android.os.Bundle.getSerializable(Bundle.java:880)
       at android.content.Intent.getSerializableExtra(Intent.java:6253)
       at org.wordpress.android.ui.posts.EditPostActivity.onCreate(EditPostActivity.java:255)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.io.InvalidClassException: org.wordpress.android.fluxc.model.SiteModel; Incompatible class (SUID): org.wordpress.android.fluxc.model.SiteModel: static final long serialVersionUID =464004224496784103L; but expected org.wordpress.android.fluxc.model.SiteModel: static final long serialVersionUID =7223616871655133993L;
       at java.io.ObjectInputStream.verifyAndInit(ObjectInputStream.java:2336)
       at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1643)
       at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:657)
       at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1782)
       at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
       at android.os.Parcel.readSerializable(Parcel.java:2506)
       at android.os.Parcel.readValue(Parcel.java:2315)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
       at android.os.BaseBundle.unparcel(BaseBundle.java:221)
       at android.os.BaseBundle.getSerializable(BaseBundle.java:992)
       at android.os.Bundle.getSerializable(Bundle.java:880)
       at android.content.Intent.getSerializableExtra(Intent.java:6253)
       at org.wordpress.android.ui.posts.EditPostActivity.onCreate(EditPostActivity.java:255)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by hypest** [comment]
Different crash report but most probably related:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.stats.StatsActivity}: java.lang.RuntimeException: Parcelable encountered IOException reading a Serializable object (name = org.wordpress.android.fluxc.model.SiteModel)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2680)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6176)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by java.lang.RuntimeException: Parcelable encountered IOException reading a Serializable object (name = org.wordpress.android.fluxc.model.SiteModel)
       at android.os.Parcel.readSerializable(Parcel.java:2626)
       at android.os.Parcel.readValue(Parcel.java:2416)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
       at android.os.BaseBundle.unparcel(BaseBundle.java:269)
       at android.os.BaseBundle.getSerializable(BaseBundle.java:1064)
       at android.os.Bundle.getSerializable(Bundle.java:958)
       at android.content.Intent.getSerializableExtra(Intent.java:6362)
       at org.wordpress.android.ui.stats.StatsActivity.onCreate(StatsActivity.java:116)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6176)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by java.io.InvalidClassException: org.wordpress.android.fluxc.model.SiteModel; local class incompatible: stream classdesc serialVersionUID = 464004224496784103, local class serialVersionUID = 7223616871655133993
       at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:606)
       at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
       at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
       at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1772)
       at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
       at android.os.Parcel.readSerializable(Parcel.java:2624)
       at android.os.Parcel.readValue(Parcel.java:2416)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
       at android.os.BaseBundle.unparcel(BaseBundle.java:269)
       at android.os.BaseBundle.getSerializable(BaseBundle.java:1064)
       at android.os.Bundle.getSerializable(Bundle.java:958)
       at android.content.Intent.getSerializableExtra(Intent.java:6362)
       at org.wordpress.android.ui.stats.StatsActivity.onCreate(StatsActivity.java:116)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2633)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2741)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6176)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by hypest** [comment]
This crash has only happen once the last 3 months.

**Comment by designsimply** [comment]
Lowering in priority because of the infrequency and also the age of the original report.

**Comment by designsimply** [comment]
Note: I searched Sentry for `Parcelable encountered IOException reading a Serializable object` and couldn't find a matching issue. Is that the best way to search for this particular issue or would it be better to search for `InvalidClassException` which was noted in the issue title?

**Comment by hypest** [comment]
Not very familiar with Sentry yet but, I would probably try both @designsimply . At the end of the day, maybe the reason nothing comes up is because this issue is now rare enough that we haven't picked an instance yet (Sentry is only being used for 2-3 months at the time of writing?).

**Comment by malinajirka** [comment]
I think these reports are related to this ticket:
https://sentry.io/organizations/a8c/issues/1144715941
https://sentry.io/organizations/a8c/issues/1142619832
https://sentry.io/organizations/a8c/issues/1142619832
https://sentry.io/organizations/a8c/issues/1136532878
https://sentry.io/organizations/a8c/issues/1138802937
https://sentry.io/organizations/a8c/issues/1132809967
https://sentry.io/organizations/a8c/issues/1159410683

=> The crash is still very rare.


P.S. I searched for `Parcelable encountered IOException`. Sentry search works very randomly. Sometimes it doesn't find an obvious match.

**Comment by designsimply** [comment]
I merged the reports linked above into one at https://sentry.io/share/issue/64684fb8c6714643853679817c22504d/.

**Comment by designsimply** [comment]
**90-day impact:** 7
**Users affected in the last 90 days:** 7
**Last seen in:** 13.1

<sup>https://sentry.io/share/issue/64684fb8c6714643853679817c22504d/</sup>

Candidate for closure in the next Groundskeeping Android rotation.

**Comment by designsimply** [comment]
**90-day impact:** 8
**Users affected in the last 90 days:** 3
**Last seen in:** 13.5

<sup>https://sentry.io/share/issue/64684fb8c6714643853679817c22504d/</sup>

Still a candidate for closing.

**Comment by malinajirka** [comment]
This issue was most probably fixed as mentioned [here](https://github.com/wordpress-mobile/WordPress-Android/issues/5677#issuecomment-521944921). However, the PR hasn't been merged yet - it's pending review. I've pinged the reviewers and it'll hopefully get merged soon.
