### ISSUE TITLE
Crash on 7.1: RuntimeException: Canvas: trying to use a recycled bitmap in showNotificationForBuilder

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5679]
```
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4224fd30
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1084)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1139)
       at android.app.Notification$Builder.clipDrawIcon(Notification.java:1511)
       at android.app.Notification$Builder.setLargeIcon(Notification.java:1605)
       at android.support.v4.app.NotificationCompatKitKat$Builder.<init>(NotificationCompatKitKat.java:72)
       at android.support.v4.app.NotificationCompat$NotificationCompatImplKitKat.build(NotificationCompat.java:709)
       at android.support.v4.app.NotificationCompat$Builder.build(NotificationCompat.java:1745)
       at org.wordpress.android.push.GCMMessageService$NotificationHelper.showNotificationForBuilder(GCMMessageService.java:747)
       at org.wordpress.android.push.GCMMessageService$NotificationHelper.showGroupNotificationForBuilder(GCMMessageService.java:673)
       at org.wordpress.android.push.GCMMessageService$NotificationHelper.buildAndShowNotificationFromNoteData(GCMMessageService.java:447)
       at org.wordpress.android.push.GCMMessageService$NotificationHelper.handleDefaultPush(GCMMessageService.java:346)
       at org.wordpress.android.push.GCMMessageService$NotificationHelper.access$100(GCMMessageService.java:317)
       at org.wordpress.android.push.GCMMessageService.synchronizedHandleDefaultPush(GCMMessageService.java:113)
       at org.wordpress.android.push.GCMMessageService.onMessageReceived(GCMMessageService.java:150)
       at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)
```

**Comment by mzorz** [comment]
I've been trying to repro / understand this with no luck. I can see this potentially happening in `PostUploadNotifier` in https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/posts/services/PostUploadNotifier.java#L74 as it's being reused - we might copy the bitmap in that line as a workaround (although the bitmap itself will not be copied by `Bitmap.createBitmap(icon)` if the source is already an immutable image). 

As to how this happens here, will have to continue investigation.

Important note: this particular problem with the bitmap seems to only happen on Android 4.2.2, device TECNO-Y6 as reported.

**Comment by mzorz** [comment]
Also, this https://github.com/wordpress-mobile/WordPress-Android/issues/2858 is related, as per this discussion http://stackoverflow.com/questions/7988018/custom-notification-java-lang-runtimeexception-bad-array-lengths

**Comment by rachelmcr** [comment]
I can't find any crash reports for this issue anymore; please reopen if I've missed something.
