### ISSUE TITLE
Crash on 7.1: StringIndexOutOfBoundsException in media analytics

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5699]
http://crashes.to/s/d6873883e41

```
Fatal Exception: java.lang.RuntimeException: Unable to start service org.wordpress.android.ui.media.services.MediaUploadService@95d5ff7 with Intent { cmp=org.wordpress.android/.ui.media.services.MediaUploadService (has extras) }: java.lang.StringIndexOutOfBoundsException: length=54; regionStart=50; regionLength=-13
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3468)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6290)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by java.lang.StringIndexOutOfBoundsException: length=54; regionStart=50; regionLength=-13
       at java.lang.String.substring(String.java:1931)
       at java.net.DefaultFileNameMap.getContentTypeFor(DefaultFileNameMap.java:38)
       at sun.net.www.protocol.file.FileURLConnection.initializeHeaders(FileURLConnection.java:120)
       at sun.net.www.protocol.file.FileURLConnection.getHeaderField(FileURLConnection.java:146)
       at sun.net.www.URLConnection.getContentType(URLConnection.java:149)
       at org.wordpress.android.util.MediaUtils.getMediaFileMimeType(MediaUtils.java:316)
       at org.wordpress.android.util.AnalyticsUtils.getMediaProperties(AnalyticsUtils.java:347)
       at org.wordpress.android.ui.media.services.MediaUploadService.trackUploadMediaEvents(MediaUploadService.java:310)
       at org.wordpress.android.ui.media.services.MediaUploadService.uploadNextInQueue(MediaUploadService.java:158)
       at org.wordpress.android.ui.media.services.MediaUploadService.onStartCommand(MediaUploadService.java:95)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3451)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6290)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by daniloercoli** [comment]
Fixed in #5765
