### ISSUE TITLE
Crash on 7.1: NPE in getLaunchCameraIntent

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5700]
http://crashes.to/s/4e58f7af682

```
Fatal Exception: java.lang.NullPointerException
       at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:583)
       at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
       at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:399)
       at org.wordpress.android.ui.media.WordPressMediaUtils.getLaunchCameraIntent(WordPressMediaUtils.java:148)
       at org.wordpress.android.ui.media.WordPressMediaUtils.makePickOrCaptureIntent(WordPressMediaUtils.java:181)
       at org.wordpress.android.ui.media.WordPressMediaUtils.launchPictureLibraryOrCapture(WordPressMediaUtils.java:173)
       at org.wordpress.android.ui.main.MeFragment.askForCameraOrGallery(MeFragment.java:530)
       at org.wordpress.android.ui.main.MeFragment.access$100(MeFragment.java:84)
       at org.wordpress.android.ui.main.MeFragment$2.onClick(MeFragment.java:216)
       at android.view.View.performClick(View.java:4207)
       at android.view.View$PerformClick.run(View.java:17358)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5041)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by tonyr59h** [comment]
Fixed in #5747, closing.
