### ISSUE TITLE
Crash on 7.0: NPE in PostPreviewActivity.onResume

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5702]
http://crashes.to/s/4c6a3e19815

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.posts.PostPreviewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.PostModel.getId()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3527)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3558)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1526)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6145)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.PostModel.getId()' on a null object reference
       at org.wordpress.android.ui.posts.PostPreviewActivity.onResume(PostPreviewActivity.java:100)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1255)
       at android.app.Activity.performResume(Activity.java:6495)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3516)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3558)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1526)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6145)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by tonyr59h** [comment]
Closed via #5716
