### ISSUE TITLE
Crash on 7.0: NPE in saveMedia

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5703]
http://crashes.to/s/78734a12585

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.fluxc.model.MediaModel.setTitle(java.lang.String)' on a null object reference
       at org.wordpress.android.ui.media.MediaEditFragment.saveMedia(MediaEditFragment.java:214)
       at org.wordpress.android.ui.media.MediaEditFragment.onOptionsItemSelected(MediaEditFragment.java:316)
       at android.app.Fragment.performOptionsItemSelected(Fragment.java:2475)
       at android.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2186)
       at android.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:337)
       at android.app.Activity.onMenuItemSelected(Activity.java:3382)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
       at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
       at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
       at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
       at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
       at android.view.View.performClick(View.java:6205)
       at android.widget.TextView.performClick(TextView.java:11103)
       at android.view.View$PerformClick.run(View.java:23653)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by nbradbury** [comment]
The `MediaEditFragment` was rewritten as part of #5640 so this should not be an issue any more.

**Comment by mzorz** [comment]
It appeared in `7.2` and `7.2.1`, should be gone when `7.3` comes out
