### ISSUE TITLE
Crash on 7.0: ISE in getPostsForSite

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#5705]
http://crashes.to/s/cdb860f94f5

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
       at android.database.CursorWindow.getLong(CursorWindow.java:507)
       at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
       at com.yarolegovich.wellsql.SelectQuery.getAsModel(SelectQuery.java:154)
       at com.yarolegovich.wellsql.SelectQuery.getAsModel(SelectQuery.java:147)
       at org.wordpress.android.fluxc.persistence.PostSqlUtils.getPostsForSite(PostSqlUtils.java:79)
       at org.wordpress.android.fluxc.store.PostStore.getPostsForSite(PostStore.java:204)
       at org.wordpress.android.ui.posts.adapters.PostsListAdapter$LoadPostsTask.doInBackground(PostsListAdapter.java:698)
       at org.wordpress.android.ui.posts.adapters.PostsListAdapter$LoadPostsTask.doInBackground(PostsListAdapter.java:672)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by daniloercoli** [comment]
This seems to be an issue in FluxC. Reported it [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/466) and closing this.
