### ISSUE TITLE
Crash report 7.3-rc-1: NPE in MediaPreviewActivity.loadImage

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5746]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
       at org.wordpress.android.ui.media.MediaPreviewActivity.loadImage(MediaPreviewActivity.java:308)
       at org.wordpress.android.ui.media.MediaPreviewActivity.onCreate(MediaPreviewActivity.java:207)
       at android.app.Activity.performCreate(Activity.java:6948)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3042)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by daniloercoli** [comment]
Fixed in #5762
