### ISSUE TITLE
Crash report in 7.2: Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5773]
```
Fatal Exception: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
       at android.os.Handler.<init>(Handler.java:200)
       at android.os.Handler.<init>(Handler.java:114)
       at android.widget.Toast$TN.<init>(Toast.java:362)
       at android.widget.Toast.<init>(Toast.java:109)
       at android.widget.Toast.makeText(Toast.java:276)
       at org.wordpress.android.util.ToastUtils.showToast(ToastUtils.java:31)
       at org.wordpress.android.util.ToastUtils.showToast(ToastUtils.java:23)
       at org.wordpress.android.ui.posts.EditPostActivity$6.run(EditPostActivity.java:1210)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by aforcier** [comment]
Fixed in #5774.
