### ISSUE TITLE
Crash - NPE in 7.2: parcelable write on null

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5784]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.putParcelableArray(java.lang.String, android.os.Parcelable[])' on a null object reference
       at org.wordpress.android.ui.notifications.NotificationsDetailActivity$NotificationDetailFragmentAdapter.saveState(NotificationsDetailActivity.java:471)
       at android.support.v4.view.ViewPager.onSaveInstanceState(ViewPager.java:1465)
       at android.view.View.dispatchSaveInstanceState(View.java:16798)
       at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3445)
       at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3451)
       at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3451)
       at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3451)
       at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3451)
       at android.view.View.saveHierarchyState(View.java:16781)
       at com.android.internal.policy.PhoneWindow.saveHierarchyState(PhoneWindow.java:2187)
       at android.app.Activity.onSaveInstanceState(Activity.java:1572)
       at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:570)
       at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:509)
       at org.wordpress.android.ui.notifications.NotificationsDetailActivity.onSaveInstanceState(NotificationsDetailActivity.java:211)
       at android.app.Activity.performSaveInstanceState(Activity.java:1502)
       at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1308)
       at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:5008)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4286)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4345)
       at android.app.ActivityThread.-wrap28(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

```

**Comment by mzorz** [comment]
Closed via #5788
