### ISSUE TITLE
Crash report 7.2: NPE in PlanUpdateService

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5798]
```
Fatal Exception: java.lang.RuntimeException: Unable to start service org.wordpress.android.ui.plans.PlanUpdateService@41365be8 with Intent { cmp=org.wordpress.android/.ui.plans.PlanUpdateService }: java.lang.NullPointerException
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2608)
       at android.app.ActivityThread.access$1900(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at org.wordpress.android.ui.plans.PlanUpdateService.downloadAvailablePlansForSite(PlanUpdateService.java:125)
       at org.wordpress.android.ui.plans.PlanUpdateService.onStartCommand(PlanUpdateService.java:71)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2591)
       at android.app.ActivityThread.access$1900(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
````

**Comment by mzorz** [comment]
Closed via #5812
