### ISSUE TITLE
Crash report 7.2.1 - "NumberFormatException" in Visual Editor, onMediaRetryClicked

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5817]
```
Fatal Exception: java.lang.NumberFormatException: Invalid int: "zss_field_content"
       at java.lang.Integer.invalidInt(Integer.java:138)
       at java.lang.Integer.parse(Integer.java:375)
       at java.lang.Integer.parseInt(Integer.java:366)
       at java.lang.Integer.parseInt(Integer.java:332)
       at java.lang.Integer.valueOf(Integer.java:490)
       at org.wordpress.android.ui.posts.EditPostActivity.onMediaRetryClicked(EditPostActivity.java:2219)
       at org.wordpress.android.editor.EditorFragment.onMediaTapped(EditorFragment.java:1378)
       at org.wordpress.android.editor.JsCallbackReceiver.executeCallback(JsCallbackReceiver.java:160)
       at org.wordpress.android.editor.EditorWebViewAbstract$1.shouldOverrideUrlLoading(EditorWebViewAbstract.java:80)
       at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:274)
       at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:376)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4903)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
       at dalvik.system.NativeStart.main(NativeStart.java)

```

**Comment by mzorz** [comment]
adding logs:
```
140	|	06:34:01:459	|	D/CrashlyticsCore d/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
141	|	06:34:02:028	|	D/CrashlyticsCore d/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
142	|	06:34:02:589	|	D/CrashlyticsCore d/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
143	|	06:34:03:161	|	D/CrashlyticsCore d/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
144	|	06:34:05:781	|	D/CrashlyticsCore w/WordPress-MEDIA: error uploading media: Response{protocol=http/1.1, code=400, message=Bad Request, url=https://public-api.wordpress.com/rest/v1.1/sites/73148972/media/new/}
145	|	06:34:05:787	|	D/CrashlyticsCore d/WordPress-API: Dispatching action: MediaAction-UPLOADED_MEDIA
146	|	06:34:05:900	|	D/CrashlyticsCore w/WordPress-MEDIA: Error uploading media: Invalid response from the Jetpack site
147	|	06:34:05:901	|	D/CrashlyticsCore d/WordPress-API: Dispatching action: MediaAction-UPDATE_MEDIA
148	|	06:34:05:910	|	D/CrashlyticsCore v/WordPress-MEDIA: No more media items to upload. Skipping this request - MediaUploadService.
149	|	06:34:05:910	|	D/CrashlyticsCore i/WordPress-MEDIA: Media Upload Service > completed
150	|	06:34:05:915	|	D/CrashlyticsCore i/WordPress-MEDIA: No more items pending in queue. Stopping MediaUploadService.
151	|	06:34:05:917	|	D/CrashlyticsCore i/WordPress-MEDIA: Media Upload Service > destroyed
152	|	06:34:09:827	|	D/CrashlyticsCore d/WordPress-EDITOR: Image tapped, id=zss_field_content~id=1~url=file:///storage/sdcard0/external_sd/OLYMPUS/image33.jpg~meta={"align":"none","alt":"","attachment_id":"","caption":"","captionClassName":"","captionId":"","classes":"failed","height":1536,"linkClassName":"","linkRel":"","linkTargetBlank":false,"linkUrl":"","size":"custom","src":"/storage/sdcard0/external_sd/OLYMPUS/image33.jpg","title":"","width":2048,"naturalWidth":2048,"naturalHeight":1536}~type=image
Stacktrace Download .txt
```

**Comment by aforcier** [comment]
Looks like the same issue as https://github.com/wordpress-mobile/WordPress-Android/issues/5673.

**Comment by mzorz** [comment]
it is - thanks @aforcier , closing the dupe and carrying the logs over to the other issue
