### ISSUE TITLE
Crash report 7.2.1: IllegalStateException accessing CursorWindow

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#5824]
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetString(CursorWindow.java)
       at android.database.CursorWindow.getString(CursorWindow.java:451)
       at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
       at android.database.CursorWrapper.getString(CursorWrapper.java:137)
       at org.wordpress.android.util.MediaUtils.getFilenameFromURI(MediaUtils.java:196)
       at org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:237)
       at org.wordpress.android.ui.media.MediaBrowserActivity$6.doInBackground(MediaBrowserActivity.java:811)
       at org.wordpress.android.ui.media.MediaBrowserActivity$6.doInBackground(MediaBrowserActivity.java:807)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by daniloercoli** [comment]
This should have been fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/5686

**Comment by mzorz** [comment]
True, thanks for reminding me this is a dupe. Users will see it in `7.3`. Closing
