### ISSUE TITLE
Crash report 7.2.1: java.lang.IllegalArgumentException: password cannot be empty

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#5850]
```
Fatal Exception: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
       at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5219)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
Caused by java.lang.IllegalArgumentException: password cannot be empty
       at com.google.android.gms.auth.api.credentials.Credential.<init>(Unknown Source)
       at com.google.android.gms.auth.api.credentials.Credential$Builder.build(Unknown Source)
       at org.wordpress.android.ui.accounts.SmartLockHelper.saveCredentialsInSmartLock(SmartLockHelper.java:114)
       at org.wordpress.android.ui.accounts.NewUserFragment.fetchSiteAndAccount(NewUserFragment.java:630)
       at org.wordpress.android.ui.accounts.NewUserFragment.onNewSiteCreated(NewUserFragment.java:719)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5219)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by tonyr59h** [comment]
Closed via #5851.
