### ISSUE TITLE
Crash report 7.3: Missing isAdded() check

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5865]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.accounts.SignInActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
       at android.app.ActivityThread.access$900(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:771)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:278)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
       at android.widget.PopupWindow.invokePopup(PopupWindow.java:1071)
       at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:970)
       at android.widget.ListPopupWindow.show(ListPopupWindow.java:635)
       at android.widget.AutoCompleteTextView.showDropDown(AutoCompleteTextView.java:1119)
       at org.wordpress.android.ui.accounts.NewUserFragment$8.onFocusChange(NewUserFragment.java:582)
       at android.view.View.onFocusChanged(View.java:5066)
       at android.widget.TextView.onFocusChanged(TextView.java:9195)
       at android.widget.EditText.onFocusChanged(EditText.java:182)
       at android.widget.AutoCompleteTextView.onFocusChanged(AutoCompleteTextView.java:1006)
       at android.view.View.handleFocusGainInternal(View.java:4846)
       at android.view.View.requestFocusNoSearch(View.java:7329)
       at android.view.View.requestFocus(View.java:7308)
       at android.view.View.requestFocus(View.java:7275)
       at android.view.View.requestFocus(View.java:7254)
       at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1944)
       at android.app.Activity.onRestoreInstanceState(Activity.java:997)
       at android.app.Activity.performRestoreInstanceState(Activity.java:969)
       at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1144)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2382)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
       at android.app.ActivityThread.access$900(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniloercoli** [comment]
Fixed in #5868
