### ISSUE TITLE
Crash report 7.3: Unable to instantiate PlanPostPurchaseActivity

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#5866]
No idea how the user was able to do that, but we should remove `PlanPostPurchaseActivity` from the manifest.

```
Fatal Exception: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.plans.PlanPostPurchaseActivity}: java.lang.ClassNotFoundException: org.wordpress.android.ui.plans.PlanPostPurchaseActivity
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2022)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
       at android.app.ActivityThread.access$600(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.ClassNotFoundException: org.wordpress.android.ui.plans.PlanPostPurchaseActivity
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
       at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2004)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
       at android.app.ActivityThread.access$600(ActivityThread.java:130)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4847)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:535)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniloercoli** [comment]
Fixed in #5869
