### ISSUE TITLE
Crash report 7.3: NPE in MediaEditFragment

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#5887]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.fluxc.model.MediaModel.setTitle(java.lang.String)' on a null object reference
       at org.wordpress.android.ui.media.MediaEditFragment.saveChanges(MediaEditFragment.java:152)
       at org.wordpress.android.ui.media.MediaPreviewActivity.onBackPressed(MediaPreviewActivity.java:258)
       at org.wordpress.android.ui.media.MediaPreviewActivity.onOptionsItemSelected(MediaPreviewActivity.java:292)
       at android.app.Activity.onMenuItemSelected(Activity.java:3208)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
       at android.support.v7.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:187)
       at android.view.View.performClick(View.java:5612)
       at android.view.View$PerformClick.run(View.java:22288)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```
[crashlytics](https://www.fabric.io/automattic/android/apps/org.wordpress.android/issues/59149d23be077a4dcc978e5e)

**Comment by tonyr59h** [comment]
Closed via #5888.
