### ISSUE TITLE
Duplicate site exception (non-fatal)

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-Android#5895]
This appears to be a harmless exception, but in the past 30 days it has happened (silently) for 31,000 users.

```
Non-fatal Exception: org.wordpress.android.fluxc.persistence.SiteSqlUtils$DuplicateSiteException
       at org.wordpress.android.WordPress.onSiteChanged(WordPress.java:562)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5641)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by maxme** [comment]
We're logging this exception to look for migration errors (it's not really useful now). And it happens a lot during migration due to Jetpack sites "replacing" previous self hosted configurations.

I added a milestone to this ticket so we can drop the call to crashlytics when we drop the migration code. 

Ref. https://github.com/wordpress-mobile/WordPress-Android/issues/5643

**Comment by maxme** [comment]
We removed that crashlytics log in https://github.com/wordpress-mobile/WordPress-Android/pull/6383
