### ISSUE TITLE
Crash report 7.4,7.3: IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5969]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{8700d93 position=1 id=1, oldPos=1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
       at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5249)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5431)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5392)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5388)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2149)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1533)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1496)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:593)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3486)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3262)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3796)
       at android.view.View.layout(View.java:17050)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:17050)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:17050)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
       at android.view.View.layout(View.java:17050)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:17050)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
       at android.view.View.layout(View.java:17050)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2798)
       at android.view.View.layout(View.java:17050)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2573)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2273)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1340)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6809)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
       at android.view.Choreographer.doCallbacks(Choreographer.java:696)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5977)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:940)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
```

**Comment by maxme** [comment]
Probably a dup of https://github.com/wordpress-mobile/WordPress-Android/issues/5969
