### ISSUE TITLE
Crash report 7.4,7.3: IllegalStateException in ReaderPostPagerActivity.onBackPressed

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5970]
This crash is due to a FragmentTransaction being committed after its owning Activity's lifecycle has already run onSaveInstanceState.  This is often caused by committing FragmentTransactions from an asynchronous callback.  Check [this link](http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html) for more details.

This is possibly related to an old unresolved [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/2912) with a similar stack trace.

```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:775)
       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
       at org.wordpress.android.ui.reader.ReaderPostPagerActivity.onBackPressed(ReaderPostPagerActivity.java:610)
       at org.wordpress.android.ui.reader.ReaderPostPagerActivity.onOptionsItemSelected(ReaderPostPagerActivity.java:535)
       at android.app.Activity.onMenuItemSelected(Activity.java:3219)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
       at android.support.v7.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:187)
       at android.view.View.performClick(View.java:5721)
       at android.view.View$PerformClick.run(View.java:22620)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7409)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by daniloercoli** [comment]
It seems that the exception occurs when calling `super.onBackPressed()` in the `onBackPressed` event. 

I think the considerations made in https://github.com/wordpress-mobile/WordPress-Android/issues/2912#issuecomment-137237577 are still valid 

> Given the rarity of this crash coupled with the fact that it's a problem in Android itself, we're leaving this as-is.

cc @nbradbury

**Comment by nbradbury** [comment]
@theck13 How many crashes are we seeing due to this?

**Comment by theck13** [comment]
Time|Crashes|Users
-|-|-
Last 24 Hours|0|0
Last 7 Days|8|8
Last 30 Days|39|37
Last 90 Days|65|62

More details can be found [here](http://crashes.to/s/55c40060213).

**Comment by nbradbury** [comment]
Well, that's not a *ton* of users, but enough to make me want to fix this. 

The weird thing is I'm not doing any fragment transactions. This activity uses a `FragmentStatePagerAdapter` which takes care of the transaction - and looking at the source code, I see it's using `commitAllowingStateLoss()`. So I'm at a loss to figure out why this is happening.

I think the only reasonable thing to do is catch and ignore the exception, or perhaps we can use `finish()` rather than `super.onBackPressed()`.
