### ISSUE TITLE
Crash report 7.4,7.3: IllegalStateException in WebViewActivity.onBackPressed

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#5992]
This crash is due to a FragmentTransaction being committed after its owning Activity's lifecycle has already run onSaveInstanceState.  This is often caused by committing FragmentTransactions from an asynchronous callback.  Check [this link](http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html) for more details.

```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:775)
       at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
       at org.wordpress.android.ui.WebViewActivity.onBackPressed(WebViewActivity.java:149)
       at android.app.Activity.onKeyUp(Activity.java:2530)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2726)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2798)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2368)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4344)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3847)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3900)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3866)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3992)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3874)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4049)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3847)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3900)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3866)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3874)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3847)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3900)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3866)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4025)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4186)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2378)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1999)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1990)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2355)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:330)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```

**Comment by nbradbury** [comment]
Well, that's not a *ton* of users, but enough to make me want to fix this. 

The weird thing is I'm not doing any fragment transactions. This activity uses a `FragmentStatePagerAdapter` which takes care of the transaction - and looking at the source code, I see it's using `commitAllowingStateLoss()`. So I'm at a loss to figure out why this is happening.

I think the only reasonable thing to do is catch and ignore the exception, or perhaps we can use `finish()` rather than `super.onBackPressed()`.
