### ISSUE TITLE
Crash report 7.4: SecurityException in ActivityLauncher.openUrlExternal

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#6001]
This is possibly related to https://github.com/wordpress-mobile/WordPress-Android/issues/4991 with a similar stack trace.  The crash is exclusive to Samsung devices running Android 7 (90%) and 6 (10%).

```
Fatal Exception: java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=https://bitcoin770.wordpress.com/... cmp=com.alibaba.intl.android.apps.poseidon/com.alibaba.android.intl.weex.activity.WeexPageActivity launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } } from ProcessRecord{1f8a09b 24402:org.wordpress.android/u0a33} (pid=24402, uid=10033) not exported from uid 10258
       at android.os.Parcel.readException(Parcel.java:1693)
       at android.os.Parcel.readException(Parcel.java:1646)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3530)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1526)
       at android.app.Activity.startActivityForResult(Activity.java:4399)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
       at android.app.Activity.startActivityForResult(Activity.java:4358)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at android.app.Activity.startActivity(Activity.java:4682)
       at android.app.Activity.startActivity(Activity.java:4650)
       at org.wordpress.android.ui.ActivityLauncher.openUrlExternal(ActivityLauncher.java:350)
       at org.wordpress.android.ui.themes.ThemeWebActivity.openTheme(ThemeWebActivity.java:58)
       at org.wordpress.android.ui.themes.ThemeBrowserActivity.startWebActivity(ThemeBrowserActivity.java:455)
       at org.wordpress.android.ui.themes.ThemeBrowserActivity.onTryAndCustomizeSelected(ThemeBrowserActivity.java:472)
       at org.wordpress.android.ui.themes.ThemeBrowserFragment$2.onClick(ThemeBrowserFragment.java:224)
       at android.view.View.performClick(View.java:6199)
       at android.view.View$PerformClick.run(View.java:23647)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by hypest** [comment]
This is still caused by the Alibaba B2B app, most probably by older versions of it since they fixed it already. I installed the Alibaba app but couldn't reproduce this.
