### ISSUE TITLE
Crash report 7.7-rc-2: NPE in PublicizeUpdateService.onHandleIntent

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6148]
```
Fatal Exception: java.lang.NullPointerException
       at org.wordpress.android.ui.publicize.services.PublicizeUpdateService.onHandleIntent(PublicizeUpdateService.java:69)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by oguzkocer** [comment]
Fixed in #6276
