### ISSUE TITLE
Crash report 7.7.1: NPE in PhotoPickerAdapter

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6268]
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
Caused by java.lang.NullPointerException: Attempt to read from field 'long org.wordpress.android.ui.photopicker.PhotoPickerAdapter$PhotoPickerItem._id' on a null object reference
       at org.wordpress.android.ui.photopicker.PhotoPickerAdapter$PhotoPickerItem.access$000(PhotoPickerAdapter.java:48)
       at org.wordpress.android.ui.photopicker.PhotoPickerAdapter$BuildDeviceMediaListTask.isSameMediaList(PhotoPickerAdapter.java:413)
       at org.wordpress.android.ui.photopicker.PhotoPickerAdapter$BuildDeviceMediaListTask.doInBackground(PhotoPickerAdapter.java:372)
       at org.wordpress.android.ui.photopicker.PhotoPickerAdapter$BuildDeviceMediaListTask.doInBackground(PhotoPickerAdapter.java:340)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by tonyr59h** [comment]
Closed via #6270.
