### ISSUE TITLE
Media: Aztec consumes too much memory

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6283]
From time to time, after writing several drafts and picking images, it starts to get super slow and images stop loading, and the whole app gets slower.
After this happens, entering again in the Editor for the Post where the included images are, an OOM exception was thrown (and ofc the app crashed).

```
07-11 15:39:02.441 27341-27341/org.wordpress.android I/art: Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 1% free, 505MB/512MB, paused 16.144ms total 124.140ms
07-11 15:39:02.454 27341-27341/org.wordpress.android W/art: Throwing OutOfMemoryError "Failed to allocate a 33177612 byte allocation with 6932056 free bytes and 6MB until OOM"
07-11 15:39:02.455 27341-27341/org.wordpress.android D/AndroidRuntime: Shutting down VM
07-11 15:39:02.462 27341-27341/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: org.wordpress.android, PID: 27341
                                                                       java.lang.OutOfMemoryError: Failed to allocate a 33177612 byte allocation with 6932056 free bytes and 6MB until OOM
                                                                           at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                           at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                           at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:646)
                                                                           at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:622)
                                                                           at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:402)
                                                                           at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:428)
                                                                           at org.wordpress.android.ui.posts.services.AztecImageLoader.loadImage(AztecImageLoader.java:28)
                                                                           at org.wordpress.aztec.AztecText.loadImages(AztecText.kt:717)
                                                                           at org.wordpress.aztec.AztecText.fromHtml(AztecText.kt:685)
                                                                           at org.wordpress.android.editor.AztecEditorFragment.setContent(AztecEditorFragment.java:324)
                                                                           at org.wordpress.android.ui.posts.EditPostActivity.fillContentEditorFields(EditPostActivity.java:1449)
                                                                           at org.wordpress.android.ui.posts.EditPostActivity.onEditorFragmentInitialized(EditPostActivity.java:2297)
                                                                           at org.wordpress.android.editor.AztecEditorFragment.onCreateView(AztecEditorFragment.java:175)
                                                                           at android.app.Fragment.performCreateView(Fragment.java:2353)
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
                                                                           at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                                           at android.app.BackStackRecord.run(BackStackRecord.java:816)
                                                                           at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                                                                           at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:563)
                                                                           at android.support.v13.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:153)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                                           at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                           at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                           at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                           at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                           at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                           at com.android.internal.policy.DecorView.onMeasure(DecorView.java:690)
                                                                           at android.view.View.measure(View.java:19857)
                                                                           at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
                                                                           at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:686)
07-11 15:39:02.462 27341-27341/org.wordpress.android E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-11 15:39:02.463 1052-2396/? W/ActivityManager:   Force finishing activity org.wordpress.android/.ui.posts.EditPostActivity
07-11 15:39:02.465 1052-2396/? W/ActivityManager:   Force finishing activity org.wordpress.android/.ui.posts.PostsListActivity
07-11 15:39:02.534 1052-21017/? I/OpenGLRenderer: Initialized EGL, version 1.4
07-11 15:39:02.534 1052-21017/? D/OpenGLRenderer: Swap behavior 1
07-11 15:39:02.966 1052-1092/? W/ActivityManager: Activity pause timeout for ActivityRecord{75131c6 u0 org.wordpress.android/.ui.posts.EditPostActivity t7826 f}

```

cc @nbradbury

**Comment by nbradbury** [comment]
I'm pretty sure the problem is with `AztecImageLoader` and was fixed by @daniloercoli [here](https://github.com/wordpress-mobile/WordPress-Android/pull/6267).

**Comment by mzorz** [comment]
that'd be awesome @nbradbury

**Comment by nbradbury** [comment]
Looking at that trace, I can see it's definitely fixed. `AztecImageLoader` was loading full-sized images until @daniloercoli made that fix.

**Comment by mzorz** [comment]
Thank you! Will test again tomorrow against `develop` and come back here to close the issue

**Comment by mzorz** [comment]
Tested again, still managed to make it fail with lots of pictures on my phone and scrolling super quickly in the media picker while adding multi-select of 10 or more pics to a post:

```
07-12 11:50:14.375 24696-26257/org.wordpress.android W/art: Suspending all threads took: 48.546ms
07-12 11:50:14.379 24696-26357/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.379 24696-26257/org.wordpress.android I/art: Forcing collection of SoftReferences for 28B allocation
07-12 11:50:14.380 24696-26257/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.380 24696-26267/org.wordpress.android I/art: Clamp target GC heap from 528MB to 512MB
07-12 11:50:14.380 24696-26267/org.wordpress.android I/art: Alloc partial concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 512MB/512MB, paused 3.652ms total 52.760ms
07-12 11:50:14.380 24696-24703/org.wordpress.android I/art: WaitForGcToComplete blocked for 325.419ms for cause Alloc
07-12 11:50:14.380 24696-24703/org.wordpress.android I/art: Starting a blocking GC Alloc
07-12 11:50:14.380 24696-26914/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.380 24696-26915/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.380 24696-26264/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.380 24696-24705/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.380 24696-26265/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.380 24696-26357/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.381 24696-26257/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.425 24696-26267/org.wordpress.android W/art: Suspending all threads took: 42.295ms
07-12 11:50:14.429 24696-26267/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.429 24696-24703/org.wordpress.android I/art: Clamp target GC heap from 528MB to 512MB
07-12 11:50:14.429 24696-24703/org.wordpress.android I/art: Alloc concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 512MB/512MB, paused 3.878ms total 49.442ms
07-12 11:50:14.429 24696-26914/org.wordpress.android I/art: WaitForGcToComplete blocked for 504.558ms for cause Alloc
07-12 11:50:14.429 24696-26914/org.wordpress.android I/art: Starting a blocking GC Alloc
07-12 11:50:14.430 24696-26914/org.wordpress.android I/art: Starting a blocking GC Alloc
07-12 11:50:14.430 24696-26915/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.430 24696-26264/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.430 24696-24705/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.430 24696-26265/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.430 24696-26357/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.430 24696-26267/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.430 24696-26257/org.wordpress.android I/art: Waiting for a blocking GC Alloc
07-12 11:50:14.432 24696-24703/org.wordpress.android W/art: Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 0 free bytes and -421KB until OOM" (recursive case)
07-12 11:50:14.469 24696-24703/org.wordpress.android W/art: "JDWP" daemon prio=5 tid=4 Runnable
07-12 11:50:14.469 24696-24703/org.wordpress.android W/art:   | group="system" sCount=0 dsCount=0 obj=0x12c051f0 self=0x78fb827400
07-12 11:50:14.469 24696-24703/org.wordpress.android W/art:   | sysTid=24703 nice=0 cgrp=default sched=0/0 handle=0x7902708450
07-12 11:50:14.469 24696-24703/org.wordpress.android W/art:   | state=R schedstat=( 531727295 50250512 305 ) utm=52 stm=0 core=3 HZ=100
07-12 11:50:14.469 24696-24703/org.wordpress.android W/art:   | stack=0x790260e000-0x7902610000 stackSize=1005KB
07-12 11:50:14.470 24696-24703/org.wordpress.android W/art:   | held mutexes= "mutator lock"(shared held)
07-12 11:50:14.470 24696-24703/org.wordpress.android W/art:   native: #00 pc 000000000047ae90  /system/lib64/libart.so (
```
One thing to note is that I was able to make it fail when using Aztec only, but couldn't repro with the Visual editor. 
Let me know if you need more info @nbradbury

**Comment by mzorz** [comment]
Pinging @0nko here as per this: 
> One thing to note is that I was able to make it fail when using Aztec only, but couldn't repro with the Visual editor.

**Comment by nbradbury** [comment]
The fact that the OOM exception only occurs with Aztec definitely suggests there's a problem in Aztec, but regardless there are things we could do to reduce memory consumption in the photo picker itself.

My first thought was to use MICRO_KIND rather than MINI_KIND media thumbnails since [they're much smaller](https://stackoverflow.com/a/20208078/1673548), but they turned out to be *too* small, resulting in obviously grainy thumbnails.

My next thought was to simply disable loading thumbnails while a fling is in progress, and so far this seems promising. I'll submit a PR for this soon if it proves to be reliable.

**Comment by mzorz** [comment]
Sounds good! Looking forward to it :+1:

**Comment by daniloercoli** [comment]
I can't reproduce this exact error, but I see a very high resources usage when Aztec is enabled and tried to add a lot of pictures to the post.
(There should memory leaks somewhere, since once the Java heap increased in size there is no way to turn it down. I tried by forcing garbage collector in AS but heap size is still at 200Mb!).

- Started writing new post
- Add several pictures to it
- Add again some other pictures
- Exit the editor
- Go to Media and delete items with state = "enqueued"
- Try to force Garbage collector. You should see the heap remain the same in size.
- The app is slowed down

The visual editor, instead, doesn't have high heap usage. It's slow on rendering pictures in the editor, but the heap size doesn't grow too much if I add a lot of pictures to it.
 

cc @theck13 @0nko

**Comment by mzorz** [comment]
I think this one can be closed now as doesn't repro anymore for me with https://github.com/wordpress-mobile/AztecEditor-Android/issues/420

**Comment by daniloercoli** [comment]
Re-opening this since we need to revert the changes done in Aztec.Keep this open till a proper fix lands in Aztec.

**Comment by mzorz** [comment]
Been testing this again on `develop` and was unable to reproduce. Closing!
