### ISSUE TITLE
NPE in WPMainActivity trackDefaultApp

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#6291]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2576)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5737)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1605)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.content.pm.IPackageManager$Stub$Proxy.resolveIntent(IPackageManager.java:2980)
       at android.app.ApplicationPackageManager.resolveActivityAsUser(ApplicationPackageManager.java:635)
       at android.app.ApplicationPackageManager.resolveActivity(ApplicationPackageManager.java:629)
       at org.wordpress.android.ui.main.WPMainActivity.trackDefaultApp(WPMainActivity.java:498)
       at org.wordpress.android.ui.main.WPMainActivity.onCreate(WPMainActivity.java:246)
       at android.app.Activity.performCreate(Activity.java:6309)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2523)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2658)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1492)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5737)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by oguzkocer** [comment]
This crash is only happening to a single user using `Intex Cloud Q11 4G` with Marshmallow (6.0) and the crash seems to be happening while resolving the intent. We are not passing anything `null`, so I think this is more than likely due to a modified Android version.

Let's keep this issue open for now and look out for any similar crashes.
