### ISSUE TITLE
Crash report 7.7: ISE in MeFragment.onActivityResult

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6316]
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1200, result=-1, data=Intent { (has extras) }} to activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.IllegalStateException: Fragment MeFragment{293d05f} not attached to Activity
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3314)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3345)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5729)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1200, result=-1, data=Intent { (has extras) }} to activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.IllegalStateException: Fragment MeFragment{293d05f} not attached to Activity
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3930)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3296)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3345)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5729)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by java.lang.IllegalStateException: Fragment MeFragment{293d05f} not attached to Activity
       at android.app.Fragment.getResources(Fragment.java:816)
       at android.app.Fragment.getString(Fragment.java:838)
       at org.wordpress.android.ui.main.MeFragment.onActivityResult(MeFragment.java:451)
       at org.wordpress.android.ui.main.WPMainActivity.onActivityResult(WPMainActivity.java:588)
       at android.app.Activity.dispatchActivityResult(Activity.java:6461)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3926)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3296)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3345)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5729)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by oguzkocer** [comment]
Fixed via #6318
