### ISSUE TITLE
Crash report 7.8: NPE in AztecEditorFragment.onCreateView

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6339]
Somehow `imageLoader` is null and passed to a Kotlin method that expects a non-null argument.

Note: the naming is pretty confusing in that file, mixing notations (hungarian and not). In that class we have a member `imageLoader` but also a `mImageLoader`.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter imageGetter
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2584)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5769)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter imageGetter
       at org.wordpress.aztec.Aztec.setImageGetter(Aztec.kt)
       at org.wordpress.android.editor.AztecEditorFragment.onCreateView(AztecEditorFragment.java:194)
       at android.app.Fragment.performCreateView(Fragment.java:2236)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:978)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1135)
       at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1980)
       at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:152)
       at android.app.Activity.performCreateCommon(Activity.java:6572)
       at android.app.Activity.performCreate(Activity.java:6585)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1114)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2531)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2666)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5769)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by 0nko** [comment]
This one's weird, as `AztecEditorFragment.setImageLoader()` should be called before Aztec is initialized in `onCreateView()`, which should already have a non-null loader. The fragment lifecycle appears to be different.

**Comment by maxme** [comment]
Steps to repro:
* enable "don't keep activity" in dev settings, 
* open Aztec, 
* put the app in background,
* reopen it -> 💥
