### ISSUE TITLE
Crash report 7.8: out of bound in AztecEditorFragment.onMediaUploadProgress

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6346]
```
Fatal Exception: org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
       at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5441)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by java.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at org.wordpress.aztec.spans.AztecMediaSpan.setOverlayLevel(AztecMediaSpan.kt:52)
       at org.wordpress.aztec.AztecText.setOverlayLevel(AztecText.kt:1193)
       at org.wordpress.android.editor.AztecEditorFragment.onMediaUploadProgress(AztecEditorFragment.java:768)
       at org.wordpress.android.ui.posts.EditPostActivity.onUploadProgress(EditPostActivity.java:818)
       at org.wordpress.android.ui.posts.EditPostActivity.onMediaUploaded(EditPostActivity.java:2419)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5441)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by maxme** [comment]
Looks like this and [another crash](https://github.com/wordpress-mobile/AztecEditor-Android/issues/418) was fixed in Aztec, we should update the dependency in wpandroid. @0nko can we do that right now, or are we waiting for other fixes on the Aztec side?

**Comment by maxme** [comment]
Should be fixed via https://github.com/wordpress-mobile/WordPress-Android/pull/6371
