### ISSUE TITLE
Media Picker is blank in post editor

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6404]
Not sure if it's an issue on my testing device or not (probably it is a local issue) but the media picker is completely blank in editor. See the video below:
https://cloudup.com/cvDbC2H_ucD

If I tap on one of the items in the picker, the picture gets inserted into the editor but the preview is broken and there is the following log entry:
```
07-26 17:53:38.852 8584-8584/org.wordpress.android W/System.err: java.io.IOException: read failed: EIO (I/O error)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at libcore.io.IoBridge.read(IoBridge.java:482)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at java.io.FileInputStream.read(FileInputStream.java:177)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:665)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:641)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:395)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:387)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at org.wordpress.android.util.ImageUtils.getImageSize(ImageUtils.java:69)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at org.wordpress.android.util.AnalyticsUtils.getMediaProperties(AnalyticsUtils.java:349)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at org.wordpress.android.ui.media.services.MediaUploadService.trackUploadMediaEvents(MediaUploadService.java:314)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at org.wordpress.android.ui.media.services.MediaUploadService.uploadNextInQueue(MediaUploadService.java:157)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at org.wordpress.android.ui.media.services.MediaUploadService.onStartCommand(MediaUploadService.java:97)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2864)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.app.ActivityThread.access$2100(ActivityThread.java:144)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.os.Looper.loop(Looper.java:135)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5221)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
07-26 17:53:38.853 8584-8584/org.wordpress.android W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
07-26 17:53:38.854 8584-8584/org.wordpress.android W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
07-26 17:53:38.854 8584-8584/org.wordpress.android W/System.err: Caused by: android.system.ErrnoException: read failed: EIO (I/O error)
07-26 17:53:38.854 8584-8584/org.wordpress.android W/System.err:     at libcore.io.Posix.readBytes(Native Method)
07-26 17:53:38.854 8584-8584/org.wordpress.android W/System.err:     at libcore.io.Posix.read(Posix.java:147)
07-26 17:53:38.854 8584-8584/org.wordpress.android W/System.err:     at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
07-26 17:53:38.854 8584-8584/org.wordpress.android W/System.err:     at libcore.io.IoBridge.read(IoBridge.java:472)
```

![device-2017-07-26-175405](https://user-images.githubusercontent.com/518232/28630805-8f9f5bbc-722b-11e7-9b41-1aa7206227d4.png)

**Comment by daniloercoli** [comment]
Closing this issue since it'a problem on my device acting crazy with SD card and device stored media. Not only in this application.
