### ISSUE TITLE
Login Rework: magic link login fails to trigger application_opened track correctly

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6426]
```
07-29 00:39:15.673 28632-28632/? E/NosaraClient: Cannot create the event: _aliasUser
        com.automattic.android.tracks.Exceptions.EventDetailsException: Username cannot be empty!
    at com.automattic.android.tracks.Event.<init>(Event.java:42)
    at com.automattic.android.tracks.TracksClient.track(TracksClient.java:379)
    at com.automattic.android.tracks.TracksClient.trackAliasUser(TracksClient.java:424)
    at org.wordpress.android.analytics.AnalyticsTrackerNosara.refreshMetadata(AnalyticsTrackerNosara.java:305)
    at org.wordpress.android.analytics.AnalyticsTracker.refreshMetadata(AnalyticsTracker.java:371)
    at org.wordpress.android.util.AnalyticsUtils.refreshMetadata(AnalyticsUtils.java:60)
    at org.wordpress.android.WordPress$ApplicationLifecycleMonitor.onAppComesFromBackground(WordPress.java:746)
    at org.wordpress.android.WordPress$ApplicationLifecycleMonitor.onActivityResumed(WordPress.java:790)
    at android.app.Application.dispatchActivityResumed(Application.java:238)
    at android.app.Activity.onResume(Activity.java:1373)
    at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
    at org.wordpress.android.ui.main.WPMainActivity.onResume(WPMainActivity.java:443)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1287)
    at android.app.Activity.performResume(Activity.java:6988)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4147)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4252)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3363)
    at android.app.ActivityThread.access$1100(ActivityThread.java:223)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7231)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
07-29 00:39:15.698 28632-28632/? E/NosaraClient: Cannot create the event: wpandroid_application_opened
        com.automattic.android.tracks.Exceptions.EventDetailsException: Username cannot be empty!
    at com.automattic.android.tracks.Event.<init>(Event.java:42)
    at com.automattic.android.tracks.TracksClient.track(TracksClient.java:379)
    at org.wordpress.android.analytics.AnalyticsTrackerNosara.track(AnalyticsTrackerNosara.java:267)
    at org.wordpress.android.analytics.AnalyticsTracker.track(AnalyticsTracker.java:317)
    at org.wordpress.android.WordPress$ApplicationLifecycleMonitor.onAppComesFromBackground(WordPress.java:751)
    at org.wordpress.android.WordPress$ApplicationLifecycleMonitor.onActivityResumed(WordPress.java:790)
    at android.app.Application.dispatchActivityResumed(Application.java:238)
    at android.app.Activity.onResume(Activity.java:1373)
    at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
    at org.wordpress.android.ui.main.WPMainActivity.onResume(WPMainActivity.java:443)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1287)
    at android.app.Activity.performResume(Activity.java:6988)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4147)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4252)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3363)
    at android.app.ActivityThread.access$1100(ActivityThread.java:223)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7231)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

To test:
* Use the `vanillaRelease` build
* With the app data cleaned up, send a valid magic link deeplink via `adb`
* App opens and correctly logs in but, `logcat` shows the exception stacktrace as above

**Comment by hypest** [comment]
Closing as non reproducible anymore. Possibly fixed with https://github.com/wordpress-mobile/WordPress-Android/pull/6634.
