### ISSUE TITLE
Create account from Share to WordPress crashes the app

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6431]
```FATAL EXCEPTION: main
Process: org.wordpress.android, PID: 10428
java.lang.RuntimeException: org.wordpress.android.ui.accounts.SignInActivity@244d85e0 must implement LoginListener
	at org.wordpress.android.ui.accounts.NewUserFragment.onAttach(NewUserFragment.java:500)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1231)
	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1085)
	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:976)
	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:95)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)```


##### Tested on [device], Android [version]
Nexus 5, Android 5.1

**Comment by mzorz** [comment]
Closing via #6432
