### ISSUE TITLE
Crash report 7.9: OOB when binding view in PostSettingsTagsActivity

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#6489]
cc @oguzkocer

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at org.wordpress.android.ui.posts.PostSettingsTagsActivity$TagsRecyclerViewAdapter.onBindViewHolder(PostSettingsTagsActivity.java:232)
       at org.wordpress.android.ui.posts.PostSettingsTagsActivity$TagsRecyclerViewAdapter.onBindViewHolder(PostSettingsTagsActivity.java:214)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
       at android.view.View.layout(View.java:16550)
```

**Comment by tonyr59h** [comment]
Closed via #6500.
