### ISSUE TITLE
Crash report 7.9: NumberFormatException in EditPostActivity.onMediaUploadCancelClicked

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#6490]
Related to #5949, but it's not a `null` value and it's coming from Aztec.

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NumberFormatException: Invalid int: "48b86f38-6f35-483c-8447-53c9b01c45be"
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3901)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3919)
       at android.app.ActivityThread.access$1500(ActivityThread.java:159)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5504)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.lang.NumberFormatException: Invalid int: "48b86f38-6f35-483c-8447-53c9b01c45be"
       at java.lang.Integer.invalidInt(Integer.java:138)
       at java.lang.Integer.parse(Integer.java:410)
       at java.lang.Integer.parseInt(Integer.java:367)
       at java.lang.Integer.parseInt(Integer.java:334)
       at java.lang.Integer.valueOf(Integer.java:525)
       at org.wordpress.android.ui.posts.EditPostActivity.onMediaUploadCancelClicked(EditPostActivity.java:2224)
       at org.wordpress.android.editor.AztecEditorFragment.onDetach(AztecEditorFragment.java:257)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
       at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1981)
       at android.app.FragmentController.dispatchDestroy(FragmentController.java:218)
       at android.app.Activity.performDestroy(Activity.java:6455)
```

**Comment by khaykov** [comment]
Looks like this was fixed in 8.1.
Closing for now.
