### ISSUE TITLE
Crash report 7.9: NPE ImageSettingsDialogFragment.loadThumbnail

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#6491]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.volley.toolbox.ImageLoader$ImageContainer com.android.volley.toolbox.ImageLoader.get(java.lang.String, com.android.volley.toolbox.ImageLoader$ImageListener, int, int)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6577)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.volley.toolbox.ImageLoader$ImageContainer com.android.volley.toolbox.ImageLoader.get(java.lang.String, com.android.volley.toolbox.ImageLoader$ImageListener, int, int)' on a null object reference
       at org.wordpress.android.editor.ImageSettingsDialogFragment.loadThumbnail(ImageSettingsDialogFragment.java:386)
       at org.wordpress.android.editor.ImageSettingsDialogFragment.onCreateView(ImageSettingsDialogFragment.java:177)
       at android.app.Fragment.performCreateView(Fragment.java:2361)
```

**Comment by nbradbury** [comment]
Note: the thumbnail will likely be dropped when #5739 is tackled, which will make this issue moot.

**Comment by daniloercoli** [comment]
Note: The old #5769 ticket is not replaced by https://github.com/wordpress-mobile/WordPress-Android/issues/6503 that is going to be worked soon. Maybe we can quickly patch this in `develop` without waiting for the new settings screen?

**Comment by daniloercoli** [comment]
Fixed in 6564
