### ISSUE TITLE
Crash report 8.1: NPE in PostsListFragment.handleEditPostResult()

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-Android#6537]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
       at org.wordpress.android.ui.posts.PostsListFragment.handleEditPostResult(PostsListFragment.java:215)
       at org.wordpress.android.ui.posts.PostsListActivity.onActivityResult(PostsListActivity.java:129)
       at android.app.Activity.dispatchActivityResult(Activity.java:6935)
```

### Steps to reproduce
1. Share an image to the WordPress app
2. Choose the 'new post' option
3. Publish the post

**Comment by aforcier** [comment]
Fixed in #6538.
