### ISSUE TITLE
Async & Aztec: Removing a video from a post could lead to crash

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6557]
It seems that removing a video from a post in Aztec does't really stop the uploading of the video, instead I see my connection busy (sending the video I guess) and other pictures are postponed until the video network upload is done.
At the end of the uploading process for the video the app crashed with the following error:

```
08-22 09:12:55.809 22585-22585/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: org.wordpress.android, PID: 22585
                                                                       org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
                                                                           at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
                                                                           at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
                                                                           at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
                                                                           at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                        Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter attributes
                                                                           at org.wordpress.aztec.AztecAttributes.<init>(AztecAttributes.kt)
                                                                           at org.wordpress.android.editor.MetadataUtils$AttributesWithClass.<init>(MetadataUtils.java:131)
                                                                           at org.wordpress.android.editor.AztecEditorFragment.markMediaFailed(AztecEditorFragment.java:1562)
                                                                           at org.wordpress.android.ui.uploads.MediaUploadReadyProcessor.markMediaUploadFailedInPost(MediaUploadReadyProcessor.java:43)
                                                                           at org.wordpress.android.ui.uploads.UploadService.updatePostWithFailedMedia(UploadService.java:520)
                                                                           at org.wordpress.android.ui.uploads.UploadService.updatePostWithCurrentlyFailedUploads(UploadService.java:373)
                                                                           at org.wordpress.android.ui.uploads.UploadService.updatePostModelWithCompletedAndFailedUploads(UploadService.java:569)
                                                                           at org.wordpress.android.ui.uploads.UploadService.stopServiceIfUploadsComplete(UploadService.java:549)
                                                                           at org.wordpress.android.ui.uploads.UploadService.onMediaUploaded(UploadService.java:727)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                           at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479) 
                                                                           at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

Video here: https://cloudup.com/cbns9SNSTW7

I also noticed (and you can see in the video) that Media Library does contain multiple instances of the video. Those items cannot be open, as shown in the video.

I experienced this issue in `develop`, but I guess it's applicable to `8.1` too. Should we fix this in 8.1 instead?

**Comment by daniloercoli** [comment]
Fixed in #6567
