### ISSUE TITLE
Crash: NullPointerException via ActivityLauncher.openUrlExternal

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6585]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1605)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2771)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1518)
       at android.app.Activity.startActivityForResult(Activity.java:3968)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
       at android.app.Activity.startActivityForResult(Activity.java:3920)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at android.app.Activity.startActivity(Activity.java:4259)
       at android.app.Activity.startActivity(Activity.java:4227)
       at org.wordpress.android.ui.ActivityLauncher.openUrlExternal(ActivityLauncher.java:326)
       at org.wordpress.android.ui.ActivityLauncher.viewCurrentSite(ActivityLauncher.java:149)
       at org.wordpress.android.ui.main.MySiteFragment$2.onClick(MySiteFragment.java:159)
       at android.view.View.performClick(View.java:5265)
       at android.view.View$PerformClick.run(View.java:21534)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5737)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by daniloercoli** [comment]
@hypest Not sure how this could happen, since we're already checking if the URL is `null` in `org.wordpress.android.ui.ActivityLauncher.viewCurrentSite` before calling `openUrlExternal`....

**Comment by hypest** [comment]
I can't find the Crashlytics report @daniloercoli and since we already have code in place to null-check the URL I'm going to close this ticket.
