### ISSUE TITLE
NPE - PostUtils.isPublishable

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#6597]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.model.PostModel.getContent()' on a null object reference
       at org.wordpress.android.ui.posts.PostUtils.isPublishable(PostUtils.java:157)
       at org.wordpress.android.ui.uploads.UploadUtils.publishPost(UploadUtils.java:182)
       at org.wordpress.android.ui.posts.PostsListFragment$2.onClick(PostsListFragment.java:223)
       at android.support.design.widget.Snackbar$1.onClick(Snackbar.java:255)
       at android.view.View.performClick(View.java:6213)
       at android.widget.TextView.performClick(TextView.java:11074)
       at android.view.View$PerformClick.run(View.java:23645)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

Ref: https://www.fabric.io/automattic/android/apps/org.wordpress.android/issues/599e830abe077a4dcc88b8fe?time=last-thirty-days

**Comment by daniloercoli** [comment]
Fixed in #6598
