### ISSUE TITLE
Crash on 8.0: IllegalStateException in LoginActivity.startLogin()

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#6627]
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
       at org.wordpress.android.ui.accounts.LoginActivity.showFragment(LoginActivity.java:89)
       at org.wordpress.android.ui.accounts.LoginActivity.startLogin(LoginActivity.java:214)
       at org.wordpress.android.ui.accounts.LoginActivity.onCredentialsUnavailable(LoginActivity.java:426)
       at org.wordpress.android.ui.accounts.SmartLockHelper$1.onResult(SmartLockHelper.java:107)
       at org.wordpress.android.ui.accounts.SmartLockHelper$1.onResult(SmartLockHelper.java:82)
       at com.google.android.gms.internal.zzzx$zza.zzb(Unknown Source)
       at com.google.android.gms.internal.zzzx$zza.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5546)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```

**Comment by theck13** [comment]
I can't reproduce this crash.  Can you?  Is there a link to reports of the the crash(es)?

**Comment by hypest** [comment]
Can't repro it, no :(
