### ISSUE TITLE
Crash on 8.1: IllegalArgumentException: Receiver not registered in ApplicationLifecycleMonitor

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Android#6667]
```
Fatal Exception: java.lang.IllegalArgumentException: Receiver not registered: org.wordpress.android.networking.ConnectionChangeReceiver@4ade5cb
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1054)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1359)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:651)
       at org.wordpress.android.WordPress$ApplicationLifecycleMonitor.onAppGoesToBackground(WordPress.java:725)
       at org.wordpress.android.WordPress$ApplicationLifecycleMonitor.access$200(WordPress.java:602)
       at org.wordpress.android.WordPress$ApplicationLifecycleMonitor$1.run(WordPress.java:698)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)
```

**Comment by daniloercoli** [comment]
It seems to me that we've already tried to fix this issue here https://github.com/wordpress-mobile/WordPress-Android/pull/6317

I've re-checked @maxme 's PR and it seems to work fine, not sure how it could happen again.
Should we put the put unregisterReceiver method into a try/catch(IllegalArgumentException) block?

**Comment by daniloercoli** [comment]
Maybe we should check if the call to `registerReceiver` [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/WordPress.java#L754) does return null or not?
