### ISSUE TITLE
Crash report 8.3: NPE in EditPostSettingsFragment

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6708]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.wordpress.android.fluxc.model.PostModel.isPage()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2482)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
       at android.app.ActivityThread.access$900(ActivityThread.java:186)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1410)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5636)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.wordpress.android.fluxc.model.PostModel.isPage()' on a null object reference
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.onCreateView(EditPostSettingsFragment.java:335)
       at android.app.Fragment.performCreateView(Fragment.java:2220)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
       at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1953)
       at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:152)
       at android.app.Activity.performCreateCommon(Activity.java:6309)
       at android.app.Activity.performCreate(Activity.java:6317)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2435)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
       at android.app.ActivityThread.access$900(ActivityThread.java:186)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1410)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5636)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

```

**Comment by elibud** [comment]
Closing with @mzorz blessing.
