### ISSUE TITLE
Crash (8.3): NullPointerException in EditPostSettingsFragment.fetchSiteSettingsAndUpdateDefaultPostFormatIfNecessary

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#6721]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.posts.EditPostActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.model.PostModel.getPostFormat()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5930)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wordpress.android.fluxc.model.PostModel.getPostFormat()' on a null object reference
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.fetchSiteSettingsAndUpdateDefaultPostFormatIfNecessary(EditPostSettingsFragment.java:169)
       at org.wordpress.android.ui.posts.EditPostSettingsFragment.onActivityCreated(EditPostSettingsFragment.java:155)
       at android.app.Fragment.performActivityCreated(Fragment.java:2120)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:928)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1065)
       at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1885)
       at android.app.Activity.performCreateCommon(Activity.java:6173)
       at android.app.Activity.performCreate(Activity.java:6199)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5930)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

https://fabric.io/automattic/android/apps/org.wordpress.android/issues/59ddfbbebe077a4dcc1aeb05

**Comment by mzorz** [comment]
Closing via #6727 (will keep an eye)
