### ISSUE TITLE
Async media crash when cancelling notifications

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#6804]
### Expected behavior
The app shouldn't crash :)

### Actual behavior
When adding some media to a draft, then exiting the editor, quickly tapping `trash` on such Post and quickly after exiting the Posts list screen, the `PostActivity` instance could get killed before the snackbar callback for post deletion gets run, thus offering no valid `Context` for the methods called in there.

```10-30 15:21:54.623 15832-15832/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: org.wordpress.android, PID: 15832
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
                                                                           at org.wordpress.android.util.SystemServiceFactoryDefault.get(SystemServiceFactoryDefault.java:7)
                                                                           at org.wordpress.android.util.SystemServiceFactory.get(SystemServiceFactory.java:12)
                                                                           at org.wordpress.android.ui.uploads.PostUploadNotifier.cancelFinalNotification(PostUploadNotifier.java:237)
                                                                           at org.wordpress.android.ui.uploads.UploadService.cancelQueuedPostUploadAndRelatedMedia(UploadService.java:371)
                                                                           at org.wordpress.android.ui.posts.PostsListFragment$8.onDismissed(PostsListFragment.java:613)
                                                                           at org.wordpress.android.ui.posts.PostsListFragment$8.onDismissed(PostsListFragment.java:596)
                                                                           at android.support.design.widget.BaseTransientBottomBar.onViewHidden(BaseTransientBottomBar.java:596)
                                                                           at android.support.design.widget.BaseTransientBottomBar$5$1.run(BaseTransientBottomBar.java:454)
                                                                           at android.os.Handler.handleCallback(Handler.java:789)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-30 15:21:54.628 939-9273/? W/ActivityManager:   Force finishing activity org.wordpress.android/.ui.main.WPMainActivity
```

**Comment by mzorz** [comment]
closing via #6805
