### ISSUE TITLE
Crash: NPE exiting posts list with in progress uploads

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-Android#6807]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
    at org.wordpress.android.util.SystemServiceFactoryDefault.get(SystemServiceFactoryDefault.java:7)
    at org.wordpress.android.util.SystemServiceFactory.get(SystemServiceFactory.java:12)
    at org.wordpress.android.ui.uploads.PostUploadNotifier.cancelFinalNotification(PostUploadNotifier.java:237)
    at org.wordpress.android.ui.uploads.UploadService.cancelQueuedPostUploadAndRelatedMedia(UploadService.java:371)
    at org.wordpress.android.ui.posts.PostsListFragment$8.onDismissed(PostsListFragment.java:613)
    at org.wordpress.android.ui.posts.PostsListFragment$8.onDismissed(PostsListFragment.java:596)
    at android.support.design.widget.BaseTransientBottomBar.onViewHidden(BaseTransientBottomBar.java:596)
    at android.support.design.widget.BaseTransientBottomBar$5$1.run(BaseTransientBottomBar.java:454)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Found the crash while going through steps in #6798. At some point there were failed uploads and when I exited the posts list back to the main activity (My SIte tab) it crashed.

**Comment by mzorz** [comment]
This is fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/6805, closing
