### ISSUE TITLE
Crash report 8.5-rc-1: NPE in MediaPreviewFragment.loadImage

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6818]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
       at org.wordpress.android.ui.media.MediaPreviewFragment.loadImage(MediaPreviewFragment.java:282)
       at org.wordpress.android.ui.media.MediaPreviewFragment.onResume(MediaPreviewFragment.java:206)
       at android.app.Fragment.performResume(Fragment.java:2398)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
       at android.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:869)
       at android.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1195)
       at android.app.FragmentManagerImpl.doPendingDeferredStart(FragmentManager.java:1605)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1589)
       at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:563)
       at android.support.v13.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:176)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
       at android.view.View.measure(View.java:21121)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:21121)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:21121)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:21121)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:21121)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:21121)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6462)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:897)
       at android.view.View.measure(View.java:21121)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2625)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1677)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1928)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
       at android.view.Choreographer.doCallbacks(Choreographer.java:734)
       at android.view.Choreographer.doFrame(Choreographer.java:670)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by mzorz** [comment]
Closing via #6820
