### ISSUE TITLE
Crash: NullPointerException in android.view.GhostView.GhostView

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Android#6857]
First appeared in version 8.4 but it really picked up in 8.7.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.transformMatrixToGlobal(android.graphics.Matrix)' on a null object reference
       at android.view.GhostView.calculateMatrix(GhostView.java:89)
       at android.app.ActivityTransitionCoordinator$GhostViewListeners.onPreDraw(ActivityTransitionCoordinator.java:1000)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2213)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
       at android.view.Choreographer.doFrame(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by daniloercoli** [comment]
Maybe this was introduced with the latest changes in Media, where we've added some shared element activity transitions. Maybe @nbradbury have more thoughts on this.

For reference I've just google'd the error and found this https://stackoverflow.com/questions/26566385/shared-element-activity-transition-on-android-5

**Comment by nbradbury** [comment]
Looking at the crash logs, I'm pretty sure @daniloercoli is right - the crash is due to the shared element transition added to `MediaSettingsActivity`. 

The crash is happening in the Android code [here](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/GhostView.java#89) and at this point I don't know what we can do about it.

**Comment by nbradbury** [comment]
Looks like Google is aware of this bug and have fixed it: https://issuetracker.google.com/issues/37943857

**Comment by maxme** [comment]
Fixed via https://github.com/wordpress-mobile/WordPress-Android/pull/6865
