### ISSUE TITLE
Crash report (develop): NPE in UploadStore.handleUpdateMedia

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6866]
Steps:

1. Create a new post
2. Go to post settings
3. Tap "Set featured image" button
4. Pick an image from the local library -> 💥 

```
  Process: org.wordpress.android.beta, PID: 6959
  org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
      at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
      at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
      at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
      at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:761)
   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.wordpress.android.fluxc.model.MediaModel.getId()' on a null object reference
      at org.wordpress.android.fluxc.store.UploadStore.handleUpdateMedia(UploadStore.java:337)
      at org.wordpress.android.fluxc.store.UploadStore.onMediaAction(UploadStore.java:131)
      at org.wordpress.android.fluxc.store.UploadStore.onAction(UploadStore.java:98)
      at java.lang.reflect.Method.invoke(Native Method)
      at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
      at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479) 
      at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46) 
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
      at java.lang.Thread.run(Thread.java:761) 
```

**Comment by nbradbury** [comment]
@maxme I'm unable to repro this. Is this happening consistently for you, and if so, what device/API?

**Comment by maxme** [comment]
It was on a Genymotion emulator Android 7.1 - I just noticed this crash appears in Crashlytics (wpandroid 8.8-rc-2) on a Samsung Galaxy Tab, Android 7.0.

**Comment by maxme** [comment]
I tried again, and I think this only happens on remote sources (Google Drive for example): https://cloudup.com/cLgYfzUXzEf

I was able to repro in branch `release/8.8`.

**Comment by mzorz** [comment]
Closing via #6902
