### ISSUE TITLE
Crash report 8.8: NPE in SiteSettingsFragment

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6888]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
       at org.wordpress.android.util.ToastUtils.showToast(ToastUtils.java:23)
       at org.wordpress.android.util.ToastUtils.showToast(ToastUtils.java:19)
       at org.wordpress.android.ui.prefs.SiteSettingsFragment.onSaveError(SiteSettingsFragment.java:683)
       at org.wordpress.android.ui.prefs.SiteSettingsInterface$3.run(SiteSettingsInterface.java:965)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5930)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

and similar:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
       at org.wordpress.android.util.ToastUtils.showToast(ToastUtils.java:23)
       at org.wordpress.android.util.ToastUtils.showToast(ToastUtils.java:19)
       at org.wordpress.android.ui.prefs.SiteSettingsFragment.onFetchError(SiteSettingsFragment.java:689)
       at org.wordpress.android.ui.prefs.SiteSettingsInterface$2.run(SiteSettingsInterface.java:952)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
```

**Comment by tonyr59h** [comment]
Closed via #6907.
