### ISSUE TITLE
Crash report 8.7: NPE in PublicizeButtonPrefsFragment

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6890]
```
Fatal Exception: java.lang.NullPointerException
       at org.wordpress.android.ui.publicize.PublicizeButtonPrefsFragment.getSiteSettings(PublicizeButtonPrefsFragment.java:289)
       at org.wordpress.android.ui.publicize.PublicizeButtonPrefsFragment.onViewStateRestored(PublicizeButtonPrefsFragment.java:140)
       at android.app.Fragment.restoreViewState(Fragment.java:617)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:910)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
       at android.app.BackStackRecord.run(BackStackRecord.java:685)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:149)
       at android.app.ActivityThread.main(ActivityThread.java:5268)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by aforcier** [comment]
Fixed in #6915.
