### ISSUE TITLE
Crash report 8.9: Unable to start activity ... accounts.LoginActivity

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#6975]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.accounts.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.CheckableImageButton.setChecked(boolean)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2947)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4974)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.CheckableImageButton.setChecked(boolean)' on a null object reference
       at android.support.design.widget.TextInputLayout.passwordVisibilityToggleRequested(TextInputLayout.java:1336)
       at android.support.design.widget.TextInputLayout.onRestoreInstanceState(TextInputLayout.java:1030)
       at android.view.View.dispatchRestoreInstanceState(View.java:16875)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3470)
       at android.support.design.widget.TextInputLayout.dispatchRestoreInstanceState(TextInputLayout.java:1038)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3476)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3476)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3476)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3476)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3476)
       at android.view.View.restoreHierarchyState(View.java:16853)
       at android.support.v4.app.Fragment.restoreViewState(Fragment.java:510)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1445)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:560)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
       at android.app.Activity.performStart(Activity.java:6929)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4974)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

https://fabric.io/automattic/android/apps/org.wordpress.android/issues/5a143d9861b02d480dee7506?time=last-ninety-days

**Comment by theck13** [comment]
### Reproducing
I can reproduce the crash by following the steps below.

0. Clear app data.
1. Tap ***Log In*** button.
2. Enter WordPress.com email address into ***Email address** field.
3. Tap ***Next*** button.
4. Tap ***Enter your password instead*** button.
5. Tap visibility toggle button in ***Password*** field.
6. Rotate device.

Tapping the visibility toggle button a second time before rotating the device does *not* cause a crash.  Replacing the [`WPLoginInputRow` view](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/layout/login_email_password_screen.xml#L60-L73) with [`TextInputLayout`](https://android.googlesource.com/platform/frameworks/support.git/+/master/design/src/android/support/design/widget/TextInputLayout.java) and `TextInputEditText` does *not* cause a crash.

### Troubleshooting
It appears to be caused by the [`TextInputLayout.setPasswordVisibilityToggleEnabled` call in the `WPLoginInputRow` class](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/widgets/WPLoginInputRow.java#L88-L89), which calls the [`TextInputLayout.updatePasswordToggleView`](https://android.googlesource.com/platform/frameworks/support.git/+/master/design/src/android/support/design/widget/TextInputLayout.java#1288) method containing the [`mPasswordToggleView` initialization](https://android.googlesource.com/platform/frameworks/support.git/+/master/design/src/android/support/design/widget/TextInputLayout.java#1103).  When the device is rotated with the visibility enabled, [`shouldShowPasswordIcon()`](https://android.googlesource.com/platform/frameworks/support.git/+/master/design/src/android/support/design/widget/TextInputLayout.java#1101) returns `false` when `WPLoginInputRow` is used and `true` when `TextInputLayout` and `TextInputEditText` are used.  When `shouldShowPasswordIcon()` returns `false`, `mPasswordToggleView` is not initialized and a [`NullPointerException` occurs](https://android.googlesource.com/platform/frameworks/support.git/+/master/design/src/android/support/design/widget/TextInputLayout.java#1338).

#### Note
This crash also occurs on the login username/password screen since the [`WPLoginInputRow` view is used as a password field in that layout](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/res/layout/login_username_password_screen.xml#L91-L101) too.

**Comment by JeneaVranceanu** [comment]
Possible fix for this issue: https://stackoverflow.com/a/56414903/7210237
