### ISSUE TITLE
Plugins page failed silently with permissions error

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-Android#7013]
### Expected behavior
To be able to view and manage the plugins on my self-hosted site

### Actual behavior
I was presented with a blank screen

![wp-android-plugins-blank](https://user-images.githubusercontent.com/7233112/34221114-d3914c5a-e584-11e7-8464-e78fee47e791.jpg)

### Steps to reproduce the behavior
1) Open the app and select a Jetpack site
2) Navigate to the Plugins screen

This was on a Pressable site that I'd created a while ago.  I created new sites (both on Pressable and elsewhere) and did not see the issue.  I then disconnected and reconnected Jetpack and was able to successfully see the plugins.

I'm guessing there's nothing we can really do from the app side to guarantee success, but it would be nice to display an error message with potential troubleshooting steps or a link to support rather than a blank screen.

Here are the relevent app log entries from the failure:
```
76 - [Dec-20 17:46 API] PluginStore onRegister
77 - [Dec-20 17:46 API] Dispatching action: PluginAction-FETCH_SITE_PLUGINS
78 - [Dec-20 17:46 API] Volley error on https://public-api.wordpress.com/rest/v1.2/sites/109843440/plugins/?locale=en_US - exception: null
79 - [Dec-20 17:46 API] StackTrace: com.android.volley.AuthFailureError
 at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:171)
 at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)

80 - [Dec-20 17:46 API] Dispatching action: PluginAction-FETCHED_SITE_PLUGINS
81 - [Dec-20 17:46 API] An error occurred while fetching the plugins: User does not have permission to view plugins.
82 - [Dec-20 17:46 READER] reader post list > saving instance state
83 - [Dec-20 17:46 UTILS] trackLastActivity, activityId: My Site
84 - [Dec-20 17:46 API] Dispatching action: AccountAction-FETCH_ACCOUNT
85 - [Dec-20 17:46 READER] reader post list > resumed from paused state
86 - [Dec-20 17:46 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
87 - [Dec-20 17:46 API] Dispatching action: PluginAction-FETCH_SITE_PLUGINS
88 - [Dec-20 17:46 API] Volley error on https://public-api.wordpress.com/rest/v1.2/sites/109843440/plugins/?locale=en_US - exception: null
89 - [Dec-20 17:46 API] StackTrace: com.android.volley.AuthFailureError
 at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:171)
 at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)

90 - [Dec-20 17:46 API] Dispatching action: PluginAction-FETCHED_SITE_PLUGINS
91 - [Dec-20 17:46 API] An error occurred while fetching the plugins: User does not have permission to view plugins.
92 - [Dec-20 17:46 READER] reader post list > saving instance state
93 - [Dec-20 17:46 UTILS] trackLastActivity, activityId: My Site
94 - [Dec-20 17:46 API] Dispatching action: AccountAction-FETCH_ACCOUNT
95 - [Dec-20 17:46 READER] reader post list > resumed from paused state
96 - [Dec-20 17:46 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
97 - [Dec-20 17:46 UTILS] trackLastActivity, activityId: Me
98 - [Dec-20 17:46 UTILS] trackLastActivity, activityId: Help Screen
99 - [Dec-20 17:46 READER] reader post list > saving instance state
```

I did confirm via Calypso web that I was able to view the plugins, so I'm not sure where the permissions error was coming from.

**Comment by oguzkocer** [comment]
@hoverduck We specifically didn't show errors from fetch plugins because it's not a user triggered action and except for rare cases like this one, it doesn't really make sense to show the user an error.

I'll look into this and see what we can do about it. Thanks!

**Comment by enejb** [comment]
Can I have more info as to what site and what user this is effecting?

**Comment by oguzkocer** [comment]
@enejb It looks like the original issue was for the site id: `109843440` @hoverduck might be able to tell who the user was.

As discussed on Slack, we also experienced this issue with @elibud for the site `http://testelibud.com/` and user `oguzkocer`. She invited me to the site as an administrator on Feb 15 and after I accepted it that day, I couldn't fetch the site plugins. After waiting for a couple days, I was still unable to fetch the plugins and got the same error as @hoverduck's user which is `User does not have permission to view plugins.`.

I think you can easily replicate the issue by following the same steps which should provide a better way to debug the issue. Let me know if I can help any with it any further. Thanks!

**Comment by hoverduck** [comment]
Yeah, this was just a test site that I had (https://hoverduck.mystagingwebsite.com).  It was a Pressable site running with an old import from my wpcom site, but it hadn't been touched in a long time prior to using it for this test.
