### ISSUE TITLE
Crash report 9.0 - 9.0.1: SecurityException in MediaBrowserActivity

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#7041]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.media.MediaBrowserActivity}: java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.photos.contentprovider.impl.MediaContentProvider from ProcessRecord{9d9ac69 9051:org.wordpress.android/u0a207} (pid=9051, uid=10207) that is not exported from uid 10194
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2984)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.photos.contentprovider.impl.MediaContentProvider from ProcessRecord{9d9ac69 9051:org.wordpress.android/u0a207} (pid=9051, uid=10207) that is not exported from uid 10194
       at android.os.Parcel.readException(Parcel.java:1693)
       at android.os.Parcel.readException(Parcel.java:1646)
       at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4920)
       at android.app.ActivityThread.acquireProvider(ActivityThread.java:6043)
       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2474)
       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1521)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1135)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:988)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:708)
       at org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:221)
       at org.wordpress.android.util.WPMediaUtils.fetchMediaAndDoNext(WPMediaUtils.java:463)
       at org.wordpress.android.ui.media.MediaBrowserActivity.uploadList(MediaBrowserActivity.java:714)
       at org.wordpress.android.ui.media.MediaBrowserActivity.handleSharedMedia(MediaBrowserActivity.java:908)
       at org.wordpress.android.ui.media.MediaBrowserActivity.onCreate(MediaBrowserActivity.java:164)
       at android.app.Activity.performCreate(Activity.java:6955)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

[Crashlytics](https://www.fabric.io/automattic/android/apps/org.wordpress.android/issues/5a3a61828cb3c2fa634aaa69)

**Comment by mzorz** [comment]
Adding information as per what I could investigate. The problem here is that the permission to the shared files in Google Photos is temporary, and apparently  the context  is lost before all items are enqueued to be uploaded (in other words, the user must be leaving the ShareIntentReceiverActivity?).

I’ve tested several paths but couldn’t reproduce:

**CASE A**
0. make sure you upload photos to Google Photos on the web (i.e. make sure they are not on the device), to force the need to download external media) (later on I’d realise the Google Photos app downloads the media before passing the share intent)
1. turn “don’t keep activities” on
2. go to the Google Photos app and select multiple items
3. share to WordPress app
4. on the WP app, choose a site and tap on “add to media library”
5. observe the items are added to the grid and they start to upload
6. tap BACK to exit the Media Browser activity (and thus we lose context?)
7. expected the crash to happen but it didn’t happen

**CASE B**:
0. log out of the app, so the ShareINtentReceiverActivity opens the login flow and hoping that this way we lose context by the time we reach to the MediaBrowserAcivity.
1. repeat case A
also can't reproduce.

**Comment by daniloercoli** [comment]
I've tried to reproduce the issue in several ways with no luck.
At this point, I think we should ask for permissions about write storage, and download pictures locally as soon as `ShareIntentReceiverActivity` is created for the first time. OFC, do this when pictures are shares to WP, and not only text.

In other words download all the media files a step earlier, and pass the new URLs instead to the MediaLibrary or EditPost activity. In this way we're sure there is no different context. 
```
        if (Intent.ACTION_SEND_MULTIPLE.equals(action)) {
            ArrayList<Uri> extra = getIntent().getParcelableArrayListExtra((Intent.EXTRA_STREAM));
            intent.putExtra(Intent.EXTRA_STREAM, extra);
        } else {
            Uri extra = getIntent().getParcelableExtra(Intent.EXTRA_STREAM);
            intent.putExtra(Intent.EXTRA_STREAM, extra);
        }
```

For what is worth I don't see a lot of users affected by this crash, that was introduced in `9.0`. Maybe it's the new login flow activities, that can cause the content lost issue? Should we just close it since the low users affected by it?
