### ISSUE TITLE
Crash report in 9.1: ISE in LoginEmailFragment.onCreate

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#7106]
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.accounts.LoginActivity}: java.lang.IllegalStateException: Already managing a GoogleApiClient with id 1001
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3506)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by java.lang.IllegalStateException: Already managing a GoogleApiClient with id 1001
       at com.google.android.gms.common.internal.zzac.zza(Unknown Source)
       at com.google.android.gms.internal.zzzt.zza(Unknown Source)
       at com.google.android.gms.common.api.GoogleApiClient$Builder.zzf(Unknown Source)
       at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
       at org.wordpress.android.ui.accounts.login.LoginEmailFragment.onCreate(LoginEmailFragment.java:234)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2339)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
       at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1109)
       at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:996)
       at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:99)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2364)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:449)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
       at android.app.Activity.performResume(Activity.java:6770)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3477)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

https://fabric.io/automattic/android/apps/org.wordpress.android/issues/5a3b85fc8cb3c2fa635a5531

**Comment by hypest** [comment]
Reopening as it seems to still be happening, albeit with a bit different stacktrace (no `Unable to resume activity`):

```
Fatal Exception: java.lang.IllegalStateException: Already managing a GoogleApiClient with id 1001
       at com.google.android.gms.common.internal.zzac.zza(Unknown Source)
       at com.google.android.gms.internal.zzzt.zza(Unknown Source)
       at com.google.android.gms.common.api.GoogleApiClient$Builder.zzf(Unknown Source)
       at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
       at org.wordpress.android.login.LoginEmailFragment.onCreate(LoginEmailFragment.java:223)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2339)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
       at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1109)
       at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:996)
       at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:99)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2364)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6379)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:111)
```

**Comment by maxme** [comment]
Still happening in 9.5:

```
Fatal Exception: java.lang.IllegalStateException: Already managing a GoogleApiClient with id 1001
       at com.google.android.gms.common.internal.zzac.zza(Unknown Source)
       at com.google.android.gms.internal.zzzt.zza(Unknown Source)
       at com.google.android.gms.common.api.GoogleApiClient$Builder.zzf(Unknown Source)
       at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
       at org.wordpress.android.login.LoginEmailFragment.onCreate(LoginEmailFragment.java:229)
```

**Comment by mzorz** [comment]
Closing via #7550, but let's keep an eye on this and see if it needs reopening 👍
