### ISSUE TITLE
Crash report 9.1: IAE in PluginUtils.isUpdateAvailable

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#7116]
```
Fatal Exception: java.lang.IllegalArgumentException: Invalid version format
       at org.wordpress.android.util.helpers.Version.<init>(Version.java:15)
       at org.wordpress.android.ui.plugins.PluginUtils.isUpdateAvailable(PluginUtils.java:48)
       at org.wordpress.android.ui.plugins.PluginListActivity$PluginListAdapter.onBindViewHolder(PluginListActivity.java:230)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
       at android.view.View.layout(View.java:19627)
       at android.view.ViewGroup.layout(ViewGroup.java:6060)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
       at android.view.View.layout(View.java:19627)
       at android.view.ViewGroup.layout(ViewGroup.java:6060)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19627)
       at android.view.ViewGroup.layout(ViewGroup.java:6060)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19627)
       at android.view.ViewGroup.layout(ViewGroup.java:6060)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19627)
       at android.view.ViewGroup.layout(ViewGroup.java:6060)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19627)
       at android.view.ViewGroup.layout(ViewGroup.java:6060)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
       at android.view.View.layout(View.java:19627)
       at android.view.ViewGroup.layout(ViewGroup.java:6060)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2488)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2204)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1390)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6754)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
       at android.view.Choreographer.doCallbacks(Choreographer.java:778)
       at android.view.Choreographer.doFrame(Choreographer.java:713)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6548)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by maxme** [comment]
Similar to that one https://github.com/wordpress-mobile/WordPress-Android/issues/7082
