### ISSUE TITLE
Crash report 9.1: IOOB in AztecText.fromHtml

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#7146]
This issue should be in the Aztec project, but for tracking the milestone, please keep it here.

```
Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (46 ... 46) ends beyond length 44
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
       at android.text.Selection.setSelection(Selection.java:76)
       at android.text.Selection.setSelection(Selection.java:87)
       at android.widget.EditText.setSelection(EditText.java:98)
       at org.wordpress.aztec.AztecText.fromHtml(AztecText.kt:919)
       at org.wordpress.aztec.AztecText.paste(AztecText.kt:1268)
       at org.wordpress.aztec.AztecText.onTextContextMenuItem(AztecText.kt:1180)
       at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:3249)
       at com.android.internal.policy.PhoneWindow$DecorView$ActionModeCallback2Wrapper.onActionItemClicked(PhoneWindow.java:3540)
       at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:85)
       at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
       at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
       at com.android.internal.view.FloatingActionMode$4.onMenuItemClick(FloatingActionMode.java:111)
       at com.android.internal.widget.FloatingToolbar$FloatingToolbarMainPanel$1.onClick(FloatingToolbar.java:1015)
       at android.view.View.performClick(View.java:5205)
       at android.view.View$PerformClick.run(View.java:21164)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by daniloercoli** [comment]
There is already a PR for this here: https://github.com/wordpress-mobile/AztecEditor-Android/pull/613
