### ISSUE TITLE
Crash when logging in WPCOM, after being logged in .org sites

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7302]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
    at org.wordpress.android.login.LoginUsernamePasswordFragment.detectNewlyAddedXMLRPCSite(LoginUsernamePasswordFragment.java:363)
    at org.wordpress.android.login.LoginUsernamePasswordFragment.onSiteChanged(LoginUsernamePasswordFragment.java:510)
    at java.lang.reflect.Method.invoke(Native Method)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6121)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Steps to reproduce:
1. Have the app logged in to .org site(s) only
2. Go to the "Me" tab/screen and tap on "Log in to WordPess.com"
3. Login via username/pass
4. Quickly rotate the screen right after hitting the final "Next" button to login
5. After a bit of time: 💥

**Comment by mzorz** [comment]
Closed via #7356
