### ISSUE TITLE
Crash report alpha-100: NPE in PluginDetailActivity.refreshViews

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#7306]
Steps to reproduce:

* Ensure you have alpha-100 installed.
* Switch to a Jetpack site.
* Go to Plugins.
* Search for “instagram”.
* Tap on “WP Instagram Widget by Scott Evans”.

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at java.io.StringReader.<init>(StringReader.java:50)
       at android.text.HtmlToSpannedConverter.convert(Html.java:746)
       at android.text.Html.fromHtml(Html.java:242)
       at android.text.Html.fromHtml(Html.java:185)
       at org.wordpress.android.ui.plugins.PluginDetailActivity.refreshViews(PluginDetailActivity.java:406)
       at org.wordpress.android.ui.plugins.PluginDetailActivity.setupViews(PluginDetailActivity.java:383)
       at org.wordpress.android.ui.plugins.PluginDetailActivity.onCreate(PluginDetailActivity.java:186)
       at android.app.Activity.performCreate(Activity.java:6999)
       at android.app.Activity.performCreate(Activity.java:6990)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by oguzkocer** [comment]
Closed by #7307
