### ISSUE TITLE
Crash on v9.4: ISE Can not perform this action after onSaveInstanceState in addGoogleLoginFragment

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7360]
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2044)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2067)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:680)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:634)
       at org.wordpress.android.ui.accounts.LoginActivity.addGoogleLoginFragment(LoginActivity.java:470)
       at org.wordpress.android.login.LoginEmailFragment$3.onClick(LoginEmailFragment.java:147)
       at android.view.View.performClick(View.java:5265)
       at android.view.View$PerformClick.run(View.java:21534)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by rachelmcr** [comment]
Closing as we haven't seen this since 9.9 (5aeea8d211e9fa0aa59d12c3-fabric).
