### ISSUE TITLE
Crash on v9.4: ISE: Can not perform this action after onSaveInstanceState at onCredentialsUnavailable

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7361]
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2044)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2067)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:680)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:634)
       at org.wordpress.android.ui.accounts.LoginActivity.showFragment(LoginActivity.java:125)
       at org.wordpress.android.ui.accounts.LoginActivity.startLogin(LoginActivity.java:259)
       at org.wordpress.android.ui.accounts.LoginActivity.onCredentialsUnavailable(LoginActivity.java:588)
       at org.wordpress.android.ui.accounts.SmartLockHelper$1.onResult(SmartLockHelper.java:107)
       at org.wordpress.android.ui.accounts.SmartLockHelper$1.onResult(SmartLockHelper.java:82)
       at com.google.android.gms.internal.zzzx$zza.zzb(Unknown Source)
       at com.google.android.gms.internal.zzzx$zza.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**Comment by rachelmcr** [comment]
Closing as I can't find an open report of this crash in Fabric. Please reopen if I'm missing something!
