### ISSUE TITLE
Crash on v9.4: NPE in WPLoginInputRow.getEditText() at LoginActivity.onActivityResult

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7362]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.EditText org.wordpress.android.login.widgets.WPLoginInputRow.getEditText()' on a null object reference
       at org.wordpress.android.login.LoginEmailFragment.onActivityResult(LoginEmailFragment.java:420)
       at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
       at org.wordpress.android.ui.accounts.LoginActivity.onActivityResult(LoginActivity.java:195)
       at android.app.Activity.dispatchActivityResult(Activity.java:7295)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4516)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
       at android.app.ActivityThread.-wrap22(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by rachelmcr** [comment]
It looks like we're still getting this crash in 11.4, although very low frequency (5bec9095f8b88c2963f23d27-fabric).

**Comment by designsimply** [comment]
I searched in Sentry and could not find a recent crash report matching this. Noting it as a candidate for closing in the next Groundskeeping Android rotation.

**Comment by planarvoid** [comment]
I think this might be the related Sentry crash - 1019195395-sentry. It seems to happen very rarely @designsimply

**Comment by designsimply** [comment]
Nice find!

**Comment by designsimply** [comment]
I also added you as the assignee because I saw that you had opened a PR for this. 🙂

**Comment by designsimply** [comment]
@planarvoid can this issue be closed based on https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/pull/16 ?

**Comment by designsimply** [comment]
Crash report numbers for this one are very low. 

**Impact:** 5 in the last 30 days
**Users affected:** 5 in the last 30 days
**Last seen in:** 12.4
<sub>(https://sentry.io/share/issue/1cda5ef2190342e9b174cb54998238e5/)</sub>

Noting that we can leave it open since the crash report is not completely empty and that we should check it at the next Groundskeeping rotation and close if it makes sense.

**Comment by planarvoid** [comment]
@designsimply It looks like it's the same issue that was already fixed. Let's keep an eye on this to be sure.

**Comment by malinajirka** [comment]
I haven't found any recent occurrences of this crash. It seems the fix in the Login-Flow-Library did fix the issue. 🎉
