### ISSUE TITLE
Caught exception: RuntimeException: Internal inconsistency error! mSmartLockHelper found null!

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7371]
```
Non-fatal Exception: java.lang.RuntimeException: Internal inconsistency error! mSmartLockHelper found null!
       at org.wordpress.android.ui.accounts.LoginActivity.saveCredentialsInSmartLock(LoginActivity.java:532)
       at org.wordpress.android.login.LoginBaseFormFragment.saveCredentialsInSmartLock(LoginBaseFormFragment.java:271)
       at org.wordpress.android.login.LoginEmailPasswordFragment.onCredentialsOK(LoginEmailPasswordFragment.java:265)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:420)
       at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
       at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
       at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
       at org.wordpress.android.login.LoginWpcomService.signalCredentialsOK(LoginWpcomService.java:286)
       at org.wordpress.android.login.LoginWpcomService.onAuthenticationChanged(LoginWpcomService.java:307)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:420)
       at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
       at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
       at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
       at org.wordpress.android.fluxc.Dispatcher.emitChange(Dispatcher.java:41)
       at org.wordpress.android.fluxc.store.Store.emitChange(Store.java:32)
       at org.wordpress.android.fluxc.store.AccountStore$1.onResponse(AccountStore.java:860)
       at org.wordpress.android.fluxc.store.AccountStore$1.onResponse(AccountStore.java:853)
       at org.wordpress.android.fluxc.network.rest.wpcom.auth.Authenticator$TokenRequest.deliverResponse(Authenticator.java:124)
       at org.wordpress.android.fluxc.network.rest.wpcom.auth.Authenticator$PasswordRequest.deliverResponse(Authenticator.java:141)
       at org.wordpress.android.fluxc.network.rest.wpcom.auth.Authenticator$TokenRequest.deliverResponse(Authenticator.java:106)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5113)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by designsimply** [comment]
**90-day impact:** 213 or ~2 per day
**Users affected in the last 90 days:** 83
<sub>https://sentry.io/share/issue/3b5d94c138ba4c89a97fbf273cdca69e/</sub>

**Comment by planarvoid** [comment]
I couldn't find this issue in Sentry so I assume it's been fixed
