### ISSUE TITLE
Crash: FileUriExposedException at GCMMessageService$NotificationHelper.showNotificationForBuilder

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7372]
```
Fatal Exception: android.os.FileUriExposedException: file:///storage/emulated/0/MIUI/ringtone/FringeNotificaci%C3%B3n.mp3 exposed beyond app through Notification.sound
       at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
       at android.net.Uri.checkFileUriExposed(Uri.java:2346)
       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:300)
       at android.app.NotificationManager.notify(NotificationManager.java:284)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:207)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:191)
       at org.wordpress.android.push.GCMMessageService$NotificationHelper.showNotificationForBuilder(GCMMessageService.java:734)
       at org.wordpress.android.push.GCMMessageService$NotificationHelper.showSingleNotificationForBuilder(GCMMessageService.java:677)
       at org.wordpress.android.push.GCMMessageService$NotificationHelper.buildAndShowNotificationFromNoteData(GCMMessageService.java:428)
       at org.wordpress.android.push.GCMMessageService$NotificationHelper.handleDefaultPush(GCMMessageService.java:331)
       at org.wordpress.android.push.GCMMessageService$NotificationHelper.access$100(GCMMessageService.java:302)
       at org.wordpress.android.push.GCMMessageService.synchronizedHandleDefaultPush(GCMMessageService.java:112)
       at org.wordpress.android.push.GCMMessageService.onMessageReceived(GCMMessageService.java:135)
       at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
       at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:760)
```

**Comment by JavonDavis** [comment]
Hey @hypest I'm similar crash on `13.2` I'm thinking the same fix we applied here should have prevented this, any thoughts on this one?
