### ISSUE TITLE
Crash on v9.2-v9.4: NoSuchMethodError in SiteSettingsTagListActivity

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7396]
```
Fatal Exception: java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.compareIgnoreCase
       at org.wordpress.android.ui.prefs.SiteSettingsTagListActivity$3.compare(SiteSettingsTagListActivity.java:275)
       at org.wordpress.android.ui.prefs.SiteSettingsTagListActivity$3.compare(SiteSettingsTagListActivity.java:273)
       at java.util.TimSort.countRunAndMakeAscending(TimSort.java:320)
       at java.util.TimSort.sort(TimSort.java:185)
       at java.util.TimSort.sort(TimSort.java:169)
       at java.util.Arrays.sort(Arrays.java:2023)
       at java.util.Collections.sort(Collections.java:1883)
       at org.wordpress.android.ui.prefs.SiteSettingsTagListActivity.loadTags(SiteSettingsTagListActivity.java:273)
       at org.wordpress.android.ui.prefs.SiteSettingsTagListActivity.onCreate(SiteSettingsTagListActivity.java:126)
       at android.app.Activity.performCreate(Activity.java:5242)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
       at android.app.ActivityThread.access$800(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5113)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Seems to be happening on Xiaomi devices only, Android v4 v5 v6.
Crashlytics ref: 5a761e5e8cb3c2fa633ce026

**Comment by daniloercoli** [comment]
Addressed in #7377
