### ISSUE TITLE
Crash on v9.1.1-9.4: ClassNotFoundException in Google SignIn

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#7397]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: ,佅￿$￿openid￿H108380595987-j91sm1alavcdgd81i2655kp8q1lbtvrc.apps.googleuserconte
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5441)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: ,佅￿$￿openid￿H108380595987-j91sm1alavcdgd81i2655kp8q1lbtvrc.apps.googleuserconte
       at android.os.Parcel.readException(Parcel.java:1601)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2661)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1507)
       at android.app.Activity.startActivityForResult(Activity.java:3933)
       at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
       at android.app.Activity.startActivityForResult(Activity.java:3894)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
       at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.zzj(Unknown Source)
       at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6257)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
       at android.app.ActivityThread.access$900(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5441)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

Crashlytics ref: 5a2d1a348cb3c2fa638efb85

**Comment by hypest** [comment]
This might be relevant: https://github.com/playgameservices/android-basic-samples/issues/207
