### ISSUE TITLE
Crash report 9.5: InflateException in SiteCreationDomainAdapter.onCreateViewHolder

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-Android#7475]
Specific to Android 4.x:

```
Fatal Exception: android.view.InflateException: Binary XML file line #0: Error inflating class EditText
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
       at org.wordpress.android.ui.accounts.signup.SiteCreationDomainAdapter.onCreateViewHolder(SiteCreationDomainAdapter.java:144)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5680)
       [...]
```

http://crashes.to/s/c63b5976d18

**Comment by maxme** [comment]
Please target the `release/9.5` branch.
