### ISSUE TITLE
Crash alpha-104 and 9.7-rc-1: StringIndexOutOfBounds in LoginActivity

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#7553]
```
Fatal Exception: java.lang.StringIndexOutOfBoundsException: length=2; regionStart=0; regionLength=-1
       at java.lang.String.substring(String.java:1931)
       at org.wordpress.android.ui.accounts.LoginActivity.onSignupSheetTermsOfServiceClicked(LoginActivity.java:369)
       at org.wordpress.android.login.SignupBottomSheetDialog$1.onClick(SignupBottomSheetDialog.java:25)
       at android.view.View.performClick(View.java:5646)
       at android.view.View$PerformClick.run(View.java:22450)
       at android.os.Handler.handleCallback(Handler.java:755)
       at android.os.Handler.dispatchMessage(Handler.java:95)
```
Ref. `5ab98f1e8cb3c2fa63028864`

**Comment by maxme** [comment]
Fixed via https://github.com/wordpress-mobile/WordPress-Android/pull/7554
