### ISSUE TITLE
Error with accented characters in Reader Tags

### ISSUE THREAD

**Issue by jeherve** [wordpress-mobile/WordPress-Android#7586]
I tried adding the "Pâques" tag to the Reader, but it seems it wasn't able to handle the accented character; it added "p??ques" instead.

And now that I've added it, I can't remove it; I receive an error when I try.

![screenshot_20180401-124530](https://user-images.githubusercontent.com/426388/38239549-54af1890-372d-11e8-90cd-ea0570a98e87.png)

### Logs

```
WordPress - alpha-105 - Version code: 547
Android device name: HTC U11
69 - [Apr-02 11:33 READER] reader post list > resumed from paused state
70 - [Apr-02 11:33 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
71 - [Apr-02 11:33 UTILS] trackLastActivity, activityId: Reader
72 - [Apr-02 11:33 READER] reader tag list > newInstance
73 - [Apr-02 11:33 READER] reader blog fragment > newInstance
74 - [Apr-02 11:33 READER] reader blog fragment > newInstance
75 - [Apr-02 11:33 READER] reader subs > refreshing tag fragment
76 - [Apr-02 11:33 READER] reader subs > refreshing blog fragment FOLLOWED
77 - [Apr-02 11:33 READER] reader subs > refreshing blog fragment RECOMMENDED
78 - [Apr-02 11:33 READER] reader service > created
79 - [Apr-02 11:33 READER] reader service > updating tags
80 - [Apr-02 11:33 READER] reader service > updating followed blogs
81 - [Apr-02 11:33 READER] reader service > updating recommended blogs
82 - [Apr-02 11:33 READER] reader post list > saving instance state
83 - [Apr-02 11:33 READER] delete tag failed
84 - [Apr-02 11:33 READER] null
85 - [Apr-02 11:33 READER] StackTrace: com.android.volley.ServerError
at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:179)
at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)

86 - [Apr-02 11:33 UTILS] trackLastActivity, activityId: Reader
87 - [Apr-02 11:33 API] Dispatching action: AccountAction-FETCH_ACCOUNT
88 - [Apr-02 11:33 READER] reader post list > resumed from paused state
89 - [Apr-02 11:33 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
90 - [Apr-02 11:33 READER] reader service > all tasks completed
91 - [Apr-02 11:33 READER] reader service > destroyed
92 - [Apr-02 11:33 UTILS] trackLastActivity, activityId: Me
93 - [Apr-02 11:33 READER] reader post list > saving instance state
```

<ul>
    <li>HTC U11</li>
    <li>WPAndroid Alpha 105</li>
</ul>

**Comment by planarvoid** [comment]
I've checked this behaviour and I think it's a bug on the backend. I can replicate the same behaviour on Calypso. Should we create another ticket to fix the API? @designsimply

**Comment by daniloercoli** [comment]
I managed to add "Pâques" to the reader, but it was added as "Paques" instead. It seems to be a backend issue, so I'm going to close this client-side ticket.
