### ISSUE TITLE
Crash report 10.1-rc-1: NPE in EditPostActivity

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#7791]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference
       at org.wordpress.android.ui.posts.EditPostActivity$SectionsPagerAdapter$1.onChanged(EditPostActivity.java:1844)
       at org.wordpress.android.ui.posts.EditPostActivity$SectionsPagerAdapter$1.onChanged(EditPostActivity.java:1842)
       at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
       at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:121)
       at android.arch.lifecycle.LiveData.access$400(LiveData.java:59)
       at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:416)
       at android.arch.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:368)
       at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:292)
       at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332)
       at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
       at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
       at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121)
       at android.arch.lifecycle.ReportFragment.onStart(ReportFragment.java:81)
       at android.app.Fragment.performStart(Fragment.java:2378)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1027)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
       at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2044)
       at android.app.FragmentController.dispatchStart(FragmentController.java:187)
       at android.app.Activity.performStart(Activity.java:6710)
       at android.app.Activity.performRestart(Activity.java:6778)
       at android.app.Activity.performResume(Activity.java:6783)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3477)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6251)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1073)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
```

internal ref. `5b040cce11e9fa0aa556fd9a`

**Comment by mzorz** [comment]
closing via #7793
