### ISSUE TITLE
ConcurrentModificationException in AppLog.toPlainText()

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Android#7906]
It looks like the app crashes if a new log occurs while `AppLog.toPlainText` is running. I have experienced this while working in the Zendesk branch, but I don't think it's directly related. In current `develop`, if the user tries to contact us through Helpshift, this could still happen since for example a FluxC event might occur (and log) at the same time as the `AppLog.toPlainText` is running.

We should check our crashes and see if we have any instances of it. If we do, we might want to address it in a release branch. /cc @mzorz 

If nobody else picks it up, I think I can work on this in a couple days.

```
06-13 22:12:20.349 16178-16178/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android.beta, PID: 16178
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at org.wordpress.android.util.AppLog.toPlainText(AppLog.java:347)
        at org.wordpress.android.support.ZendeskHelperKt.buildZendeskCustomFields(ZendeskHelper.kt:162)
        at org.wordpress.android.support.ZendeskHelperKt.buildZendeskConfig(ZendeskHelper.kt:141)
        at org.wordpress.android.support.ZendeskHelperKt.access$buildZendeskConfig(ZendeskHelper.kt:1)
        at org.wordpress.android.support.ZendeskHelper$createNewTicket$2.invoke(ZendeskHelper.kt:108)
        at org.wordpress.android.support.ZendeskHelper$createNewTicket$2.invoke(ZendeskHelper.kt:34)
        at org.wordpress.android.support.SupportHelper.getSupportIdentity(SupportHelper.kt:36)
        at org.wordpress.android.support.ZendeskHelper.createNewTicket(ZendeskHelper.kt:105)
        at org.wordpress.android.ui.accounts.HelpActivity.createNewZendeskTicket(HelpActivity.kt:86)
        at org.wordpress.android.ui.accounts.HelpActivity.access$createNewZendeskTicket(HelpActivity.kt:23)
        at org.wordpress.android.ui.accounts.HelpActivity$onCreate$1.onClick(HelpActivity.kt:56)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by oguzkocer** [comment]
I've checked Fabric and it looks like we **do** have crashes  for it, but it's not very frequent, so fixing in `develop` should be fine.
