### ISSUE TITLE
Crash: swiping to a notification next to a pingback notification

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-Android#7973]
I noticed a crash when using notifications: if you open a notification, then swipe left/right to move to a different notification, the app will crash when you reach a notification where the next one would be a pingback notification.

I've tried to debug this but I'm not sure how to make the android debugger stop on crash. I'm seeing this on the debug console though:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.wordpress.android, PID: 13542
                  java.lang.ClassCastException: org.wordpress.android.widgets.WPTextView cannot be cast to android.view.ViewGroup
                      at android.support.v4.app.FragmentTransition.configureTransitionsOrdered(FragmentTransition.java:310)
                      at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:134)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6123)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by koke** [comment]
This only happens for a specific notification that happens to be a pingback, but I've tried on different accounts and pingback notifications and it only happens in this one.

**Comment by designsimply** [comment]
I tried testing this with 13.6-rc-1 and couldn't replicate the crash. ([25s](https://cloudup.com/c9a5DogjRWV)) 😕
<sup>Tested with WPAndroid 13.6-rc-1 on Pixel 3 Android 10.</sup>

**Comment by designsimply** [comment]
Setting to low priority unless it comes up again or can be re-confirmed.

**Comment by malinajirka** [comment]
I checked Sentry and the app haven't crashed to anyone with this exception in the last 90 days => we probably fixed in another issue => closing.
