### ISSUE TITLE
Crash 10.3: NPE in ReaderPostListFragment onCreateView

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#7993]
```
Fatal Exception: java.lang.NullPointerException
       at org.wordpress.android.ui.reader.ReaderPostListFragment.onCreateView(ReaderPostListFragment.java:525)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:829)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
       at android.app.BackStackRecord.run(BackStackRecord.java:635)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:426)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4794)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
internal ref: `5b3b369b6007d59fcd7d2bc0`

**Comment by daniloercoli** [comment]
Marking this issue as closed since latest occurrences happened on August 30 with Version 10.3.1 (579)
