### ISSUE TITLE
Crash 10.3: IAE GCMRegistrationService No such service ComponentInfo...

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-Android#8000]
```
Caused by java.lang.IllegalArgumentException: No such service ComponentInfo{org.wordpress.android/org.wordpress.android.push.GCMRegistrationIntentService}
       at android.os.Parcel.readException(Parcel.java:1962)
       at android.os.Parcel.readException(Parcel.java:1904)
       at android.app.job.IJobScheduler$Stub$Proxy.enqueue(IJobScheduler.java:211)
       at android.app.JobSchedulerImpl.enqueue(JobSchedulerImpl.java:53)
       at android.support.v4.app.JobIntentService$JobWorkEnqueuer.enqueueWork(JobIntentService.java:342)
       at android.support.v4.app.JobIntentService.enqueueWork(JobIntentService.java:522)
       at android.support.v4.app.JobIntentService.enqueueWork(JobIntentService.java:500)
       at org.wordpress.android.push.GCMRegistrationIntentService.enqueueWork(GCMRegistrationIntentService.java:37)
       at org.wordpress.android.WordPress.deferredInit(WordPress.java:396)
       at org.wordpress.android.WordPress$ApplicationLifecycleMonitor.onActivityResumed(WordPress.java:932)
       at android.app.Application.dispatchActivityResumed(Application.java:240)
       at android.app.Activity.onResume(Activity.java:1364)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
       at org.wordpress.android.ui.main.WPMainActivity.onResume(WPMainActivity.java:420)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
       at android.app.Activity.performResume(Activity.java:7352)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.IllegalArgumentException: No such service ComponentInfo{org.wordpress.android/org.wordpress.android.push.GCMRegistrationIntentService}
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
internal ref: 5b3d1a576007d59fcda04d0a

**Comment by mzorz** [comment]
Seems to happen only on Android 8
