### ISSUE TITLE
Crash 10.3: AIOBE in AztecAttributes removeAttribute

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#8018]
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=5; index=-5
       at org.xml.sax.helpers.AttributesImpl.removeAttribute(AttributesImpl.java:444)
       at org.wordpress.aztec.AztecAttributes.removeAttribute(AztecAttributes.kt:45)
       at org.wordpress.aztec.source.CssStyleFormatter$Companion.removeStyleAttribute(CssStyleFormatter.kt:95)
       at org.wordpress.aztec.AztecParser.withinNestable(AztecParser.kt:402)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:381)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:333)
       at org.wordpress.aztec.AztecParser.toHtml(AztecParser.kt:92)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1157)
       at org.wordpress.aztec.AztecText.hasChanges(AztecText.kt:1115)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:868)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1264)
       at org.wordpress.android.ui.posts.EditPostActivity.access$900(EditPostActivity.java:179)
       at org.wordpress.android.ui.posts.EditPostActivity$4$1.run(EditPostActivity.java:560)
       at java.lang.Thread.run(Thread.java:762)
```

5b295c576007d59fcd47325c-fabric

**Comment by daniloercoli** [comment]
See: https://github.com/wordpress-mobile/AztecEditor-Android/issues/705

**Comment by 0nko** [comment]
Possibly fixed by https://github.com/wordpress-mobile/AztecEditor-Android/pull/758.
