### ISSUE TITLE
Crash: Aztec Index Out of Bounds Exception

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#8107]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: getChars (0 ... 139) ends beyond length 138
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1269)
       at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:1151)
       at android.text.TextUtils.getChars(TextUtils.java:89)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:66)
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:50)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1138)
       at org.wordpress.aztec.AztecText.toHtml(AztecText.kt:1122)
       at org.wordpress.android.editor.AztecEditorFragment.getContent(AztecEditorFragment.java:868)
       at org.wordpress.android.ui.posts.EditPostActivity.updatePostObject(EditPostActivity.java:1264)
       at org.wordpress.android.ui.posts.EditPostActivity.access$900(EditPostActivity.java:179)
       at org.wordpress.android.ui.posts.EditPostActivity$4$1.run(EditPostActivity.java:560)
       at java.lang.Thread.run(Thread.java:776)
```

First seen in 10.4

5b4072a46007d59fcdd8e216-fabric

**Comment by designsimply** [comment]
It appears this crash is still happening but only for older 10.x versions of the app. I am not sure at what point the issue becomes a candidate for closing when the issue does not happen in newer versions but still has a semi-high frequency. Adding to Groundskeeping for review.

**30-day impact:** ~7 per day
**Users affected:** 92
**Last seen in:** 10.7

<sup>(5b4072a46007d59fcdd8e216-fabric-android)</sup>

**Comment by planarvoid** [comment]
@designsimply I'd consider this issue fixed if it doesn't happen in newer versions. I think we generally expect people to be on the latest version of the app (the one that was released to 100%) and updating the app should be the first thing you do to fix any issue.

**Comment by designsimply** [comment]
Awesome. Thank you for the explanation!
