### ISSUE TITLE
Crash: Aztec array index out of bound

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#8108]
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
       at org.xml.sax.helpers.AttributesImpl.addAttribute(AttributesImpl.java:383)
       at org.wordpress.aztec.AztecAttributes.setValue(AztecAttributes.kt:13)
       at org.wordpress.aztec.source.CssStyleFormatter$Companion.addStyleAttribute(CssStyleFormatter.kt:122)
       at org.wordpress.aztec.AztecParser.withinNestable(AztecParser.kt:408)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:381)
       at org.wordpress.aztec.AztecParser.withinHtml(AztecParser.kt:333)
       at org.wordpress.aztec.AztecParser.toHtml(AztecParser.kt:92)
       at org.wordpress.aztec.AztecText.toPlainHtml(AztecText.kt:1157)
       at org.wordpress.aztec.AztecText.toHtml(AztecText.kt:1120)
       at org.wordpress.aztec.AztecText.toHtml$default(AztecText.kt:1119)
       at org.wordpress.aztec.AztecText.toFormattedHtml(AztecText.kt:1161)
       at org.wordpress.aztec.History.beforeTextChanged(History.kt:42)
       at org.wordpress.aztec.AztecText$addHistoryLoggingWatcher$historyLoggingWatcher$1.beforeTextChanged(AztecText.kt:520)
       at android.widget.TextView.sendBeforeTextChanged(TextView.java:8848)
       at android.widget.TextView.access$1100(TextView.java:282)
       at android.widget.TextView$ChangeWatcher.beforeTextChanged(TextView.java:11241)
       at android.text.SpannableStringBuilder.sendBeforeTextChanged(SpannableStringBuilder.java:956)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:466)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:437)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:30)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:679)
       at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:197)
       at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:279)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

First seen on 10.3.

5b2c7bb96007d59fcd7fb9b9-fabric

**Comment by daniloercoli** [comment]
It seems to me that this issue was already reported our Aztec repo here: https://github.com/wordpress-mobile/AztecEditor-Android/issues/705
