### ISSUE TITLE
Shooting and adding a photo fails iwth "Error downloading image"

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#8133]
### Expected behavior
While inside the editor and the post content, taking+adding a new photo should work normally.

### Actual behavior
After taking the photo, the app returns to the editor but the photo is not added and a Toast comes up with the "Error downloading image" message.

Checking logcat, I see this error:
```
08-02 12:22:43.253 5246-5246/org.wordpress.android.beta E/WordPress-UTILS: / exists, but is not accessible
    java.io.FileNotFoundException: / exists, but is not accessible
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at java.net.URL.openStream(URL.java:1057)
        at org.wordpress.android.util.MediaUtils.downloadExternalMedia(MediaUtils.java:227)
        at org.wordpress.android.ui.posts.EditPostActivity.fetchMediaList(EditPostActivity.java:2719)
        at org.wordpress.android.ui.posts.EditPostActivity.addMediaList(EditPostActivity.java:2390)
        at org.wordpress.android.ui.posts.EditPostActivity.addMedia(EditPostActivity.java:2382)
        at org.wordpress.android.ui.posts.EditPostActivity.addLastTakenPicture(EditPostActivity.java:2685)
        at org.wordpress.android.ui.posts.EditPostActivity.onActivityResult(EditPostActivity.java:2646)
        at android.app.Activity.dispatchActivityResult(Activity.java:6935)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4086)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3470)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

### Steps to reproduce the behavior
* start a new post
* go into the content area
* tap to add media
* tap on the “camera” icon and select “Take photo”
* take a new photo and return to the app
* `Error downloading image` pops up and no image is added to the post

##### Tested on [device], Android [version]
Nexus 5X running Android 7.1.2, app version alpha-120

**Comment by daniloercoli** [comment]
I have experienced this issue on a fresh installation on a new device. I think it was a problem with permissions since cannot reproduce it anymore. (It started working at the 2nd attempt, after I had given it permissions).

Note that I started with a blank device, with no photos, and selected take new photo.
