### ISSUE TITLE
Crash (10.3 to at least 10.5.1) while refreshing posts list

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-Android#8156]
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.List org.wordpress.android.fluxc.network.rest.wpcom.post.PostWPComRestResponse$PostsResponse.posts' on a null object reference
       at org.wordpress.android.fluxc.network.rest.wpcom.post.PostRestClient$3.onResponse(PostRestClient.java:112)
       at org.wordpress.android.fluxc.network.rest.wpcom.post.PostRestClient$3.onResponse(PostRestClient.java:107)
       at org.wordpress.android.fluxc.network.rest.GsonRequest.deliverResponse(GsonRequest.java:50)
       at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

5b1abbb16007d59fcd461166-crashlytics

**Comment by Reviewer210** [comment]
It might be a server error or a bug in your server. I have the solution for you, if your issue is not resolved yet.

**Comment by hypest** [comment]
👋 @Reviewer210 , happy to receive a PR, thanks for considering!

**Comment by Reviewer210** [comment]
No issue
