### ISSUE TITLE
Crash: Aztec Edit link IOOBE

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#8165]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: setSpan (-1 ... 346) starts before 0
       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1314)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
       at org.wordpress.aztec.formatting.InlineFormatter.applySpan(InlineFormatter.kt:192)
       at org.wordpress.aztec.formatting.InlineFormatter.joinStyleSpans(InlineFormatter.kt:274)
       at org.wordpress.aztec.formatting.InlineFormatter.applyInlineStyle(InlineFormatter.kt:174)
       at org.wordpress.aztec.formatting.InlineFormatter.applyInlineStyle$default(InlineFormatter.kt:104)
       at org.wordpress.aztec.formatting.InlineFormatter.handleInlineStyling(InlineFormatter.kt:72)
       at org.wordpress.aztec.watchers.InlineTextWatcher.afterTextChanged(InlineTextWatcher.kt:63)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:9387)
       at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:11956)
       at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1262)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:574)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:504)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:502)
       at org.wordpress.aztec.formatting.LinkFormatter.editLink(LinkFormatter.kt:112)
       at org.wordpress.aztec.AztecText.link(AztecText.kt:1426)
       at org.wordpress.aztec.AztecText$showLinkDialog$1.onClick(AztecText.kt:1474)
       at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6600)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
```

5b3df88f6007d59fcdadb85e-fabric

**Comment by designsimply** [comment]
Crashed ~24 times a day, 724 times for 293 users, in the last thirty days Feb 13 - Mar 14, 2019. 
<sub>(5b3df88f6007d59fcdadb85e-fabric)</sub>

**Comment by designsimply** [comment]
**30 day impact:** 5 times a day
**Noteworthy:** no occurrences for 11.9 or later in the last 30 days
<sub>(5b3df88f6007d59fcdadb85e-fabric-android)</sub>

**Comment by designsimply** [comment]
Still happening a couple times a day, and it seems to be dissipating.

**30-day impact:** ~2.5 per day
**Users affected:** 38
**Last seen in:** 11.7

<sup>(5b3df88f6007d59fcdadb85e-fabric-android)</sup>

**Comment by planarvoid** [comment]
It looks like this is not happening in the latest builds. I'm closing the issue.
