### ISSUE TITLE
Crash in MenuPopupHelper

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#8203]
New in 10.6: 
```
Fatal Exception: java.lang.IllegalStateException: MenuPopupHelper cannot be used without an anchor
       at com.android.internal.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:135)
       at android.widget.PopupMenu.show(PopupMenu.java:227)
       at org.wordpress.android.ui.media.MediaBrowserActivity.showAddMediaPopup(MediaBrowserActivity.java:842)
       at org.wordpress.android.ui.media.MediaGridFragment$3.onClick(MediaGridFragment.java:249)
       at android.view.View.performClick(View.java:6291)
       at android.view.View$PerformClick.run(View.java:24931)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

#0. Crashed: main
       at com.android.internal.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:135)
       at android.widget.PopupMenu.show(PopupMenu.java:227)
       at org.wordpress.android.ui.media.MediaBrowserActivity.showAddMediaPopup(MediaBrowserActivity.java:842)
       at org.wordpress.android.ui.media.MediaGridFragment$3.onClick(MediaGridFragment.java:249)
       at android.view.View.performClick(View.java:6291)
       at android.view.View$PerformClick.run(View.java:24931)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7425)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
5b669ad46007d59fcddb5140-fabric

**Comment by theck13** [comment]
Fortunately, this has already been fixed and will be included in the 10.7 release.
