### ISSUE TITLE
Crash (10.9-rc-1): NullPointerException in ReaderPostListFragment.onResume

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-Android#8311]
### Expected
When resuming the ***Reader*** tab, the app does not crash.

### Observed
When resuming the ***Reader*** tab, the app crashes.  See the stack trace below for details.

```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.reader.ReaderPostListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.wordpress.android.models.ReaderTag.equals(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3194)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3225)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1506)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:5541)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.wordpress.android.models.ReaderTag.equals(java.lang.Object)' on a null object reference
       at org.wordpress.android.ui.reader.ReaderPostListFragment.onResume(ReaderPostListFragment.java:397)
       at android.support.v4.app.Fragment.performResume(Fragment.java:2390)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1474)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3212)
       at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:217)
       at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
       at org.wordpress.android.ui.reader.ReaderPostListActivity.onResumeFragments(ReaderPostListActivity.java:91)
       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:171)
       at android.app.Activity.performResume(Activity.java:6192)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3183)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3225)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1506)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:5541)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

5b9800de6007d59fcd5de8be-fabric

**Comment by rachelmcr** [comment]
Fix in https://github.com/wordpress-mobile/WordPress-Android/pull/8312.
