### ISSUE TITLE
IllegalStateException after moving away from Pages

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#8401]
I've got the crash reported below a couple of seconds after moved away from Pages.

I was on Pages, deleted a page, went back to main app screen, and the went to posts-> create new post. The crash happened while i was in the editor with a blank content (it should not be related to the editor though). 

```
10-09 12:41:07.163 24498-24498/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android, PID: 24498
    org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
        at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:505)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:487)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
        at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Already resumed
        at kotlin.coroutines.experimental.SafeContinuation.resume(SafeContinuationJvm.kt:49)
        at org.wordpress.android.fluxc.store.PageStore.onPostChanged(PageStore.kt:179)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479) 
        at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
10-09 12:41:07.164 24498-24498/org.wordpress.android E/WordPress-EDITOR: HTML content of Aztec Editor before the crash:
10-09 12:41:07.173 24498-24498/org.wordpress.android D/WordPress-EDITOR: Below are the details of the content in the editor:
10-09 12:41:07.183 24498-24498/org.wordpress.android D/WordPress-EDITOR:   length = 0
    x        000 -> 000 : ChangeWatcher
    x        000 -> 000 : ChangeWatcher
    x        000 -> 000 : TextKeyListener
    x        000 -> 000 : SpanController
    <        000 -> 000 : START
    <        000 -> 000 : END
```

**Comment by designsimply** [comment]
<blockquote>I was on Pages, deleted a page, went back to main app screen, and the went to posts-> create new post. The crash happened while i was in the editor with a blank content.</blockquote>

I tried testing these steps using WPAndroid alpha-170 on Pixel 3 Android 9 and the app did not crash for me. 

@daniloercoli because you only saw the issue happen one time and because it has not come up again for over 6 months from what I can see, would you agree we can close this issue for now and re-visit if it gets reported again or do you think it should be tested a bit more before closing?

**Comment by malinajirka** [comment]
I've checked Sentry and it seems that this crash was fixed -> Closing.

**Comment by malinajirka** [comment]
Sentry Issue: [WORDPRESS-ANDROID-7G](https://sentry.io/organizations/a8c/issues/1020603375/?referrer=github_integration)

```
IllegalStateException: Already resumed
    at org.wordpress.android.fluxc.store.PageStore.onPostChanged(PageStore.kt:230)
...
(7 additional frame(s) were not displayed)

EventBusException: Invoking subscriber failed
    at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:527)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:509)
    at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
    at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
    at android.os.Handler.dispatchMessage(Handler.java:105)
...
(5 additional frame(s) were not displayed)

Invoking subscriber failed
```

Note: Thank you @jd-alexander for noticing I created a duplicated issue.
