### ISSUE TITLE
IllegalStateException while editing a new page

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#8402]
I was editing a new page, typing fast, and going back and forward between pages list, the editor screen, and the options screen. 
Got the crash reported below, although I'm not quite sure If I had just changed its status, or I was already back to the editor screen.

```
   
    --------- beginning of crash
10-09 12:38:21.001 19987-24110/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-6
    Process: org.wordpress.android, PID: 19987
    java.lang.IllegalStateException: post must not be null
        at org.wordpress.android.fluxc.store.PageStore.updatePageInDb(PageStore.kt:73)
        at org.wordpress.android.viewmodel.pages.PagesViewModel$changePageStatus$$inlined$let$lambda$1$1.doResume(PagesViewModel.kt:408)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
10-09 12:38:21.002 19987-24110/org.wordpress.android E/WordPress-EDITOR: HTML content of Aztec Editor before the crash:
10-09 12:38:21.032 19987-24110/org.wordpress.android E/WordPress-EDITOR: Ggggh
10-09 12:38:21.035 19987-24110/org.wordpress.android D/WordPress-EDITOR: Below are the details of the content in the editor:
10-09 12:38:21.111 19987-24110/org.wordpress.android D/WordPress-EDITOR: Ggggh  length = 5
    >----<       000 -> 005 : ChangeWatcher
    >----<       000 -> 005 : ChangeWatcher
    >----<       000 -> 005 : TextKeyListener
    >----<       000 -> 005 : SpanController
    <             000 -> 000 : START
    <             000 -> 000 : END
```

**Comment by mzorz** [comment]
I've experienced this same one a couple of times today, notes here:

I did this on a self-hosted site but I guess works for other sites as well.

0. go into Site Pages screen.
1. turn airplane mode ON
2. draft a new page
3. tap publish, tap PUBLISH NOW when confirm dialog appears
4. observe it appears in the PUBLISHED LIST with label `Local changes`
5. the overflow menu icon doesn't appear now, so there's no way to take action except for the following.
6. go back to the main screen, and then go into the Site Pages screen again
7. observe the overflow menu icon appears again on all items
8. now tap on the overflow menu icon of the recently created page (the one with `Local changes` under PUBLISHED tab)
9. tap `Move to Trash`
10. switch to the `TRASHED` tab
11. Observe it's there, but no overflow menu icon
12. pull to refresh
13. the item is now gone! Where is it?
14. switched tabs to search for it went back and boom crash:

```
10-31 12:57:18.389 1648-2753/system_process W/android.os.Debug: failed to get memory consumption info: -1
10-31 12:57:18.447 22292-11652/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-1
    Process: org.wordpress.android, PID: 22292
    java.lang.IllegalStateException: post must not be null
        at org.wordpress.android.fluxc.store.PageStore.updatePageInDb(PageStore.kt:79)
        at org.wordpress.android.viewmodel.pages.PagesViewModel$changePageStatus$$inlined$let$lambda$2$1.doResume(PagesViewModel.kt:423)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(ForkJoinPool.java:1112)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1156)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
10-31 12:57:18.451 1648-2753/system_process W/ActivityManager:   Force finishing activity org.wordpress.android/.ui.pages.PagesActivity
10-31 12:57:18.467 22292-22292/org.wordpress.android V/WordPress-UTILS: trackLastActivity, activityId: My Site
```

When trying to reproduce the same, at step 9 (Move to trash when offline) doesn't do anything.

Then I tried going online and moving some other Page to trash. It was moved there ,but when going back to the Main screen a snackbar appeared saying "Page published" (but I just moved it to trash didn't I?), and shortly after another crash (same as above):

```
1 13:10:23.397 13051-19058/org.wordpress.android E/AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-1
    Process: org.wordpress.android, PID: 13051
    java.lang.IllegalStateException: post must not be null
        at org.wordpress.android.fluxc.store.PageStore.updatePageInDb(PageStore.kt:79)
        at org.wordpress.android.viewmodel.pages.PagesViewModel$changePageStatus$$inlined$let$lambda$2$1.doResume(PagesViewModel.kt:423)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(ForkJoinPool.java:1112)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1156)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
10-31 13:10:23.400 1648-2323/system_process W/ActivityManager:   Force finishing activity org.wordpress.android/.ui.pages.PagesActivity
10-3
```

**Comment by loremattei** [comment]
I've experienced this as well today. It seems to start with 11.0 (5bd3504ef8b88c296350c7f9-fabric).
