### ISSUE TITLE
Crash: NPE in Parent Page View Model

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#8597]
New in 11.0

```
Fatal Exception: kotlin.KotlinNullPointerException
       at org.wordpress.android.viewmodel.pages.PageParentViewModel.isNotChild(PageParentViewModel.kt:93)
       at org.wordpress.android.viewmodel.pages.PageParentViewModel.access$isNotChild(PageParentViewModel.kt:25)
       at org.wordpress.android.viewmodel.pages.PageParentViewModel$loadPages$1.doResume(PageParentViewModel.kt:70)
       at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
       at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:149)
       at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:13)
       at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
       at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
       at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
       at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
       at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
       at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
``` 
5bc6aeeff8b88c29631774a4-fabric

**Comment by rachelmcr** [comment]
Closing as it looks like #8600 fixed this crash as of 11.2.
