### ISSUE TITLE
RTE: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#8660]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
```

New in 11.2
5bf389e2f8b88c2963a85654-fabric

**Comment by rachelmcr** [comment]
I checked and don't see any reports of this crash for versions after 11.2. Is this fixed?

**Comment by designsimply** [comment]
I checked Fabric and verified there are no new crash reports in the same Fabric report referenced above for versions newer than 11.2 and I didn't find anything in Sentry (tracking starting in 12.3) either. Adding to Groundskeeping for review and recommend closing.

**30-day impact:** ~4 per month
**Users affected:** 3
**Last seen in:** 11.2

<sup>(5bf389e2f8b88c2963a85654-fabric-android)</sup>

**Comment by planarvoid** [comment]
I'm closing this issue as it is no longer happening
