### ISSUE TITLE
NumberFormatException in NotesAdapter

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-Android#8741]
```
Fatal Exception: java.lang.NumberFormatException: For input string: ""
       at java.lang.Long.parseLong(Long.java:602)
       at java.lang.Long.valueOf(Long.java:804)
       at org.wordpress.android.ui.notifications.adapters.NotesAdapter.getItemId(NotesAdapter.java:203)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5823)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1191)
       at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:876)
       at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:895)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:764)
       at android.view.View.layout(View.java:19693)
       at android.view.ViewGroup.layout(ViewGroup.java:6079)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2536)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2252)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1432)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6861)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
       at android.view.Choreographer.doCallbacks(Choreographer.java:838)
       at android.view.Choreographer.doFrame(Choreographer.java:769)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:171)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

Crashes from 11.1 -> 11.4-rc-2

Fabric: http://crashes.to/s/104ba1b58de

**Comment by jtreanor** [comment]
This seems to be caused by `note.getId()` giving the empty string in `getItemId()` here: https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/ui/notifications/adapters/NotesAdapter.java#L203

**Comment by jtreanor** [comment]
This issue was caused by an API change that meant that the first note could have an empty ID. We have fixed the API bug that caused this.

It has also been fixed in the client by https://github.com/wordpress-mobile/WordPress-Android/pull/8742.
