### ISSUE TITLE
Not allowed to bind to service Intent (com.google.android.finsky.BIND_GET_INSTALL_REFERRER_SERVICE)

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-Android#8830]
It seems that in many cases, we're not able to use Google's download attribution.

We're not crashing because of it – but we are handling a `java.lang.SecurityException` thrown.

Stack trace:

```
Non-fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.finsky.BIND_GET_INSTALL_REFERRER_SERVICE cmp=com.android.vending/com.google.android.finsky.externalreferrer.GetInstallReferrerService }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1480)
       at android.app.ContextImpl.bindService(ContextImpl.java:1434)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
       at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:135)
       at org.wordpress.android.util.analytics.service.InstallationReferrerServiceLogic.performTask(InstallationReferrerServiceLogic.java:120)
       at org.wordpress.android.util.analytics.service.InstallationReferrerService.onStartCommand(InstallationReferrerService.java:48)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3394)
       at android.app.ActivityThread.-wrap21(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1632)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6284)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1094)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
```

It appears all that's required to fix this is the addition of the `com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE` permission, but that may or may not be something we want to add to the bundle?
(source: https://stackoverflow.com/questions/47706419/installreferrerclient-startconnection-throwing-error)

(someone else with the same issue: https://issuetracker.google.com/issues/70193614)

reference: 5bab95e3f8b88c29636353be-fabric

**Comment by theck13** [comment]
I wasn't able to reproduce the exception with any referral source.  I tried the emulator configuration described in the [Google issue](https://issuetracker.google.com/issues/70193614), but it didn't cause the exception either.  I did see the following entry in the log while using the Nexus 5X API 25 image with the stock emulator, but there was no exception.

```
installation_referrer_obtained, Properties: {"install_referrer":"utm_source=(not%20set)&utm_medium=(not%20set)"}
```

I couldn't find much while researching `BIND_GET_INSTALL_REFERRER_SERVICE`.  It could be caused by the `android:exported="false"` attribute in [`InstallationReferrerService`](https://github.com/wordpress-mobile/WordPress-Android/blob/4a6e3b7a331e067a432ae739af64d7b4e12aa61e/WordPress/src/main/AndroidManifest.xml#L653-L656), which doesn't allow applications outside of WordPress to bind to the service according to the [`android:exported`](https://developer.android.com/guide/topics/manifest/service-element#exported) documentation.  That documentation also states:

> You can also use a permission to limit the external entities that can interact with the service (see the [permission](https://developer.android.com/guide/topics/manifest/service-element#prmsn) attribute).

That implies we can add the `android:permission="android.permission.BIND_GET_INSTALL_REFERRER_SERVICE"` attribute to [`InstallationReferrerService`](https://github.com/wordpress-mobile/WordPress-Android/blob/4a6e3b7a331e067a432ae739af64d7b4e12aa61e/WordPress/src/main/AndroidManifest.xml#L653-L656) and fix the exception, but I couldn't find anything confirming that and I'm not sure what security implications that could cause.

It looks like we did everything correctly according to the [Android Developers Blog post](https://android-developers.googleblog.com/2017/11/google-play-referrer-api-track-and.html) and 
[Play Install Referrer Library documentation](https://developer.android.com/google/play/installreferrer/library).  I'd like to summon @mzorz (creator of the [installation referral service](https://github.com/wordpress-mobile/WordPress-Android/pull/8299)) and @hypest (creator of the [security exception safe guard](https://github.com/wordpress-mobile/WordPress-Android/pull/8359)) for some help.

**Comment by mzorz** [comment]
Oh I see the problem. I think the problem is that we've encapsulated the `InstallReferrer` client inside a Service, and the Service is not exported, hence it cannot be invoked / bound to externally. 

I checked the issue in Fabric, seeing that all of the devices having this problem have Android 6 or below. This indicates it's a problem with the `Service` (as opposed to the `JobService`) as we run it [for devices below API 26](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/util/analytics/service/InstallationReferrerServiceStarter.java#L21).

The [gradle declaration](https://developer.android.com/google/play/installreferrer/library)  for the plugin already adds the `uses-permission` line for `BIND_GET_INSTALL_REFERRER_SERVICE`, I confirmed this by using `aapt` tool on the [production apk](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/11.4) `aapt l -a wpandroid-11.4.apk`

```
E: uses-permission (line=64)
      A: android:name(0x01010003)="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" (Raw: "com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE")
```

The specific documentation about install referrer doesn't mention the service part because it's assuming code is going to be called from elsewhere.

Following this, I think we should, as per @theck13 's suggestion:
1. add `android:exported="true"` to make it available,  and 
2. add `android:permission="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE"`  to restrict it to only be called from the vending app. 

To test @jkmassel , we'd need to deliver a new alpha through Google Play and try (that's the only way to test that path as it's not possible to issue 3rd party app intents artificially even from adb, for security reasons).
