### ISSUE TITLE
[GB-Android] Tapping on a picture block does trigger an error

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#8838]
If you add a picture to a new post, and then tap on it  an `IllegalViewOperationException` error is triggered. Stack trace reported below.
After that the UI doesn't give you the ability of getting out of the post with the Back button. You need to use the menu and publish or save as draft the post.

This issue doesn't happen all the time, and it seems that on new posts it does happen more frequently.

Steps to repro:
- Start GB on a new post
- Add an Image block to it
- Tap on the picture (not the caption)
- Boom!

(if the error doesn't happen, keep trying).

```
D/ViewRootImpl@cad90e[EditPostActivity]: ViewPostIme pointer 1
E/unknown:ReactNative: Exception in native call
    com.facebook.react.uimanager.IllegalViewOperationException: Unable to execute operation dispatchViewManagerCommand on view with tag: 997, since the view does not exists
        at com.facebook.react.uimanager.UIImplementation.assertViewExists(UIImplementation.java:919)
        at com.facebook.react.uimanager.UIImplementation.dispatchViewManagerCommand(UIImplementation.java:798)
        at com.facebook.react.uimanager.UIManagerModule.dispatchCommand(UIManagerModule.java:637)
        at com.facebook.react.uimanager.UIManagerModule.dispatchViewManagerCommand(UIManagerModule.java:632)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by hypest** [comment]
>  doesn't happen all the time

I can confirm that it doesn't happen always. I have had instances that did happen and instances that it didn't.

**Comment by hypest** [comment]
Hmm, I think it happens consistently if you first tap into the empty body to auto-create a paragraph block and then "replace" it with an Image block. @daniloercoli , can you confirm if that extra step makes it consistent on your side? Thanks!

**Comment by daniloercoli** [comment]
> Hmm, I think it happens consistently if you first tap into the empty body to auto-create a paragraph block and then "replace" it with an Image block.

Yes, confirming that it happens consistently with the extra step.

**Comment by hypest** [comment]
I added this to milestone 11.5 but if we don't get the chance to fix it by then we will bump it to the next one.

**Comment by mzorz** [comment]
Fixed through https://github.com/wordpress-mobile/gutenberg-mobile/pull/423
