### ISSUE TITLE
IllegalStateException in StatsFragment.kt

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-Android#8959]
First appeared in 11.5.

```
Caused by java.lang.IllegalStateException: Required value was null.
       at org.wordpress.android.ui.stats.refresh.StatsFragment.initializeViewModels(StatsFragment.kt:93)
       at org.wordpress.android.ui.stats.refresh.StatsFragment.onViewCreated(StatsFragment.kt:61)
       at android.support.v4.app.FragmentManagerImpl.ensureInflatedFragmentView(FragmentManager.java:1670)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1399)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1659)
       at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1905)
       at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3715)
       at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:114)
       at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:374)
       at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:39)
       at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:68)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at org.wordpress.android.ui.stats.refresh.StatsActivity.onCreate(StatsActivity.kt:13)
       at android.app.Activity.performCreate(Activity.java:7183)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6940)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

5c3cff94f8b88c296347a6e6-fabric

cc @planarvoid

**Comment by jtreanor** [comment]
This hasn't happened since 11.6
