### ISSUE TITLE
IllegalArgumentException in MediaUtils

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-Android#8978]
This seems to have been introduced in 10.9.1 and is now quite a common crash. I did not see another issue open for it.

```
Caused by java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/1261
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
       at android.content.ContentResolver.query(ContentResolver.java:754)
       at android.content.ContentResolver.query(ContentResolver.java:704)
       at android.content.ContentResolver.query(ContentResolver.java:662)
       at org.wordpress.android.util.MediaUtils.getDataColumn(MediaUtils.java:513)
       at org.wordpress.android.util.MediaUtils.getDocumentProviderPathKitkatOrHigher(MediaUtils.java:460)
       at org.wordpress.android.util.MediaUtils.getPath(MediaUtils.java:422)
       at org.wordpress.android.util.MediaUtils.getRealPathFromURI(MediaUtils.java:401)
       at org.wordpress.android.util.analytics.AnalyticsUtils.getMediaProperties(AnalyticsUtils.java:434)
       at org.wordpress.android.ui.media.MediaBrowserActivity.trackAddMediaFromDeviceEvents(MediaBrowserActivity.java:489)
       at org.wordpress.android.ui.media.MediaBrowserActivity.getMediaFromDeviceAndTrack(MediaBrowserActivity.java:421)
       at org.wordpress.android.ui.media.MediaBrowserActivity.onActivityResult(MediaBrowserActivity.java:443)
       at android.app.Activity.dispatchActivityResult(Activity.java:7250)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4434)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4481)
       at android.app.ActivityThread.-wrap20(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6673)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

fabric-5bad29f5f8b88c2963908b5c

It seems similar to https://github.com/wordpress-mobile/WordPress-Android/issues/5455

**Comment by designsimply** [comment]
**30-day impact:** ~1.3 times a day
**Operating System:** Android 8 or below
**Last seen in:** 11.6
<sub>(5bad29f5f8b88c2963908b5c-fabric-android)</sub>

**Comment by planarvoid** [comment]
I think [this solution](https://stackoverflow.com/a/53021624) should fix this crash. I'll implement it in the Utils project. I tried to reproduce this crash but I failed. I think it might be device+version specific.
