### ISSUE TITLE
NullPointerException in LoginActivity.java

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-Android#8979]
This was first seen in 11.1. It seems to be related to Google Login:

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.login.LoginEmailFragment.finishLogin()' on a null object reference
       at org.wordpress.android.ui.accounts.LoginActivity.onGoogleLoginFinished(LoginActivity.java:744)
       at org.wordpress.android.login.LoginGoogleFragment.onAuthenticationChanged(LoginGoogleFragment.java:161)
       at java.lang.reflect.Method.invoke(Method.java)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
       at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
       at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6715)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

~5be1415bf8b88c2963be71d60-fabric~
5c6550e4f8b88c2963cb7398-fabric

**Comment by designsimply** [comment]
@jtreanor I checked for crash report `5be1415bf8b88c2963be71d60` in Fabric and couldn't get it to load. I also tried searching a bit and still couldn't find the report. Can you help me check in on this one? Can you get the crash report to load properly? (I can see others working, just not `5be1415bf8b88c2963be71d60`.)

**Comment by jtreanor** [comment]
@designsimply I'm not sure how this got mixed up, but I've search Fabric and the correct id is actually `5c6550e4f8b88c2963cb7398`.

**Comment by designsimply** [comment]
Thank you! I am still working on my Fabric/Sentry search skills. 😁 I did try searching Sentry for `finishLogin` as well and didn't find it there either. [1021180221](https://sentry.io/organizations/a8c/issues/1021180221/) was the closest I could find based on a search for `org.wordpress.android.login.LoginEmailFragment` but it's not an exact match.

**30-day impact:** 1.5~ per day
**Users affected:** 43
**First seen in:** 11.1
**Last seen in:** 12.2

<sup>(5c6550e4f8b88c2963cb7398-fabric-android)</sup>

**Comment by designsimply** [comment]
Note: couldn't find any matching reports in Sentry in a search for `onGoogleLoginFinished`. @JavonDavis can you help me double check whether this crash is still showing up or not in new releases?

**Comment by JavonDavis** [comment]
@designsimply I looked and couldn't find any matching or related reports, so I think we can say this one isn't showing up anymore.

**Comment by planarvoid** [comment]
I'm closing this ticket since it's not happening any more
