### ISSUE TITLE
NullPointerException in MySiteFragment

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#9264]
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {org.wordpress.android/org.wordpress.android.ui.main.WPMainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3811)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3851)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3052)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6798)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
       at org.wordpress.android.ui.main.MySiteFragment.setTitle(MySiteFragment.java:836)
       at org.wordpress.android.ui.main.WPMainActivity.updateTitle(WPMainActivity.java:647)
       at org.wordpress.android.ui.main.WPMainActivity.updateTitle(WPMainActivity.java:642)
       at org.wordpress.android.ui.main.WPMainActivity.initSelectedSite(WPMainActivity.java:1024)
       at org.wordpress.android.ui.main.WPMainActivity.onResume(WPMainActivity.java:528)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
       at android.app.Activity.performResume(Activity.java:7107)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3785)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3851)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3052)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6798)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
``` 

5c5353daf8b88c296332f25a-fabric

**Comment by designsimply** [comment]
No reports in the last 30 days.
<sub>(5c5353daf8b88c296332f25a-fabric-android)</sub>

**Comment by designsimply** [comment]
No reports in the last 60 days. Last seen in 11.7.
(5c5353daf8b88c296332f25a-fabric-android)

**Comment by loremattei** [comment]
I looked at the source code and I think that some changes made since 11.7 fixed this. I'm closing it.
