### ISSUE TITLE
java.lang.RuntimeException in StatsFragment.kt

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-Android#9331]
A crash has been introduced in `StatsFragment.kt` in 11.8.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.wordpress.android/org.wordpress.android.ui.stats.refresh.StatsActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class fragment
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

fabric-5c74bc2ef8b88c296324779c

**Comment by jtreanor** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9332.
