### ISSUE TITLE
Submiting comment error for visitor from the app

### ISSUE THREAD

**Issue by pharma-vie** [wordpress-mobile/WordPress-Android#9369]
1- Login with google sign in firebase for visitor.
2- post a comment in the post :

   --------- beginning of system
2019-03-05 22:31:06.055 529-560/system_process I/ProcessStatsService: Prepared write state in 171ms
2019-03-05 22:31:10.294 4765-4765/org.wordpress.android I/WordPress-STATS: 🔵 Tracked: reader_article_commented_on, **Properties**: **{"feed_id":0,"post_id":65,"feed_item_id":0,"is_jetpack":false,"blog_id":158894909}**
2019-03-05 22:31:10.322 4765-4765/org.wordpress.android I/WordPress-READER: **submitting comment**
2019-03-05 22:31:10.710 4765-4928/org.wordpress.android E/Volley: [450] BasicNetwork.performRequest: Unexpected response code 403 for https://public-api.wordpress.com/rest/v1.1/sites/158894909/posts/65/replies/new?locale=en_US
2019-03-05 22:31:10.748 4765-4765/org.wordpress.android W/WordPress-READER: **comment failed**
2019-03-05 22:31:10.749 4765-4765/org.wordpress.android E/WordPress-READER: null
    com.android.volley.AuthFailureError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:171)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)

**Comment by rachelmcr** [comment]
Thanks for this report! I haven't been able to reproduce the issue with those steps, so it looks like there's probably something specific to this case (the specific comment, user, and/or site involved) that caused the failure.

Can you please contact our app support team (under Me > Help & Support in the app) so they can gather more details and troubleshoot this particular case? Thanks!
