### ISSUE TITLE
Crash report 11.9: ArrayIndexOutOfBoundsException in TextView

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-Android#9400]
New crash first seen in 11.9. The details are not very helpful unfortunately.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=37; index=-1
       at android.text.Layout.primaryIsTrailingPreviousAllLineOffsets(Layout.java:1114)
       at android.text.Layout.getLineHorizontals(Layout.java:1235)
       at android.text.Layout.access$000(Layout.java:57)
       at android.text.Layout$HorizontalMeasurementProvider.init(Layout.java:1593)
       at android.text.Layout$HorizontalMeasurementProvider.(Layout.java:1584)
       at android.text.Layout.getOffsetForHorizontal(Layout.java:1490)
       at android.text.Layout.getOffsetForHorizontal(Layout.java:1466)
       at android.widget.TextView.getOffsetAtCoordinate(TextView.java:13439)
       at android.widget.TextView.getOffsetForPosition(TextView.java:13409)
       at android.widget.TextView.onResolvePointerIcon(TextView.java:8399)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewGroup.dispatchResolvePointerIcon(ViewGroup.java:2034)
       at android.view.ViewGroup.onResolvePointerIcon(ViewGroup.java:2009)
       at android.view.ViewRootImpl.updatePointerIcon(ViewRootImpl.java:6221)
       at android.view.ViewRootImpl.access$3800(ViewRootImpl.java:198)
       at android.view.ViewRootImpl$ViewPostImeInputStage.maybeUpdatePointerIcon(ViewRootImpl.java:6122)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6097)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5874)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5323)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5376)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5342)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5501)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5350)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5558)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5323)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5376)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5342)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5350)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5323)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8385)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8318)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8271)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8500)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8459)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8527)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:690)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

5c8787e5f8b88c2963cf597f-fabric

**Comment by designsimply** [comment]
**30-day impact:** 9 times total
**Versions/devices affected:** 11.9, Samsung, Android 9
<sub>5c8787e5f8b88c2963cf597f-fabric-android</sub>

**Comment by jian156j** [comment]
Is Android SDK issue?

**Comment by designsimply** [comment]
**30-day impact:** ~2 per day
**Users affected:** 18 in the last 30d
**First seen in:** 11.9
**Last seen in:** 12.7 (latest major point release at the time of this report)

<sup>https://sentry.io/share/issue/167f819ba7f24bf0a651a50ac0881aa8/</sup>

@jian156j I'm not sure! @jtreanor do you know?

**Comment by jtreanor** [comment]
@designsimply I don't know the source of this crash I'm afraid. Its possible its an Android SDK issue but I haven't investigated it.

**Comment by designsimply** [comment]
**90-day impact:** <1 per day
**Users affected in the last 90 days:** 18
**First seen in:** 11.9

<sup>https://sentry.io/share/issue/167f819ba7f24bf0a651a50ac0881aa8/</sup>

**Comment by designsimply** [comment]
**90-day impact:** 72 or <1 per day
**Users affected in the last 90 days:** 8

<sup>https://sentry.io/share/issue/167f819ba7f24bf0a651a50ac0881aa8/</sup>

**Comment by designsimply** [comment]
**90-day impact:** 73
**Users affected in the last 90 days:** 4

<sup>https://sentry.io/share/issue/167f819ba7f24bf0a651a50ac0881aa8/</sup>

**Comment by malinajirka** [comment]
These 3 issues seem related
https://sentry.io/share/issue/90c29c40aecd412b9b19172e20512fa5/
https://sentry.io/share/issue/ffface6dcd76446c8df482e20bdb1f34/

However, the impact seems minor => closing.
