### ISSUE TITLE
UninitializedPropertyAccessException in AppRatingDialog.kt

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-Android#9416]
There is a new crash in 12.0-rc-1:

```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property preferences has not been initialized
       at org.wordpress.android.widgets.AppRatingDialog.incrementInteractions(AppRatingDialog.kt:88)
       at org.wordpress.android.ui.posts.EditPostActivity.onPositiveClicked(EditPostActivity.java:1741)
       at org.wordpress.android.ui.posts.BasicFragmentDialog$onCreateDialog$1.onClick(BasicFragmentDialog.kt:87)
       at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

Seems to have been introduced in https://github.com/wordpress-mobile/WordPress-Android/search?q=rating&type=Issues

5c86ee00f8b88c2963c36e1f-fabric

**Comment by jtreanor** [comment]
This was fixed in https://github.com/wordpress-mobile/WordPress-Android/pull/9419
