### ISSUE TITLE
java.lang.RuntimeException in EditPostActivity.java

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-Android#9494]
This crash first appeared in `12.0-rc-1` and has become quite prevalent in `12.0`.

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void org.wordpress.android.ui.posts.PostEditorAnalyticsSession.end()' on a null object reference
       at org.wordpress.android.ui.posts.EditPostActivity.onDestroy(EditPostActivity.java:768)
       at android.app.Activity.performDestroy(Activity.java:7239)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1249)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4398)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4429)
       at android.app.ActivityThread.-wrap5(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6524)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
```

It is crashing when calling `mPostEditorAnalyticsSession.end();`. This is possibly related to https://github.com/wordpress-mobile/WordPress-Android/pull/9293.

@mzorz could you take a look at this?

5c893de0f8b88c2963f9ed3c-fabric

**Comment by JavonDavis** [comment]
I'm still seeing this happen up to 13.1, @mzorz think you could take a look and see if it's related or if it's a different crash?

**Comment by designsimply** [comment]
**90-day impact:** ~11 per day
**Users affected in the last 90 days:** 461
**Limited to:** Android 9

<sup>https://sentry.io/share/issue/136cee38cb79491db456071ee0c686a0/</sup>

**Comment by designsimply** [comment]
**90-day impact:** ~16 per day
**Users affected in the last 90 days:** 626
**Limited to:** Android 9 and above

<sup>https://sentry.io/share/issue/136cee38cb79491db456071ee0c686a0/</sup>

**Comment by mzorz** [comment]
This is weird - the  NPE crash stacktrace that can be read in this issue's description (and in Fabric - 5c893de0f8b88c2963f9ed3c) has nothing to do with the one linked to by Sentry in this comment here https://github.com/wordpress-mobile/WordPress-Android/issues/9494#issuecomment-528908689, I'm guessing it was just some problem with the bot; a new issue should be opened instead @JavonDavis 

Closing this for now and opened a new one separately here: https://github.com/wordpress-mobile/WordPress-Android/issues/10606
