### ISSUE TITLE
UninitializedPropertyAccessException in StatsSiteProvider.java

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-Android#9582]
New crash in 12.1:

```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property siteModel has not been initialized
       at org.wordpress.android.ui.stats.refresh.utils.StatsSiteProvider.hasLoadedSite(StatsSiteProvider.java:43)
       at org.wordpress.android.ui.stats.refresh.StatsViewAllViewModel$loadData$3.invokeSuspend(StatsViewAllViewModel.java:90)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:32)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:233)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:594)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.java:60)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:742)
```

5ca288ddf8b88c2963f19898-fabric

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
