### ISSUE TITLE
Crash: NPE in StatsViewAllFragment$setupObservers

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-Android#9750]
This is new in 12.2. 
It's not super common, but since it's new it's probably worth to take a look. 

``` 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setElevation(float)' on a null object reference
       at android.support.v4.view.ViewCompat.setElevation(ViewCompat.java:2028)
       at org.wordpress.android.ui.stats.refresh.StatsViewAllFragment$setupObservers$8$1.run(StatsViewAllFragment.java:226)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

5cbf5257f8b88c296303e06c-fabric

**Comment by designsimply** [comment]
**7-day impact:** ~12 per day
**Users affected:** 75 per week
**First seen in:** 12.2 on Apr 23

<sup>(5cbf5257f8b88c296303e06c-fabric-android)</sup>

@planarvoid could this crash also be related to https://github.com/wordpress-mobile/WordPress-Android/pull/9552?
