### ISSUE TITLE
Bring the app working again on devices without Google Services

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#9826]
Tried to run the Android app on a device without Google Services installed on it.

The app installed & started fine, but crashed right after, at login screen, when I tapped on the email field.
```
2019-05-08 12:04:29.240 3473-3473/? E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2019-05-08 12:04:29.255 3473-3473/? E/MessageQueue-JNI: android.content.ActivityNotFoundException: No Activity found to handle null
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
        at android.app.Activity.startIntentSenderForResultInner(Activity.java:4845)
        at android.app.Activity.startIntentSenderForResult(Activity.java:4812)
        at android.support.v4.app.FragmentActivity.startIntentSenderForResult(FragmentActivity.java:796)
        at android.support.v4.app.ActivityCompat.startIntentSenderForResult(ActivityCompat.java:271)
        at android.support.v4.app.FragmentActivity.startIntentSenderFromFragment(FragmentActivity.java:908)
        at android.support.v4.app.FragmentActivity$HostCallbacks.onStartIntentSenderFromFragment(FragmentActivity.java:1002)
        at android.support.v4.app.Fragment.startIntentSenderForResult(Fragment.java:1116)
        at org.wordpress.android.login.LoginEmailFragment.getEmailHints(LoginEmailFragment.java:437)
        at org.wordpress.android.login.LoginEmailFragment$1.onFocusChange(LoginEmailFragment.java:128)
```

At login I've got this message from the app:
<img width="200" alt="Screen Shot 2019-05-09 at 18 57 03" src="https://user-images.githubusercontent.com/518232/57472213-33693980-728d-11e9-83ff-9d7ba1d19dc8.png">

We think it's just a matter of checking if Play Services are installed on the device before invoking those smart features that require Google Services. It's just a matter of couple of `if`s.

Note: Push notifications will not work after that, as well as Google login, but the rest of the app should work fine without major issues.

**Comment by daniloercoli** [comment]
Adding more details about the configuration I tried that made the app crashing on login:

- Genymotion Samsung S9 emulator running Android 9
- Just start the emulator and install the app

I've also tested on S9 emulator with Android 8 and didn't crash.

**Comment by maxme** [comment]
> At login I've got this message from the app:
