### ISSUE TITLE
Error loading revisions history on new post

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-Android#9874]
Creating a new post from the app make a call to retrieve `History revisions`. The backend replies with an error, since the post ID passed is 0.

```
2019-05-16 10:44:34.968 2451-2595/org.wordpress.android E/Volley: [1069] BasicNetwork.performRequest: Unexpected response code 400 for https://public-api.wordpress.com/rest/v1.1/sites/15592836/post/0/diffs/?locale=it_IT
2019-05-16 10:44:34.971 2451-2451/org.wordpress.android E/WordPress-API: Volley error on https://public-api.wordpress.com/rest/v1.1/sites/15592836/post/0/diffs/?locale=it_IT
    com.android.volley.ServerError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:179)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
2019-05-16 10:44:34.974 2451-2451/org.wordpress.android D/WordPress-API: Dispatching action: PostAction-FETCHED_REVISIONS
2019-05-16 10:44:34.976 2451-2456/org.wordpress.android I/art: Do full code cache collection, code=507KB, data=501KB
2019-05-16 10:44:34.976 2451-2451/org.wordpress.android E/WordPress-API: An error occurred while fetching History revisions
2019-05-16 10:44:34.978 2451-2456/org.wordpress.android I/art: Starting a blocking GC JitCodeCache
2019-05-16 10:44:34.978 2451-2456/org.wordpress.android I/art: After code cache collection, code=449KB, data=392KB
2019-05-16 10:44:35.085 2451-2590/org.wordpress.android E/Volley: [1064] BasicNetwork.performRequest: Unexpected response code 400 for https://public-api.wordpress.com/rest/v1.1/sites/15592836/post/0/diffs/?locale=it_IT
2019-05-16 10:44:35.089 2451-2451/org.wordpress.android E/WordPress-API: Volley error on https://public-api.wordpress.com/rest/v1.1/sites/15592836/post/0/diffs/?locale=it_IT
    com.android.volley.ServerError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:179)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:114)
2019-05-16 10:44:35.093 2451-2451/org.wordpress.android D/WordPress-API: Dispatching action: PostAction-FETCHED_REVISIONS
2019-05-16 10:44:35.096 2451-2451/org.wordpress.android E/WordPress-API: An error occurred while fetching History revisions
```

**Comment by cameronvoell** [comment]
Verified still seeing the same error:

```021-04-07 13:24:39.557 5357-5357/org.wordpress.android.prealpha E/WordPress-API: An error occurred while fetching History revisions
2021-04-07 13:24:39.559 5357-5859/org.wordpress.android.prealpha D/WordPress-API: Dispatching action: ListAction-LIST_DATA_INVALIDATED
2021-04-07 13:24:39.573 5357-5452/org.wordpress.android.prealpha E/Volley: [311] BasicNetwork.performRequest: Unexpected response code 400 for https://public-api.wordpress.com/rest/v1.1/sites/191657202/post/0/diffs/?locale=en_US
2021-04-07 13:24:39.584 5357-5357/org.wordpress.android.prealpha E/WordPress-API: Volley error on https://public-api.wordpress.com/rest/v1.1/sites/191657202/post/0/diffs/?locale=en_US
    com.android.volley.ClientError
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
        at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
2021-04-07 13:24:39.591 5357-5357/org.wordpress.android.prealpha D/WordPress-API: Dispatching action: PostAction-FETCHED_REVISIONS
2021-04-07 13:24:39.593 5357-5357/org.wordpress.android.prealpha E/WordPress-API: An error occurred while fetching History revisions
```
(Samsung Galaxy S10+, Android 11, WPAndroid 17.1 )
